### ISSUE TITLE
Restructure the frame grabbing

### ISSUE THREAD

**Issue by tvdzwan** [tvdzwan/hyperion#10]
The only frame grabbing available at the moment is the dispmanx based grabber. It would be nice to have a X11 and V4L based grabber. These could actually operate simultanuous. To facilitate this the frame grabbing has to be structured in a more layered manner with a 'manager' to runtime select the grabber to use.

**Comment by Gamadril** [comment]
I think already available now. Can be closed?

**Comment by poljvd** [comment]
Yes those grabbers are available.

I saw that you were working on a grabber directly from the framebuffer. We also want to add such a grabber. What is the status of your grabber? Can we expect a pull request when it is finished?

**Comment by Gamadril** [comment]
It seems to work, at least on OpenELEC 5.0. i used XBian only for compilation, so have to test on it properly as well. OSMC is sadly not available yet for imx6.
I plan to send a pull request tomorrow.

**Comment by poljvd** [comment]
Thanks for your efforts. I merged your code into the master branch.

I would like the framebuffer code to use the [ImageResampler](https://github.com/tvdzwan/hyperion/blob/master/include/utils/ImageResampler.h) class for scaling the grabbed image down, becasue the screen size may be large and for calculating led outputs this is not needed. It would save some CPU time which may be relevant for slower processors. The image resampler class should be extended with the pixel formats you decode. Are you up for this or do you want me to do this when I have time again...?

**Comment by Gamadril** [comment]
The framebuffer grabber is already resizing the screen to the size of the passed image. But i will take a look at the ImageResampler and do some performance tests.

**Comment by Gamadril** [comment]
I've tried the ImageResampler and could not detect any significant time differences - at least on OSX. But I'm not sure how to use the ImageResampler for correct downscaling.
If I grab the screen content (1280x800@32bit) it should be downscaled to the size specified in the framegrabber settings (64x64 by default). But the ImageResampler just cut the 64x64 part from top left corner without downscaling.
I call it that (simplified) way:
```
_imgResampler.processImage(pImgData, 64, 64, 1280 * 4, PIXELFORMAT_BGR32, image);
```

**Comment by poljvd** [comment]
The size parameters of processImage specify the input image size. The output is determined by the size decimation options you can set. A size decimation factor of 16 would result in an output image of 80x50.
```
_imgResampler.setHorizontalPixelDecimation(16);
_imgResampler.setVerticalPixelDecimation(16);
_imgResampler.processImage(pImgData, 1280, 800, 1280 * 4, PIXELFORMAT_BGR32, image);
```

**Comment by Gamadril** [comment]
I see, but that would mean the framegrabber options would be ignored completely. It would be different to the dispmanx grabber. Also fixed decimation values would result in output images of different sizes. High resolution would lead to too big images. Low resolutions to too small ones - maybe even not big enough to control the leds.

**Comment by poljvd** [comment]
Calculating the decimation factor based on the frame grabber settings is ofcourse also an option:
```
_imgResampler.setHorizontalPixelDecimation(1280/64);
_imgResampler.setVerticalPixelDecimation(800/64);
_imgResampler.processImage(pImgData, 1280, 800, 1280 * 4, PIXELFORMAT_BGR32, image);
```

**Comment by Gamadril** [comment]
Could be enough for small target sizes. However the aspect ratio will be lost. For the case above the output image is 64x67, If I resize 1280x800 to 640x480 I get the output image 640x800.
I could modify the ImageResampler to use the algorithm from the framebuffer grabber for proper scaling if you give me your OK.

**Comment by poljvd** [comment]
Why is the aspect ratio important? The resolution of the resampled image should be large enough to contain enough detail for the calculation of led values. Because you will most probable have more leds horizontally than you have vertically, it makes more sense to end up with an image of 80x50 than 64x64.

**Comment by Gamadril** [comment]
For the number of leds that's true in the most cases - also don't know why the default value 64x64 was chosen for the dispmanx grabber. But as you can see fixed decimation values lead to the target images with the hight bigger than the width

**Comment by poljvd** [comment]
Probably we have 64x64 as the default, because the default Boblight config had it as an default too for the RPi. Having the same default made things comparable.

When people choose an output size which maintains the aspect ratio of the screen, then it is unlikely that the hight ends up being bigger than the width. But even when this is the case, then it would still be OK and the led mapping will work.

**Comment by Gamadril** [comment]
you are right. I will do some refactoring to use the resampler in the framebuffer grabber and also use it in the new OsxGrabber for Mac OSX.

**Comment by tpmodding** [comment]
@tvdzwan can be closed?

**Comment by tpmodding** [comment]
we have now all grabbers, i close it :)
