### ISSUE TITLE
Disable the "PAL Hacks" from the fushicai driver

### ISSUE THREAD

**Issue by HyperFann** [tvdzwan/hyperion#105]
Hi there, I post this issue here even if it's not Hyperion related so it can help others like me that want NTSC support for the fushicai USB grabber.

I've been able to install the driver from "Ambi-TV" repository but it contains a "PAL Hacks" by default. So i'm only able to catch video in PAL format from my HDMI2AV.

Does someone can tell me how to revert back to NTSC the fushicai driver from "Ambi-TV" repository ?

thanks a lot !

**Comment by tpmodding** [comment]
@HyperFann can be closed?

**Comment by HyperFann** [comment]
Yes you can!

Sent from TypeApp<http://www.typeapp.com/r>


On Mar 2, 2016, at 17:01, tpmodding <notifications@github.com<mailto:notifications@github.com>> wrote:

@HyperFann<https://github.com/HyperFann> can be closed?

**Comment by tpmodding** [comment]
@HyperFann i cant do it, could you please close it? thanks
