### ISSUE TITLE
Hyperion fails if grabber-v4l2 section is defined, but grabber is not connected

### ISSUE THREAD

**Issue by tociek** [tvdzwan/hyperion#106]
Hi,

It was brought to my attention that hyperion does not start, if grabber-v4l2 section is defined, but no video device is connected.
(...)
Display opened with resolution: 1280x720
Frame grabber created and started
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot identify '/dev/video0' error 2, No such file or directory
Aborted

I think it should rather ignore the section if device does not exist, instead on aborting the hyperion, right?

**Comment by tpmodding** [comment]
@tociek think can be closed?
