### ISSUE TITLE
Segmentation fault when leds are not defined for the transformation

### ISSUE THREAD

**Issue by tociek** [tvdzwan/hyperion#108]
Hi,

When someone makes a mistake in a config file, where there is transformation defined for the leds that don't exists in the config file, Hyperion terminates with segmentation fault.

pi@raspbmc:~$ hyperiond /etc/hyperion.config.json
Application build time: Apr 14 2014 19:17:54
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0-37]
ColorTransform 'turnedoff' => [38-43]
Segmentation fault

Handling (i.e. printing a message) of such mistake made by the user would be very helpful :)

**Comment by tpmodding** [comment]
@tociek still need this or can be closed?

**Comment by brindosch** [comment]
Please generate your files with HyperCon to get a fault proof config
