### ISSUE TITLE
3D HOU issue?

### ISSUE THREAD

**Issue by strikegun** [tvdzwan/hyperion#113]
Can it be, that on Openelec 4.0 the 3D detection don't detects HOU (Half Over under)?
If I play a 3D movie in HOU I see the LED left and right correct, but the colours are not correct after the middle.

I am using the addon and not the capture technic.

thx

**Comment by tpmodding** [comment]
@strikegun can be closed?

**Comment by strikegun** [comment]
is it fixed? can I test with HOU again?

**Comment by brindosch** [comment]
I will close it. I added your wish to the list. We have to sort what is to do and what can we do.
The list is long after 2 years now.
Thank you
