### ISSUE TITLE
Question about controlling an other hyperion+RPi

### ISSUE THREAD

**Issue by alucard29** [tvdzwan/hyperion#114]
Hi,

First of all thanks for your great job.

I would like to know if it is possible to communicate with an other RPi to control a second remote Led strip. Explanation :

I have a first RPi running OpenElec + hyperion + led strip on my TV and wired to my network. This works fine.
I have a second RPi running OpenElec + hyperion +led strip hidden in my ceiling and connected to my network through Wifi. I can control these leds using your App.

What I would like to do is when I play a movie with the first RPi, the second one reacts and controls its own leds (in order to have the top-border colors of my tv on my ceiling).

Is it feasable with your configuration file ?

Thanks a lot

**Comment by tpmodding** [comment]
@alucard29 can be closed?

think the forwarder is what you searchin for?

**Comment by alucard29** [comment]
Hi,
Yes you can. Thanks

Regards

**Comment by tpmodding** [comment]
Could you close it please? I have no rights. Thanks

Von meinem iPhone gesendet
