### ISSUE TITLE
Grabber image too bright

### ISSUE THREAD

**Issue by EvilBoris** [tvdzwan/hyperion#117]
Hi all

I've been changing settings all over the place, but cannot figure out how to get past it, but basically the image getting through to the grabber is overexposed, which throws off colours, particularly yellow colours.

Is their any way to change the brightness/contrast of the signal that is being seen by hyperion?

**Comment by tpmodding** [comment]
@EvilBoris can be closed?

**Comment by brindosch** [comment]
One year - should be done. If not please open a new one
Thank you
