### ISSUE TITLE
V4L grabber

### ISSUE THREAD

**Issue by tvdzwan** [tvdzwan/hyperion#12]
Add a frame grabber based on Video For Linux (V4L)

**Comment by rhammons** [comment]
Got my hands on a Fushicai easycap device to feed my sources through to Hyperion on my Pi2 with OSMC, and I'm at a loss on how to fix one dangling issue, which was glossed over in this discussion and I'm looking for some help.  The brightness of black areas on the LEDs are much higher when using the v4l2 grabber device than it is when using the framegrabber and kodi/xbmc.  The screen grabs I get all appear to be balanced brightness wise, black's register at black using the eye dropper in Photoshop for instance. Even if I feed a solid black screen I get a pretty bright (maybe 20%) always on LED glow, the same black screen through Kodi comes out black.  Is there anything specifically I should be adjusting in my config to fix this?

**Comment by jaydeshan** [comment]
RaspberryPi 2, Linux osmc 4.1.3-2-osmc, easycap fushicai usbtv007, ws2801, HDMI2AV.
Lights work great while playing a video from within OSMC. Nada when trying to capture HDMI externally. I've searched the web far and wide, watched greatscott numerous times, and I just can't get a decent (as in even close,) screen capture. All I get is black/grey with a few green lines. I've rebuilt my SD image three times on three different cards. Same results, three times.
Currently, I'm trying to debug my screen capture. Should the HDMI out of the pi show the OSMC GUI or what's being captured on the easycap? (I'm seeing the OSMC interface.)
Most of the support on this seems to point to an old raspbmc build. Has anyone got it working with my setup? Thanks in advance for any support on getting past this. I want to solve this and move on to new projects. :)

**Comment by jaydeshan** [comment]
ok, got it working. for some reason, i needed to do this, hyperion-v4l2 --width 720 --height 576 --screenshot, before I could use, hyperion-v4l2  --screenshot. The latter would just hang until I did the former then both would work. go figure. The only (current) issue I have is that crop doesn't work for me no matter what the setting. The screen cap stays the same. It's not a huge deal, but I prefer when commands do what they're advertised to do. It's probably something I'm doing wrong. 

Advice to those struggling. Simplify. I finally broke it up all into pieces and verified them one at a time. I validated my easycap while hooked to a mac, then plugged an old playstation which only had composite out into the cap. I tweaked things at each step and finally arrived at a working ambilight. frustrating, yes, but well worth the struggle. Thanks Hyperion dev team. Very cool code.

**Comment by tpmodding** [comment]
@tvdzwan can be closed?

**Comment by jaydeshan** [comment]
yes, thanks!

**Comment by subsessor** [comment]
I'm just reporting, that there is still an issue with the screenshot-function. In my case the STK1160 / SAA7113 will not produce a screenshot but just hangs on, doing nothin. Tried several combinations of width/height and PAL/NTSC. The HDMI2AV-Converter seems to work, when i connect it to my TV.
Beeing a newbe to linux i'm just guessing that V4L2 itself became faulty within a recent update or somethin like that.

gmesg tells me this:
stk1160: cannot alloc 196608 bytes for tx[10] buffer

http://easycapexpertti.mybisi.com/pages/drivers
is offering updates, but i was not able to install them.

mplayer gave me some green rubbish when running via SSH....
and when startet via XRDP, it simply killed the session.

i sat the whole evening at this, trying to get it working but its 04:21 now and i'm tired as hell. i think, i just order a utv007 at lightberry.eu as its obviously known to be working, so consider this just FYI.

If anybody wants i can share my so-far-maybe-useless-experience though...

**Comment by brindosch** [comment]
stk1160 is not recommended, as it throws more errors than just your reported.
You could try with Raspbian wheezy, jessie don´t like it

**Comment by tpmodding** [comment]
it is more a firmware problem than a problem with hyperion...

@bimsarck uses a own patch (hope i am right) which works very nice with stk

you can look here for his "solution" but its german
http://www.forum-raspberrypi.de/Thread-hyperion-openelec-mit-automatisierter-ambilight-quellenumschaltung-milhouse-31-10-15-2

**Comment by Phil1988** [comment]
@brindosch : thats not completely correct.
I own a STK1160 and a Fushicai grabber and on jessie the fushicai is really unstable while the STK runs for more then 4 month now without one single problem (no freeze, no stop, no problem at all).

**Comment by brindosch** [comment]
That´s interesting, maybe mixed revisions?

**Comment by subsessor** [comment]
@tpmodding thank you, i'll have a look.
