### ISSUE TITLE
Help Web App Hyperion on a NAS

### ISSUE THREAD

**Issue by epoxsv** [tvdzwan/hyperion#120]
Hello,
I try to install the Web App Hyperion on my NAS Synology Web Server.
I change the file 'configuration.php' with : 
'serverAddress' =>' IP of my NAS.
'hyperionAddress' =>' IP of my RASPBERRY:19444.

But it does not work. I have the web page but the button TURN ON doesn't work
Is it possible to run the Web App on a NAS?
Did I miss something?

Thank you for your help

**Comment by tpmodding** [comment]
@epoxsv can be closed?
