### ISSUE TITLE
Black border detection

### ISSUE THREAD

**Issue by Phil1988** [tvdzwan/hyperion#121]
Sorry guys I open another one for this issue but I cant solve it alone.

I am using Raspbian with an USBGrabber and v4l2 for hyperion but I can get the black border detection to work.
I tried values for the black border threshold from 0,01 to 5,00 without any results.
Has someone running hyperion on raspbian and a working black border detection?

Thanks a lot!

**Comment by brindosch** [comment]
I will close it duo to age. Please open a new one, if problems still exists.
Thank you
