### ISSUE TITLE
Hyperion stops after a while

### ISSUE THREAD

**Issue by yanivfre** [tvdzwan/hyperion#122]
Hi All,

I am running xbmc on ubuntu os.
everything worked fine until recent xbmc update (now running 13.1) or other ubuntu update.
now, if I reboot my computer, leds are working fine, but after a while (comp is always on) it stops working and only return if I reboot my system.
even restarting hyperion from command line or other solutions didn't work.
any idea where to start?

**Comment by brindosch** [comment]
Due to age i will close this issue. Please open a new one if you have questions
Than you
