### ISSUE TITLE
hyperion on Cubox i?

### ISSUE THREAD

**Issue by SePiHL** [tvdzwan/hyperion#123]
Does anyone know, if the hyperion install script would/should be working on a Cubox i2...? Or are these specific RPI modules & scripts which are installed with the script?

Running OpenElec on a Cubox i2 right now... but my lightpack won't light up after installing with the install script for OE :/

There's currently only OE and a thing called GeexBox available for it.

Would be GREAT if you could help me with this?

**Comment by brindosch** [comment]
I added this to a invetigate list. Due to age i will close it,
Thank you

**Comment by brindosch** [comment]
@derechtedude @SePiHL 
There is a imx6 .tar.gz available. Did you tested this?
