### ISSUE TITLE
Hyperion v4l2 grabber aspect ratio?

### ISSUE THREAD

**Issue by KingScooty** [tvdzwan/hyperion#126]
All my feeds are 16:9, but they seem to be grabbed at 4:3 when hyperion grabs them. Is there a way to make them 16:9 or does it not matter when sampling colours?

**Comment by tpmodding** [comment]
@KingScooty can be closeD?

**Comment by brindosch** [comment]
Closed due to age. If you have problems, open a new one
Thank you
