### ISSUE TITLE
pressing question regarding PC only. please

### ISSUE THREAD

**Issue by threesquare** [tvdzwan/hyperion#128]
i've done my research on ambilight-clone. one questions i have is which system will work for my setup.

my main usage is OSX for Plex/movies and dual boot with win8 for gaming. no XBMC. all of which are wired via HDMI to a TV

Arduino setup relies on a computer to do the processing, which isn't what i want.
VS.
RPI does all the processing and Hyperion has HDMI "pass-thru", which is what i want.

will the RPI+Hyperion route works with my setup? Since all my research only shows RPI being use with XBMC; capturing video stream ONLY, rather than screen grabs of the monitor.

Since the HDMI conversion/Pass thru method is suppose to work with ANY HDMI input, and i'm using HDMI out for my computer.

just want to know this before i jump in
thank you!

**Comment by tpmodding** [comment]
@threesquare try ambibox :)

could you close this?
