### ISSUE TITLE
Leds out of sync with TV 

### ISSUE THREAD

**Issue by tvdzwan** [tvdzwan/hyperion#13]
Some TV's are relatively slow in decoding and displaying the images on screen. This causes the leds to change color ahead of the TV image.

**Comment by tpmodding** [comment]
@tvdzwan can be closed?

**Comment by WorkerJJ** [comment]
I'm try on 12.3, 13.2, 14.1, 15.x versions of XMBC/Kodi, runnin on xbian, raspmc and osmc, hyperion and delay parameter works pertfectly.
Thanks for your work.

**Comment by brindosch** [comment]
This is done.
/closed
