### ISSUE TITLE
hyperion-v4l2.sh for install scripts

### ISSUE THREAD

**Issue by gixxpunk** [tvdzwan/hyperion#131]
Hi, please add hyperion-v4l2.sh to your hyperion.deps.openelec-rpi.tar.gz package. With this script it is possible to manually take grabber screenshots in openelec.

example of how to make a screenshot:
killall hyperiond
cd /storage/screenshots
../hyperion/bin/hyperion-v4l2.sh --screenshot

script download: https://www.dropbox.com/s/0c0qffr7fi3pzg2/hyperion-v4l2.sh

**Comment by tpmodding** [comment]
@gixxpunk could you closet this pls? thx
