### ISSUE TITLE
Question: Arduino and PWM

### ISSUE THREAD

**Issue by SquallHalle** [tvdzwan/hyperion#132]
Hey There !
Sorry for ask here ...

got an rgb led strip (not digital) on an arduino leonardo.
I control this with pwm  ( same 12v+ and transistors on the gnd).
How is it possible the speak with Hyperion in this case ?
There is a serial connection over usb form (pc in my case) hyperion to the arudino,
but which kind of type have to be in the config and what should the arduino do ? 
greetings 

squall

**Comment by tpmodding** [comment]
@SquallHalle can be closed?

**Comment by brindosch** [comment]
Closed duo to age. Please open a new one if problems still exists.
Thank you
