### ISSUE TITLE
Smoothing 50Hz Problem

### ISSUE THREAD

**Issue by Schlunze** [tvdzwan/hyperion#135]
Hi,

first thanks for this great software.
I recognized a problem, which occurs when smoothing set to 50Hz. If i do so with 50 pcs WS2801 leds HDMI-CEC in open-elec stop working. If it is set to 20-30 Hz, everything works properly.

**Comment by tpmodding** [comment]
@Schlunze can be closeD?

**Comment by brindosch** [comment]
I will close this due to age. open a new one if problems still exists.
Thank you
