### ISSUE TITLE
latest raspbian 3.12.x with stk1160 led flickering

### ISSUE THREAD

**Issue by pete111** [tvdzwan/hyperion#143]
Hello, I installed the latest upgrade to Raspbian 3.12.25+ but my hyperion is not working ok (LED flickering). It looks like there is stk1160 problem because with 3.10.25+ everything worked ok. 

Who has the same problem? Is it stk1160 driver problem or hyperion problem?

**Comment by tpmodding** [comment]
@pete111 can be closed?

**Comment by kas1kas** [comment]
yeah, no problems!
