### ISSUE TITLE
Add support for delay (Input lag, ...)

### ISSUE THREAD

**Issue by Calico** [tvdzwan/hyperion#148]
If for some reason we have some input lag on the display (some LCD TVs can be up to 100 ms), Hyperion change colors too soon.

A configurable delay in milliseconds would be nice.

Thank you.

**Comment by Calico** [comment]
Confirmed : works perfectly, thanks for all  tvdzwan !

**Comment by fritzmg** [comment]
Is this implemented in the latest release? If so, it should get added to the Wiki.
