### ISSUE TITLE
OpenELEC install instructions and cURL

### ISSUE THREAD

**Issue by jamieburchell** [tvdzwan/hyperion#150]
I followed the OpenELEC install instructions but had issues with the cURL commands that ran due to SSL certificates. To fix the problem, I needed to add the `-k` switch to each cURL request:

Initial get:

`curl -L -k --output install_hyperion.sh --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
sh ./install_hyperion.sh`

install_hyperion.sh:

```
curl -L -k --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hyperion.tar.gz | tar -C /storage -xz
curl -L -k --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hyperion.deps.openelec-rpi.tar.gz | tar -C /storage/hyperion/bin -xz
```

**Comment by Gamadril** [comment]
I confirm that had the same issue. Also git clone didn't work because of the wrong system time showing the same issue with certificates. Issue can be closed IMHO

**Comment by tpmodding** [comment]
@jamieburchell could you close this please? thanks
