### ISSUE TITLE
unable to install hyperion

### ISSUE THREAD

**Issue by dvodonne** [tvdzwan/hyperion#151]
I've recently updated to Raspbmc Gotham and have done a fresh install via usb. now when following your instructions on how to install Hyperion i get the following error:

Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|62.252.172.241|:443... connected.
GnuTLS: A TLS packet with unexpected length was received.
Unable to establish SSL connection.

is there a way to install the Install_Hyperion.sh without having to use wget? 

i'm not very experienced with linux so sorry if there's a simple way to resolve this

**Comment by cstpac** [comment]
Was there ever a resolution to this issue? I still can't use wget due to the TLS error.

**Comment by dvodonne** [comment]
None that I know of. But then I changed to openelec and got it working. Never tried it again on the newer omsc so couldn't answer

Sent from Yahoo Mail on Android 
 
  On Mon, 30 Nov, 2015 at 18:38, Philip Cross<notifications@github.com> wrote:   
Was there ever a resolution to this issue? I still can't use wget due to the TLS error.

**Comment by tpmodding** [comment]
@dvodonne think can be closed? could you close this pls?
