### ISSUE TITLE
Bottom part of the image cropped with UTV007

### ISSUE THREAD

**Issue by tociek** [tvdzwan/hyperion#153]
Hi Guys,

I have discovered weird problem. I am not sure if this is an issue with hyperion or openelec. I hope you can help out.

On Openelec Fushicai/UTV007 grabber has image cropped like this (please note the bottom on the picture):
![screenshot1](https://cloud.githubusercontent.com/assets/6353615/4103220/577c138e-3150-11e4-934a-adcd7404b7ce.png)

On raspbmc with modified kernel it is perfectly fine:
![screenshot-raspbmc](https://cloud.githubusercontent.com/assets/6353615/4103222/75b8e9da-3150-11e4-826d-77f0ce6023b8.png)

Output from taking the screenshot is this:
Openelec:
V4L2 width=720 height=480
V4L2 pixel format=YUYV
V4L2 grabber signal threshold set to: {0,0,0}
V4L2 grabber started
V4L2 grabber stopped

Raspbmc:
V4L2 width=720 height=576
V4L2 pixel format=YUYV
V4L2 grabber signal threshold set to: {0,0,0}
V4L2 grabber started
V4L2 grabber stopped

Please note that the height is different. I guess I don't need to add that --height 576 does not change anything. I would be grateful for any hints.

Jacek

**Comment by tpmodding** [comment]
@tociek can you close this pls? thanks
