### ISSUE TITLE
Terrible flickering with Hyperion

### ISSUE THREAD

**Issue by tghm1801** [tvdzwan/hyperion#155]
So I have a Lightberry (52 LEDs), a Raspberry Pi Model B, a UTV007/Fushicai USB grabber, and Hyperion.
I've finally got the RPi to read the information from the USB grabber, however, it constantly seems to flicker really badly before crashing. It goes like this:
Proper reading - flickering - crashing - rainbow lights - proper reading
And that cycle just repeats.
Additionally, despite configuring my .json file to only use 46 of the 52 LEDs, the remaining 6 stay on - only showing white - even when the rest of the lights are doing the rainbow wheel thing.

Can anyone help?

**Comment by tpmodding** [comment]
@tghm1801 no answer? could you close this ?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, of problems still exists.
Thank you
