### ISSUE TITLE
Run two instances of Hyperion ?

### ISSUE THREAD

**Issue by Blabla51** [tvdzwan/hyperion#157]
Hi,

I would like to have to led system in my room: one doing Ambilight on my TV, and the other to control the light from my android phone.

I bought one 5m led strip to do this. Is it possible to control only a part of the led strip as Ambilight and let the other as ambilight, or is it possible to run two instances of Hyperion to control the differents led strip ?

Thks

**Comment by KristopherKubicki** [comment]
Is there an accepted way to add hue and lightpack-multi together in one instance?

**Comment by tpmodding** [comment]
@Blabla51 works now with the forwarder, could you close this? thanks

**Comment by brindosch** [comment]
Please refer to the new Json/Proto forwarder from rePanther.

Closed
Thank you
