### ISSUE TITLE
WS2812b support

### ISSUE THREAD

**Issue by r3dr4bbit** [tvdzwan/hyperion#160]
Hi guys

This is not an issue, but a way to resolve an issue. I had a quick look around and it seems that there is still no support for the WS2812 leds.

Currently, you use SPI to drive the WS2801 leds.  Wouldn't it be possible to, when generating the data, replacing each bit with a 4 bit pattern (1000) for a zero and (1110) for a one.  Running the SPI at 1MHz for example will meet the strict timing of the WS2812 with 250 ns for a zero and 750 ns for a one.  The timings you mentioned on the page is correct, but a feature on Hackaday.com (http://hackaday.com/2014/06/25/here-come-the-rgb-led-clones/) showed a more detailed analysis of the timings.

The only drawback is the maximum allowed LEDs will now be cut in 4.

**Comment by tpmodding** [comment]
@r3dr4bbit ws2812b works now,
could you close this?

**Comment by r3dr4bbit** [comment]
Once I confirmed it works tonight on a clean OpenELEC I will.

**Comment by r3dr4bbit** [comment]
Ok.  I managed to get it working, but not with the code in this repo.
