### ISSUE TITLE
Hyperion-v4l2 and black border detection leaves a single corner red

### ISSUE THREAD

**Issue by RetepNamenots** [tvdzwan/hyperion#162]
I'm running hyperion/hyperion-v4l2 on raspbian with a USB grabber. The system works great, with one minor niggle:

When my AV receiver isn't receiving a signal it will simply send a blue screen to the TV and my grabber. By setting the --blue-threshold of hyperion-v4l2 to 1.0 it will turn the LEDs off after 100 frames of a blue screen.

This seems to be working perfectly, however my top left three LEDs turn a red pink colour while the rest are all 'off'.

I've taken a couple of screenshots using my current settings and the resulting images appear to be blue (no red). I've also tested on another set of WS2801 so it seems like Hyperion is the thing which is sending these red pixels...

**Comment by tpmodding** [comment]
@RetepNamenots can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, of problems still exists.
Thank you
