### ISSUE TITLE
v4l2 grabber : 'MJPG' pixel format support ?

### ISSUE THREAD

**Issue by nmorel** [tvdzwan/hyperion#163]
Hello, 

I'm trying to configure v4l2 grabber but the pixel format used by my grabber isn't supported.

From lsusb, my grabber is a `Arkmicro Technologies Inc.` 

```
Driver Info (not using libv4l2):
	Driver name   : uvcvideo
	Card type     : USB2.0 PC CAMERA
	Bus info      : usb-bcm2708_usb-1.2
	Driver version: 3.12.22
	Capabilities  : 0x84000001
		Video Capture
		Streaming
		Device Capabilities
	Device Caps   : 0x04000001
		Video Capture
		Streaming
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height  : 352/288
	Pixel Format  : 'MJPG'
	Field         : None
	Bytes per Line: 0
	Size Image    : 202752
	Colorspace    : Unknown (00000000)
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 352, Height 288
	Default     : Left 0, Top 0, Width 352, Height 288
	Pixel Aspect: 1/1
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
                     brightness (int)    : min=0 max=255 step=1 default=-8193 value=0
                       contrast (int)    : min=0 max=255 step=1 default=57343 value=255
                     saturation (int)    : min=0 max=255 step=1 default=57343 value=255
                            hue (int)    : min=-127 max=127 step=1 default=-8193 value=-127
                          gamma (int)    : min=1 max=8 step=1 default=57343 value=4
                           gain (int)    : min=0 max=65535 step=1 default=57343 value=16
           power_line_frequency (menu)   : min=0 max=2 default=1 value=1
                      sharpness (int)    : min=0 max=255 step=1 default=57343 value=3
```

I tried mplayer but the colors are wrong. When taking screenshot, blue color is red on the screenshot.

When I try hyperion-v4l2, the ouput is : 
```
V4L2 width=352 height=288
Only pixel formats UYVY, YUYV, and RGB32 are supported error
```

Any chance you can add support for `MJPG` format please ?

**Comment by JimmyBondi** [comment]
Hey,
i have the same grabber.
Is there a way to use it on RPi2 with hyperion ?
With the new RPi2, perfomance schouldnt be a problem anymore.

**Comment by tpmodding** [comment]
@nmorel can be closeD?

**Comment by nmorel** [comment]
Yes, it can be closed

**Comment by pigbait** [comment]
just wanted to see if any progress has been made on this? I got this device to see if we could use HDMI capture instead of A/V capture.. i got this device http://www.ezcap.com/article_read_426.html it has V4L2 support, also i have this theard https://hyperion-project.org/threads/hdmi-grabber.3302/#post-13703 if anyone wants me to test anything


pi@raspberrypi:~ $ v4l2-ctl --all
Driver Info (not using libv4l2):
        Driver name   : uvcvideo
        Card type     : ezcap U3 capture
        Bus info      : usb-20980000.usb-1.3
        Driver version: 4.9.35
        Capabilities  : 0x84200001
                Video Capture
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps   : 0x04200001
                Video Capture
                Streaming
                Extended Pix Format
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
        Width/Height  : 1920/1080
        Pixel Format  : 'MJPG'
        Field         : None
        Bytes per Line: 0
        Size Image    : 4147200
        Colorspace    : SRGB
        Flags         :
Crop Capability Video Capture:
        Bounds      : Left 0, Top 0, Width 1920, Height 1080
        Default     : Left 0, Top 0, Width 1920, Height 1080
        Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 1920, Height 1080
Selection: crop_bounds, Left 0, Top 0, Width 1920, Height 1080
Streaming Parameters Video Capture:
        Capabilities     : timeperframe
        Frames per second: 30.000 (30/1)
        Read buffers     : 0
                     brightness (int)    : min=0 max=255 step=1 default=-8193 va                                                                                                             lue=128
                       contrast (int)    : min=0 max=255 step=1 default=57343 va                                                                                                             lue=128
                     saturation (int)    : min=0 max=255 step=1 default=57343 va                                                                                                             lue=128
                            hue (int)    : min=-32 max=31 step=1 default=-8193 v                                                                                                             alue=0
                     brightness (int)    : min=0 max=255 step=1 default=-8193 va                                                                                                             lue=128
                       contrast (int)    : min=0 max=255 step=1 default=57343 va                                                                                                             lue=128
                     saturation (int)    : min=0 max=255 step=1 default=57343 va                                                                                                             lue=128
                            hue (int)    : min=-32 max=31 step=1 default=-8193 v                                                                                                             alue=0
