### ISSUE TITLE
Compile error on ubuntu 14.04

### ISSUE THREAD

**Issue by iLLiac4** [tvdzwan/hyperion#166]
After make it get stucked at compiling LedDeviceWS2812b:

[ 28%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/LedDevicePhilipsHue.cpp.o
[ 29%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceTpm2.cpp.o
[ 30%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceWS2812b.cpp.o
/tmp/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp: In member function âunsigned int LedDeviceWS2812b::mem_phys_to_virt(uint32_t)â:
/tmp/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:582:21: error: cast from âuint8_t* {aka unsigned char*}â to âuint32_t {aka unsigned int}â loses precision [-fpermissive]
    return (uint32_t)virtbase + i * PAGE_SIZE + pg_offset;
                     ^
/tmp/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp: In member function âvoid LedDeviceWS2812b::initHardware()â:
/tmp/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:715:42: warning: format â%dâ expects argument of type âintâ, but argument 2 has type âlong unsigned intâ [-Wformat=]
  printf("Page map: %d pages\n", NUM_PAGES);
                                          ^
make[2]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceWS2812b.cpp.o] Error 1
make[1]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/all] Error 2
make: *** [all] Error 2
root@Biostar:/tmp/hyperion#

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if you encounter any problems.
Thank you
