### ISSUE TITLE
Edit existing hyperion.config.json with editor

### ISSUE THREAD

**Issue by hari-bo** [tvdzwan/hyperion#17]
I've created several config files trail and error, but will there be support to edit an existing file. Instead of creating a new file when adjusting an setting.

**Comment by tpmodding** [comment]
@hari-bo think can be closed...brindosch works on new hypercon

**Comment by brindosch** [comment]
It is now possible so save and load your HypCon settings (the hypercon.dat stays the same)
Backup your settings file at a save place!
