### ISSUE TITLE
v4l2 issue

### ISSUE THREAD

**Issue by T3chrage** [tvdzwan/hyperion#170]
I finally got my ambilight working under raspbmc with a STK1160 grabber, but I am having a couple issues (which might be connected to each other) and was wondering if someone could point me in the right direction. I have it setup going from a ps3 to hdmi splitter, hdmi splitter to a hdmi to composite adapter set to PAL (I am in california and was unable to get the grabber to work with NTSC), then adapter to STK1160. 

in my rc.local, I have this line to fire up the grabber on boot:
sudo /opt/hyperion/bin/hyperion-v4l2 --size-decimator 8 --frame-decimator 3 --skip-reply --signal-threshold 0.08

with this setup and some color tweaking everything looks pretty spot on, except for some reason I am having some flickering LED's on the left side of my television. Now, I am not sure if this is a software issue, or because of the second problem I am having. 

When I use hyperion-v4l2 --screenshot, my image is off center with a black bar on the left, and cropped on the right and the top. here is a picture:
http://tinypic.com/view.php?pic=a3zd54&s=8#.VCKhAfldUQk

can anybody point me in the right direction on how to get my image centered with the grabber? I have a feeling once I fix that the flickering issue might go away. thanks!

**Comment by tpmodding** [comment]
@T3chrage still need help or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
