### ISSUE TITLE
V4L2 works, but hypirion doesn't use it

### ISSUE THREAD

**Issue by speeskeek** [tvdzwan/hyperion#172]
I don't know how to short descibe the problem in the title but:

- hyperion is working (I get a nice boot animation on my ledstrip)
- the remote app (android) is working, the colour wheel, the effects all work - yay!
- I can grab some screenshots using "sudo hyperion-v4l2 --width 720 --height 480 --screenshot --crop-left 26 --crop-right 26 --crop-top 18 --crop-bottom 22" - I saw it, it is decent, no black borders

BUT my ledstrip doens't glow according to what the grabber sees, they stay black. Hyperion uses some % of the cpu

What is also nagging me is: after havind hyperiond running for a while, and I stop it and I try to grab a screenshot again, it takes ages (does not take the screeny actually ("V4L2 grabber started").

Currently I'm in test-phase, so only 20leds are attached to the rpi, and the config file is configured accordingly.

Where is my fault?

**Comment by hallard** [comment]
Could you try 
"standard" : "NTSC"
in the config of the grabber ?
I had the same issue blocking when setup PAL, then worked fine with NTSC

**Comment by tpmodding** [comment]
@speeskeek think can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
