### ISSUE TITLE
Toggle LED output via JSON interface when using grabber-v4l2

### ISSUE THREAD

**Issue by RickDB** [tvdzwan/hyperion#179]
Recently started using Hyperion thanks to this guide (http://techtalk.christian-moser.ch/wordpress/?p=562) and have one question as I want to integrate it into Mediaportal as well:

- Is it possible to remotely enable and disable leds via the Hyperion JSON server even when the grabber-v4l2 is getting new images from an active HDMI source?

What I want to achieve with this is that Mediaportal can enable or disable the leds upon certain playback actions similar to XBMC but because Mediaportal has no built-in web server it has to be handled differently as Hyperion can't retrieve status information from it.
So for instance if it's not playing any videos it would send an command to the JSON server so that it would disable the leds, hoping this is possible as I really like the way Hyperion works and how easy it is to setup. 

/edit:
Mediaportal does have an optional web server plugin but seems the commands aren't similar to XBMCs:

http://wiki.team-mediaportal.com/1_MEDIAPORTAL_1/17_Extensions/3_Plugins/WifiRemote/Messages

P.S. Posted this at the forum thread as well but though that this might be better place to ask it, if not I'll remove this request :)

**Comment by tpmodding** [comment]
@RickDB can be closeD?

**Comment by brindosch** [comment]
@RickDB 
Status of the mediaportal integration?

**Comment by RickDB** [comment]
Can be closed, we have had full Hyperion support for some time now but forgot to close this issue.
Sorry about that :)
