### ISSUE TITLE
Integrated grabber issue while hyperion-v4l2 works fine

### ISSUE THREAD

**Issue by tociek** [tvdzwan/hyperion#180]
Hi All,

I have found something... weird.

I have STK1160 with 2013-09 raspbian. When I define grabber-v4l2 section in hyperion config file, the leds 'refresh rate' is very low - it is like I would have 10 times less frames. When I execute hyperion-v4l2 with exactly the same parameters, it works smoothly... Any ideas?

       "grabber-v4l2" :
        {
                "device" : "/dev/video0",
               "input" : 0,
                "standard" : "PAL",
                "width" : 360,
                "height" : 288,
              "cropRight" : 9,
                "cropBottom" : 6

        },

pi@raspberrypi ~ $ hyperion-v4l2 -v PAL -d /dev/video0 --input 0 --width 360 --height 288 --crop-right 9 --crop-bottom 6

Jacek

**Comment by tpmodding** [comment]
@tociek think can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
