### ISSUE TITLE
Leds turning random colours - unsure if faulty leds

### ISSUE THREAD

**Issue by djsmiley2k** [tvdzwan/hyperion#183]
So I get no errors from hyperiond; using pretty much the default config and just passing it colours to test with -c red, -c blue etc.

I end up with the led strip showing random colours, not normally the colour I chose and each led will be showing highly irregular colours too - for example when I chose -c red, one did turn red; some turned green, blue, yellow, white, and orange.

**Comment by tpmodding** [comment]
@djsmiley2k can be closed or still need help?

**Comment by djsmiley2k** [comment]
Needed a resistor adding to the circuit.
