### ISSUE TITLE
Philips Hue supports

### ISSUE THREAD

**Issue by pana800** [tvdzwan/hyperion#184]
Dear all,
May I ask if Philips Hue is currently supported in hyperion? Could someoe please instruct how to have the Hue work with Hyperion?
Many thanks for the great project. It makes my TV more joyful.

**Comment by evanluzi** [comment]
Just want to chime in that I would love support for both hue lights and an LED strip! Still, love the work on Hyperion so far :)

**Comment by ntim** [comment]
In principle, they should work right away, there is no color space correction for the strips yet.

**Comment by beatschubser** [comment]
Is there any other way to get two devices working at the same time, e.g. running two instances of Hyperion under OpenELEC? I'd love to support my Adalight with some Hue-lights.

**Comment by ntim** [comment]
You could try it out and report back. Not sure the framegrabber allows it...

**Comment by ntim** [comment]
@evanluzi:

I implemented the latest model ids in the code and the right gamut triangle should be selected for the strips. Until it is in the offical repo, try it out here:

https://github.com/ntim/hyperion/tree/support_for_philips_hue

**Comment by 11Schotter** [comment]
Hi ntim,

i´m building a dual Hyperion System with 2 Rasp B Plus.

Everything works fine on the one with hyperion, v4l2 grabber and  LDP8806 stripes.
Same image for the other Pi, but when i try to set up the hyperion.config "output : "192.168.X.XX",
hyperion crashes.

Starting hyperiond...                             Ok
pi@raspberrypi ~ $ sudo /etc/init.d/hyperion restart
Stopping hyperiond                                /etc/init.d/hyperion: Zeile 53: kill: (3949) - Kein passender Prozess gefunden
Ok
The v4l2 screenshot etc. works fine.
But i can´t connect the Pi to the bridge... (i have the user "newdeveloper" on hue api)

Thank you in advance!

**Comment by tvdzwan** [comment]
Could you run hyperion directly from the commandline: 'hyperion /etc/hyperion.config.json'?
The output could give a clue what is going wrong.

**Comment by 11Schotter** [comment]
hi tvdzwan,

please tell me please precisely what command i should send via putty?

**Comment by ntim** [comment]
hyperiond /etc/hyperion.config.json

I have the suspicion that the bridge blocks the requests since maybe two clients using the same user is not allowed.

**Comment by 11Schotter** [comment]
Awesome, got the mistake!

2 Problems remaining:

1. Using the Android Hyperion App, i can send a Colour Command.
The HUE Bulbs turn red for example, but after ca. 3-4 Seconds they turn off (fast fading).

2. How about the v4l2 grabber setting?
the normal "framegrabber" has this frequence setting, to match the number of HUE devices to the speed of the bridge. How can i adjust the v4l2 grabber?

Thank you both so much for your amazing work! Haven´t found a donation button ;)

**Comment by rwilleme** [comment]
I'm currently having a RPi (w/ Hyperion) and WS2801 strips working.
I don't really mind having Ambilight working on my hue spots, but I would like to control the led strips (on/off, brightness and color) via the Hue app.
Baseline: The hyperion config should be seen as a Hue bulb.

Any suggestions?

**Comment by ntim** [comment]
There is a node-js package which can mimic a hue bridge, best to start there and modify the package to relay the information to hyperion. Don't know the name anymore but I am sure you will find it ;-)

**Comment by 11Schotter** [comment]
Nice idea! Those Philips Stripes are damn expensive. 

@ntim 
Do you have a way to make the Hue Bulbs beeing more 'in time'? I've spend a lot of money to build this System and have many others who are interested in the dual pi System Hyperion+Hue!

**Comment by ntim** [comment]
@11Schotter 
you can try to reduce the "transitiontime" attribute to 1 (100 ms) or even 0 (instant change, but looks a bit clumsy)

**Comment by ntim** [comment]
I believe this is the node module I used:
https://github.com/nooblucker/hueSimulator

**Comment by xander054** [comment]
hey guys,

Just came across this thread, about to get a rapsberry pi and would love to get my hue bulbs working with lightberry/hyperion. Have you been successful in reducing the lag and also has it been possible to mimic the hue bridge?

Xander

**Comment by pana800** [comment]
Hi,

It has been long time since I did touch it the script.  But it really works
(acceptably smooth).  I use the patch by Birchmark that can switch the HDMI
signal and also can swith between single and multiple LED. (LED and Hue)

Regards,
Le

**Comment by xander054** [comment]
Can you run me through your set up please Le?

**Comment by pana800** [comment]
Will send u the link to the thread and my confg file later on tonight
(GMT+7).

**Comment by pana800** [comment]
You can check the thread here to apply the patch by Bismark.

http://www.forum-raspberrypi.de/Thread-hyperion-openelec-inklusive-videograbber-easycap-stk1160-fushicai-usbtv007-unterstuetzung

Attached is my Config file.

Best regards

**Comment by xander054** [comment]
Great thanks for the link, I can't read German heh but should be OK to translate it on google. Pi is coming tomorrow, think I'm going to go the OSMC route and add Hyperion to that.
How about simulating the hue bridge so hue apps can control the lightberry LEDs did you get that to work?
Rwilleme/ntim is this working? I mostly use iconnect hue and hue widget. Really hoping this works so I dont have to spend £70 on the hue light strips!! :)






On Mon, Nov 30, 2015 at 5:25 AM -0800, "pana800" <notifications@github.com> wrote:










You can check the thread here to apply the patch by Bismark.



http://www.forum-raspberrypi.de/Thread-hyperion-openelec-inklusive-videograbber-easycap-stk1160-fushicai-usbtv007-unterstuetzung



Attached is my Config file.



Best regards

**Comment by EvilBuu** [comment]
Hi Quick question here. Youve mentioned we cant run two multiple devices on Hyperion yet for example a Philips Hue  + Ledstrip. 

But, can we use a deamon and run 2 hyperion instances at the same time? Ive already purchased the necessary hardware such as a bridge and Philpips light and got hyperion working on my tv with a utv007 videograbber. Hoping this will work ill get back on this asap.

**Comment by tpmodding** [comment]
@pana800 can be closed?
@EvilBuu just use the ne forwarder to run multiple devices :)

**Comment by pana800** [comment]
Hi,
Yes,  please close
Thanks a lot.

**Comment by tpmodding** [comment]
Could you close it please? I have no rights. Thanks

Von meinem iPhone gesendet

> Am 03.03.2016 um 15:22 schrieb pana800 <notifications@github.com>:
> 
> Hi,
> Yes, please close
> Thanks a lot.
>
