### ISSUE TITLE
hyperion_v412 breaks wiringPi DHT22

### ISSUE THREAD

**Issue by ScarletStar** [tvdzwan/hyperion#185]
Whenever I start hyperion_v412, it's not possible to read a DHT22 (bitbanged Temp/Humidity sensor).
Running hyperiond is not an issue. I can also use the Android app and still read the sensor.
I have the DHT22 wired to GPIO17 (Pin11, WiringPi 0).

Is hyperion_v412 doing anything with the GPIOs?

**Comment by osadiq** [comment]
Anyone find a solution to this? I'm using openelec and after leaving my Pi off for a few hours, the lirc remote doesn't respond, regardless of which GPIO pin I configure it to. After using the web remote for openelec, the lirc remote starts responding fine well.

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
