### ISSUE TITLE
Multiple Configuration Switcher

### ISSUE THREAD

**Issue by NoOneAtHome** [tvdzwan/hyperion#186]
I am using Hyperion with an EasyCap USB grabber that is accepting input from my AVR.  I have noticed that each device, needs a slightly different crop for left and right.  Having multiple configs that could be switched on the fly via the android app would be a nice feature.

**Comment by tpmodding** [comment]
@NoOneAtHome still need help or can be closeD?

**Comment by Hwulex** [comment]
@NoOneAtHome: @Schamper forked my network based switcher and converted it to CEC based switcher which may work for you?

https://github.com/Schamper/hyperion-switcher

**Comment by brindosch** [comment]
Nice script anyway, we should put it to the hyperion repo and add it to the wiki?
@Hwulex @Schamper

Closed due to age. Please open a new one, if problems still exists.
Thank you

**Comment by MarcDahlem** [comment]
@brindosch Did you mean my script? For sure, you can use it in the wiki, or maybe directly in the repo. But its only the init.d script, as I didn't need other startup scripts... ;-)

**Comment by brindosch** [comment]
I will have look to extend this - later :) I would place it in the hyperion repo in a new directory :)
thank you MarcDahlem!
