### ISSUE TITLE
Hyperion get's stuck after 2secs

### ISSUE THREAD

**Issue by SePiHL** [tvdzwan/hyperion#187]
hey,

i was successfully using hyperion as client-server, with an RPI an raspian-base as server and e.g. a FireTV (which is android based) as client, through the XBMC hyperion addon. Just added the IP/port of the hyperion server in settings and it worked out just fine.

I now got a new Android Box, based on Android 4.4 and wanted to to this the same way. Installed XBMC, installed the hyperion plugin and it kind of connected, but after 2 secs of working LEDs, they just stopped and stay the way they began...

Any clues how I can narrow down the problem? It seems to work... but it kind of gets stuck right at the beginning.

I appreciate any help with this!

Thanks a lot!

**Comment by tpmodding** [comment]
@SePiHL still need help or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, of problems still exists.
Thank you
