### ISSUE TITLE
Frame Grabber not Working?

### ISSUE THREAD

**Issue by Batmanan** [tvdzwan/hyperion#188]
I'm not sure how this is supposed to work but i have everything connected up and i get my bootup swirl and the App works fine but should all the LEDS come on straight away even when just the TV is playing? In other words as soon as i power up the Rpi will ambilight be on all the time?
When I play a movie through OpenELEC the ambilight works which is causing me to think it must be the frame grabber.
I've been playing around with my config file but it could all be useless unless i understand how the ambilight is supposed to work.

**Comment by tpmodding** [comment]
@Batmanan still need help or can be closeD?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
