### ISSUE TITLE
Hyperion on Openelec won't work with app

### ISSUE THREAD

**Issue by loganw9119** [tvdzwan/hyperion#189]
I have hyperion installed on openelec and the hyperion app wont connect with the server.

**Comment by cavemandaveman** [comment]
I have a similar problem...the app is working with hyperion on openelec, but some things don't work. Actually the only thing that works on the app is changing the HSV. Effects and Color Wheel don't do anything.

**Comment by SimonBeccari** [comment]
could u guys pls share the information? im new to this and there isnt any guide for it. it says for me on the app  failed to connect to .... ip... but i added the ip same as kodi

**Comment by tpmodding** [comment]
@loganw9119 can be closed?

**Comment by SimonBeccari** [comment]
Yes
Den 2 mar 2016 22:36 skrev "tpmodding" <notifications@github.com>:

**Comment by tpmodding** [comment]
@SimonBeccari could you close it please? i cant :)

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
