### ISSUE TITLE
Unicorn HAT for Rasberry Pi B+

### ISSUE THREAD

**Issue by scottsweb** [tvdzwan/hyperion#190]
I am hoping you can give me some pointers for integrating Hyperion with the new Unicorn Hat from Pimoroni (http://shop.pimoroni.com/products/unicorn-hat). The drivers for it seem to be a fork of the [NeoPixel library] (https://github.com/626Pilot/RaspberryPi-NeoPixel-WS2812) and can be found here: https://github.com/pimoroni/UnicornHat

If you could point me in the right direction for integrating new hardware it would be hugely appreciated.

**Comment by tpmodding** [comment]
@scottsweb can be closed?

**Comment by scottsweb** [comment]
Sure thing, I never did get it working.
