### ISSUE TITLE
Openelec  (not pi!)

### ISSUE THREAD

**Issue by JanStevens** [tvdzwan/hyperion#191]
Hello,

How can I use this on an Intel Nuc with openelec? The xbmc plugin is not updated in the last 9 months and doesn't work at all.

I would like to use the v4l extension of hyperion so my ambient light works on any HDMI source ( I have a grabber that is recognised in Openelec)

Thanks.

**Comment by JanStevens** [comment]
To clarify my setup:

```
  PS4, XBMC (Intel Nuc), PC,..         
   +  + +                              
   |  | |                              
   v  v v                              
HDMI Switch                            
     +                                 
     |                                 
     |                                 
     v                                 
HDMI Splitter +-------> Analoge Grabber
     +                       +         
     |                       |         
     |                       |         
     v                       v         
    TV                      PI         
                             +         
                             |         
                             |         
                             v         
                         LightPack     
```

So as you can see I have a PI right now but its a bit stupid because I only use the PI for the lights, my intel NUC detects the analoge grabber (and could in theory use it) but I cannot compile or get hyperion to work on my intel NUC. It would be awesome if I could leave out the pi and go back to the intel NUC. The NUC also recognizes the lightpack (Ive used boblight with the lightpack)

So how can I compile/install/build/create hyperion for openelec on a intel nuc?

Thanks!

**Comment by pdf** [comment]
@JanStevens the short answer is that there's no easy way to compile software on OpenELEC.  To build Hyperion for OpenELEC, you would need to [create it as an addon](http://wiki.openelec.tv/index.php?title=How_to_make_OpenELEC_addon_-_on_MuMuDVB_sample) using the [OE build environment](https://github.com/OpenELEC/OpenELEC.tv).

**Comment by maxnet** [comment]
I do have makefiles laying around to compile libqt and Hyperion using the OE build environment.
Right now it builds a complete new OpenELEC image including hyperion though, instead of have it as add-on.
If someone else has time to properly package this into an add-on (including things like adding a startup script, and a simple XBMC interface to turn it on and off), I can put up my files somewhere.

**Comment by tpmodding** [comment]
@JanStevens can be closeD?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
