### ISSUE TITLE
Hyperion on HummingBoard: LEDs flash randomly

### ISSUE THREAD

**Issue by Bavilo** [tvdzwan/hyperion#193]
I have just received my HummingBoard and installed OpenELEC to it. 

I followed your guide on how to install Hyperion for OpenELEC and everything works fine.
After the install I switched the binaries for the newly compiled ones for the HummingBoard.

I also installed the Hyperion XBMC Add-on.

Here is the Problem:

When Hyperion is grabbing a playing video from XBMC, some LEDs will randomly flash different colors.
If I send effects like Rainbow Swirl or some static color, this is not the case.

Here is a short video to demonstrate this:
https://www.youtube.com/watch?v=lZBCfv_-tr4

Here is my config:
http://pastebin.com/cvaDE82f

Any ideas?
Thanks!

**Comment by tpmodding** [comment]
@Bavilo still need help or can be closed?

**Comment by Bavilo** [comment]
I no longer own a HummingBoard. I guess this can be closed.

Thanks!
Am 02.03.2016 10:34 nachm. schrieb "tpmodding" <notifications@github.com>:

**Comment by tpmodding** [comment]
could you close it please? i cant..thanks

**Comment by Bavilo** [comment]
No longer needed
