### ISSUE TITLE
ws2812b and sound

### ISSUE THREAD

**Issue by gregd72002** [tvdzwan/hyperion#194]
Is it just me or is there is interference between the ws2812b controller and RPi sound subsystem?
I've got RPi B+ with WS2812b and a speakers connected to my RPi in the usual way (jack)

When I play music (mp3) the lights blink randomly
When I switch on some hyperion light effects my speakers make unbearable noise

It looks like there is some kind of interference going on between the implementation of the controller and the sound on RPi

Anyone else have this issue?

**Comment by tpmodding** [comment]
@gregd72002 can be closeD?

**Comment by gregd72002** [comment]
Haven't tried it. This is a known issue and the workaround sounds good but someone should test it.

**Comment by gregd72002** [comment]
Suggest to close.

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
