### ISSUE TITLE
Client/Server Setup, and x86 (x64) install?

### ISSUE THREAD

**Issue by Hwulex** [tvdzwan/hyperion#195]
Sorry if this is perhaps obvious, but is it easy to have two instances of Hyperion running in a client/server arrangement? I can't seem to find any specific documentation, and the only previous mention here appears in issue #2, which refers to the [XBMC plugin](https://github.com/tvdzwan/hyperion/wiki/XBMC-addon-(not-for-RPi)). With the availability and responsiveness of the JSON server and the Android app it certainly seems possible, I just don't know how to set it up.

Without RasPlex having usbtv007 support and not wanting to dedicate both my Pi to the cause, I'd prefer to run the grabber on my OpenMediaVault NAS - currently on OMV 0.5 (Deb 6, Squeeze), but soon to upgrade to OMV 1 (Deb 7 Wheezy) - and have that send capture data to the RasPlex Pi to control the LEDs. Even if not possible on OMV, I would like to run in a client/server setup with my other Pi on Raspbian if I have to. Heck, I'd even do it from my Ubuntu laptop as I know the grabber works on there. I have come across one fellow that seems to have [installed Hyperion on an x86 box](http://forum.kodi.tv/showthread.php?tid=180472).

Thanks.

**Comment by tpmodding** [comment]
@Hwulex can be closeD?

**Comment by Hwulex** [comment]
@tpmodding  I never got to implementing the suggestion, but if I do (which I plan to eventually) I can always re-open, or create a new issue if I have problems. Thanks.
