### ISSUE TITLE
Running multiple LED strips at once?

### ISSUE THREAD

**Issue by milhouse34521** [tvdzwan/hyperion#197]
Is it possible to run mutiple LED strips at once that are "related?"  My plan is to run Hyperion on my Raspberry Pi B+. I have a WS2081 (100LEDs) as a standard ambilight which will be connected to the RPB+ via GPIO.  What I would like to do is have an additional strip running along the floor below the TV behind a credenza that will "mimic" the bottom row of the ambilight.  XBMC will be running on a seperate Windows HTPC, so Hyperion is the only function for the RPB+. I can think of two ways to do this but I am not sure if either will work. (1) Connect a seperate WS2081 to another controller (I have a Teensy 2) and connect via USB to the RPB+.  Then setup that strip using Hypercon.  So here the issue is whether I can have two strips connected - one controlled via RBP+/GPIO and one controlleed by Teensy.  (2) Or I could connect both WS2081s to the RBP+ GPIO, and use Hypercon to configure everything in one "instance."  I think I could tell Hypercon to double" the number of LEDs along the bottom of the screen, and have half of them along the bottom of the TV, the other half along the floor.  

So my questions are, will either of these methods work, and if both will work, will one be better than the other?

Thanks.

**Comment by hallard** [comment]
Wohhhh I wanted to ask this too
Would it be possible to launch 2 hyperiond daemon with 2 differents configuration files (and so change TCP port for the 2nd daemon) ? worth to ask ;-)

**Comment by joeplus** [comment]
I think this has been mentioned before, but controlling multiple strips of leds would be great enhancement of hyperion! The FastLED library already supports this as far as I know. And use case described in the initial post is awesome and I had that in mind as well!

**Comment by jwarder** [comment]
Did this functionality ever get implemented?

**Comment by ookyn** [comment]
Hi all,

Like jwarder, i'd like to know if this functionality did ever get implemented?

Thanks !

**Comment by tpmodding** [comment]
@milhouse34521 can be closed, we have now a fully working forwarder!

**Comment by brindosch** [comment]
Stick with the Json/Proto Forwwarder. Create a second Hyperion instance and set up a new config with just leds /left/right/top. HyperCon V2.2.4 will provides this. Will be uploaded soon

Closed due to age. Please open a new one, if problems still exists.
Thank you
