### ISSUE TITLE
frame too small: 0 != 829440

### ISSUE THREAD

**Issue by falbala** [tvdzwan/hyperion#198]
Note that I used a SOMAGIC SMI2021 *(I know this is not ideal)* on the RASPBMC sd class10.
* The usb grabber is OK.
* The /dev/video0 is OK.

#### But impossible to make an screenshot. :rage:

Any feedback and comment will be welcome.

> Thx in advance :smirk:

**Comment by Apalasys** [comment]
Hi falbala. I seem to be in the unfortunately position of having the exact same grabber as you (SOMAGIC SMI2021)... Did you manage to get it working? Additionally, how did you manage to install drivers for it? I am using OSMC RC3 at the moment, but I am willing to go back to RaspBMC if necessary. Thanks for you help. Jason

**Comment by tpmodding** [comment]
@falbala can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
