### ISSUE TITLE
LED colours in right half of frame do not match up with content on screen when content is zoomed

### ISSUE THREAD

**Issue by RetepNamenots** [tvdzwan/hyperion#199]
Hi,

I watch films on my Raspberry Pi (running the latest version of Raspbmc) zoomed to fill the 16:9 display of my TV. I do this because I prefer having a bigger picture and virtually zero gap between the LEDs and the edge of the display and think it is a worthwhile compromise to losing the edges of the image.

Anyway, a few months ago I noticed that the LEDs along the right side of the frame were slightly misaligned. At first I put this down to me having incorrectly set up the configuration file, but after triple-checking I'm certain that this is not the case. Furthermore the alignment is perfect for native 16:9 content.

I tried experimenting with this and found that if I adjust the zoom level within XBMC to 'normal', the content lines up with the LEDs perfectly (although of course I then have black bars on the top and bottom of the video). If I change the zoom level to 'Zoom' (to fill the screen) the LEDs on the left half of the display 'adjust' to accurately reflect the image on that side, but there is no change to the LEDs around the right half, regardless of zoom level.

I'm not sure entirely how hyperion grabs the image from the XBMC player, so I'm unsure as to where the issue lies.

Here's my config file, just in case:

http://pastebin.com/C5iH8Ewu

Thanks

**Comment by tpmodding** [comment]
@RetepNamenots still need help or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
