### ISSUE TITLE
Correct Amblight Setup

### ISSUE THREAD

**Issue by Batmanan** [tvdzwan/hyperion#202]
I'm having issues with my Fushicai frame grabber and just need some clarification on my setup.

My setup is for multiple HDMI sources so I am using a HDMI splitter and HDMI2AV convertor with a Rpi model B running Rasbian.  With this setup I am unable to get my framegrabber to take screenshots or work with my TV. I am pretty sure I have tried everythung and it is still not working. So i just want to check something so i know what i should be aiming for.

With this setup up would I be correct in thinking that if my framegrabber is working correctly if i plug in another TV using a HDMI cable from the Rpi to the TV I should see whatever is on my source input? For example my Blu-ray player / laptop / sky box? Or will the display output from the Rpi be XMBC?

Please help?

**Comment by tpmodding** [comment]
@Batmanan still need help?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
