### ISSUE TITLE
Disabling LEDs (e.g. bottom row) - flicker bug?  

### ISSUE THREAD

**Issue by KingScooty** [tvdzwan/hyperion#204]
So i need a way to disable an entire row of LEDs, specifically the bottom row as the light is reflecting off my TV stand :/

I've changed the `whitelevel` and `valuegain` to 0 for all the LEDs on the bottom row, but they seem to still flicker white rapidly every so often. Is there another way to permanently disable specific LEDs from coming on?

**Comment by tpmodding** [comment]
@KingScooty can be closed or need help?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
