### ISSUE TITLE
Hyperion like Philips

### ISSUE THREAD

**Issue by ghost** [tvdzwan/hyperion#205]
Hey Guys,

sorry for my bad english.

I have 180 LEDs LPD8806 with a STK1160 Grabber on my Pi.
Before i used Hyperion with my new TV i have a Philips TV with Ambilight. This was Good but on Bluray Disk not so good like Hyperion.

On Bluray Hyperion is very nice, but on TV i would its like this
https://www.youtube.com/watch?v=hE8K0kwmv0Y
on 0:18 .. all LEDs its on. Not Black.
it is possible to mix the colors ? so that there are no areas are the Black?

I have Test it with smoothing 120 - 20 and with horizontal depth, vertical depth and overlap.

it would be best example may Summarize 10 leds , so not all leather has a different color

that would be very good

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
