### ISSUE TITLE
Anyone know apa102 leds supportted hyperion with raspi?

### ISSUE THREAD

**Issue by BTopbas** [tvdzwan/hyperion#206]
question is clearly. Very thanks for answers.

**Comment by samuelengelking** [comment]
I've seen that the files for APA102 are there, but I can't choose it in HyperCon. Should I choose WS2801 and change it in the config file to APA102?

**Comment by ssoerensen** [comment]
yeah, just set it to ws2801 in hypercon and change it to apa102 in the configuration file. You should also be able to increase the rate, you can test with a value between 512Khz and 16Mhz depending on wire quality and length.

**Comment by ssoerensen** [comment]
If the APA102 is working, this issue should be closed

**Comment by Fid3lity** [comment]
Config file changing type "ws2801" to "apa102" works fine here using Hyperion on a RPi 2 running Openelec.

**Comment by MrMennens** [comment]
i tried the above, but the apa102 string doesn't work how it should.. i get all sorts of different colours..
could someone copy the important part of the config.json file?
the one with the name, led name, etc.

or are there other things i should change in hypercon?

**Comment by samuelengelking** [comment]
Hi,
here is my Device segment:
```
"device" :
	{
		"name"       : "MyPi",
		"type"       : "apa102",
		"output"     : "/dev/spidev0.0",
		"rate"       : 1200000,
		"colorOrder" : "bgr"
	},
```
Works fine for me. I had to change the colorOrder to make it work

**Comment by MrMennens** [comment]
Thanks for the quick response!

tried it already, also played around with the rate, but nothing seems to be working...
al my leds light up, but sometimes they're just all white, other configurations they're all the different colours. But they never show the colours i tell them to with the android app or just watching a movie.

i don't understand...

**Comment by ssoerensen** [comment]
It looks like a completely different problem to me, it seems that hyperiond is unable to create the json server. This could be that you already have hyperiond running, or some other process using that port. 

- Check if hyperiond is running
- Check JsonServer part in your config, note the port number
- Check 'netstat -ln' and see if the json port is already open

**Comment by MrMennens** [comment]
- if i run "top" i can see hyperiond running
- the jsonserver part is 19444 like the default setting
- if i run 'netstat -ln' i can see 19444 being open.

I just hooked everything on again, and the lights just have a mind of their own... they start in rainbow, and now and then they just start showing different colours or doing effects.

i did notice that the hyperion.config.json file was actually a shortcut to /opt/hyperion/hyperion.config.json i didn't know if that was supposed to be like that, so i deleted the shortcut and made a new proper file.

same stuff happens :( 

______
I just edited the file (just the port numbers) ran 'hyperiond /etc/hyperion.config.json' and tried connecting with the android app. I can see stuff happening in putty! so i see my app connecting and i see effects being activated. The leds just don't seem to respond in the way they should :( they just keep doing random stuff, and when i tried the fast rainbow swirl it goes reaaaaaally slow and just the 10 first LED's change colour..
Whenever i try to play a movie (RGB test Sequence) the LED's don't do anything...

Thanks for all the help guys!!

**Comment by Fid3lity** [comment]
And are you sure the wiring is all correct? Because it sounds like either
data / clock are switched around or some soldering is not quite right.

**Comment by MrMennens** [comment]
i'll try it in a minute, 
i do have a raspberry pi B 2, not sure if this is a problem.. i looked over all the GPIO pages, and i have them at the exact same pins as the Raspberry pi B. 

i'll search once again if i made a mistake somewhere..

**Comment by MrMennens** [comment]
Data and Clock where wrong :| thanks man, the led strip had the yellow cable connected to the clock and the hardware picture of hyperion the yellow cable is data.

but i do have a different issue, if i'm not doing anything and the menu of osmc is just standing still, the led's starts doing different effects without me telling them to.
don't know if my hyperiond is constantly restarting or something?

it seems the half of the LED's work like they are supposed to, but one side is just showing his own colours..

**Comment by Fid3lity** [comment]
I'd say try to power down / reset for a second just because you can. I
haven't used my strip in OSMC itself since I only wanted it to grab an
external source. But how do they now behave in movies?

**Comment by MrMennens** [comment]
how'd you know it only wanted to grab external sources?
i'm uploading a little light show as we speak.. just so you can see what's going on.

i'm also running a clean install of osmc and hyperion on a raspberry pi B just to see how it reacts.
Thanks again for all the help en i'll keep you guys posted if i find out something else.

**Comment by Fid3lity** [comment]
It didn't. I wanted it to. But it wasn't friendly to the odd aspect ratio
of 21:9 so I had to ditch the Raspberry for it. I had the effects running
just fine though.

**Comment by pcaffardi** [comment]
I Just created my first hyperion+rpi2+apa102 (98 leds strip). I still have an issue always with Last led of the chain, no matter the number of leds i configure  in hyperion, i always see N-1 leds correctly, and the Last led changes randomly every time. It seems that next spi transfer starts before the previous end bits of sequence are transferred. Am i the only one with these issues?

**Comment by Darkein** [comment]
I have the same problem with the last led. I have 156 leds and to prevent this i set 157 in the config file.

With this method the blue color of the first led doesn't work, only green and red. But it's better than a random color :)

**Comment by pcaffardi** [comment]
I tried that before, but the led colors should not match the screen exactly
(try the snake effect of hyperion). Try my patch by replacing your hyperion
executable with mine (tested on RPI2):
http://www.arsenio.net/download/hyperion_apa102_patch.zip . The patched
source file is included.

Ciao,
Paolo Scaffardi
skype: pscaffardi
http://www.arsenio.net
http://www.sognilucidi.it

2015-08-19 15:08 GMT+02:00 Darkein <notifications@github.com>:

**Comment by JackBerkhout** [comment]
Hi TVdzan,

I'm using Hyperion with APA102 LED strip with 240 LEDs (4 meter).
The last three LEDs are not updated (and display wrong colors).
This is because the “End frame” needs to supply more clock pulses to the string until the data has permeated to the last LEDs. The total number op clock pulses needed for the END frame is the number of used LEDs divided by two. So for a string with 240 LEDs, 120 clock pulses are needed in the END frame.
I know, the datasheet is not clear on that. I have tested it, and this works.
More information:
https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/
Hope this helps.
I happen to have this LED strip and can test it. Once there is an update, I will test it and give you feedback.

Regards,
Jack.

**Comment by j88ke** [comment]
I also am having an issue where my final LED (out of 240 on an apa102 strand) is not being controlled correctly. Sometimes it is off completely, but most of the time it is maxing out the red and green values while the blue is non existent. This causes an extremely bright yellow on almost constantly.

At first i thought my LED strip was defective, but after reading this thread I am wondering if it is a software issue. Anyone figure this out yet?

**Comment by j88ke** [comment]
adding an extra led to my config did fix my issue with the last led in my strip. I will post back when I find a better solution.

**Comment by pcaffardi** [comment]
Added a LED will make the other leds color computation a little wrong
(shifted). Have you tried my patch (
http://www.arsenio.net/download/hyperion_apa102_patch.zip)

Ciao,
Paolo Scaffardi
skype: pscaffardi
http://www.arsenio.net
http://www.sognilucidi.it

2015-09-30 23:35 GMT+02:00 j88ke <notifications@github.com>:

**Comment by j88ke** [comment]
I installed your patch and its definitely working, Thanks!

**Comment by JackBerkhout** [comment]
Thank you very much!
That works!

**Comment by field3d** [comment]
Hello to all nice post so much to learn. I'm considering in buy this led strip with 60 LEDs per meter:

http://www.amazon.com/gp/product/B00YVYF4GQ

Now my question is can I use a power supply of 5V 8A to supply the whole led strip at maximum? Suppose at maximum white all LEDs for example?

Or what I need to supply the whole strip?

**Comment by JackBerkhout** [comment]
Hi,
according to the datasheet, an LED can consume up to 26mA.
For my television, I need 4 meter (240 LEDs).
This LED strip can then consume up to 0.026*240 = 6.24A.
I also use a 5V 8A power supply for it, and it works fine.

**Comment by JackBerkhout** [comment]
Btw, on their page they state 72W Max, but for 60 LEDs, it can't be true 
I would think. :-)

**Comment by field3d** [comment]
I see I will try my power supply. If you are working fine there is not trouble. I will use with Hyperion 
and raspberry PI. And about 72 W would be 14.4A a lot of Amperes to find a power supply like that.

**Comment by field3d** [comment]
Just to ask what you think in the use of Hyperion with a 144 LEDs 4 meters ledstrip apa102? That could work and really could be worth it for Hyperion ? The total of 576 LEDs scenario could be 576*.026=14.98 and worst scenario like the webpage 576*.06=34.56 there are power supplies support including more like 300w for example. But with that amazing quantity of LEDs not distort or make loss the ambiance of Hyperion or the opposite makes look amazing better? I just ask to know what is the best and worst sceneario with Hyperion having amazing quantities of LEDs.

**Comment by samuelengelking** [comment]
Hi,
I have this strip on my tv:
http://www.aliexpress.com/item/1m-DC5V-APA102-led-pixel-srip-IP33-144pcs-APA102-5050-LED-M-with-144pixels-black-PCB/32230139623.html

That's with 144/m and it works great! I use a old PC ATX power supply for it and the raspberry pi. Never has needed the full current though. I tried it once with all LEDs on 100% white

**Comment by AlexBGoode** [comment]
The most difficult part here is to find out for sure how much current each LED consumes at maximum.
I searched for APA102-C datasheet and around and the information I didn't look trustful for me
If we assume each LED consume 60mA at maximum (20mA per each R-G-B channel) then we have 3,6A for 1m of APA102-C strip (60 LEDs per meter) which causes 14,4A for 4m

Pretty heavy

At least for my setup I know for sure that my WS2812B with 60 LEDs per meter causes 14,4A power requirements for LED 4m long.

So you'd better discover the power consumption of one LED - the rest is mathematics

And BTW take serious care of power cables as well because of Ohm's law!
:-)
Imagine such the current running thru thin cables from the power supply to the strip's ends - you will face voltage drop, super stress on thin strip's power lines... fun is just beginning. And you's also better distribute points to connect the power along the strip

At least in my project now it is the most difficult and serious part - power management

**Comment by field3d** [comment]
Interesting I will think in use a larger strip to with. Sounds great and I imagine how amazing looks the effect with a larger strip.
