### ISSUE TITLE
openelec switch to usbgrabber as a source

### ISSUE THREAD

**Issue by pete111** [tvdzwan/hyperion#207]
Hi guys, this is first time I installed latest openelec 4.2.1 and hyperion. Source for hyperion after installation is RPi desktop. But how can I switch my source to my usbgrabber?

**Comment by tpmodding** [comment]
@pete111 can be closeD?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
