### ISSUE TITLE
autostart.sh isn't starting Hyperion

### ISSUE THREAD

**Issue by cmvac** [tvdzwan/hyperion#211]
Hi, I am having an issue running Hyperion and hacklib through autostart.sh. After updating Openelec to the latest stable version with Hyperion compiled, I use the addon XBMC Tools to update librtmp on Openelec. This addon changes the autostart file, removes the hyperion commands and adds hacklib's. After adding the command lines again manually, when I restart my Pi, Hyperion doesn't automatically start and I have to run the command on SSH to make it work. Any ideas why? Here's a copy of my autostart.sh file:

#!/bin/sh
/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &

# Hack for third-party libraries
[ $PPID -eq 1 -a -f /storage/.config/hacklib ] && . /storage/.config/hacklib

# Rest of autostart.sh goes here...

**Comment by cbabbman** [comment]
I have this same type of problem and I;d LOVE to resolve it...

Basically, hyperion fails to start correctly when being loaded through autostart.sh.. It does work, but there is a greenish flicker throughout the entire string of LED's... If I SSH in, kill hyperion and start it with exactly the same start command that's in my autostart.sh, it fires up and works just fine until the next time I reboot...

Anyone know what's causing this? Or better yet, how to fix it? It's not a hardware problem as far as I can tell, especially since a manual start fixes the problem 100% of the time

Openelec 5.0
RPi B+
WS2812b LED
20A Power Supply

**Comment by RanzQ** [comment]
In depian you can define dependencies for the startup scrips, but I'm not sure if it's possible in OpenELEC. I found that people have solved these kind of problems by adding sleep to their startup scripts. The [wiki](http://wiki.openelec.tv/index.php/Autostart.sh) says the startup script blocks, so you have to wrap it like this:

```(
  sleep 5;
  /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json /dev/null 2>&1 &
) &```

**Comment by cbabbman** [comment]
After messing around with autostart and stuff, I found out by accident that my issue seems to be with the 1st time hyperion starts, regardless of where in the boot sequence it is...

basically, I took it out of the autostart.sh so it wouldn't start at all. The 1st time I manually started it, I got the greenish flicker problem. Killed it and started it again, and it worked perfectly.

Again, this problem happens 100% of the time and killing/restarting hyperion got it working 100% of the time.

Could this be a hyperion problem?

**Comment by broncodfw** [comment]
I have the same issue, I tried to insert a start-Hyperion -> Kill Hyperion -> start-Hyperion again in the startup script and still I can't get it to work automatically. I have to manually restart it through SSH.

**Comment by Carote** [comment]
Hi, 

Same greenish flikering problem when starting up RPi... and same solution kilo/restarting hyperion by SSH. Did somebody found out a solution ?

**Comment by cbabbman** [comment]
nothing yet that I've found... quite honestly, it seems to be an Openelec/Hyperion problem as this is happening on 3 systems I've put together... 1 with a RPi2 and the other 2 with RPI B+'s.. Exact same problem on all 3... 1st start flicker, restart fixes it.

Would still love this to be addressed by someone

**Comment by Carote** [comment]
Ok. Anybody knows if somebody is working on this problem at hyperion ?

Other question : currently, I need to kill and restart hyperion using putty from my computer. But as soon as I close putty, Hyperion is killed and the LEDs are frozen. So I have to keep the putty connexion alive and the computer on when I want Hyperion to be active. Is there another way to be able to close putty and to shutdown the computer ?

Carote

**Comment by Gamadril** [comment]
Append "&" at the end of the command

**Comment by Carote** [comment]
Thanks for the tip ;-)

**Comment by tpmodding** [comment]
@cmvac think can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
