### ISSUE TITLE
RPi/OpenELEC - Turn TV off, LEDs stay on

### ISSUE THREAD

**Issue by B3nihana** [tvdzwan/hyperion#213]
Hyperion is working amazingly for me, just a couple of issues I would like to try and clear up.

The main one for me is that when I turn my TV off the LEDs remain on (I have left it for several hours with no change). I assume that this is because the RPi is still showing sending out a video signal while the screen is off? I have set the screensaver to be a black screen, but its still showing what was displayed on the screen. E.g if I select a film, I can see the LEDs change to the fan art. I turn off the TV and the LEDs remain the same.

For now I have mapped a button on my remote to turn Hyperion off (but cant get it to turn back on, so needs a restart) something more automated would be awesome, I just don't know if this is a common issue (searching here showed nothing).

Secondly, a nice-to-have would be control over the LED brightness, is this possible? I have fiddled with the config, but no joy. All hints are welcome!

**Comment by Fire69** [comment]
grabmenu should be set to false

**Comment by tpmodding** [comment]
@B3nihana still need help or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
