### ISSUE TITLE
2 grabbers switch

### ISSUE THREAD

**Issue by posthok** [tvdzwan/hyperion#219]
is it possible to switch between 2 stk1160 usb grabbers?

**Comment by tvdzwan** [comment]
Hyperion has no direct support for runtime switching two grabbers.
The devices should be mapped to different devices in the OS (say /dev/video0 and /dev/video1). You could make two configuration files and use a shell-script (or similar) to switch between the two.

**Comment by tociek** [comment]
... or you can use something called AV switch, where you can connect multiple composite inputs to one output.  That's not very sophisticated,  but does the job well :)

**Comment by posthok** [comment]
In my case AV switch is not possible. I've got one HDMI grabber and one scart (AV) grabber connected to a Raspberry Pi.

**Comment by tociek** [comment]
You "hdmi grabber"  has rca output,  right?

**Comment by posthok** [comment]
Yes My HDMI grabber has rca output. But what do you want to do with it?
I think the best way to swith between them is via a script /dev/video0 and /dev/video1.

**Comment by tpmodding** [comment]
@posthok we have now the forwarder...
could you close this issue?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
