### ISSUE TITLE
Border detector - correction of misplaced LEDS when border detector is active

### ISSUE THREAD

**Issue by trionix** [tvdzwan/hyperion#22]
If border detector is on and active (borders found), then led colors are little bit moved, because border is not calculate at all.

Little correction is missing...

Misplaced colors on top and bottom example.:

![patternnok1](https://f.cloud.github.com/assets/6390103/1902259/12f42890-7c70-11e3-99c4-28c2675554dc.png)

Correct mapping examples:
![patternok1](https://f.cloud.github.com/assets/6390103/1902271/518c56a4-7c70-11e3-89b1-fe480b764619.png)
![patternok2](https://f.cloud.github.com/assets/6390103/1902273/55b9b15e-7c70-11e3-8edf-3c6ba135aa3c.png)

Copy of http://forum.stmlabs.com/showthread.php?tid=11053&pid=87716#pid87716, just for evidence on github :)
Thankes :)

**Comment by tpmodding** [comment]
we have now a better border detector! think can be closed....

**Comment by brindosch** [comment]
Closed
open a new issue if this is still a problem.
