### ISSUE TITLE
[Feature Req] Hyperion Addon for creating hyperion.config.json

### ISSUE THREAD

**Issue by BTopbas** [tvdzwan/hyperion#220]
Hi all;
Anyone else have information about this? I know config file creating HyperJon java software. But addon can do it?

**Comment by posthok** [comment]
What do you mean by addon. With hypercon.jar you can setup every setting.

**Comment by BTopbas** [comment]
Yes i know. Its support all platform such as linux mac and windows. But i mean maybe we create settings in addon on xbmc. For no config file transfer and no computer usage. Only remote and selecting led type top leds count etc on addon..

**Comment by tpmodding** [comment]
@BTopbas the new config maker has to many options..think its to much for a addon...

could you close this? thanks

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
