### ISSUE TITLE
Ondroid C1 support

### ISSUE THREAD

**Issue by iLLiac4** [tvdzwan/hyperion#221]
I do not have it yet but i assume it should work also on C1 or. to get a support on that board. As soon as i get one, i will try to compile and see how far i will come.

**Comment by josefwells** [comment]
Sounds interesting, you mean "ODROID" right?
http://www.hardkernel.com/main/products/prdt_info.php?g_code=G141578608433

**Comment by brindosch** [comment]
I noted the request

Closed due to age. Please open a new one, if problems still exists.
Thank you
