### ISSUE TITLE
Compilation fails when enabling ws2812b option 

### ISSUE THREAD

**Issue by Tijmus** [tvdzwan/hyperion#222]
Compilation on Ubuntu (Kodibuntu Helix) fails when the ws2812b option is enabled. Following the CompileHowto.txt all goes well when the ws2812-option is not enabled. When enabling it, cmake finishes without issues, but the subsequent make does not (error log below). Any ideas?

/tmp/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp: In member function âunsigned int LedDeviceWS2812b::mem_phys_to_virt(uint32_t)â:
/tmp/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:582:21: error: cast from âuint8_t* {aka unsigned char*}â to âuint32_t {aka unsigned int}â loses precision [-fpermissive]
    return (uint32_t)virtbase + i * PAGE_SIZE + pg_offset;
                     ^
/tmp/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp: In member function âvoid LedDeviceWS2812b::initHardware()â:
/tmp/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:715:42: warning: format â%dâ expects argument of type âintâ, but argument 2 has type âlong unsigned intâ [-Wformat=]
  printf("Page map: %d pages\n", NUM_PAGES);
                                          ^
make[2]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceWS2812b.cpp.o] Error 1
make[1]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/all] Error 2

**Comment by tvdzwan** [comment]
The WS2812B code is specific for the RPi (and maybe similar hardware with a PWM-pin and DMA transfer to that pin). 
The error is probably caused because you are using a 64bit OS and there are some statements that seem to assume that memory-pointers are 32bit i.o. 64bit.

**Comment by tpmodding** [comment]
if i compile it on my rpi i got no errors.

@Tijmus can be closed?

**Comment by Tijmus** [comment]
Jep, can be closed.

**Comment by tpmodding** [comment]
Could you close it please? I have no rights. Thanks

Von meinem iPhone gesendet
