### ISSUE TITLE
XBMC Checker -- Not shutting off or doing what it's meant to.

### ISSUE THREAD

**Issue by bad1dea** [tvdzwan/hyperion#223]
Just wanted to point out -- not sure when this started happening as I've had my leds off for a few months, updated to latest -- noticing that XBMC menu is not forcing leds off or that sort. I can see it connecting to the XBMC host -- as per netstat and also response from hyperion -- its sending the proper info and hyperion sees it.. however its not doing anything.. same goes for screen saver..

I have verified correct IP/Port as its seeing the JSON responses from XBMC..

Message from XBMC: {"id":667,"jsonrpc":"2.0","result":{"item":{"file":"smb://10.10.0.254/disk03/TV Shows/The Office (US)/Season 5/The Office (US) - S05E26 - Company Picnic HDTV-720p.mkv","id":4471,"label":"Company Picnic","type":"episode"}}}
Message from XBMC: {"id":669,"jsonrpc":"2.0","result":{"stereoscopicmode":{"label":"Disabled","mode":"off"}}}
Message from XBMC: {"jsonrpc":"2.0","method":"Player.OnStop","params":{"data":{"end":false,"item":{"id":4471,"type":"episode"}},"sender":"xbmc"}}
XBMC checker: switching to OFF mode
Message from XBMC: {"jsonrpc":"2.0","method":"GUI.OnScreensaverActivated","params":{"data":null,"sender":"xbmc"}}

**Comment by tpmodding** [comment]
@bad1dea need help? or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
