### ISSUE TITLE
Disable the color wheel icon when active

### ISSUE THREAD

**Issue by scottsweb** [tvdzwan/hyperion#224]
Is there a way to disable the color wheel at the top right of the screen when Hyperion is active?

![2015-01-03 18 19 04](https://cloud.githubusercontent.com/assets/411945/5603275/751f16ca-9375-11e4-84b5-e4a7c9ed6f92.jpg)

**Comment by maxnet** [comment]
Think that is the warning symbol you get when your power supply (or cable) is not up for the job.
See the "Under-voltage warnings" thread at http://www.raspberrypi.org/forums/viewtopic.php?f=29&t=82373

**Comment by scottsweb** [comment]
Thanks @maxnet ... that is indeed the cause. The symbol only appears when my Hyperion lights are on so it would suggest that my power supply is struggling a touch.
