### ISSUE TITLE
Lightpack with Firmware 7.6: LIBUSB_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by fritzmg** [tvdzwan/hyperion#225]
I was wondering if anyone here is running Hyperion with a Lightpack + the newest Firmware 7.6. I recently flashed mine to 7.6, however, Hyperion wasn't working with the Lightpack anymore afterwards. When trying to manually start the daemon via `sudo hyperiond /etc/hyperion.config.json`, this error occurs:
```
unable to claim interface(-5): LIBUSB_ERROR_NOT_FOUND
```
I wasn't having any issues with the older firmware (as far as I could tell), so I simply flashed it back to Firmware 6. But I am just wondering if someone else encountered the same problem.

Lightpack works fine under Windows and Ambibox with Firmware 7.6 though.

**Comment by poljvd** [comment]
Are you sure that Hyperion isn't already running in the background?

Also version 7.6 is firmware 6. The first number is the hardware revision number as far as I can tell. You should not upgrade with firmware meant for another hardware revision as the one you have. After a quick browse through the firmware code I don't see much differences between hw6 and hw7 though, but at least the USB led will probably not work anymore.

**Comment by fritzmg** [comment]
Hm... firmware 7.6 is the latest official one found on the download page: http://lightpack.tv/downloads
I think the second number is actually the hardware revision. .6 refers to the mass produced Lightpack (which I meant in the original post as well).

Firmware 7.6 fixes an issue where the led strips are not turned off when the PC is hibernated or shutdown (under windows at least, though I didn't have that problem with fw 6.6 either). There is also a modded 7.6 version which turns off the blue LED entirely and apparently improves performance, since it fixes a bug where the HID device reports too frequently and causes a lot of wasted CPU cycles on the host.

I am not entirely sure on the version numbers, but as I said, 7.6 is the latest official one for the mass produced Lightpack. And 7.6 also works fine under Windows with Prismatik and Ambibox.

> Are you sure that Hyperion isn't already running in the background?

Hm, well, after updating the firmware, reinitializing the Lightpack and reconnecting it to the Raspberry Pi, I made a `sudo initctl restart hyperion`. When it didn't work I tried starting it manually with `sudo hyperiond /etc/hyperion.config.json`. I also tried a complete reboot and it simply wasn't working.

I get your point though, I think I'll try once more with 7.6, then stop hyperion completely with `sudo initctl stop hyperion` and then starting it manually with `sudo hyperiond /etc/hyperion.config.json`, to see if any other error message arises.

**Comment by fritzmg** [comment]
Ok, just tried with 7.6 again, with the hyperion daemon fully stopped and then manually started with `sudo hyperiond /etc/hyperion.config.json`, same error message. Here is the full output:
```
Application build time: Dec 21 2014 15:25:38
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 9]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "95230303231351112181",
        "rate" : 250000,
        "type" : "lightpack"
}

USB context initialized
Found a lightpack device. Retrieving more information...
Lightpack device found: bus=1 address=40 serial=95230303231351112181
unable to claim interface(-5): LIBUSB_ERROR_NOT_FOUND
Unable to open Lightpack device. Searching for other device(-5): LIBUSB_ERROR_NOT_FOUND
No Lightpack device has been found
Black border threshold set to 0.01 (3)
Not creating any smoothing
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Initializing Python interpreter
```

**Comment by fritzmg** [comment]
Ah, after a reboot, stopping the hyperion dameon with `initctl stop hyperion` and then starting it manually via `hyperiond`, the error message is now `LIBUSB_ERROR_PIPE`:
```
Application build time: Dec 21 2014 15:25:38
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 9]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "95230303231351112181",
        "rate" : 250000,
        "type" : "lightpack"
}

USB context initialized
Found a lightpack device. Retrieving more information...
unable to retrieve serial number from Lightpack device(-9): LIBUSB_ERROR_PIPE
Lightpack device found: bus=1 address=15 serial=
No Lightpack device has been found
Black border threshold set to 0.01 (3)
Not creating any smoothing
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Initializing Python interpreter
```
(sorry for comment spam ;))

**Comment by fritzmg** [comment]
Ah I see now... I always tested with the unofficial, modified firmware 7.6 (the one that turns the blue LED off and introduces the HID device reporting "fix"). I thought I also tested with the original firmware 7.6, but I was mistaken - the original one works. It's just the modified one that causes problems.

May the the change to the HID device reporting in the modified firmware actually causes problems on the Raspberry Pi.

**Comment by poljvd** [comment]
Do you know if the source of the fixed firmware is also available from somewhere? I want to see what the differences are with the official firmware.

**Comment by poljvd** [comment]
Why I think the 7 is the harware version and 6 the firmware version:

Have a look at version.h: https://github.com/woodenshark/Lightpack/blob/master/Firmware/version.h
There are multiple releases for fw6: https://github.com/woodenshark/Lightpack/releases/tag/FW_version_6

**Comment by fritzmg** [comment]
> Do you know if the source of the fixed firmware is also available from somewhere? I want to see what the differences are with the official firmware.

No, but I'll try to contact the original author on Reddit. He published it here: http://www.reddit.com/r/Lightpack/comments/286utc/how_to_build_76_hex/cirjb38


> Why I think the 7 is the harware version and 6 the firmware version:

Hm, you are right. This is pretty confusing. All I know is: I got the official (Kickstarter), mass produced Lightpack (not a DIY one) and the firmware 7.6 is the latest official on on their download page. The official firmware 7.6 seems to work fine both under Windows and on the Raspberry Pi with the Lightpack that I got.

Looking back at old reddit threads I can gather, that the official firmware version before that was in fact 7.5. So the hardware version of the mass produced Lightpack seems to be "7" indeed.

CapnBry, the guy on reddit who published the modified firmwares with switched off blue LED, also released a modified version of the previous firmware version, which was called "_hw6" (see [here](http://www.reddit.com/r/Lightpack/comments/1whlu2/dont_like_the_alwayson_led_on_lightpack_flash/)).
May be he accidentally used the hw6 version instead of the hw7 version? Or maybe it just didn't matter because the actual hardware or rather firmware difference was negligible, I don't know. The modified "hw6" firmware also works on my Lightpack (both under Windows and on the Raspberry Pi).

**Comment by CapnBry** [comment]
I'm a little behind but the USB HID reporting bug I reported to the lightpack github
https://github.com/Atarity/Lightpack/issues/71

The only change is returning false on the HID report, which means don't *force* a transfer every period, only every timeout.

**Comment by tpmodding** [comment]
@fritzmg is that fixed? can be closeD?

**Comment by fritzmg** [comment]
Huh, I am not sure, I haven't really tested this particular issue for a long time. But I think the issue can be closed for now.

**Comment by tpmodding** [comment]
Could you close it please? I have no rights. Thanks
If somebody have issues Can be open a new one:)

Von meinem iPhone gesendet

**Comment by fritzmg** [comment]
Sure :)
