### ISSUE TITLE
ws2812b + RaspBMC (Kodi) + raspberry pi b+

### ISSUE THREAD

**Issue by Nueveb** [tvdzwan/hyperion#227]
Hello

This is my first question after some weeks checking forums, articles, tutorials ...

I have a raspberry pi b+, and i have installed a RaspBMC (Kodi) and im using a 240 ws2812b leds stripe.

I have used the pinout described on https://github.com/tvdzwan/hyperion/wiki/Ws2812b

On first stage i have instaled RaspBMC, then it have updated to KODI version

Then i have installed the hyperion lib following step by step this tuto:
https://github.com/tvdzwan/hyperion/wiki/Installation

Then i have change config, following this article:
https://github.com/tvdzwan/hyperion/wiki/Ws2812b

But when i start XBMC only 2 leds are on white, and does not change with the screen, the other leds are off

I have test the stripe with an arduino and it is workig.

Please, can someone help me on this?

Thanks

This is the hyperion.config.json config file that i have uploaded to /etc folder

```javascript
// Automatically generated configuration file for 'Hyperion daemon'
// Generated by: HyperCon (The Hyperion deamon configuration file builder

{
	/// Device configuration contains the following fields: 
	/// * 'name'       : The user friendly name of the device (only used for display purposes)
	/// * 'type'       : The type of the device or leds (known types for now are 'ws2801', 'ldp8806',
	///                  'lpd6803', 'sedu', 'adalight', 'lightpack', 'test' and 'none')
	/// * 'output'     : The output specification depends on selected device. This can for example be the
	///                  device specifier, device serial number, or the output file name
	/// * 'rate'       : The baudrate of the output to the device
	/// * 'colorOrder' : The order of the color bytes ('rgb', 'rbg', 'bgr', etc.).
	"device" :
	{
		"name"       : "MyPi",
		"type"       : "adalight",
		"output"     : "/dev/ttyAMA0",
		"rate"       : 115200,
		"colorOrder" : "rgb"
	},

	/// Color manipulation configuration used to tune the output colors to specific surroundings. 
	/// The configuration contains a list of color-transforms. Each transform contains the 
	/// following fields:
	///  * 'id'   : The unique identifier of the color transformation (eg 'device_1')	///  * 'leds' : The indices (or index ranges) of the leds to which this color transform applies
	///             (eg '0-5, 9, 11, 12-17'). The indices are zero based.	///  * 'hsv' : The manipulation in the Hue-Saturation-Value color domain with the following 
	///            tuning parameters:
	///            - 'saturationGain'  The gain adjustement of the saturation
	///            - 'valueGain'       The gain adjustement of the value
	///  * 'red'/'green'/'blue' : The manipulation in the Red-Green-Blue color domain with the 
	///                           following tuning parameters for each channel:
	///            - 'threshold'       The minimum required input value for the channel to be on 
	///                                (else zero)
	///            - 'gamma'           The gamma-curve correction factor
	///            - 'blacklevel'      The lowest possible value (when the channel is black)
	///            - 'whitelevel'      The highest possible value (when the channel is white)
	///
	/// Next to the list with color transforms there is also a smoothing option.
	///  * 'smoothing' : Smoothing of the colors in the time-domain with the following tuning 
	///                  parameters:
	///            - 'type'            The type of smoothing algorithm ('linear' or 'none')
	///            - 'time_ms'         The time constant for smoothing algorithm in milliseconds
	///            - 'updateFrequency' The update frequency of the leds in Hz
	"color" :
	{
		"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"hsv" :
				{
					"saturationGain" : 1.0000,
					"valueGain"      : 1.0000
				},
				"red" :
				{
					"threshold"  : 0.2000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 0.8500
				},
				"green" :
				{
					"threshold"  : 0.2000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 0.8500
				},
				"blue" :
				{
					"threshold"  : 0.2000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 0.8500
				}
			}
		],
		"smoothing" :
		{
			"type"            : "linear",
			"time_ms"         : 90,
			"updateFrequency" : 30.0000
		}
	},

	///  The configuration for each individual led. This contains the specification of the area 
	///  averaged of an input image for each led to determine its color. Each item in the list 
	///  contains the following fields:
	///  * index: The index of the led. This determines its location in the string of leds; zero 
	///           being the first led.
	///  * hscan: The fractional part of the image along the horizontal used for the averaging 
	///           (minimum and maximum inclusive)
	///  * vscan: The fractional part of the image along the vertical used for the averaging 
	///           (minimum and maximum inclusive)
	"leds" : 
	[
	{
			"index" : 239,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.0700 },
			"vscan" : { "minimum" : 0.2043, "maximum" : 0.2236 }
		}
	],

	/// The black border configuration, contains the following items: 
	///  * enable    : true if the detector should be activated
	///  * threshold : Value below which a pixel is regarded as black (value between 0.0 and 1.0)
	"blackborderdetector" : 
	{
		"enable" : true,
		"threshold" : 0.01
	},

	/// The configuration of the effect engine, contains the following items: 
	///  * paths        : An array with absolute location(s) of directories with effects 
	///  * bootsequence : The effect selected as 'boot sequence'
	"effects" : 
	{
		"paths" : 
		[
			"/storage/hyperion/effects"
		]
	},

	"bootsequence" : 
	{
		"effect" : "Rainbow swirl fast",
		"duration_ms" : 7000
	},

	///  The configuration for the frame-grabber, contains the following items: 
	///   * width        : The width of the grabbed frames [pixels]
	///   * height       : The height of the grabbed frames [pixels]
	///   * frequency_Hz : The frequency of the frame grab [Hz]
	"framegrabber" : 
	{
		"width" : 64,
		"height" : 64,
		"frequency_Hz" : 10.0
	},

	/// The configuration of the XBMC connection used to enable and disable the frame-grabber. Contains the following fields: 
	///  * xbmcAddress       : The IP address of the XBMC-host
	///  * xbmcTcpPort       : The TCP-port of the XBMC-server
	///  * grabVideo         : Flag indicating that the frame-grabber is on(true) during video playback
	///  * grabPictures      : Flag indicating that the frame-grabber is on(true) during picture show
	///  * grabAudio         : Flag indicating that the frame-grabber is on(true) during audio playback
	///  * grabMenu          : Flag indicating that the frame-grabber is on(true) in the XBMC menu
	///  * grabScreensaver   : Flag indicating that the frame-grabber is on(true) when XBMC is on screensaver
	///  * enable3DDetection : Flag indicating that the frame-grabber should switch to a 3D compatible modus if a 3D video is playing
// 	"xbmcVideoChecker" : 
// 	{
// 		"xbmcAddress" : "127.0.0.1",
// 		"xbmcTcpPort" : 9090,
// 		"grabVideo" : true,
// 		"grabPictures" : true,
// 		"grabAudio" : true,
// 		"grabMenu" : false,
// 		"grabScreensaver" : true,
// 		"enable3DDetection" : true
// 	},

	/// The configuration of the Json server which enables the json remote interface
	///  * port : Port at which the json server is started
// 	"jsonServer" : 
// 	{
// 		"port" : 19444
// 	},

	/// The configuration of the Proto server which enables the protobuffer remote interface
	///  * port : Port at which the protobuffer server is started
// 	"protoServer" : 
// 	{
// 		"port" : 19445
// 	},

	/// The configuration of the boblight server which enables the boblight remote interface
	///  * port : Port at which the boblight server is started
// 	"boblightServer" : 
// 	{
// 		"port" : 19333
// 	},

	"endOfJson" : "endOfJson"
}
```

**Comment by tvdzwan** [comment]
The described connection is deprecated. The UART does not have the capabilities to drive WS2812b reliably. 
There are other options:
-Using the PWM-pin (simply connect the data to pin 12 (PWM) directly, no inverter required)
-Using an external module (e.g. arduino)

**Comment by Nueveb** [comment]
Thanks for the comment.

I have connected the data wire, from pin 8 (TxD) to pin 12 (PWM0), i have restarted raspbmc, but nothing happens.

I have bought an Arduino, to make this, but i dont know which config or file i have to compile on arduino and how configure raspbmc to send the info to arduino. 

I have try both options, but i have not any result.

Thanks

**Comment by Poopi** [comment]
This will not work with OpenELEC out of the box due to fact that GPIO 18 by default is used by lirc driver. You have to manually disable this device by modification of the rootfs. THIS IS A MUST.

Regarding the level shifter. You should add a simple level shifter i.e. like this [Level shifter](http://husstechlabs.com/support/tutorials/bi-directional-level-shifter/) . In my case I was using 4.7k resisitors and BS170 transistor ( just make sure that you will have a voltage level >4.5V with nice slopes). Without the shifter I was experiencing the random blinks.

**Comment by Nueveb** [comment]
Thanks for your coment Poopi, but im not using OpenELEC, im using RaspBMC, which is the recomended on the main page.

Thanks

**Comment by Poopi** [comment]
Hmmm. The problem is that the GPIO18 is very popular and many custom modules are using it. Once it was configured as normal output I couldn't get it to running with DMA even after reconfiguration ( although I must admit I didn't crosscheck the datasheet ). I also have found the rtc module as the interfering one. Basically try to remove peripheral modules to see whether this helped or not.
BTW are you sure that RaspBMC is not using the lirc with default config?

**Comment by Nueveb** [comment]
Thanks Poopi 
Im not using GPIO18, im using GPIO12  (PWM0). I have not any other peripherals or module.

But i have not any result. Im not sure if im using the right config on hyperconf

Thanks

**Comment by Nueveb** [comment]
i have some question about it:

Does hyperion support ws2812b led strip ?

How can i use?

1 - Can i use only raspberry pi b+ ?
2 - Can i use hyperion trought arduino?

on both cases, i have some doubts.

I have installed hyperion on raspbmc, how can i ensure that hyperion is enabled and i have made a right installation? can i send a command from ess to know if hyperion service is installed and running? 

Thanks

**Comment by Poopi** [comment]
There is no difference between B and B+ for controlling the GPIO18 pin ( please note that the current WS2812 driver will only work with GPIO18.
See the code...:
`// Set PWM alternate function for GPIO18`
`// ---------------------------------------------------------------`
`SET_GPIO_ALT(18, 5);`

**Comment by Nueveb** [comment]
Thanks Poopi

Where i have to add this line? i have not found on hyperion config.
I just hve followed steps defined on wiki, and i have not found any of these.
Also, how i can ensure that libraries are properly installed and service is running?

Thanks

**Comment by Poopi** [comment]
Nowhere. This is a snapshot from the source code.
I have exactly same setup as you have (but with OpenELEC).
I connect the PIN12 ( GPIO18 ) via levelshifter (as already commented) to Data in of the strip/WS2812B.

In config section device change the type to "ws2812b". That should work. If not connect the logic analyzer(or scope) to GPIO18 and check the waveform.

**Comment by cbabbman** [comment]
So I have an issue I can't seem to resolve... hoping someone here can give me some insight...

RPi B+ running Openelec 5 & Kodi... WS2812B strip, Data connected to GPIO18. Latest version of hyperion installed and working.

I have no problem starting Hyperion up through the command line and once up, it works perfectly.

The problem is that I absolutely cannot get Hyperion to run automatically through autostart.sh.. I've directed the output to a file and it 'looks' like it's running, but it doesn't do anything at all nor is it listed when I do a top command after the boot is completed. But as I said, when I run it manually, it starts every time and works flawlessly.

 Is something stomping on GPIO18 or resetting it during the boot process?

Any thoughts or suggestions would be greatly appreciated.

**Comment by cbabbman** [comment]
Well, not sure what my problem was initially, but I rebuilt the OS, installed hyperion, dropped my config in and it started working perfectly with no issues...

**Comment by tpmodding** [comment]
@Nueveb can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
