### ISSUE TITLE
Rasplex with hyperion

### ISSUE THREAD

**Issue by posthok** [tvdzwan/hyperion#228]
I'm not a linux expert, but is there somebody who has the skills to build a rasplex 0.4.1 image for raspberry ???

I think you would be a hero for many plex user's !!!

**Comment by Gamadril** [comment]
Seems that RasPlex is based on OpenELEC so try out the installation guide for OpenELEC

**Comment by poljvd** [comment]
Rasplex is indeed built on OpenELEC. I tested the installation and it still works. Have a look at this page for more info:
https://github.com/tvdzwan/hyperion/wiki/Installation-on-RPi-with-OpenELEC

In case you don't know, the login for Rasplex is 
user: root 
passwd: rasplex

**Comment by posthok** [comment]
hyperion is working in rasplec 0.4.1 and 0.5
that's not the problem.
But there is no stk1160 driver in the image.
my goal is a working lightberry sytem in rasplex.
the driver was available in rasplex 0.3.9.

**Comment by hari-bo** [comment]
I've got exactly the same issue, how can i solve this?

**Comment by tpmodding** [comment]
@posthok problem fixxed? or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
