### ISSUE TITLE
No video Grabbing?

### ISSUE THREAD

**Issue by energysumo** [tvdzwan/hyperion#230]
hello,
I have installed Hyperion on RasPi and got the iOS and android apps... app work fine.
However the Amiblight video grabber is not.
lsusb
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. 
Bus 001 Device 004: ID 05e1:0408 Syntek Semiconductor Co., Ltd STK1160 Video Capture Device
Bus 001 Device 005: ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter

I have tried many different hyperion.config.json variations with no results.
I have done all the updates
what am I missing?  any help would be great!

**Comment by posthok** [comment]
Witch image are you you using?

**Comment by evanluzi** [comment]
I am having a very similar problem. Running Raspbmc on a RasPi B+. When I run `ls /dev/video*` I get an output of "ls: cannot access /dev/video*: No such file or directory".

Any ideas?

**Comment by posthok** [comment]
i think the grabber driver is not available in your image

**Comment by evanluzi** [comment]
That's what I'm thinking. Are there any grabbers compatible with RasPi B+ and raspbmc? Or should I just switch to xbian or openelec?

**Comment by posthok** [comment]
easycap stk1160 but not every image is compatible. you'll find images on http://lightberry.eu/#download

**Comment by evanluzi** [comment]
Right I have easycap stk1160, but what do you mean by image? Are you referring to the OS, the kernel, all combinations?

The lightberry site doesn't have an image for raspbmc + stk1160. It has one for openelec, which I don't mind installing, but seeing as I already have raspbmc setup, I'd prefer to go that route if it's possible.

**Comment by evanluzi** [comment]
OK have installed openelec using the lightberry images, but now when trying to get a screenshot I get this error: `VIDIOC_S_FMT error 16, Device or resource busy`

any thoughts?

**Comment by posthok** [comment]
Did you adjust your hyperion config setting?

**Comment by evanluzi** [comment]
Yes. I've found someone else who is having a similar problem in issue #216 . The device or resource busy error was from hyperion already running, so I do `killall hyperiond` and then try to take the screenshot, but it hangs and never returns anything.

**Comment by mharrison310** [comment]
I am in the same boat as you, I am running OSMC and get the same error. [#482](https://github.com/tvdzwan/hyperion/issues/482)

**Comment by tpmodding** [comment]
@energysumo can be closed now? or didnt fixed the issue?

**Comment by brindosch** [comment]
`Device or resource busy`
Stop the Hyperion process before you do screenshots

Closed due to age. Please open a new one, if problems still exists.
Thank you
