### ISSUE TITLE
cubox-i + hyperion + xbian

### ISSUE THREAD

**Issue by coolwormgit** [tvdzwan/hyperion#231]
i try to make but i get errors..

i try also:
git clone https://github.com/tvdzwan/hyperion.git
cd hyperion/deploy
sudo tar -C /opt -xzf hyperion.tar.gz 
sudo ln -fs /opt/hyperion/bin/hyperiond /usr/bin/hyperiond
sudo ln -fs /opt/hyperion/bin/hyperion-remote /usr/bin/hyperion-remote
sudo ln -fs /opt/hyperion/bin/hyperion-v4l2 /usr/bin/hyperion-v4l2
sudo ln -s /opt/hyperion/config/hyperion.config.json /etc/hyperion.config.json
hyperiond /etc/hyperion.config.json

but i get error:
hyperiond: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory

is there any way to install or make compatible????

Thank you

**Comment by Gamadril** [comment]
After cloning the repository you have to compile, not just extracting the version for RPi.

Try following:
git clone https://github.com/tvdzwan/hyperion.git
mkdir hyperion/build
cd hyperion/build
cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_X11=OFF -DENABLE_V4L2=OFF -DENABLE_PROTOBUF=OFF ..
make

create a config file and test it by running bin/hyperiond hyperion.config.json

**Comment by coolwormgit** [comment]
ok i try and i get errors:

xbian@xbian /tmp/hyperion/build $  cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_X11=OFF -DENABLE_V4L2=OFF -DENABLE_PROTOBUF=OFF ..
-- ENABLE_DISPMANX = OFF
-- ENABLE_SPIDEV   = OFF
-- ENABLE_WS2812BPWM = OFF
-- ENABLE_V4L2 = OFF
-- ENABLE_X11 = OFF
-- ENABLE_TINKERFORGE = ON
-- ENABLE_PROTOBUF = OFF
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUSB_1_INCLUDE_DIR
   used as include directory in directory /tmp/hyperion/dependencies/build/hidapi
   used as include directory in directory /tmp/hyperion/libsrc/leddevice
LIBUSB_1_LIBRARY
    linked by target "hidapi-libusb" in directory /tmp/hyperion/dependencies/build/hidapi
    linked by target "leddevice" in directory /tmp/hyperion/libsrc/leddevice

-- Configuring incomplete, errors occurred!
See also "/tmp/hyperion/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/hyperion/build/CMakeFiles/CMakeError.log".


thanks

**Comment by poljvd** [comment]
You seem to be missing the libusb library:
sudo apt-get install libusb-1.0-0

**Comment by coolwormgit** [comment]
ok the libusb-1.0-0-dev was missing ..

**Comment by coolwormgit** [comment]
after success make i get error for framebuffer...


xbian@xbian ~ $ sudo hyperiond /etc/hyperion.config.json
Application build time: Jan 16 2015 09:32:02
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 101]
Device configuration: 
{
	"colorOrder" : "rgb",
	"name" : "MyPi",
	"output" : "/dev/ttyACM0",
	"rate" : 115200,
	"type" : "adalight"
}

Opening UART: /dev/ttyACM0
Black border threshold set to 0.01 (3)
Creating linear smoothing
Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
Effect directory can not be loaded: /storage/hyperion/effects
Initializing Python interpreter
Hyperion created and initialised
XBMC video checker created and started
The dispmanx framegrabber can not be instantiated, becuse it has been left out from the build
terminate called after throwing an instance of 'std::runtime_error'
  what():  Json server could not bind to port
xbian@xbian ~ $

**Comment by Gamadril** [comment]
comment out framegrabber settings from your config

**Comment by coolwormgit** [comment]
ok i did looks ok now, leds light up white but leds doesnt work on video :(

Application build time: Jan 16 2015 09:32:02
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 101]
Device configuration: 
{
	"colorOrder" : "rgb",
	"name" : "MyPi",
	"output" : "/dev/ttyACM0",
	"rate" : 115200,
	"type" : "adalight"
}

Opening UART: /dev/ttyACM0
Black border threshold set to 0.01 (3)
Creating linear smoothing
Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
Effect directory can not be loaded: /storage/hyperion/effects
Initializing Python interpreter
Hyperion created and initialised
XBMC video checker created and started
Json server created and started on port 19444
XBMC Connected
Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[]}
XBMC checker: switching to OFF mode
Message from XBMC: {"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":false}}
Message from XBMC: {"id":670,"jsonrpc":"2.0","result":{"version":{"major":13,"minor":2,"revision":"20141203-e4e8391","tag":"stable"}}}
Message from XBMC: {"jsonrpc":"2.0","method":"Playlist.OnClear","params":{"data":{"playlistid":1},"sender":"xbmc"}}
Message from XBMC: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"Hot Tub Time Machine 2 - Trailer","type":"movie"},"playlistid":1,"position":0},"sender":"xbmc"}}
Message from XBMC: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"title":"Hot Tub Time Machine 2 - Trailer","type":"movie"},"player":{"playerid":1,"speed":1}},"sender":"xbmc"}}
Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
XBMC checker: switching to VIDEO mode
Message from XBMC: {"id":667,"jsonrpc":"2.0","result":{"item":{"file":"plugin://plugin.video.itunes_trailers/trailer/play/http%3A%2F%2Fmovietrailers.apple.com%2Fmovies%2Fparamount%2Fhottubtimemachine2%2Fhottubtimemachine2-tlr_h720p.mov","label":"Hot Tub Time Machine 2 - Trailer","type":"unknown"}}}
Message from XBMC: {"id":669,"jsonrpc":"2.0","result":{"stereoscopicmode":{"label":"None","mode":"off"}}}

**Comment by Gamadril** [comment]
They won't, because there is no suitable frame grabber for imx6 at the moment. I'm working on one, but still testing, look here https://github.com/tvdzwan/hyperion/issues/149

**Comment by coolwormgit** [comment]
seems i have to wait for it ... nothing seems to work...

**Comment by Gamadril** [comment]
The framebuffer grabber was merged into the main source tree, so try to compile it (see https://github.com/tvdzwan/hyperion/blob/master/CompileHowto.txt for flags) and test.

close the issue if it works.

**Comment by coolwormgit** [comment]
Looks Perfect :) thanks
