### ISSUE TITLE
IMPORTENT FOR WIKI:Raspberry Pi no LED-function

### ISSUE THREAD

**Issue by kotarokun** [tvdzwan/hyperion#232]
I want to say,
after solder cable 4 times on LED and Raspberry with no function on Rasbian and 3 days with talking to electric-men, i want to say:
befor Install:
Just activate on Raspi-config the SPI-Output or same function like discribed for xbian
"
Enable spi on XBian

This step is not necessary for Raspbmc which has the spidev enabled by default. On XBian however, Spidev needs to be enabled if you have your leds attached to SPI. If you don't need SPI to work, you can leave this step and remove the modprobe line from /etc/init/hyperion.conf later on.

Remove the spidev from the blacklist by placing a '#' in front of the spi module entry:

xbian@xbian ~ $ sudo nano /etc/modprobe.d/raspi-blacklist.conf
xbian@xbian ~ $ cat /etc/modprobe.d/raspi-blacklist.conf
# blacklist spi and i2c by default (many users don't need them)

#blacklist spi-bcm2708
blacklist i2c-bcm2708
xbian@xbian ~ $ 
"

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
