### ISSUE TITLE
Hyperion with Arduino Yun (openwrt)

### ISSUE THREAD

**Issue by NicoHood** [tvdzwan/hyperion#233]
I tried to download hyperion with my Arduino Yun Shield. But it didnt want to start at all. I downloaded the tar and extracted it because the installation skript failed.

root@YunShield:/mnt/sda1/hyperion/bin# ./hyperiond
./hyperiond: line 1: syntax error: unexpected word (expecting ")")

Is there any way to get this working with openwrt? We could use the serial to the Arduino to trandmit via the adalight "protocol". Then I could use the xbmc addon to send data to the Arduino yun. Any help with that?

**Comment by poljvd** [comment]
The binaries you downloaded are for the Raspberry Pi and will not work on your processor. You will have to compile the Hyperion sources for your processor, but at first glance it looks like the processor may be a little too lightweight for Hyperion to run on.

**Comment by NicoHood** [comment]
Closing this, since it was just a question and the Arduino yun is just not made for this. Maybe its possible, but I wont use it anyways.
