### ISSUE TITLE
Will not compile on 12.04

### ISSUE THREAD

**Issue by iLLiac4** [tvdzwan/hyperion#234]
This is the log file of compiler:

cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_X11=ON
-- ENABLE_DISPMANX = OFF
-- ENABLE_SPIDEV   = OFF
-- ENABLE_WS2812BPWM = OFF
-- ENABLE_V4L2 = ON
-- ENABLE_X11 = ON
-- ENABLE_TINKERFORGE = ON
-- ENABLE_PROTOBUF = ON
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/i386-linux-gnu/libusb-1.0.so
CMake Error at dependencies/CMakeLists.txt:9 (add_subdirectory):
  The source directory

    /tmp/hyperion/dependencies/external/protobuf

  does not contain a CMakeLists.txt file.

CMake Error at dependencies/CMakeLists.txt:17 (export):
  export given target "protoc_compiler" which is not built by this project.

CMake Error at dependencies/CMakeLists.txt:25 (get_property):
  get_property could not find TARGET protoc_compiler.  Perhaps it has not yet
  been created.

-- Using protobuf compiler:
CMake Warning at doc/CMakeLists.txt:31 (message):
  Doxygen not found, unable to generate documenation!

-- Configuring incomplete, errors occurred!

**Comment by poljvd** [comment]
Hi,

We recently added the protobuf sources as a submodule to avoid versioning problems between the protoc compiler and the cross compilations. The submodule has to be initialized. I have updated the compile instructions with the following:

```sh
# get the Hyperion sources
git clone --recursive https://github.com/tvdzwan/hyperion.git "$HYPERION_DIR"

# if you forget the --resursive in above statement or you are updating an existing clone you need
# to clone the protobuf submodule by runnning the follwing two statements:
git submodule init
git submodule update
```

Hope this helps.

**Comment by iLLiac4** [comment]
Is protobufer needed for non rpi users?
if not cmake like:
cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_X11=OFF -DENABLE_V4L2=OFF -DENABLE_PROTOBUF=OFF

Will help?

**Comment by poljvd** [comment]
In most cases they do require protobuf, becasue the XBMC addon requires the proto interface.

**Comment by iLLiac4** [comment]
OK. TNX it works now.
