### ISSUE TITLE
[Question] What is gpio2spi utility for?

### ISSUE THREAD

**Issue by tociek** [tvdzwan/hyperion#235]
What is gpio2spi utility for?

**Comment by poljvd** [comment]
In october 2013, when we introduced Hyperion, there was an issue with Raspbmc. The SPI drivers were loaded and working, but somehow the GPIO of the RPi was not setup correctly. This utility does some low-level calls to setup the GPIO is the correct mode for SPI. I have not checked lately, but I assume (or hope) that this utilty os not needed any more for the current distributions of Raspbmc.

**Comment by tociek** [comment]
Ok, Thanks!
