### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by IDmedia** [tvdzwan/hyperion#239]
After reading the wiki and a lot of other issues I'm still unsure about a few things. While everything works I think the leds are flickering a bit much and I'm also troubled with quite a bit of lag. I have 80 leds running with raspbian 2013-09-25 using the STK1160 video grabber. My config is here: http://pastebin.com/TRHU2zdP

1. What version of Raspbian is supported?
Most guides say you have to use a 2013-version of Raspberian. Is there any good reason for that and not using the latest version from 2014? I can see that a later version of the image (20/12/2013) includes V4L2 fixes (and kernel) and also state changes to the video grabber driver. Any comments on this?

2. What does the framegrabber-part do in the hyperion config?
Hoping to reduce lag I've tried to change the width, height and frequency_Hz of the framegrabber. Changing it from 4x4 (width/height) and 10Hz to 256x256@200Hz doesn't seem to change anything. I've now set it back to the default, but what should I look out for in terms of gaining more responsiveness?

3. Disable the framegrabber in xbmcVideoChecker
For some reason, changing any values from true to false or false to true does not turn of the videograbber in xbmc. I would rather want to use the xbmc addon as this is by far much smoother then using the video grabber. Am I doing it wrong by setting every value here to false? The IP to xbmc is correct and it's connected.

4. Improving performance to grabber-v4l2
After playing around with the grabber-v4l2 I'm quite happy with the screenshots. They look (I think) as good as it get's with this kind of connection/hardware. However, how does frameDecimation and sizeDecimation relate to responsiveness and color quality/accuracy??

Any other tips on how to tweak the config to get improved responsiveness would be awesome! Thanks for creating this amazing project! The json-part/xbmc addon works perfectly, so would be nice to get the videograbber to work almost as responsive and smooth. :)

**Comment by clarkent86** [comment]
I have the same chipset as your grabber (STK1160) with ws2801 lights and I was wondering about the lag as well! It's not significant but it is noticeable with fast flashes.

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
