### ISSUE TITLE
Building für OpenELEC on Odroid

### ISSUE THREAD

**Issue by janhieber** [tvdzwan/hyperion#240]
Hi, great Software, used in on my PI.

Could you give me a few hints how to build this for OpenELEC on Odroid U3?
OpenELEC has no package management, i can use the toolchain from OpenELEC build and pull the dependencies manually.
Or could i build and run hyperion it in a chroot?
Your howtos are very rPI specific.

**Comment by Mitchou** [comment]
Hi Janhleber,

Any new info about how to compil for Odroid ??
I want buy an Odroid C1+ but I have to be sure that I can use Hyperion on it

**Comment by janhieber** [comment]
Hi,
it worked then but I use Embest MarS Board now with freescale/NXP i.MX6 SOC.


Am 17. Februar 2016 13:53:06 MEZ, schrieb Mitchou <notifications@github.com>:
>Hi Janhleber,
>
>Any new info about how to compil for Odroid ??
>I want buy an Odroid C1+ but I have to be sure that I can use Hyperion
>on it
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tvdzwan/hyperion/issues/240#issuecomment-185186455

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Mitchou** [comment]
You have compil from scratch or use Rpi install ??

**Comment by janhieber** [comment]
Can't remember. But on my i.MX with OpenELEC there are the libs missing for hyperion, like QT...

So I copied an Arch Linux ARM rootfs on the SDcard and used it with chroot from OpenELEC to compile and run hyperion.

There is the easy way, not the clean one ;)

Am 17. Februar 2016 14:17:47 MEZ, schrieb Mitchou <notifications@github.com>:
>You have compil from scratch or use Rpi install ??
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tvdzwan/hyperion/issues/240#issuecomment-185200376

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
