### ISSUE TITLE
Warnings when upgrading to jessie

### ISSUE THREAD

**Issue by NicoHood** [tvdzwan/hyperion#241]
I got the following warnings over and over when I try to upgrade to Jessie (instead of wheezy). Maybe this can be solved very simple, dunno.

```
insserv: warning: script 'K01hyperion' missing LSB tags and overrides
insserv: warning: script 'hyperion' missing LSB tags and overrides
```

Following this tutorial to upgrade:
http://www.raspberrypi.org/forums/viewtopic.php?f=66&t=92662

**Comment by milhouse34521** [comment]
Sounds like this might fix it. http://www.raspberrypi.org/forums/viewtopic.php?f=66&t=68263

**Comment by NicoHood** [comment]
Jessie is now officially available, I will close this now.
