### ISSUE TITLE
X11 grabber as service

### ISSUE THREAD

**Issue by Lockzi** [tvdzwan/hyperion#244]
Hello, I am trying to start the X11 grabber as service on Ubuntu Desktop 14.04 but I am getting:
"Failed to open the default X11-display"

What variables are required for starting X11 as a service running as root? Adding:
"export DISPLAY=:0"

does not seem to work either...

**Comment by pdf** [comment]
Just run the grabber as part of your user's login process, if you're using a desktop environment, it should have a GUI for adding startup programs, otherwise you might add it to `~/.xinitrc`.  This is a general Linux question, rather than hyperion-specific.

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
