### ISSUE TITLE
LIRC Remote Not Responding

### ISSUE THREAD

**Issue by osadiq** [tvdzwan/hyperion#246]
I'm using openelec and I have been able to reproduce this issue on raspbmc with no solution. After leaving my Pi untouched for a few hours (screensaver and menu framegrabber set to false), the lirc remote doesn't respond. I've tried it on gpio pin 23 and pin 11. After using the web remote to play a video, the lirc remote starts responding normally. I'm currently using ws2812b's running directly from gpio 18.
Disabling hyperion seems to resolve the issue. Any suggestions?

**Comment by thommy86** [comment]
I have almost the same problem.. Using WS2812b connected with an Arduino/USB to the Pi.. Just setup my Harmony Remote and it was working with the IR attached to the GPIO. After installing Hyperion, the remote stopt working.. Remote is connected to GPIO pin 18..

**Comment by osadiq** [comment]
Does the remote work after you play a video for a few minutes?

**Comment by thommy86** [comment]
No still not working. /dev/lirc0 Device or resource busy.. When I run fuser it gives me "397"

**Comment by osadiq** [comment]
what is process 397?

**Comment by thommy86** [comment]
Sorry, wanted to finish that post. I tried to change permissions, with no luck.. the process is:
 /usr/sbin/lircd --driver=default --device=/dev/lirc0 --uinput --output=/var/run/lirc/lircd-lirc0 --pidfile=/var/run/lirc/l

**Comment by thommy86** [comment]
I can't find a way to change the gpio for lirc.
The interference is clear. In openelec I can't edit /etc/modules 

RasPlex:~ # dmesg | grep lirc_rpi
[28522.391045] lirc_rpi: AIEEEE: 1 1 550f582c 550f57b6 5c83c 1c375
[28784.131831] lirc_rpi: AIEEEE: 0 0 550f5932 550f58ad 1c28a 1c445
[30123.928250] Modules linked in: snd_usb_audio snd_pcm snd_timer snd_hwdep snd_usb
midi_lib snd_rawmidi snd bluetooth iptable_filter ip_tables x_tables nfnetlink saa7
115 stk1160 videobuf2_core v4l2_common videodev videobuf2_vmalloc videobuf2_memops
cdc_acm lirc_rpi(C) lirc_dev rc_core

**Comment by osadiq** [comment]
I had a similar problem. I changed the gpio for the lircd in two steps.
1) Edit ~/.config/modprobe.d so that it has the line "blacklist lircd_rpi"
2) Add the line "modprobe lirc_rpi gpio_in_pin=11" to ~/.config/autostart.sh
Obviously change gpio_in_pin=11 to whatever pin you are using yourself.

**Comment by thommy86** [comment]
Still no luck! Placed the IR on pin 22.. and it works if I disable Hyperion, I am using the raspi 2 btw.

**Comment by osadiq** [comment]
Does it work after you start playing a video?

**Comment by thommy86** [comment]
No.. Not even after a few minutes. Only if I kill hyperiond.

**Comment by osadiq** [comment]
Have you connected the grounds on your rpi and powersupply powering the
leds? It helped me a little. I used the same pin as the ir ground.

**Comment by thommy86** [comment]
I have 1 power supply for everything. (5v10a) My Pi is powered with USB (connected to the same power supply) My leds are connected to an Arduino. the arduino is connect to the Pi with USB.

How can that make any difference? As I don't use the GPIO pins for the leds, is it possible to turn them off for Hyperion.. Or am I missing the point?

**Comment by JimmyBondi** [comment]
I have a similar Problem with my IR TSOP
But the problem is the V4L2 Grabber.
When i activate hyperion with the grabber, then the IR stops working.
When i activate hyperion without the V4L2 grabber or stop hyperion, then the IR starts working again.

This is, since the device tree is implemented early in the year.
In older OpenElec or Raspbmc Versions, everything works fine.

**Comment by thommy86** [comment]
What would be the solution in this situation? And who can we address to fix such an issue?

I am using a harmony 895 remote.. So it should be possible to stop V4L2 when I am using RasPlex (openelec).. Hyperion will use the standard grabber.. And when I switch to TV V4L2 should start again.. This would be a good workaround.

**Comment by JimmyBondi** [comment]
I have two config files for hyperion. One for use in Kodi and one for use with the grabber.
Hyperion does not start automatically. So i can be sure that IR is working, when the RPi starts.

I customized the keymap.xml and use the colour keys on the remote to switch the hyperion configs.

Red - start Hyperion without grabber (i use this to watch movies with kodi)
Yellow - start Hyperion with v4l2 grabber (i use this to watch sat-tv)
Blue - stop Hyperion

When i watch sat-tv then i usually do not need the IR.
In this case i use my smartphone to turn off hyperion or shutdown kodi (with yatse app on android)
I know this is a bit complicated, but HDMI-CEC does not work very well on my TV.

**Comment by thommy86** [comment]
Lirc is already active.. The remote works when Hyperion is off.. At the moment I use 1 hyperion config file.. But I will have to use 2 to disable the v4l2 grabber.. CEC also doesnt work here.. Each HDMI splitter I use will break CEC, thats why I am using IR now..

What you are doing seems devious.. Why can't you choose the right config when selecting the kodi channel? I have several activities on my remote, so it should be possible to switch config when switching activity.

**Comment by JimmyBondi** [comment]
This workaround is okay for me.
So I can turn hyperion on, when it goes darker outside.
But to program an little makro on the remote is a good idea...   :-D

**Comment by thommy86** [comment]
I edited the config by removing the v4l2 grabber.. Everything is working fine now. But I was thinking, How can you switch when v4l2 is on? the IR isn't working so how will it get the switch command?

**Comment by JimmyBondi** [comment]
When the v4l2 is on, I use the Hyperion Android App and chose a static colour from the colour wheel.
Then the IR is working again and I can switch the config.

I guess there is a way to use an other GPIO Pin, but i can't test it at the moment.
You can configure the Pin in the \flash\config.txt for example with:
dtoverlay=lirc-rpi,gpio_in_pin=16

**Comment by thommy86** [comment]
That's nice to know..! 

I have tried pin 22 but that gives the same problems. Just like described above.

**Comment by osadiq** [comment]
But  pin 22 works when hyperion is off?

**Comment by thommy86** [comment]
Yes 18 and 22 work when hyperion is off

**Comment by osadiq** [comment]
You're in the same spot as I am. Except I don't have the v412 frame grabber
in my settings at all. No idea what to do.

**Comment by thommy86** [comment]
What is your problem then? If v4l2 is off, hyperion and the remote work!

**Comment by osadiq** [comment]
IR remote stops working if openelec isn't used for a while. After turning
on a video or rebooting the device, it starts working. The remote stops
working half way through a TV show as well.

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you

**Comment by JimmyBondi** [comment]
please reopen.
Problem still exists !!!

**Comment by tpmodding** [comment]
@penfold42

**Comment by penfold42** [comment]
I have osmc and a tsop IR receiver
In is gpio 22
Out is gpio 17

**Comment by ThomasHack** [comment]
Can confirm. Problem still exists when hyperion is active. switching pins doesn't solve the problem

**Comment by Uatschitchun** [comment]
Same problem here, but with vdr.backend on libreelic (even cause of v4l2?) see:
https://forum.libreelec.tv/thread-4230.html
