### ISSUE TITLE
Philips Hue and personal username

### ISSUE THREAD

**Issue by ManusSs** [tvdzwan/hyperion#247]
I try to use my new Philips Hue with hyperion. The setup works perfectly good but for security reasons I would like to use another username than "newdeveloper" to link hyperion and my Hue bridge. Is-it possible to create username parameter in config file to do this ?

Actually the username "newdeveloper" is in "hard-text" in "libsrc/leddevice/LedDevicePhilipsHue.cpp ".

Best regards

**Comment by ntim** [comment]
I will look into this during this weekend. Regs...

**Comment by ManusSs** [comment]
Thank's.

Did you use the "transitiontime" parameter in the command sent to the bridge ? I see in Philips documentation the following information : 

"When you set the light state, and update color, brightness etc., the light will not respond immediately because by default there is a transition time to the new state of 400 milliseconds. If you want the light to respond quickly to a state change, set the transition time in the light state to zero milliseconds."
http://www.developers.meethue.com/things-you-need-know

**Comment by ntim** [comment]
Added both config options. Default transition time is now 100 ms which makes it  a lot snappier. Did not implement it in the past due to worries about the performance of the bridge (only 30 commands per second possible). But seems to work out quite well now.

**Comment by ManusSs** [comment]
I saw your modifications, thank's a lot !
I just have to wait the next compil to try the news options.
