### ISSUE TITLE
Build on Ubuntu 14.10 x64 successful, but ws2801 is not creatable

### ISSUE THREAD

**Issue by hanzoh** [tvdzwan/hyperion#249]
Hi,

I built hyperion from the latest source without any errors, but the application crashes when using the following configuration for my Arduino Uno with WS2801 LEDs:

>$ sudo hyperiond /etc/hyperion.conf.json
Application build time: Feb  1 2015 14:49:00
QCoreApplication initialised
Selected configuration file: /etc/hyperion.conf.json
ColorTransform 'default' => [0; 137]
Device configuration: 
{
	"colorOrder" : "rgb",
	"name" : "MyPi",
	"output" : "/dev/ttyACM1",
	"rate" : 115200,
	"type" : "ws2801"
}

Unable to create device ws2801
Black border threshold set to 0.01 (3)
Not creating any smoothing
Initializing Python interpreter
>$ 

However, when I set the type to "adalight", it starts up perfectly. (even though the LEDs don't work because they are is no Adalight controller, which is normal)

**Comment by Gamadril** [comment]
"type" : "ws2801" is for a configuration with a device with SPI bus support. In you case "type" must be one of the protocols your Arduino Uno has implemented to get data over serial port. hyperion needs to know in which format to send data to your external LED controller.

**Comment by tpmodding** [comment]
@hanzoh type must be adalight , connected with arduino and adalight sketch

can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
