### ISSUE TITLE
Not an issue: Updated to Openelec 5.0.1, it is working with Hyperion!!

### ISSUE THREAD

**Issue by cmvac** [tvdzwan/hyperion#252]
Just updated my Raspberry Pi B to the latest Openelec 5.0.1. I had the latest Gotham build installed and decided to update. After I did the usual manual update the ambilight responded immediately! You can change the Install on Openelec bit.

**Comment by slovdahl** [comment]
I can confirm what @cmvac says, I just got my LED strip, and after I connected it to my OpenELEC 5.0.1 RPi, installed hyperion and rebooted the lights turned on!

**Comment by tpmodding** [comment]
@cmvac could you close this pleasE?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
