### ISSUE TITLE
pi-blaster no reaction

### ISSUE THREAD

**Issue by ghost** [tvdzwan/hyperion#256]
I'm trying to use hyperion with pi-blaster.
the config for pins 17 (red), 22 (green) and 24 (blue) ist the following (full config here: http://pastebin.com/vg10z82f)
```
"device" :
	{
		"name"       : "MyPi",
		"type"       : "piblaster",
		"output"     : "/dev/pi-blaster",
		"assignment" : " r  g b "
	},
```

```
hyperion-remote --priority 50 --color red
```
has no effect on the light.

I think, that there's something wrong with the pins.
```
echo "17=1" > /dev/pi-plaster
```
works as it should

EDIT: I found the solution. In the past, pi-blaster worked with channels. Channel 0 was GPIO pin 4, Channel 1 was GPIO pin 17, etc.
Now you interact directly with the GPIO pin name.
So you're not using ```echo "1=1" > /dev/pi-blaster``` to activate pin 17.
You're supposed to use the pin number:
```
echo "17=1" > /dev/pi-blaster
```

**Comment by JimmyBondi** [comment]
I have the same problem.
Is there any way to get hyperion working with the actual pi-blaster version ?

**Comment by tvdzwan** [comment]
I think I accidentally broke the pi-blaster code. I will create an update that should bring the pi-blaster back to its original state.

**Comment by JimmyBondi** [comment]
It seems that it now works fine.
I can Adjust the Colors now with the Hyperion Android App :-)

**Comment by tpmodding** [comment]
@JimmyBondi could you close this issue please?

**Comment by brindosch** [comment]
Done
