### ISSUE TITLE
3D SBS (or TAB) and Hyperion for Kodi with Ubuntu ?

### ISSUE THREAD

**Issue by Nico83500** [tvdzwan/hyperion#258]
Hi,
I'm using Hyperion and it's a very good soft, thanks !
I have a question : does Hyperion for Kodi with Ubuntu manage 3D SBS or TAB ? If yes, how can I do to do that ? If not, does it support it on the future ?
I don't know if it's easily to scan only half of a screen with Hyperion but it could be the solution.
Thanks !

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
