### ISSUE TITLE
Confuguration : xbmcVideoChecker not working on OpenElec 5.0.2

### ISSUE THREAD

**Issue by Salokyn** [tvdzwan/hyperion#260]
Hi,

I am using OpenElec on a RPi B+ with a Lightberry driven by Hyperion.

Recently, I updated to OpenElec 5. I installed a the img found on their website for RPi. Then I installed hyperion with "install_hyperion.sh" and imported my old hyperion.config.json.

It works great, except the xbmcVideoChecker part. On the Kodi menu, my Lightberry is still working though it should not.

Here is the xbmcVideoChecker section of my hyperion.config.json :
```json
"xbmcVideoChecker" : 
	{
		"xbmcAddress" : "127.0.0.1",
		"xbmcTcpPort" : 9090,
		"grabVideo" : true,
		"grabPictures" : true,
		"grabAudio" : true,
		"grabMenu" : false,
		"grabScreensaver" : true,
		"enable3DDetection" : true
	}
```

What should I do to make it work ?

**Comment by Salokyn** [comment]
Duplicate of https://github.com/tvdzwan/hyperion/issues/223
Sorry

**Comment by dkruyt** [comment]
Got the same issue...

**Comment by tociek** [comment]
Same here... If I have grabber-v4l2 section defined, the leds won't work with video played from pi. If grabber-v4l2 section is not there, leds react to the video files.
I thought it was the fault of priority of g-v4l2 (currently 800) or to the remote control settings (both are on), but nothing helps.

**Comment by dkruyt** [comment]
Well, after I installed a new OpenElec and hyperion, it works. So not sure what happend before.

**Comment by drawlix** [comment]
it is on OpenElec 5.0.5 to

**Comment by tvdzwan** [comment]
There have been issues with the JSON interface of XBMC after updates (or fresh installs). Disabling and then enabling the JSON interface used to help solve this issue.

**Comment by Salokyn** [comment]
@tvdzwan How do you do that ?

**Comment by tvdzwan** [comment]
There is a menu option in xbmc under external interfaces. It says something like 'enable JSON interace' and 'allow external' (can not check right now exact terms). Just toggle them both (even if they are already on) and it should/could help with the issue you are seeing.

**Comment by Salokyn** [comment]
I'm sorry. I browsed all parameters menus in expert mode in Kodi and I found nothing about interfaces or JSON. Maybe I don't look in the right place.

**Comment by Salokyn** [comment]
Indeed, "Allow programs on other systems to control Kodi" must be checked in System/Settings/Services/Remote control.

Thank you !

**Comment by tociek** [comment]
Well, this solution does not work for me. I have tried several times turning it off and on and rebooting. Nothing helps. On the same system it used to work fine some time ago.

As far as I can tell hyperion is communication fine with XBMC so what else that could be?

V4L2 grabber stopped
effect finished
V4L2 grabber started
Message from XBMC: {"jsonrpc":"2.0","method":"Playlist.OnClear","params":{"data":{"playlistid":1},"sender":"xbmc"}}
Message from XBMC: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"The.Knick.S01E02.720p.HDTV.X264-DIMENSION.mkv","type":"movie"},"playlistid":1,"position":0},"sender":"xbmc"}}
Message from XBMC: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"title":"The.Knick.S01E02.720p.HDTV.X264-DIMENSION.mkv","type":"movie"},"player":{"playerid":1,"speed":1}},"sender":"xbmc"}}
Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
XBMC checker: switching to VIDEO mode
Message from XBMC: {"id":667,"jsonrpc":"2.0","result":{"item":{"file":"/var/media/file.mkv","label":"Tfile.mkv","type":"unknown"}}}
Message from XBMC: {"id":669,"jsonrpc":"2.0","result":{"stereoscopicmode":{"label":"Nieaktywne","mode":"off"}}}
Message from XBMC: {"jsonrpc":"2.0","method":"Player.OnStop","params":{"data":{"end":false,"item":{"title":"file.mkv","type":"movie"}},"sender":"xbmc"}}
XBMC checker: switching to OFF mode

The light do not work with video played from pi.

**Comment by tociek** [comment]
I have just found out that everything works fine as soon as I add frameGrabber section back.... 

@tvdzwan Does it make any sense to you?

**Comment by jorisbrauns** [comment]
Have the same issue, without the v4l2 grabber defined it works on xbmc, when placing it back it breaks.

Resetting the option like @Salokyn did not worked out for me...
Someone else any clue?
