### ISSUE TITLE
How to define two different color transformations

### ISSUE THREAD

**Issue by MtotheB** [tvdzwan/hyperion#261]
Hello,
first of all: Great work....I love it.

But one issue: Because of having two different lots of LED-chain I need to define two sets of transformation. By trying I didn't find syntax in hyp.config.json to set the first 50 LEDs in another way than the last ones. I duplicated the section with id 1;led 0-49 and id 2 ; led 50-123 but Hyperion didn't like my tries and stopped working.
Need help with the syntax please.

**Comment by tvdzwan** [comment]
The configuration tool should help you with getting the correct syntax. It is basically duplicating the existing transform section and setting the correct indices (zero-based). Make sure that you set the komma's in the right places as per json-standard.

**Comment by tpmodding** [comment]
@MtotheB can be closeD?
