### ISSUE TITLE
IR Remote to change config file?

### ISSUE THREAD

**Issue by RabidSnail90** [tvdzwan/hyperion#264]
First off, I am new to this world of Ambilight /Hyperion, and I have to say.. I love it!  Thank you to all who have contributed!

But I have found that different config files seem to work better with different video content (ex. Movies in a dark room with Black bars on the top VS. playing a video game in a lighted room with fast motion around the edges).  Not to mention that when the video source is off, the HDMI2AV device produces a rainbow effect... 

So my solution is to swap out config files.  Thats easy enough to do via SSH from my laptop, but that takes way too much time for every day use.  So, i figure there has to be a way to hook up an IR receiver to the RPi and use a universal remote to execute a series of commands to do the same thing I do through SSH.  

I will warn you that this is my first experience with an RPi, or Linux for that matter.  So it has been a little bit of a struggle.  But I have enjoyed the process thus far and would really like to continue to enhance my Ambilight setup.

Any help here is greatly appreciated!

**Comment by RabidSnail90** [comment]
Looks like I am going to be the first to respond to my own post :-p  So far I have successfully written .sh scripts to change the config files.  The scripts are real easy to write (maybe a no brainer for some here, but it took me an hour or so to figure out)  I also just purchased this IR receiver from Amazon.

http://www.amazon.com/gp/product/B00CW8WUGA/ref=od_aui_detailpages00?ie=UTF8&psc=1

I have no clue where im gonna go from here, but I think im on the right path.  

Anyone have any experience with LIRC?  I think that is my next thing to learn about...

**Comment by ctugt** [comment]
Did you got the remote to work? If so could you tell me how

**Comment by RabidSnail90** [comment]
I have not gotten it to work thus far.  I just ordered a different remote off eBay though so I'm still workin on it. If you have any luck keep me updated! I'll do the same!

**Comment by JimmyBondi** [comment]
Here ist a link to the german raspberry pi forum.
The User .bismark had all done, what you need to switch configs with the IR Remote.

http://www.forum-raspberrypi.de/Thread-hyperion-openelec-mit-automatisierter-ambilight-quellenumschaltung-rpi1-rpi2-17-03-15

**Comment by ctugt** [comment]
Many thanks i will go follow this
Op 26 mrt. 2015 12:21 schreef "JimmyBondi" <notifications@github.com>:

**Comment by JimmyBondi** [comment]
You're welcome !

and there is also a little problem with the v4l2 grabber / IR Remote combination
https://github.com/tvdzwan/hyperion/issues/246

**Comment by ctugt** [comment]
I have no idea where to start, my raspberry is connected trough a mce remote, now that works perfect with my harmony ultimate remote. but i need to redifine button, so if i press button X on the MCE remote, kodi has to start script....stable purple light. Any one with skills wanne help for a paypal donation?

**Comment by JimmyBondi** [comment]
when you're using kodi, just put a remote.xml in /storage/.kodi/userdata/keymaps
In the remote.xml is a section called "global" at the beginning
There you can (user-)define the buttons.
In my case I've editet the colour keys on my mce remote to switch different configs.

here ist my remote.xml

<?xml version="1.0" encoding="UTF-8"?>
































<keymap>
<global>
<remote>
<play>PlayPause</play>
<pause>Pause</pause>
<stop>Stop</stop>
<forward>FastForward</forward>
<reverse>Rewind</reverse>
<left>Left</left>
<right>Right</right>
<up>Up</up>
<down>Down</down>
<select>Select</select>
<enter>FullScreen</enter>
<pageplus>PageUp</pageplus>
<pageminus>PageDown</pageminus>
<back>Back</back>
<menu>PreviousMenu</menu>
<contentsmenu>PreviousMenu</contentsmenu>
<rootmenu>PreviousMenu</rootmenu>
<title>ContextMenu</title>
<info>Info</info>
<skipplus>SkipNext</skipplus>
<skipminus>SkipPrevious</skipminus>
<display>FullScreen</display>
<start>PreviousMenu</start>
<record>Record</record>
<eject>EjectTray()</eject>
<volumeplus>VolumeUp</volumeplus>
<volumeminus>VolumeDown</volumeminus>
<mute>Mute</mute>
<power>ShutDown()</power>
<myvideo>ActivateWindow(MyVideos)</myvideo>
<mymusic>ActivateWindow(MyMusic)</mymusic>
<mypictures>ActivateWindow(MyPictures)</mypictures>
<mytv>ActivateWindow(TVChannels)</mytv>
<guide>ActivateWindow(TVGuide)</guide>
<livetv>ActivateWindow(TVChannels)</livetv>
<liveradio>ActivateWindow(RadioChannels)</liveradio>
<recordedtv>ActivateWindow(TVRecordings)</recordedtv>
<epgsearch>ActivateWindow(TVSearch)</epgsearch>
<red>XBMC.RunScript(/storage/.kodi/addons/service.hyperion-switcher/switchHyperionSource.py, KODI)</red>
<green>XBMC.RunScript(/storage/.kodi/addons/service.hyperion-switcher/switchHyperionSource.py, KODI)</green>
<yellow>XBMC.RunScript(/storage/.kodi/addons/service.hyperion-switcher/switchHyperionSource.py,VIDEOGRABBER)</yellow>
<blue>XBMC.RunScript(/storage/.kodi/addons/service.hyperion-switcher/switchHyperionSource.py, STOP)</blue>
<zero>Number0</zero>
<one>Number1</one>
<two>JumpSMS2</two>
<three>JumpSMS3</three>
<four>JumpSMS4</four>
<five>JumpSMS5</five>
<six>JumpSMS6</six>
<seven>JumpSMS7</seven>
<eight>JumpSMS8</eight>
<nine>JumpSMS9</nine>
<print>Screenshot</print>
</remote>
</global>
<Home>
<remote>
<info>ActivateWindow(SystemInfo)</info>
<clear>ActivateWindow(Weather)</clear>
<hash>ActivateWindow(Settings)</hash>
</remote>
</Home>
<MyTVRecordings>
<remote>
<clear>Delete</clear>
<red>Red</red>
<green>Green</green>
<yellow>Yellow</yellow>
<blue>Blue</blue>
</remote>
</MyTVRecordings>
<MyTVTimers>
<remote>
<clear>Delete</clear>
<red>Red</red>
<green>Green</green>
<yellow>Yellow</yellow>
<blue>Blue</blue>
</remote>
</MyTVTimers>
<MyRadioRecordings>
<remote>
<clear>Delete</clear>
<red>Red</red>
<green>Green</green>
<yellow>Yellow</yellow>
<blue>Blue</blue>
</remote>
</MyRadioRecordings>
<MyRadioTimers>
<remote>
<clear>Delete</clear>
<red>Red</red>
<green>Green</green>
<yellow>Yellow</yellow>
<blue>Blue</blue>
</remote>
</MyRadioTimers>
<MyFiles>
<remote>
<clear>Delete</clear>
<zero>Highlight</zero>
<star>Move</star>
<hash>Rename</hash>
</remote>
</MyFiles>
<MyMusicPlaylist>
<remote>
<clear>Delete</clear>
<zero>Delete</zero>
</remote>
</MyMusicPlaylist>
<MyMusicPlaylistEditor>
<remote>
<zero>Queue</zero>
</remote>
</MyMusicPlaylistEditor>
<MyMusicFiles>
<remote>
<zero>Queue</zero>
<star>Queue</star>
</remote>
</MyMusicFiles>
<MyMusicLibrary>
<remote>
<zero>Queue</zero>
<star>Queue</star>
</remote>
</MyMusicLibrary>
<FullscreenVideo>
<remote>
<zero>Number0</zero>
<one>Number1</one>
<two>Number2</two>
<three>Number3</three>
<four>Number4</four>
<five>Number5</five>
<six>Number6</six>
<seven>Number7</seven>
<eight>Number8</eight>
<nine>Number9</nine>
<left>StepBack</left>
<right>StepForward</right>
<up>ChapterOrBigStepForward</up>
<down>ChapterOrBigStepBack</down>
<back>Back</back>
<menu>OSD</menu>
<contentsmenu>OSD</contentsmenu>
<rootmenu>OSD</rootmenu>
<start>OSD</start>
<select>OSD</select>
<title>CodecInfo</title>
<info>Info</info>
<guide>ActivateWindow(PVROSDGuide)</guide>
<teletext>ActivateWindow(Teletext)</teletext>
<subtitle>NextSubtitle</subtitle>
<star>NextSubtitle</star>
<language>AudioNextLanguage</language>
<playlist>Playlist</playlist>
<hash>AudioNextLanguage</hash>
<pageplus>SkipNext</pageplus>
<pageminus>SkipPrevious</pageminus>
</remote>
</FullscreenVideo>
<VideoTimeSeek>
<remote>
<select>Select</select>
<enter>Select</enter>
</remote>
</VideoTimeSeek>
<FullscreenInfo>
<remote>
<title>CodecInfo</title>
<info>Back</info>
<menu>OSD</menu>
<contentsmenu>OSD</contentsmenu>
<rootmenu>OSD</rootmenu>
</remote>
</FullscreenInfo>
<PlayerControls>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
</remote>
</PlayerControls>
<Visualisation>
<remote>
<left>StepBack</left>
<right>StepForward</right>
<up>SkipNext</up>
<down>SkipPrevious</down>
<back>Back</back>
<title>CodecInfo</title>
<select>ActivateWindow(VisualisationPresetList)</select>
<menu>OSD</menu>
<contentsmenu>OSD</contentsmenu>
<rootmenu>OSD</rootmenu>
<start>OSD</start>
<info>Info</info>
<guide>ActivateWindow(PVROSDGuide)</guide>
<playlist>ActivateWindow(PVROSDChannels)</playlist>
</remote>
</Visualisation>
<MusicOSD>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
<title>Info</title>
<info>CodecInfo</info>
</remote>
</MusicOSD>
<VisualisationSettings>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
</remote>
</VisualisationSettings>
<VisualisationPresetList>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
</remote>
</VisualisationPresetList>
<SlideShow>
<remote>
<zero>ZoomNormal</zero>
<one>ZoomLevel1</one>
<two>ZoomLevel2</two>
<three>ZoomLevel3</three>
<four>ZoomLevel4</four>
<five>ZoomLevel5</five>
<six>ZoomLevel6</six>
<seven>ZoomLevel7</seven>
<eight>ZoomLevel8</eight>
<nine>ZoomLevel9</nine>
<info>CodecInfo</info>
<skipplus>NextPicture</skipplus>
<skipminus>PreviousPicture</skipminus>
<title>Info</title>
<select>Rotate</select>
</remote>
</SlideShow>
<ScreenCalibration>
<remote>
<select>NextCalibration</select>
<zero>ResetCalibration</zero>
<display>NextResolution</display>
<xbox>NextResolution</xbox>
</remote>
</ScreenCalibration>
<GUICalibration>
<remote>
<select>NextCalibration</select>
<zero>ResetCalibration</zero>
</remote>
</GUICalibration>
<VideoOSD>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
<start>Back</start>
</remote>
</VideoOSD>
<VideoMenu>
<remote>
<menu>OSD</menu>
<contentsmenu>OSD</contentsmenu>
<rootmenu>OSD</rootmenu>
<info>Info</info>
<title>CodecInfo</title>
<zero>Number0</zero>
<one>Number1</one>
<two>Number2</two>
<three>Number3</three>
<four>Number4</four>
<five>Number5</five>
<six>Number6</six>
<seven>Number7</seven>
<eight>Number8</eight>
<nine>Number9</nine>
<play>Select</play>
<pageplus>SkipNext</pageplus>
<pageminus>SkipPrevious</pageminus>
</remote>
</VideoMenu>
<OSDVideoSettings>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
<start>Back</start>
</remote>
</OSDVideoSettings>
<OSDAudioSettings>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
<start>Back</start>
</remote>
</OSDAudioSettings>
<VideoBookmarks>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
<start>Back</start>
<zero>Delete</zero>
</remote>
</VideoBookmarks>
<MyVideoLibrary>
<remote>
<zero>Queue</zero>
<clear>Delete</clear>
</remote>
</MyVideoLibrary>
<MyVideoFiles>
<remote>
<zero>Queue</zero>
<star>Queue</star>
</remote>
</MyVideoFiles>
<MyVideoPlaylist>
<remote>
<clear>Delete</clear>
<zero>Delete</zero>
</remote>
</MyVideoPlaylist>
<VirtualKeyboard>
<remote>
<back>BackSpace</back>
<star>Shift</star>
<hash>Symbols</hash>
<zero>Number0</zero>
<one>Number1</one>
<two>Number2</two>
<three>Number3</three>
<four>Number4</four>
<five>Number5</five>
<six>Number6</six>
<seven>Number7</seven>
<eight>Number8</eight>
<nine>Number9</nine>
<enter>Enter</enter>
<pageminus>CursorLeft</pageminus>
<pageplus>CursorRight</pageplus>
</remote>
</VirtualKeyboard>
<ContextMenu>
<remote>
<title>Back</title>
</remote>
</ContextMenu>
<Scripts>
<remote>
<info>info</info>
</remote>
</Scripts>
<NumericInput>
<remote>
<zero>Number0</zero>
<one>Number1</one>
<two>Number2</two>
<three>Number3</three>
<four>Number4</four>
<five>Number5</five>
<six>Number6</six>
<seven>Number7</seven>
<eight>Number8</eight>
<nine>Number9</nine>
<enter>Enter</enter>
<back>BackSpace</back>
</remote>
</NumericInput>
<Weather>
<remote>
<back>PreviousMenu</back>
</remote>
</Weather>
<Settings>
<remote>
<back>PreviousMenu</back>
</remote>
</Settings>
<AddonBrowser>
<remote>
</remote>
</AddonBrowser>
<AddonInformation>
<remote>
<back>Close</back>
</remote>
</AddonInformation>
<AddonSettings>
<remote>
<back>Close</back>
</remote>
</AddonSettings>
<TextViewer>
<remote>
<back>Close</back>
</remote>
</TextViewer>
<MyPicturesSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</MyPicturesSettings>
<MyProgramsSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</MyProgramsSettings>
<MyWeatherSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</MyWeatherSettings>
<MyMusicSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</MyMusicSettings>
<SystemSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</SystemSettings>
<MyVideosSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</MyVideosSettings>
<NetworkSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</NetworkSettings>
<AppearanceSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</AppearanceSettings>
<Profiles>
<remote>
<back>PreviousMenu</back>
</remote>
</Profiles>
<systeminfo>
<remote>
<back>PreviousMenu</back>
</remote>
</systeminfo>
<shutdownmenu>
<remote>
<back>PreviousMenu</back>
</remote>
</shutdownmenu>
<submenu>
<remote>
<back>PreviousMenu</back>
</remote>
</submenu>
<MusicInformation>
<remote>
<info>Back</info>
</remote>
</MusicInformation>
<MovieInformation>
<remote>
<info>Back</info>
</remote>
</MovieInformation>
<LockSettings>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
</remote>
</LockSettings>
<ProfileSettings>
<remote>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
</remote>
</ProfileSettings>
<PictureInfo>
<remote>
<skipplus>NextPicture</skipplus>
<skipminus>PreviousPicture</skipminus>
<info>Back</info>
</remote>
</PictureInfo>
<Teletext>
<remote>
<zero>number0</zero>
<one>number1</one>
<two>number2</two>
<three>number3</three>
<four>number4</four>
<five>number5</five>
<six>number6</six>
<seven>number7</seven>
<eight>number8</eight>
<nine>number9</nine>
<red>Red</red>
<green>Green</green>
<yellow>Yellow</yellow>
<blue>Blue</blue>
<info>Info</info>
<menu>Back</menu>
<contentsmenu>Back</contentsmenu>
<rootmenu>Back</rootmenu>
<start>Back</start>
<teletext>Back</teletext>
</remote>
</Teletext>
<Favourites>
<remote>
<back>Close</back>
</remote>
</Favourites>
<FullscreenLiveTV>
<remote>
<left>StepBack</left>
<right>StepForward</right>
<up>ChannelUp</up>
<down>ChannelDown</down>
</remote>
</FullscreenLiveTV>
<FullscreenRadio>
<remote>
<left>StepBack</left>
<right>StepForward</right>
<up>ChannelUp</up>
<down>ChannelDown</down>
</remote>
</FullscreenRadio>
<PVROSDChannels>
<remote>
<back>Close</back>
<menu>Close</menu>
<contentsmenu>Close</contentsmenu>
<rootmenu>Close</rootmenu>
<start>Close</start>
<playlist>Close</playlist>
</remote>
</PVROSDChannels>
<PVROSDGuide>
<remote>
<back>Close</back>
<menu>Close</menu>
<contentsmenu>Close</contentsmenu>
<rootmenu>Close</rootmenu>
<start>Close</start>
<guide>Close</guide>
</remote>
</PVROSDGuide>
<MyTVSettings>
<remote>
<back>PreviousMenu</back>
</remote>
</MyTVSettings>
<AddonSettings>
<remote>
<clear>Delete</clear>
</remote>
</AddonSettings>
<Addon>
<remote>
<red>Red</red>
<green>Green</green>
<yellow>Yellow</yellow>
<blue>Blue</blue>
</remote>
</Addon>
</keymap>

**Comment by ctugt** [comment]
This is exactly what is was looking for i will defintly try this thanks may
i ask which led strip youre using if the ws2801 could youv share youre
config with us
Op 26 mrt. 2015 21:17 schreef "JimmyBondi" <notifications@github.com>:

**Comment by ctugt** [comment]
Could you also send me youre hyperion config switch files?
Many many thanks

2015-03-27 0:52 GMT+01:00 Thomas Dalen, van <thomasvdalen@gmail.com>:

> This is exactly what is was looking for i will defintly try this thanks
> may i ask which led strip youre using if the ws2801 could youv share youre
> config with us
> Op 26 mrt. 2015 21:17 schreef "JimmyBondi" <notifications@github.com>:
>
> when you're using kodi, just put a remote.xml in
>> /storage/.kodi/userdata/keymaps
>> In the remote.xml is a section called "global" at the beginning
>> There you can (user-)define the buttons.
>> In my case I've editet the colour keys on my mce remote to switch
>> different configs.
>>
>> here ist my remote.xml
>>
>> <?xml version="1.0" encoding="UTF-8"?>
>>
>>
>>
>>
>> PlayPause
>> Pause
>> Stop
>> FastForward
>> Rewind
>> Left
>> Right
>> Up
>> Down
>> Select
>> FullScreen
>> PageUp
>> PageDown
>> Back
>> PreviousMenu
>> PreviousMenu
>> PreviousMenu
>> ContextMenu
>> Info
>> SkipNext
>> SkipPrevious
>> FullScreen
>> PreviousMenu
>> Record
>> EjectTray()
>> VolumeUp
>> VolumeDown
>> Mute
>> ShutDown()
>> ActivateWindow(MyVideos)
>> ActivateWindow(MyMusic)
>> ActivateWindow(MyPictures)
>> ActivateWindow(TVChannels)
>> ActivateWindow(TVGuide)
>> ActivateWindow(TVChannels)
>> ActivateWindow(RadioChannels)
>> ActivateWindow(TVRecordings)
>> ActivateWindow(TVSearch)
>> XBMC.RunScript(/storage/.kodi/addons/service.hyperion-switcher/switchHyperionSource.py,
>> KODI)
>> XBMC.RunScript(/storage/.kodi/addons/service.hyperion-switcher/switchHyperionSource.py,
>> KODI)
>>
>> XBMC.RunScript(/storage/.kodi/addons/service.hyperion-switcher/switchHyperionSource.py,VIDEOGRABBER)
>> XBMC.RunScript(/storage/.kodi/addons/service.hyperion-switcher/switchHyperionSource.py,
>> STOP)
>> Number0
>> Number1
>> JumpSMS2
>> JumpSMS3
>> JumpSMS4
>> JumpSMS5
>> JumpSMS6
>> JumpSMS7
>> JumpSMS8
>> JumpSMS9
>> Screenshot
>>
>>
>>
>>
>> ActivateWindow(SystemInfo)
>> ActivateWindow(Weather)
>> ActivateWindow(Settings)
>>
>>
>>
>>
>> Delete
>> Red
>> Green
>> Yellow
>> Blue
>>
>>
>>
>>
>> Delete
>> Red
>> Green
>> Yellow
>> Blue
>>
>>
>>
>>
>> Delete
>> Red
>> Green
>> Yellow
>> Blue
>>
>>
>>
>>
>> Delete
>> Red
>> Green
>> Yellow
>> Blue
>>
>>
>>
>>
>> Delete
>> Highlight
>> Move
>> Rename
>>
>>
>>
>>
>> Delete
>> Delete
>>
>>
>>
>>
>> Queue
>>
>>
>>
>>
>> Queue
>> Queue
>>
>>
>>
>>
>> Queue
>> Queue
>>
>>
>>
>>
>> Number0
>> Number1
>> Number2
>> Number3
>> Number4
>> Number5
>> Number6
>> Number7
>> Number8
>> Number9
>> StepBack
>> StepForward
>> ChapterOrBigStepForward
>> ChapterOrBigStepBack
>> Back
>> OSD
>> OSD
>> OSD
>> OSD
>> OSD
>> CodecInfo
>> Info
>> ActivateWindow(PVROSDGuide)
>> ActivateWindow(Teletext)
>> NextSubtitle
>> NextSubtitle
>> AudioNextLanguage
>> Playlist
>> AudioNextLanguage
>> SkipNext
>> SkipPrevious
>>
>>
>>
>>
>> Select
>> Select
>>
>>
>>
>>
>> CodecInfo
>> Back
>> OSD
>> OSD
>> OSD
>>
>>
>>
>>
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> StepBack
>> StepForward
>> SkipNext
>> SkipPrevious
>> Back
>> CodecInfo
>> ActivateWindow(VisualisationPresetList)
>> OSD
>> OSD
>> OSD
>> OSD
>> Info
>> ActivateWindow(PVROSDGuide)
>> ActivateWindow(PVROSDChannels)
>>
>>
>>
>>
>> Back
>> Back
>> Back
>> Info
>> CodecInfo
>>
>>
>>
>>
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> ZoomNormal
>> ZoomLevel1
>> ZoomLevel2
>> ZoomLevel3
>> ZoomLevel4
>> ZoomLevel5
>> ZoomLevel6
>> ZoomLevel7
>> ZoomLevel8
>> ZoomLevel9
>> CodecInfo
>> NextPicture
>> PreviousPicture
>> Info
>> Rotate
>>
>>
>>
>>
>> NextCalibration
>> ResetCalibration
>> NextResolution
>> NextResolution
>>
>>
>>
>>
>> NextCalibration
>> ResetCalibration
>>
>>
>>
>>
>> Back
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> OSD
>> OSD
>> OSD
>> Info
>> CodecInfo
>> Number0
>> Number1
>> Number2
>> Number3
>> Number4
>> Number5
>> Number6
>> Number7
>> Number8
>> Number9
>> Select
>> SkipNext
>> SkipPrevious
>>
>>
>>
>>
>> Back
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> Back
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> Back
>> Back
>> Back
>> Back
>> Delete
>>
>>
>>
>>
>> Queue
>> Delete
>>
>>
>>
>>
>> Queue
>> Queue
>>
>>
>>
>>
>> Delete
>> Delete
>>
>>
>>
>>
>> BackSpace
>> Shift
>> Symbols
>> Number0
>> Number1
>> Number2
>> Number3
>> Number4
>> Number5
>> Number6
>> Number7
>> Number8
>> Number9
>> Enter
>> CursorLeft
>> CursorRight
>>
>>
>>
>>
>> Back
>>
>>
>>
>>
>> info
>>
>>
>>
>>
>> Number0
>> Number1
>> Number2
>> Number3
>> Number4
>> Number5
>> Number6
>> Number7
>> Number8
>> Number9
>> Enter
>> BackSpace
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>>
>>
>>
>>
>> Close
>>
>>
>>
>>
>> Close
>>
>>
>>
>>
>> Close
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> Back
>>
>>
>>
>>
>> Back
>>
>>
>>
>>
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> NextPicture
>> PreviousPicture
>> Back
>>
>>
>>
>>
>> number0
>> number1
>> number2
>> number3
>> number4
>> number5
>> number6
>> number7
>> number8
>> number9
>> Red
>> Green
>> Yellow
>> Blue
>> Info
>> Back
>> Back
>> Back
>> Back
>> Back
>>
>>
>>
>>
>> Close
>>
>>
>>
>>
>> StepBack
>> StepForward
>> ChannelUp
>> ChannelDown
>>
>>
>>
>>
>> StepBack
>> StepForward
>> ChannelUp
>> ChannelDown
>>
>>
>>
>>
>> Close
>> Close
>> Close
>> Close
>> Close
>> Close
>>
>>
>>
>>
>> Close
>> Close
>> Close
>> Close
>> Close
>> Close
>>
>>
>>
>>
>> PreviousMenu
>>
>>
>>
>>
>> Delete
>>
>>
>>
>>
>> Red
>> Green
>> Yellow
>> Blue
>>
>>
>>  —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tvdzwan/hyperion/issues/264#issuecomment-86697865>.
>>
>


-- 
Met vriendelijke Groet,

Thomas van Dalen
*E*: thomasvdalen@gmail.com
*T*: 06 831 680 37

**Comment by ctugt** [comment]
I use two buttons on my MCE remote, blue for switching on/off, yellow to create a static purple colour. This is how (if you know this its really easy to change the purple colour to youre like)

On/off script for hyperion Remote. In /storage/.kodi/userdata/keymaps/remote.xml define:
<yellow>RunScript("/storage/hyperion/effects/purple.py")</yellow>
<blue>>RunScript("/storage/hyperion/effects/hyperionswitch.py")</blue>

Then create two files in the /storage/hyperion/effects folder.
One called purple.py with this content:
import subprocess
<lrusak> subprocess.Popen('/storage/hyperion/bin/hyperion-remote.sh --priority 100 --color purple', shell=True)

One called hyperionswitch.py with this content:
import subprocess

pid = subprocess.Popen('pidof hyperiond', shell=True, close_fds=True, stdout=subprocess.PIPE)

try:
    if pid.stdout.readlines():
        subprocess.Popen('killall hyperiond', shell=True)
    else:
        subprocess.Popen('/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &', shell=True)
except Exception, e:
    pass

now reboot and thats it.

**Comment by tpmodding** [comment]
@RabidSnail90 can be closed?

ps: this is not an hyperion issue :)
