### ISSUE TITLE
Hyperion no autostart after reboot RASPBMC

### ISSUE THREAD

**Issue by WorkerJJ** [tvdzwan/hyperion#265]
I've a Raspbmc clean installation, last version "raspbmc-rls-1.0-hardfp-b20130208-u20150125". Install hyperion and script works fine, start hyperiond and leds on, but on pi reboot don't autostart hyperion. I execute on ssh "initctl start hyperion" or "service hyperion start" and work fine and leds on again. 

"/etc/init/hyperion.conf" is correct (with #modprobe spidev).

I found how solve this issue, edit vnc.conf and paste hyperion.conf  content, and then active check box con raspbmc configuration app. This work and hyperion start on startup, but is a botched job.

Why hyperion.conf is ignored at startup?

**Comment by WorkerJJ** [comment]
On XBIAN last version works fine!.

**Comment by tpmodding** [comment]
@WorkerJJ fixed? need help? or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
