### ISSUE TITLE
Choose Philips Hue Lights to use with hyperion

### ISSUE THREAD

**Issue by ManusSs** [tvdzwan/hyperion#268]
I have 3 Hue Lamp LCT001 and 1 LightStrip LST001. For my hyperion config, I want to use my last Hue Lamp LCT001 (third lamp register on the Bridge) and my LightStrip LST001 (fourth device register).

If I change the index led parameter of the hyperion JSON config, I'm not able to choose Hue device to use. It's everytime the two first device.

@ntim Can you help me on this ?

**Comment by ntim** [comment]
Ok, this is currently not possible, but
I will look into it this week. Will come back to you.

Tim

**Comment by ntim** [comment]
Hi, I implemented a new device config option. I will test this before creating a pull request but you can have a look here:

https://github.com/ntim/hyperion/tree/support_for_philips_hue

The option would be e.g. "lightIds: [1, 2, 3]" and to be added to the device section of you hyperion.config.json

**Comment by kleusch** [comment]
Do I understand it right, that I can control with this option the lamps of my HUE products? E.g. if I set lightIds to [1, 3] my first and third device is controlled by hyperion?

What do I have to do to get the modifications and update my hyperion?

**Comment by ntim** [comment]
Correct. The necessary code is now in the main repository of hyperion. Not sure if this is already in the latest binary but you can always compile from source following the CompileHowTo.

**Comment by ntim** [comment]
I think this one is resolved, please close!
