### ISSUE TITLE
Arduino connection

### ISSUE THREAD

**Issue by Phil1988** [tvdzwan/hyperion#27]
I open this issue to discuss and realize an connection to an arduino that controlls the LEDs.

At the moment I have set the device type at the hyperion config as "adalight".
On my tv are 94 LEDs.

The adalight sends a 6byte header in front of the LED-color-data.

It looks like..
_ledBuffer[0] = 'A';
_ledBuffer[1] = 'd';
_ledBuffer[2] = 'a';
_ledBuffer[3] = ((ledValues.size() - 1) >> 8) & 0xFF; // LED count high byte
_ledBuffer[4] = (ledValues.size() - 1) & 0xFF; // LED count low byte
_ledBuffer[5] = _ledBuffer[3] ^ _ledBuffer[4] ^ 0x55; // Checksum

The Arduino is directly connected to the RPis GPIO.
But only the TXD of the PI to the RX of the arduino (because of different voltage and a Arduino TX -> RxD of the PI would damage it).

The baudrate is set to 115200 and the arduino is readings 6 bytes.
Checks if:
byte 0 == 'A' 
byte 1 =='d'
and byte 2 == 'a' 
to ensure that the arduino received the header.

If so it reads 3 Bytes and writes the values to the first led.
then the next 3 bytes to the next led....

It saves the "LED count low byte" as number of the LEDs (at the moment i dont need more then 255 leds) to ensure it just does this the needed time.

after this it sets the lights up:
LEDS.show(); 

and read another 6 bytes to start the "next round".

On ambi-tv everything worked well so my hardware can work together and is not broken.

**Comment by tpmodding** [comment]
arduino works perfectly with hyperion, think can be closed?

**Comment by brindosch** [comment]
I will close it, just start a new discussion if problems occur.
