### ISSUE TITLE
HDMI UVC Grabber

### ISSUE THREAD

**Issue by Hackmodford** [tvdzwan/hyperion#270]
I found a video of a hdmi grabber working on the pi. Has anyone tried this? Think it would work? I'm willing to test it if I can get my hands on one :)

http://youtu.be/4520K1HMXiw

As I find more info I'll post here.

It looks like it doesn't support HDCP :(
I emailed the guy to see if there's a version that does and has a low res output.

**Comment by derTim** [comment]
More Info on the grabber:
http://febon.blogspot.com/2013/10/febon168-uvc-usb-hdmi-grabber-card-user.html

There are 2 models, the up/downscaling version looks interesting, input from 480p to 1080p and always 720p 30fps mjpeg output.

129€ + shipping according to the following review video, a little bit too much for me :)
https://www.youtube.com/watch?v=0hYnkrFSyig

**Comment by Hackmodford** [comment]
Look at this! http://www.auvidea.com/index.php/theme-styles/2013-06-22-21-23-34/raspberry-pi-hdmi-in
Again, no HDCP support :(

**Comment by Hackmodford** [comment]
LOL something like this would solve everything... If it worked with Linux
http://www.roxio.com/enu/products/game-capture/console/overview.html

**Comment by Hackmodford** [comment]
He doesn't have a version that supports HDCP, but it's possible the hdmi splitter strips it right?

**Comment by tpmodding** [comment]
@Hackmodford can this be closed?

**Comment by Hackmodford** [comment]
Sure
