### ISSUE TITLE
BORDER SWITCH REQUIRED, what does it mean?

### ISSUE THREAD

**Issue by Fabi1080** [tvdzwan/hyperion#271]
I have added the grabber-v4l2 part to my config and now I get the message: BORDER SWITCH REQUIRED!! CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0.
What does it mean and where does it come from? (Is there any way to search in the source code online on github?)

The update rate of my leds is very very low, like once every two seconds. 
When i don't start the grabber via config, but manually, everything works fine.

**Comment by Fabi1080** [comment]
Ok Googling "Border Switch required" site:https://github.com/tvdzwan/hyperion gives me the hint that it has something to do with the blackborder detector. Does it make a difference in which order things are defined in the config file?

**Comment by tvdzwan** [comment]
The border switch is nothing to worry about. It means that the automatic detected a different black-border then before and is switching the removal algorithm to compensate.  
Your second issue seems related to starting the 'service'. It could be that it is using a different configuration file. How are you starting manually? The default installation takes the config-file from '/etc/hyperion.config.json'.

**Comment by polykoma** [comment]
i think we are starting via config file.
as i understand this isnt manually?!
the /etc/hyperion.config.json  ist just a link to the main config file folder /opt/hyperion/config ?

we replaced our config there with "frame grabber" section excluded. and the extra v4l2grabber included.

should we replace the "link" with the same main file from opt folder ?
or can we ignore this message

**Comment by tvdzwan** [comment]
The link in /etc is only created if there is no file present and will then link to /opt/hyperion/config. The idea is that the user can put its own configuration in /etc and this will not be overwritten by running the update script.
The order in the json file does not matter as long as it is proper json (easy to get a komma wrong).

**Comment by tpmodding** [comment]
@Fabi1080 kannst ma schliessen bitte :D danke
