### ISSUE TITLE
WS2801 RPI2 190LED's 'stuttering'

### ISSUE THREAD

**Issue by benjy3gg** [tvdzwan/hyperion#272]
Hi,

i have a RPI2 with OpenELEC 5.0.4 and i use it to drive 190 WS2801 LED's.
When the color changes i get "stuttering" which means that the smoothing just isn't smooth.

I also have another hyperion instance running that is driving my backlight through adalight (arduino) with 50LED's and that one is running smooth.

Is it because of the high number of LED's or can i do anything about it?

**Comment by tvdzwan** [comment]
If your 'baudrate' for the device is too low, it could cause issues which are related to the length of the led-string. You should be able to increase this to around 100k, but some people have reported interference with other systems.

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
