### ISSUE TITLE
Average color over all leds

### ISSUE THREAD

**Issue by mhaggren** [tvdzwan/hyperion#273]
Hi!

First of all. Great work with this feature:)
Before I got this, I had a philips Hue Led strip behind the TV and used a xbmc addon that calculated the average color of the movie and used this color on the strip.
I think this is a great feature when watching a movie that doesn't suite the flickering effects of the ambilight. 
Would this be possible to write in a configure file, to be used when watching this kind of movies?

//Magnus

**Comment by tpmodding** [comment]
you must only manually edit the hscan and vscan part :)
could you close this issue?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
