### ISSUE TITLE
App values

### ISSUE THREAD

**Issue by mhaggren** [tvdzwan/hyperion#274]
Hi!

Happy to see the uppdate on the iOS app. 
But the values Max on 1.00, like the gamma level can only be set to 1 as Max.

**Comment by tpmodding** [comment]
@mhaggren can be closed?

**Comment by brindosch** [comment]
We are not affiliated with the ios app

closed

**Comment by tpmodding** [comment]
You can contact him on his site

https://chaosspace.de/contact
