### ISSUE TITLE
multiple "colorOrder" possible ?

### ISSUE THREAD

**Issue by falbalala** [tvdzwan/hyperion#276]
Well, I am facing a problem. I have 2 LED strips which WS2801 not the same "order bytes color".

First LED strip | Second LED strip
------------ | -------------
RGB | GBR

Is there a solution for more "order bytes color" in the same config.json ?

> PS: If you have not already, it will be better to have the "colorOrder": "rgb" in "color" "transfom" rather than in "device".

**Comment by tvdzwan** [comment]
It is possible since a short while to specify the color-order per led. Add the coloroder-tag to each led that you want a different order for (or add it to all of them).

**Comment by falbalala** [comment]
Thank you very much, it works perfectly.
### Problem solved.

> PS: thank you for the great work and for the future.
