### ISSUE TITLE
Hyperion on OpenElec 5.0.5

### ISSUE THREAD

**Issue by r3dr4bbit** [tvdzwan/hyperion#277]
I recently received the new Raspberry PI 2 and loaded it with OpenElec 5.0.5.  Installation of Hyperion went fine, copied the config from my RPI 1, which is currently working fine, but I cant seem to get output to the RPI 2.  Running ps shows hyperiond.sh is running with the correct config.  LEDS have power.  I am using WS2812b and GPIO18 to drive them.

**Comment by r3dr4bbit** [comment]
OpenELEC:/flash # ps
< Some stuff removed>
  357 root       0:00 {hyperiond.sh} /bin/sh /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.c
< Some stuff removed>
OpenELEC:/flash # /storage/hyperion/bin/hyperion-remote.sh  --effect "Rainbow swirl fast" --duration 300000
Connected to localhost:19444
Start effect Rainbow swirl fast

**Comment by r3dr4bbit** [comment]
Possibly to do with the increase frequency of the processor?

I don't have a scope nearby

**Comment by r3dr4bbit** [comment]
Used a scope and could not find any output on GPIO18. 

Possibly the change of the PWM address on the DMA controller?

**Comment by tociek** [comment]
Have you turned SPI on in config.txt?

pt., 6 mar 2015, 05:07 r3dr4bbit użytkownik <notifications@github.com>
napisał:

**Comment by r3dr4bbit** [comment]
Correct me if am wrong, but the WS2812b implementation does not use SPI.  Rather it uses a PWM signal generated on the PCM_Clock.

**Comment by r3dr4bbit** [comment]
As suspected, it is a problem with the new memory address.

See fix here: https://github.com/tvdzwan/hyperion/issues/6#issuecomment-77109750
