### ISSUE TITLE
Ambient light sensor integration / hyperiond configuration change realtime

### ISSUE THREAD

**Issue by Domas1232** [tvdzwan/hyperion#279]
I have an ambient light sensor and I want to change whiteLevel or valueGain parameters depending on the sensor data.

Is it possible to make hyperion re-read configuration file without a restart?
Ir it possible to make a json request with new settings to hyperiond ?

**Comment by Fabi1080** [comment]
You can set the values temporarely (until the next restart of hyperion) via the hyperion-remote app (https://github.com/tvdzwan/hyperion/wiki/Command-line-utility#usage) or sending requests to the json server.
