### ISSUE TITLE
hyperion cpu loads

### ISSUE THREAD

**Issue by Domas1232** [tvdzwan/hyperion#280]
Why does hyperion use CPU even if it's not working (kodi is at idle) ?

root      2905  1.2  2.0  70856 15388 ?        Ssl  12:42   5:47 /usr/bin/hyperiond /etc/hyperion.config.json
 20:38:15 up 1 day, 18 min,  1 user,  load average: 0.30, 0.34, 0.35

**Comment by tvdzwan** [comment]
The processor usage when kodi is idle depends on your configuration. If, for example, you have smoothing enabled, the color of your leds will continuously updated. It could also be that the frame-grabber is still grabbing, even if there is nothing on the screen.
I always have difficulty with interpreting the load averages. Are they high enough to worry about?

**Comment by Domas1232** [comment]
thanks for answer.

How to make grabber work ONLY if movie is running ?

**Comment by tpmodding** [comment]
only set video true :)

@Domas1232 can be closed?

**Comment by brindosch** [comment]
Should be done
