### ISSUE TITLE
New RPI2 release

### ISSUE THREAD

**Issue by tjandt** [tvdzwan/hyperion#281]
Could you update the RPI binaries for RPI2? Maybe with ARMv7 and eventually NEON optimizations?

Does anyone has some experiences about performance increase?

**Comment by tvdzwan** [comment]
As I understood it, the current binaries are compatible with the RPI2. 
Therefor I do not expect we will release an specifically optimised version for the RPI2. I also do not expect huge performance increase as a lot of processing is capturing input (from video-stream/device) and writing output to led device which does not benefit from NEON. 
Do you have experience with optimisation for ARM with NEON?

**Comment by tpmodding** [comment]
@tjandt could you close this issue? thanks

**Comment by tpmodding** [comment]
Closed -> works on rpi2
Thank you
