### ISSUE TITLE
rasplex 0.5.1

### ISSUE THREAD

**Issue by phishlite** [tvdzwan/hyperion#283]
I have a issue with RPI2 and rasplex 0.5.1
1/ pgrep seems to be not implemented in 0.5.1 (bypassed with "ps aux | grep $NAME | wc -l) = 2" in hyperion.init.sh
however, after starting the deamon, when i check the status, i have this result : Checking hyperiond...                             Process dead but pidfile exists"
and i can't solve this error :(

**Comment by tvdzwan** [comment]
You could try and run hyperion from the commandline and see if the output gives clue why it is not running:
```bash
hyperiond /etc/hyperion.config.json
```

**Comment by tvdzwan** [comment]
I believe more people have issues with the installation on the RPI2 (not
rasplex specific). For some reason the service is not recognized. We will
look into it.

**Comment by phishlite** [comment]
Hi
After a reinstall by following your procedure in the wiki, everything works normally. 
However, I found that the GPIO port RP2 are not enabled by default in rapslex (not tested under OpenELEC). Simply add the parameter
<code> dtparam=spi=on</code>
in /flash/config.txt file to working again.

**Comment by tvdzwan** [comment]
Thanks for the information. We will add the information to our installation
instructions.
