### ISSUE TITLE
Wiki: ws2812B picture

### ISSUE THREAD

**Issue by NicoHood** [tvdzwan/hyperion#287]
https://github.com/tvdzwan/hyperion/wiki/WS2812b-PWM

The connection picture is missing

**Comment by tvdzwan** [comment]
I do not have the picture in question, maybe @kammerjaeger could push it to the wiki?

**Comment by kammerjaeger** [comment]
How can I do that? I could not find a button to add pictures directly on the wiki pages (or am I missing something).
I checked out the wiki git, but can not push the changes there:

git.exe push --progress "origin" master:master

remote: Permission to tvdzwan/hyperion.wiki.git denied to kammerjaeger.
fatal: unable to access 'https://kammerjaeger@github.com/tvdzwan/hyperion.wiki.git/': The requested URL returned error: 403

Is this the wrong way to do it? I could only find a guide how to add an external link.

**Comment by NicoHood** [comment]
Picture seems to be back
