### ISSUE TITLE
Not an issue but a suggestion

### ISSUE THREAD

**Issue by ctugt** [tvdzwan/hyperion#288]
Hi! thanks for this awesome app! Can we get a option to use static light on main menu and screensaver etc lets say im not watching a movie but tv trough my regular tv statoin that it will be enabled as a static lightt or is there any other way i can configure this on my harmony remote?

**Comment by ZereoX** [comment]
@ctugt Hyperion does indeed allow you to set a static light using hyperion-remote. You can use either the [Chrome Extension](https://chrome.google.com/webstore/detail/hyperion-remote-control/ohlgoegainndhjejojilnchmkoghjbpd), [iOS App](https://itunes.apple.com/us/app/hyperion-remote/id943635503?l=de&ls=1&mt=8) or [Android App](https://play.google.com/store/apps/details?id=nl.hyperion.hyperionfree). The application allows you to pick from a color wheel and choose the brightness and saturation levels to be sent to your LEDS. Other features are also available, see the [Wiki](https://github.com/tvdzwan/hyperion/wiki) for more details.

**Comment by ctugt** [comment]
Thanks for this option, i already have that app, but i just want it to move to purple when im on the main menus,, so if i watch tv in the night and the raspberry is on, it can be o a stable static purple screen. Maybe i should create a new catagorie with a purple background in Kodi / OpenElec with Rapier 2 Skin. en dan turn off the screensaver option, this is a workable workaround but would be greate if we can get this function opt in the hyp. conf. tool

**Comment by ctugt** [comment]
I found a way to get it work, with some help from the openelec irc user: lrusak all credits to him!

I use two buttons on my MCE remote, blue for switching on/off, yellow to create a static purple colour. This is how (if you know this its really easy to change the purple colour to youre like)

On/off script for hyperion Remote. In /storage/.kodi/userdata/keymaps/remote.xml define:

```
<yellow>RunScript("/storage/hyperion/effects/purple.py")</yellow>
<blue>RunScript("/storage/hyperion/switch.py")</blue>
```

Then create two files in the /storage/hyperion/effects folder.
One called purple.py with this content, place it in /storage/hyperion/effects/purple.py:

```
import subprocess
subprocess.Popen('/storage/hyperion/bin/hyperion-remote.sh --priority 100 --color purple', shell=True)
```

One called switch.py with this content, place under /storage/hyperion/switch.py:
```
import subprocess

pid = subprocess.Popen('pidof hyperiond', shell=True, close_fds=True, stdout=subprocess.PIPE)

try:
    if pid.stdout.readlines():
        subprocess.Popen('killall hyperiond', shell=True)
    else:
        subprocess.Popen('/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &', shell=True)
except Exception, e:
    pass
```

now reboot and thats it should work on most remotes.
