### ISSUE TITLE
Error: Unable to open RS232 device (Empty port is invalid.)

### ISSUE THREAD

**Issue by oceaness** [tvdzwan/hyperion#289]
I have a Pi 2 running OSMC (RC). Hyperion installed pretty normally, and accepts input from the command line and from the app on my phone, however the lights connected via an Arduino Uno running LEDstream.pde don't do anything (they work perfectly when driven from my PC), and when I manually start hyperiond with the config file below, I see the following line in amongst the output.

`Unable to open RS232 device (Empty port is invalid.)`

I've confirmed that /dev/ttyACM0 is the correct port as it appears and disappears as I plug and unplug the Arduino.

I've tried googling this error message to no avail.

I'd appreciate it if someone could give me some advice and direction on how to get this working.
Jack

Config file:
```
// Automatically generated configuration file for 'Hyperion daemon'
// Generated by: HyperCon (The Hyperion deamon configuration file builder

{
        /// Device configuration contains the following fields:
        /// * 'name'       : The user friendly name of the device (only used for display purposes)
        /// * 'type'       : The type of the device or leds (known types for now are
        /// APA102, Adalight, AmbiLed, Atmo, Hyperion-USBASP-WS2801, Hyperion-USBASP-WS2812, Lightberry, Lightpack, LPD6803, LPD8806, Multi-Lightpack, P9813, $9813, Paintpack, PhilipsHUE, PiBlaster, SEDU, Test, ThinkerForge, TPM2, WS2801, WS2812b, None)
        /// * [device type specific configuration]
        /// * 'colorOrder' : The order of the color bytes ('rgb', 'rbg', 'bgr', etc.).
        "device" :
        {
                "name"       : "MyPi",
                "type"       : "adalight",
                "Output"     : "/dev/ttyACM0",
                "Baudrate"     : 115200,
                "delayAfterConnect"     : 3000,
                "colorOrder" : "rgb"
        },
```

**Comment by tvdzwan** [comment]
There was a bug in the config tool where 'Output' and 'Baudrate' were used (note the capital) and not 'output' and 'baudrate'. I fixed it and uploaded a new version of the tool.
You can also manually correct your configuration by changing the names.

**Comment by oceaness** [comment]
Hi

Thanks very much, I'd never have noticed the capitals.

Got it working now using Raspbian and a Fushicai UTV007 video grabber and the inbuilt V4L2 config.

Now planning to strip it down to a very minimal Raspbian install.
