### ISSUE TITLE
Missing options in hyperion config tool

### ISSUE THREAD

**Issue by ctugt** [tvdzwan/hyperion#290]
Is it possible in the next release of Hyperion Config Tool that we can set the left or the right side un equilly. Left i have 39 leds, right i have 42, right now the programm does set both sides to 40 But its vertically out of sync a bit

**Comment by ctugt** [comment]
*bump

**Comment by tvdzwan** [comment]
So this should technically be on the HyperCon issues list, but the item is noted. 
We are discussing changing the working of the tool. But to get a user friendly, robust tool with lots of configuration options is a lot of work and we do have other items on the wish list aswel.

**Comment by ctugt** [comment]
HI Cool, while instead i soldered a extra led on the left. otherwise the screen was just off.

Maybe the option updateDelay can be in this gui config too. As i have to paste it every test in the config file manually

**Comment by tvdzwan** [comment]
'updateDelay' is in the latest release, but you will have to use
HyperCon_ssh.jar.
