### ISSUE TITLE
Light / screen off sync

### ISSUE THREAD

**Issue by ctugt** [tvdzwan/hyperion#291]
Hi if i load this video on my tv,
https://www.youtube.com/watch?v=sr_vL2anfXA

It gets out of sync, the lights are way faster then the tv. Could anyone send met there config for W2801?

**Comment by tvdzwan** [comment]
There is a parameter for delaying the output to your leds. Add 'updateDelay' to the smoothing configuration. 
The output can be delayed in periods of the smoothing algorithm. For example if your smoothing is running at 20Hz. The period of the smoothing is therefor 50ms. An updateDelay of '3' will give a delay of 3*50 = 150 ms.

**Comment by ctugt** [comment]
Thanks, whats going in with 20 Hz? i dont see it back in the calculation.. Is there any reason you mention this and the period 50ms. 

I personally have Update FreQ. 24 Time ms on 90 so it will just be...

updateDelay = 3x90ms=180 ms delay?

Thanks again, i will try several values, btw can we have this option in the hyperion config tool?

**Comment by ctugt** [comment]
Im also unsure about boutrate, does anyone know the correct baudrate for WS2801, i saw on youtube video where it was 1 million, but the other video it was 250k

**Comment by ctugt** [comment]
According to:
http://forum.osmc.tv/showthread.php?tid=2143&pid=77118#pid77118

Its hould be 1 million but im not sure if it will brake things up
