### ISSUE TITLE
[Quastion] Use Hyperion as Server

### ISSUE THREAD

**Issue by BTopbas** [tvdzwan/hyperion#292]
Hi all devs;
I have wetek(amlogic device). Before this device i used raspberry pi with openelec and hyperion. And everything is perfect. But now i need to use wetek device(Because built-in tuner card). What i do;

I installed Raspbian on raspberry. And install hyperion. I copy my old hyperion config to raspbian.(I enabled 1933 port for boblight client). I testing with hyperion chrome addon and leds is change color. There is no problem with led connection and port. Hyperion works like a charm!

After i installed boblightd and xbmc boblight addon. I configure addon ip to my raspberry pi. But leds only change one color. blue and green. So here is problem. Hyperion not working as well. I missing something? Frame grabber is enabled in hyperion configs. And i am not create boblight config file and etc. Whats the problem? How can i check clients screen. I think scale problem. Image is too big or too small. 

P.S.: I tryed script.hyperion addon too. I configure addon to raspberry ip but no change any led colors.. Maybe this addon not work openelec on amlogic. But boblight working because devloper has tested and patched kernel for amlvideocap. 

P.S.2: I make many system restart. server and client. But no hope.

**Comment by pigbait** [comment]
same thing is happening to me, if i disable hardware acceleration the LED will work

**Comment by brindosch** [comment]
Closed
due to age, please open a new one if problem still exists
