### ISSUE TITLE
Not working under Openelec 5.0.6 with RPI2

### ISSUE THREAD

**Issue by NicoHood** [tvdzwan/hyperion#293]
I installed Hyperion as the wiki said (did that half a yeah ago some times) but the installed hyperion doesnt seem to work.

1) There is no .sh file in the installation path which should be executed instead.
2) the hyperiond file itself cant be executed due to missing libs

```bash
OpenELEC:~/hyperion/bin # ./hyperiond
./hyperiond: error while loading shared libraries: libQtGui.so.4: cannot open shared object file: No such file or directory
```

**Comment by ctugt** [comment]
apt-get install libqtcore4 libqtgui4 libqt4-network libusb-1.0-0 ca-certificates

**Comment by NicoHood** [comment]
Openelec, not Raspbian! Openelec has no apt-get

**Comment by ctugt** [comment]
Then download the packages or try wget not sure if their is a srouce for it but you can try

**Comment by NicoHood** [comment]
it is a clean install

**Comment by ctugt** [comment]
Mm thats strange causr i have openelec latest beta working flawpess is this
on a pi or pi 2
Op 28 mrt. 2015 17:45 schreef "Nico" <notifications@github.com>:

**Comment by lrusak** [comment]
Use this command to install
```curl -L -k https://raw.githubusercontent.com/tvdzwan/hyperion/master/bin/install_hyperion.sh | sh```

**Comment by Tester0815** [comment]
The shell script is pointing to the local libs which should be in in hyperion bin directory...

The install script should load the hyperion binaries with openelec specific library which can not be installed...
hyperion.deps.openelec-rpi.tar.gz

#!/bin/sh
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/storage/hyperion/bin /storage/hyperion/bin/hyperiond "$@" 

Zappatron compiled a rpi2 version:
https://github.com/tvdzwan/hyperion/issues/6
Zappatron commented on 16 Feb with link to googledrive 
"EDIT2 Link to a binary for ease of testing"

**Comment by tpmodding** [comment]
@NicoHood think can be closed?

**Comment by NicoHood** [comment]
Yeah. Too old, no idea if it works now. Other will complain if it doesnt ;)
