### ISSUE TITLE
Hyperion Works - Grabber Works -- No LED output

### ISSUE THREAD

**Issue by 4moto** [tvdzwan/hyperion#296]
I'm new here, but I've been working on an ambilight clone.

I'm using a raspberry pi B+ with ws2801 strip - a separate power supply for LEDs, and a powered USB hub for the accessories (converters/splitters/and grabber) the grabber I have is a  Fuschicai Easycap Stick 3002 -- USBTV007

Long story short, I'm running an older build of Raspbmc w/ specific firmware for my grabber because OSMC has firmware issues with my easycap which caused flickering and poor color representation.

I can command the LEDs with hyperion

hyperion-remote --priority 50 --color red --duration 5000

everything turns red, no issues

I can take a screenshot and it looks great 

hyperion-v412 --crop-top 8 --crop-bottom 17 --crop-left 9 --crop-right 10 --size-decimator 4 --frame-decimator 2 --red-threshold 0.4 --green-threshold 0.2 --blue-threshold 1.0 --screenshot

takes a screenshot and looks great.
 
![final_top9bottom19right10left9](https://cloud.githubusercontent.com/assets/11764757/6956914/986aa09e-d8c2-11e4-859f-53ffc31c65f5.png)

The LEDs have no output at all though, they're off entirely. When I start my Pi, they go through the boot sequence, but then they just turn off.

This is just the latest in multiple days of different software and revisions and other things I've tried, but it seems like the most likely to work... I'm not sure where to go from here with no output at all. 

Just to clarify, I did have this working with OSMC, it was just not at the standard of quality I wanted (led wouldn't turn off for blacks, reds were awful, and the whole strip would flicker on the top and bottom strips).

Any help would be greatly appreciated!! If this is not the correct forum for this, I apologize and I'd greatly appreciate some direction.

I'm using this kernel http://sourceforge.net/p/raspbmcusbtv/wiki/Installation/

on a pre-built image. Is this an issue because it only works with PAL (hdmi converter is set to PAL as well) and my PS4 output is NTSC? I was assuming it wasn't -- since it was fine taking a screenshot.

**Comment by tvdzwan** [comment]
Do you have the v4l2-frame grabber configured in hyperion.config.json? You
can use the latest release of HyperCon_ssh.jar to add this.

**Comment by 4moto** [comment]
I have the V4l2 configured, I'm using the same configuration that was 'working' with osmc

**Comment by tvdzwan** [comment]
You can try disabling the xbmc-checker (just comment the section in de
configuration file). Maybe it is incorrectly disabling the grabber when it
should not.

**Comment by 4moto** [comment]
Interesting, so I narrowed down the problem it seems, but I don't know a solution:

So here's my configuration for the grabber (I removed the comments):

 /// Configuration for the embedded V4L2 grabber
       "grabber-v4l2" :
        {
                "device" : "/dev/video0",
                "input" : 0,
                "standard" : "PAL",
                "width" : 1,
                "height" : 1,
                "frameDecimation" : 2,
                "sizeDecimation" : 4,
                "priority" : 800,
                "mode" : "2D",
                "cropLeft" : 5,
                "cropRight" : 9,
                "cropTop" : 9,
                "cropBottom" : 13,
                "redSignalThreshold" : 0.4,
                "greenSignalThreshold" : 0.2,
                "blueSignalThreshold" : 1.0
        },



The key part of that is this::

                "standard" : "PAL",

The kernel I'm using supposedly is only good with PAL standard. When I have it on PAL and I try to use hyperion-remote it says  "Unable to connect to host"

When I use the exact same config, but change

               "standard" : "NTSC",

hyperion-remote works, but the grabber works -- but not exactly as it should (still some flickering, but better than oscm, LEDs don't turn off on blacks)



Conclusion: Somehow it's working now with NTSC when It didn't yesterday...I'll do more of a write-up but I just had a root canal and not up for it.

**Comment by tvdzwan** [comment]
Your signal thresholds seem to be high. Are you sure that they are the
correct value?

**Comment by 4moto** [comment]
I used this as a guide for making my setup -- the thresholds are from here:

https://christianmoser.me/how-to-ambilight-for-every-hdmi-source/

It's currently working mostly, but it's a bit weird and doesn't really show yellows unless the saturation is huge, then everything is overcompensated. Also, is there any way to get the LEDs to turn off when parts of the picture are black? They currently are a kind of brownish...

https://drive.google.com/file/d/0B6RXvkIYAy3AREJxX3FkVHhPbjQ/view?usp=sharing

**Comment by tpmodding** [comment]
still need help or can be closed?
@4moto

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
