### ISSUE TITLE
OpenElec Cubox-i4 since update from 5.0.3 to 5.0.7 just grabbing the main menu and fanarts but not videos

### ISSUE THREAD

**Issue by derechtedude** [tvdzwan/hyperion#298]
Hey everybody,

I have been using Hyperion for some time now on openelec.
Recently updated to 5.0.7 (now 8)
Since then frame grabbing only worked in the menus but not anymore during videos.
During videos I just get a light purple lighting.
I have tried to reinstall hyperion with the openelec script. But this did not help.
Do you have any idea what the problem could be?

Thanks 

Cheers derdude

**Comment by derechtedude** [comment]
I read this post btw.
https://github.com/tvdzwan/hyperion/issues/260
Did not solve my problem though. Switches on and of json a dozen times, combined with killing hyperion, and editing the config falsing out the grabber. Did not work for me :-(
Any idea besides installing kodi from scratch?!? Which I really don't want to do!

Cheers dude

**Comment by derechtedude** [comment]
Reinstalling open elec 5.0.8 did not help. Still no ambilight during videos.
With one exclusion: I have one DVD rip of the naked canon which shows a running ambilight?!?
Everything else, no matter if YouTube or different kind of mkv, avi etc. don't work.
Any ideas?!? How to fix this?

Cheers dude

**Comment by derechtedude** [comment]
Reinstalling open elec 5.0.8 from scratch did not help. Still no ambilight during videos.
With one exclusion: I have one DVD rip of the naked canon which shows a running ambilight?!?
Everything else, no matter if YouTube or different kind of mkv, avi etc. don't work.
As Hole DVD rips seem to work I think the problem lays in hyperion not detecting, that a video is playing.
I have no idea why it recognizes DVDs though...
Any ideas?!? How to fix this?

Cheers dude

**Comment by derechtedude** [comment]
Reinstalling open elec 5.0.8 from scratch did not help. Still no ambilight during videos.
With one exclusion: I have one DVD rip of the naked canon which shows a running ambilight?!?
Everything else, no matter if YouTube or different kind of mkv, avi etc. don't work.
As Hole DVD rips seem to work I think the problem lays in hyperion not detecting, that a video is playing.
I have no idea why it recognizes DVDs though...
@tvzwan Any ideas?!? How to fix this?

Cheers dude

**Comment by derechtedude** [comment]
Reinstalling open elec 5.0.8 from scratch did not help. Still no ambilight during videos.
With one exclusion: I have one DVD rip of the naked canon which shows a running ambilight?!?
Everything else, no matter if YouTube or different kind of mkv, avi etc. don't work.
As Hole DVD rips seem to work I think the problem lays in hyperion not detecting, that a video is playing.
I have no idea why it recognizes DVDs though...
@tvdzwan Any ideas?!? How to fix this?

Cheers dude

**Comment by Javintosh** [comment]
@derechtedude same here, I cant make it work hyperion + cuboxi (using openelec 5.0.7 or 5.0.8) + arduino uno (ws2801 led strip). The frame grabber works on menus but not on video player.

**Comment by derechtedude** [comment]
I  downgraded back to 5.0.0
Worked again straight away.
I guess, something was changed trat hypwrion does not recognise Films anymore...

**Comment by Javintosh** [comment]
@derechtedude with openelec 5.0.0 works fine :)
Now we should know what's happening with newer openelec versions :S

**Comment by Gamadril** [comment]
For some reason in the new openelec versions the video playback is rendered on the second framebuffer. That means that the whole GUI incl. menu, pictures and other functions are on /dev/fb0, but the video is on /dev/fb1
I guess will have to add additional configuration separation for the framebuffer grabber to handle this...
As a temporary solution add an additional line to the framebuffer options
```
"device": "/dev/fb1"
```
in your config file:
```
"framegrabber" :
        {
                "width" : 128,
                "height" : 64,
                "frequency_Hz" : 10.0,
                "device": "/dev/fb1"
        },
```
This will make it working for video playback, but won't work for all other media and menu.

**Comment by derechtedude** [comment]
Good to know, what the problem is.
Gonna stick to 5.0.0 until you found a solution.
Thank you!

Cheers mat

**Comment by Gamadril** [comment]
Well, the solution is above, and since it works for video playback (IMHO the main use case) it might take a longer time until I will do a fix...

**Comment by sivilya** [comment]
So, I added the "device" line to my config file and then the leds did not responde at all (not even for menu items).. so I switched the device to /dev/fb0 - that too did not help. Only when removed the device line altogether did the menu item came back to life - but in any case no lights responding to movie.

Should I have done something else?  (installed the hyperion from the main repo)

**Comment by Gamadril** [comment]
No it should be enough, paste the whole block of the "framegrabber" config and check the terminal output if you start hyperiond manually

**Comment by sivilya** [comment]
oh! stupid me :) dropped the comma before that line...
OK. it works now - just the colors issue remains.

Great! thanks for all of your efforts and looking forward to the fix ;)

**Comment by zarboz** [comment]
@Gamadril I have used this fix and now I can't get colors to show properly no matter which color order i use in config... Blues show as yellow and red shows as blue... I am using my last known working configuration in order to ensure a smooth OS update on my hummingboard.

**Comment by Gamadril** [comment]
Had no time to rebuild the binaries yet, but you can compile yourself the code from https://github.com/Gamadril/hyperion on xbian for example and replace the binary later on OpenELEC.

**Comment by brindosch** [comment]
@Gamadril 
Could this be closed? How should we handle the Cubox support?

**Comment by brindosch** [comment]
Closed
