### ISSUE TITLE
Please Consider making a qt5 version of hyperion

### ISSUE THREAD

**Issue by LongChair** [tvdzwan/hyperion#299]
Hi,
I have been willing to use hyperion but I only have qt5 available on my target platform.
I have been looking into the modifications and modified all the CMakeList.txt files so that they refer to Qt5 rather than QT4 and ended up with FindQT4.cmake and gave up.

Is there any plans to have this ported to qt5 ? qt4 starts to get pretty old now :)

maybe using a cmake variable or detecting which version is installed could make it cope with both qt4 and qt5 versions ...

**Comment by LongChair** [comment]
For the record, cmake and qt5 should be easier than with qt4 :
http://doc.qt.io/qt-5/cmake-manual.html

**Comment by mbnn** [comment]
Vote for this one, please consider this.

**Comment by frostworx** [comment]
you might be interested in
#445

**Comment by tpmodding** [comment]
@LongChair think can be closed now?

**Comment by ntim** [comment]
Yes, compiles with qt5.

**Comment by tpmodding** [comment]
Could you close it please? I have no rights. Thanks

Von meinem iPhone gesendet

**Comment by LongChair** [comment]
Yes sure :)
