### ISSUE TITLE
Kodi installed via RetroPie

### ISSUE THREAD

**Issue by ghost** [tvdzwan/hyperion#300]
Hi, 

On my RPi2 I installed Kodi via RetroPie and installed Hyperion through the `sh` script. I used the test command `hyperion-remote --priority 50 --color red --duration 5000`, however nothing happens. Is my installation currently supported? Is there a way to debug the installation?

**Comment by tpmodding** [comment]
still need help? or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
