### ISSUE TITLE
RPi and Hyperion installed, I assume correctly, Lightpack not lighting up.

### ISSUE THREAD

**Issue by Billium28** [tvdzwan/hyperion#301]
When I originally bought my lightpack around Xmas I had this same issue with the Hyperion/Pi not even lighting the Lightpack up nor the swirling rainbow on the screen. I want to try again since this is the reason I bought the LP and Pi in the first place. Is there anyway to check the Pi, either through Hyperion/Openbmc or through the windows SSH software? I am not super smart in this but I assume I can do some digging and finding a log file etc.?

**Comment by tpmodding** [comment]
@Billium28 need help? or can be closed?

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
