### ISSUE TITLE
Kodi menu grab enabled, but not working

### ISSUE THREAD

**Issue by rwilleme** [tvdzwan/hyperion#302]
Hi folks.

My question is more like the opposite of the other questions.
I have menu grab enabled, but only Movies and TV Shows are working.

My config:
```
    "xbmcVideoChecker" :
    {
        "xbmcAddress" : "192.168.167.18", //IP of my HTPC
        "xbmcTcpPort" : 9090,
        "grabVideo" : true,
        "grabPictures" : true,
        "grabAudio" : true,
        "grabMenu" : true,
                "grabScreensaver" : true,
                "enable3DDetection" : true
    },
```

Any clue what needs to be changed in the (Kodi) config to get this working?

Thanks in advance!
Rick

**Comment by rwilleme** [comment]
I've read in other topics that this is just not possible.
As far as I understood, Kodi can only 'grab' video-content and not something else like menus.

Hopefully somebody will get this fixed in the future..

**Comment by alex240188** [comment]
I have the opposite effect. It is capturing the menu but I only want it to grab video content

**Comment by Gamadril** [comment]
check that remote control from external applications is enabled in kodi system settings

**Comment by Grabber66** [comment]
Is it now possible to use the lights with external Kodi. Like rwilleme asked, or not ?

**Comment by brindosch** [comment]
It should be possible, we are investigating this because we have different results.

**Comment by brindosch** [comment]
It is working for me with a kodi on my windows desktop (hyperion runs on a pi)
So it should work!
I will close this, if you have any issues please open a new one
