### ISSUE TITLE
Hyperion on OpenELEC: 1-4 LEDs turn on and shine blue or white after awhile 

### ISSUE THREAD

**Issue by tlnagy** [tvdzwan/hyperion#304]
I've been having this weird problem where 1-4 LEDs of my ws2801 strip will turn on and shine blue and white after about 12 hours. I'm using Rasplex 0.5.1, which is based on OpenELEC. This is really annoying at night. I've been manually killing the hyperion server to solve this, but is there a better way of doing this?

**Comment by brindosch** [comment]
1. cut your leds from power if not used
2. send with a script a constanst "black", but the rpi have to run for this all the time.

I will close this issue, just open a new one if you struggling with this
