### ISSUE TITLE
Failed to open /dev/mem: Permission denied

### ISSUE THREAD

**Issue by nuovocampo** [tvdzwan/hyperion#305]
Hi all,

I am using hyperion to drive my WS2812b which was working well until suddenly the lights keep staying off.

hyperiond /etc/hyperion.config.json is showing me the following:

Application build time: Mar  6 2015 20:57:44
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 133]
Device configuration:
{
	"colorOrder" : "rgb",
	"name" : "MyPi",
	"type" : "ws2812b"
}

Failed to open /dev/mem: Permission denied
Segmentation fault

I guess the issue is not with hyperion but with some broken permissions on my PI. Unfortunately I'm quite new to Linux so I'd appreciate if someone has a hint on how to solve this.

Many thanks in advance!

**Comment by cyber-nl** [comment]
you could try in SSH
mount -o remount,rw /dev

**Comment by nuovocampo** [comment]
Hi,
unfortunately that also doesn't work. Quite weird, espacially since the problem started from one moment to the other... I think I'm just gonna rewrite the image to the SD. That should do the job.

Thanks for trying to help!
