### ISSUE TITLE
Make error 2 

### ISSUE THREAD

**Issue by sweekly44** [tvdzwan/hyperion#307]
I keep encountering:

/mnt/usb/hyperion/build/libsrc/leddevice/../../../libsrc/leddevice/LedDevicePhilipsHue.h:137:72: error: expected primary-expression before '{' token

make[2]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/moc_LedDevicePhilipsHue.cxx.o] Error 1
make[1]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/all] Error 2
make: *** [all] Error 2

Is there a problem with this Philips file?

**Comment by ntim** [comment]
This is C++11. Which gcc are you using? Try adding "-std=c++0x" to your gcc command line.

**Comment by sweekly44** [comment]
Good call, I had a different version of gcc than I needed, I have it successfully compiled now. Thanks!

**Comment by blub2** [comment]
Hi,
I had the same problem with Ubuntu 12.04 and gcc 4.6.3, installed gcc-4.8 from 

    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update; sudo apt-get install gcc-4.8 g++-4.8

then configured with 

    cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DCMAKE_C_COMPILER=/usr/bin/gcc-4.8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.8
