### ISSUE TITLE
RPi2 - OpenELEC - Hyperion - Only LED 1-50 controlled 50-102 Rainbow?

### ISSUE THREAD

**Issue by sailandbrew** [tvdzwan/hyperion#308]
After a 3 days I’m about 90% there but at a loss. I have 102 LEDs around my TV, but only 1-50 are controlled 51-102 are simply ‘on’ and in a rainbow patern (Red/orange/yellow...). I’ve checked and double checked my hyperion.config and everything looks okay. Any suggestions as to where to look?

**Comment by cyber-nl** [comment]
have You placed you'r hyperion.config.json in [/storage/.config] and not in [/storage/hyperion/config]

**Comment by sailandbrew** [comment]
Ended up finding the problem.... loaded the config into /storage/.config, but then after some searching around I found refference to using explorer and going to \\192.168.1.12\Configfiles, and found another copy of hyperion.config.json. Replaced it with my own version, and now all of the LEDs are controllable.

Strange how hyperion.config.json is in more than one location

**Comment by brindosch** [comment]
Solved

Closed
