### ISSUE TITLE
framegrabber resolution/crash issue 

### ISSUE THREAD

**Issue by cyber-nl** [tvdzwan/hyperion#309]
Hi all

my setup
RPI2 with openelec 5.0.8
96 Led's APA102
running Hyperion

after I finally got it all install and working i now have a couple op issues.
the first issue:
I try to raise the frame width grabber resolution but when I raise the resolution above 58 width the Kodi checker stops working (the leds start working in the menu although this is disabled).
the height grabber resolution I can make as high as I like it does't affect anything accept the performance :).
how can I fix this?

second issue:
this is the more annoying issue.
when Hyperion is running I can't watch twitch youtube and some video files because if I do The PI crashes If i disable Hyperion it works fine.

like to hear from you If you know a solution.

**Comment by brindosch** [comment]
@cyber-nl 
Your problem is gone?

**Comment by cyber-nl** [comment]
fixed think it was ip or poort issue json server
