### ISSUE TITLE
Hyperion crashes on Pi2 (process dead...)

### ISSUE THREAD

**Issue by Phil1988** [tvdzwan/hyperion#311]
Im using a Raspberry Pi 2 with raspbian (2015-02-16-raspbian-wheezy) for external video sources.
I can use the stk1160 video grabber and the one with a fushicai chipsets but I get randomly crashes.

Im using the v4l2grabber with a frame decimation of 2 and a size decimation of 8.
The load is about 9%.
I also using linear smoothing and blackborder detection.

Everything is working perfect but the LEDs sometimes stop.

When I enter "sudo service hyperion status" I get "process dead but pidfile exists".
I can start hyperion again with "sudo /etc/init.d/hyperion start" but it will crash most of the time in a few minutes.
Sometimes a reboot seems to help.

First I thougt it was a driver issue of the STK1160 but it happened several times to a fushicai grabber as well.
I also formated the sd card and started with a clean raspbian (2 times) but the problem still exists.

Im using an active USB-Hub.

Sometimes the Pi 2 does not start properly and I get a bootloop.
I think these 2 problems have different reasons but I wanted to say it.

I hope anyone can help me!

**Comment by p1n9** [comment]
I have the same issue with the pi B (512M)
Perhaps we should look into the rpi firmware, I think the problem is there since I upgrade it...

**Comment by brindosch** [comment]
@p1n9 
@Phil1988 

> Sometimes the Pi 2 does not start properly and I get a bootloop.
You should sort this out first. Maybe problems with your usb hub or half dead sd card
You should power your Pi and LEDs with the same power source to prevent problems.

**Comment by brindosch** [comment]
Closed due to lack of information
