### ISSUE TITLE
LED blinking and colors missing

### ISSUE THREAD

**Issue by Carote** [tvdzwan/hyperion#312]
Hi everybody,

I'm trying to build an ambilight for my TV and I'm using LED strip from LightBerry and the LightBerry HD premium kit from LightBerry too. Between those 2, I have an openelec distribution running on Raspberry Pi 2 with a 2A power supply and with the openelec SD-card image from Lightberry.

For now, I'm facing 2 problems : 
1. When starting the Pi, LEDs does the boot sequence (rainbow) and then, they are blinking white and green, but not all the LED strip, just the beginning and the end. I have to open ssh connection to kill hyperiond and start it again to make it work correctly regarding the TV activity : how can I do o fix this issue ?

2. LEDs color seems to be a greystone (or slightly blue, but green and red are nearly missing)  instead of colors from the TV. When using effect or single color, I can have all the colors. I tried to make a screenshot with the v4l2 grabber to see the processed image. I got the answer saying grabber is stopped but there is no screenshot.png in \\openelec\Configfiles : can somebody help me to understand why ?

Thanks in advance for your help ;-)

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
