### ISSUE TITLE
[Discussion] Control Hyperion using fhem home automation / HTTP

### ISSUE THREAD

**Issue by sticilface** [tvdzwan/hyperion#313]
I'd like to control hyperion using a home automation package called fhem. 

It supports phillips hue, so is it possible to configure hyperion to respond to philips hue commands? 

I'm also confused by hyperion-remote as it is a binary that will only run on openelec. the .sh file just points to the binary.  Is there a hyperion script that will run in bash to connect to a remote version of hyperion? 

I've been thinking about this a little more.  I'm very new to java, very new.  I've searched and cannot find anything.  

Can I control hyperion via HTTP requests.  I suspect I can with this JSON server, but i can't find any examples.  This would be perfect... 

something like http://192.168.1.128:19444/color=ffffff for example.
or turn animations on?

Works great though.   Thank you.

**Comment by adamnmcc** [comment]
Hi, did you ever get any further with this? i'd like to attempt a similar process using other Home Automation Software.

**Comment by sticilface** [comment]
I got around it by using ssh. Log into the pi and execute the local copy of Hyperion control.

**Comment by adamnmcc** [comment]
yeah, i amusing scripts, but i'd relly like to be able to send the values
from Domoticz (domoticz.com) they have an RGB switch type but it doens't
seem very easy to modify to use with Hyperion.

**Comment by jilleb** [comment]
You can send json to the hyperion. I did a packet capture when using the Hyperion remote app on Android, and you can just control the color like this:
{"command":"color","priority":50,"color":[251,164,223],"duration":14400000}

clear it like this:
{"command":"clear","priority":50}

I guess it's easy to turn the color into a domoticz variable.
Is this what you're looking for?

**Comment by frostworx** [comment]
hi!
I'd like to use hyperion too in domoticz.
there are several "problems" though:
domoticz:
- doesn't give the option to get the configured color (f.e. in the colorpicker) via json or even better take the configured (hex) color as argument for a virtual device:
see f.e. 
https://www.domoticz.com/forum/viewtopic.php?f=15&t=8527
https://github.com/domoticz/domoticz/issues/222
- a global colorpicker where you can choose which (virtual) rgb device you want to "live edit" would rock

hyperion:
- looks like it is "impossible" to send json commands via curl - at least I have the same problems like described here: https://github.com/tvdzwan/hyperion/issues/316  (yes nc, works)
- the hyperion-remote works very fine, but for rgb color (and image) functions it depends on qtgui, which is very bloated for a headless (domoticz-)controlserver.
I hacked a dirty "hyperion-slimremote" without qtgui dependency (only qtcore and qtnetwork, removed image and transform functions). in case someone is interested I could clean it up a bit and push it somewhere. of course a proper fix for the "curl" problem would obsolete that hack :}

**Comment by penfold42** [comment]
Could you take inspiration from the UDP "effect" I wrote today ?

It listens on a UDP socket for raw led data.

The effects api supports feeding led colour data and images so it could simply listen for an http post of an image  or a color command etc...

**Comment by adamnmcc** [comment]
i eventually stopped using hyperion and went for an arduino based sketch
that uses MySensors with the rest of my Home Automation project.

**Comment by frostworx** [comment]
@penfold42 
thank you for the quick reply!
great timing with your new UDP socket, eh? :}
I'll try it soon (need to apply it to my qt5 #445 fork first)
within the next days.

@adamnmcc 
probably also a solution, but I prefer keeping hyperion and hoping for a better global rgb solution within domoticz :}

**Comment by frostworx** [comment]
@penfold42, gave it a quick try.
If I'm not totally wrong I require some wifi led device to get something working with it, right?
I ordered a esp8266 led device some days ago, so I'm sure I'll like your fork when the device arrives.
but I can't control my arduino /dev/ttyACM0 with your fork right?
I might have not looked close enough though :}

**Comment by frostworx** [comment]
hm, above try seems to have killed my arduino(?)

**Comment by sticilface** [comment]
So in the end, I use hyperion behind the television on (plexbmc, raspberryPi) and it outputs hyperion signals to an ESP8266 via UART.  The ESP8266 runs some software that i've written to control the LEDs.  However, it offer the bed of both worlds as it is entirely controllable by HTTP and MQTT.  so you can select the ADALIGHT mode and have the ws2812s controlled by hyperion, or just set plain colours, or blobs or whatever.  write your own effects.  

My first release of this software is on github, 
https://github.com/sticilface/ESP8266-wifi

it works.  But does have some bugs!!   I've been using it for a long time now.  

If you just want the adalight driver, here is a non-blocking ADALight sketch for the ESP8266.  I can run this bad boy at 1,000,000 baud, which is pleanty fast to not have any lag using hyperion. 

https://github.com/sticilface/Adalight-ESP8266

finally.  Im working on a massive massive upgrade to the ESP8266-WiFi... it is getting there but I'm still working out some stuff.  I've shifted everything over to C++ style classes, with preset management.  The interface uses jquerymobile and so sending and receiving commands is much much smoother as the ESP doesn't have to do any web page generation.  All files are stored on SPIFFS..  

There is a version, ESPmanager, which my new lib will use that will give you a feel for it.  this library configures the ESP wifi, host name, and offers some simple functions.  again it is work in progress.
https://github.com/sticilface/ESPmanager

**Comment by frostworx** [comment]
yay, reuploading the scetch fixed my arduino :}
thanks, @sticilface,
this sounds very interesting. still have some "naked" esp8266 devices flying around here, but didn't have the time to do something useful with them. can't wait to play with your Adalight-ESP8266 combo :}
btw I found the esp-led device I ordered here (in case someone searches something similar):
https://www.domoticz.com/forum/viewtopic.php?f=38&t=7957

**Comment by p1n9** [comment]
Hi,

I've make a web interface for hyperion.
I send json commands through a websocket to control hyperion, or ssh to manage processes, conf,..
here is sample code in js : 
```
// open websocket
socket = new WebSocket("ws://hyperionhost_ip:19444");
// websocket events
socket.onopen = function () { console.log("Connection opened.");};
socket.onerror = function (e) { console.log("Error: "+e.data);};
socket.onclose = function () { console.log("Connection closed.");};
socket.onmessage = function (e) { console.log($.parseJSON(e.data));};
// define and send command
var myObject = {"command":"effect","effect":{"name":"Knight rider","args":{"color":[255,0,0],"fadeFactor":0.7,"speed":2}},"priority":99};
socket.send(JSON.stringify(myObject));
```
myObject is the json command to send (find them with hyperion-remote and --print option)
in this example : knight rider effect with given parameters and priority

You can make a little web script (html/php/js) and call it with GET parameters.
ex: http://hostname/script.php?command=color&color=FF0000

**Comment by frostworx** [comment]
hey p1n9,
sounds good! at least the non ssh-part would be very interesting to see.
any chance you have an url to your code?

**Comment by greg4b** [comment]
@sticilface 
I'm also looking for controlling hyperion by http with FHEM homeautomation 

A simple URL request would be best.

Could you please point out more detail your solution?

Thx,

Greg

**Comment by sticilface** [comment]
I ended up using fhem to SSH into the pi running hyperion, and issue the commands using the hyperion command line tool.  so not much help I'm afraid.  

I've got a better handle on json these days so i might be able to find a better way of doing it.  But i can't right now as I'm not going to be near the devices for 2 months.

**Comment by p1n9** [comment]
Hey,

You can try this little script.
It's a simple html file with js code (like my previous message).


Test it with : 
(you need to edit line 13 for hyperion ip)
```
http://YOUR_HOST/hyperion.html?command=color&color=[255,0,0]&priority=100
```
will set all leds to red with priority 100.
```
http://YOUR_HOST/hyperion.html?command=clear&priority=100
```
will kill previous command.

It's just an example, feel free to modify it according to your needs :wink: 

@frostworx 
for now I'm in a huge refactoring process, so no I can't give it like that.

ps : you can see the console.log() output with a web debuger

[hyperion.html.zip](https://github.com/tvdzwan/hyperion/files/93024/hyperion.html.zip)

**Comment by penfold42** [comment]
I did something similar in perl.

I have a pair of PIs that are forwarding infrared remote control signal between 2 rooms that each have Hyperion running. 
The perl script is there to forward lirc messages so I extended it to also talk to Hyperion 
For mood lighting I can now use an IR remote control to set brightness and colours.

**Comment by penfold42** [comment]
I did something similar in perl.

I have a pair of PIs that are forwarding infrared remote control signal between 2 rooms that each have Hyperion running. 
The perl script was there to forward lirc messages so I extended it to also talk to Hyperion over the Json interface with 1 line commands like that.
For mood lighting I can now use an IR remote control to set brightness and colours.

**Comment by aydemirm** [comment]
There is a possibility to control hyperion using FHEM. The approach is described in http://forum.fhem.de/index.php?topic=27900.msg252540#msg252540.

**Comment by mikiline** [comment]
Thx very much....and how to send http request to start effect?

this not work

> http://YOUR_HOST/hyperion.html?command=color&color=[255,0,0]&priority=100
