### ISSUE TITLE
Wireless WS2801 for ambiant lightning

### ISSUE THREAD

**Issue by daaf84** [tvdzwan/hyperion#314]
Hello, is it possible to make 2 (or more) WS2801 leds wireless. I want to recreate a 'Phillips Hue-like' effect. Maybe with some XBee modules? 
My setup is right now 50 WS2801 leds behind theTV. 
I don't know if theSPI signal can be passed thru the air...

**Comment by tpmodding** [comment]
we have now udp support, you can do it with a simple esp8266 now

can you close this issue? thanks
