### ISSUE TITLE
BGR LED stripe problems 

### ISSUE THREAD

**Issue by patovolador** [tvdzwan/hyperion#315]
I have a led stripe BGR and I install hyperion with configuration "bgr" but it still do blue-> Red and Red-> blue, and if i put RGB happens the same. nothing change, what can it happens¿¿??

**Comment by Liukkjan** [comment]
Are you absolutely positive that you overwrited the config? Restarted hyperion? How do you check the settings (e.g test video from youtube)?

**Comment by tpmodding** [comment]
Closed, the order option works.
