### ISSUE TITLE
send JSON request with curl... 

### ISSUE THREAD

**Issue by sticilface** [tvdzwan/hyperion#316]
hi all, 

making progress...  

How do I send this son request

```````
{"color":[255,255,255],"command":"color","priority":100}
```````

Using every which way that i can try I still get this

`````````
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 2, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
``````````

I've tried 
``````````````
curl -X POST -d "{\"color\":[0,255,255],\"command\":\"color\",\"priority\":100}" 192.168.1.138:19444
curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d "{\"color\":[0,255,255],\"command\":\"color\",\"priority\":100}" 192.168.1.138:19444
curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"color":[0,255,255],"command":"color","priority":100}' 192.168.1.138:19444
````````
and lots of others....

**Comment by bimsarck** [comment]
```
echo  '{ "color": [0,255,255], "command": "color", "priority": 100 }' | nc 192.168.1.138 19444
{"success":true}
```

.bimsarck

**Comment by sticilface** [comment]
well that was easy!  

Thank you

**Comment by raspiuser1** [comment]
this command: {"color": [0,255,255], "command": "color", "priority": 100}   is working for me directly through tcp connection to port 19444 with program putty. but  it does not work the first time i have to send the command twice than it succeeds, anyone know how?


and is there a command for the effects like: {"effect": "Snake", "command": "effect"}   ?
when its sended it will disconnect the terminal and nothing happends.

thx alot

**Comment by sticilface** [comment]
I have this sort of error, when hyperion is configured with X LEDs, and the device I'm sending it to has <X.

**Comment by sticilface** [comment]
I also struggled to get this to work properly and resorted to using ssh
```ssh rasplex '/usr/bin/hyperion-remote -c XXX```

**Comment by raspiuser1** [comment]
i need to get it working direct from the  telnet or tcp command without login. i want to send color commands to the raspberry via openremote home automation software . it works for the color commands but i have to send it twice to get it working. 

and im wondering if somebody knows the raw joson command to call the effects

**Comment by tpmodding** [comment]
@sticilface can be closed?

**Comment by brindosch** [comment]
Not related to Hyperion

closed

**Comment by neilpryde1984** [comment]
> hi all,
> 
> making progress...
> 
> How do I send this son request
> 
> ```
> {"color":[255,255,255],"command":"color","priority":100}
> ```
> 
> Using every which way that i can try I still get this
> 
> ```
> {"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
> {"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
> {"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
> {"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
> {"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
> {"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
> {"error":"Error while parsing json: * Line 2, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
> ```
> 
> I've tried
> 
> ```
> curl -X POST -d "{\"color\":[0,255,255],\"command\":\"color\",\"priority\":100}" 192.168.1.138:19444
> curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d "{\"color\":[0,255,255],\"command\":\"color\",\"priority\":100}" 192.168.1.138:19444
> curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"color":[0,255,255],"command":"color","priority":100}' 192.168.1.138:19444
> ```
> 
> and lots of others....

hi all

i know this is pretty old, but probably helpful for someone..

i had the same problem like sticilface. during a wireshark analysis, i figured out, that the JSON, Python, Whatever packets are slightly different to the ones generated by the android app. These ones have a newline (0A) at the end.

so adding a '\n' at the end, solves the problem. do not forget the $ sign. otherwise, bash escapes the newline character

curl -X POST -d $'{\"color\":[0,255,255],\"command\":\"color\",\"priority\":100}\n'

cheers
neil

**Comment by jghaanstra** [comment]
This is an old and closed issue but I'm facing the same problem. Even with the suggestion of @neilpryde1984 I keep getting this error. What's wrong?

```
λ curl -X POST -d $'{"color":[0,255,255],"command":"color","priority":100}\n' 192.168.0.135:19444
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 1, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
{"error":"Error while parsing json: * Line 2, Column 1\n  Syntax error: value, object or array expected.\n","success":false}
```
