### ISSUE TITLE
Hyperion transmitting even when there is no picture? Option to disable it?

### ISSUE THREAD

**Issue by Povezi** [tvdzwan/hyperion#318]
Is it possible to disable transmitting to device while in menu or sleep?

Why? I detect RF noise and RXTX diodes on my arduino are glowing all the time...

relevant part of my config (with disabled grab in menu/screensaver): 
                "type"       : "adalight", // Arduino clone driving WS2812b
                "output"     : "/dev/ttyUSB0",
                "rate"       : 500000,
                "colorOrder" : "rgb"
        "xbmcVideoChecker" :
        {
                "xbmcAddress" : "127.0.0.1",
                "xbmcTcpPort" : 9090,
                "grabVideo" : true,
                "grabPictures" : true,
                "grabAudio" : true,
                "grabMenu" : false,
                "grabScreensaver" : false,
                "enable3DDetection" : true
        },

**Comment by Povezi** [comment]
Any idea? I am thinking about... is it possible to disable plugin while screensaver is on? This way my raspberry wouldn't transmit to arduino thus solving the problem?

**Comment by brindosch** [comment]
@Povezi 

As far as i know no.

Could this be closed?

**Comment by Povezi** [comment]
could this be moved to feature request?

**Comment by brindosch** [comment]
Added it.

thank you, i will cose it.

**Comment by redPanther** [comment]
did you use smoothing?
when smoothing is on, the led device are feed with data all the time regardless if there is input or not.

**Comment by Povezi** [comment]
yes, I use smoothing, type:linear, time_ms: 200, updateFrequency 25.0000

how do I disable it? just comment "smoothing" section?

**Comment by brindosch** [comment]
yes

**Comment by redPanther** [comment]
or set type "none"

**Comment by Povezi** [comment]
redPanther, you are genius, how can I send you a beer? 👍 

if I set smoothing to "none" rxtx led stops blinking if screensaver is active, but if I play movie, lights are "jumping" and feeling unnatural... 

Is there anyway to enable smoothing for video playback and disable it for screensaver & menu? 

(because it interfere on 500MHz & its harmonics with my FM radio ;)))

**Comment by redPanther** [comment]
currently there is no way. The smoothing driver must be enhanced. some sort of "pause" would be nice. this could be called by xbmc checker

**Comment by brindosch** [comment]
You might be interested in this too :)
https://hyperion-project.org/threads/kodicheck-picture-modus-bad-detection-rate.90/

**Comment by penfold42** [comment]
Or do we fix this more generally with a "don't update LEDs if same" option that's checked before we call update() ?

**Comment by redPanther** [comment]
Yes thats better. There is a updateleds method. If i see this right, I have to delete some lines and then we get: do nothing when buffer empty, instead off sending last led data again and agsin

**Comment by tpmodding** [comment]
didnt @RickDB implemented something similar to his atmoorb devices to prevent network-flodd? may you can use his code?

**Comment by brindosch** [comment]
Hm, a additional option.
The result will be a reduced cpu load too (during idle picture)?
Might be interesting to use it default enabled if smoothing is enabled.

**Comment by redPanther** [comment]
I won't make an option. I will prevent smoothing from flood the device in general.

**Comment by brindosch** [comment]
accepted :+1:

**Comment by RickDB** [comment]
Yep we should not keep on sending when there's no new data however would test it on different hardware as some might require multiple sends even if data is identical due to packet loss or slower leds with wrong refresh setup.
Some devices also don't have a callback so we don't need if it was received so need to take that into account as well.

**Comment by redPanther** [comment]
When smoothing is off, devices get data only when new data available. If there is a problem when smoothing on and devices aren't flooded, then we have already a problem.

**Comment by Povezi** [comment]
if smoothing is on (linear), kodi is sleeping and all diodes off, my Arduino is blinking like crazy..
video: http://www.screencast.com/t/VGUzQvKylyM

I think that there should be no updates on usb/serial to arduino if kodi is sleeping or color is constant?
(ambilight hardware setup according to http://ai.rs/reviews/rgb-delight-raspberry-pi2-arduino-nano-ws2812b-using-hyperion-on-openelec/ )

**Comment by redPanther** [comment]
@Povezi now you can test with latest beta version. I changed colorSmoothing code to don't stress the devices. see my PR #653

**Comment by brindosch** [comment]
@Povezi 
now available via beta tar.gzs
https://hyperion-project.org/threads/install-latest-hyperion-beta-v1-03-0.25/

**Comment by Povezi** [comment]
Hi @brindosch 
it looks that after reboot my OpenElec died (no picture on HDMI, shell is working)

update log:

OpenELEC (official) Version: 6.0.3
rbp2:~ # curl -# -k -L --output install_hyperion.sh --get https://raw.github.com/hyperion-project/hyperion/Beta/bin/install_hyperion.sh && sh ./install_hyperion.sh BETA
######################################################################## 100.0%
*******************************************************************************
This script will update Hyperion to the latest BETA
Created by brindosch - hyperion-project.org - the official Hyperion source.
*******************************************************************************
---> Stop Hyperion, if necessary
---> RPi with OpenELEC/LibreELEC found, but SPI is not set, we write "dtparam=spi=on" to /flash/config.txt
---> Backup Hyperion configuration(s), if present
'/storage/.config/hyperion.config.json' -> '/tmp/hyperion.config.json'
---> Downloading the appropriate Hyperion release
---> Downloading Hyperion OpenELEC/LibreELEC release
######################################################################## 100.0%
---> Downloading Hyperion OpenELEC/LibreELEC dependencies
######################################################################## 100.0%
---> Restore Hyperion configuration(s), if present
'/tmp/hyperion.config.json' -> '/storage/.config/hyperion.config.json'
---> Starting Hyperion
*******************************************************************************
Hyperion Installation/Update finished!
Please download the latest HyperCon version to benefit from new features!
To create a config, follow the HyperCon Guide at our Wiki (EN/DE)!
Wiki: wiki.hyperion-project.org Webpage: www.hyperion-project.org
Please reboot your OpenELEC/LibreELEC, we inserted dtparam=spi=on to /flash/config.txt
*******************************************************************************
---> Do you want to reboot your Raspberry Pi now? (y or n) :y
---> You entered "y". Rebooting now...

**Comment by Povezi** [comment]
looks like a problem with CEC (HDMI)

rbp2:~ # tail -c 999 .kodi/temp/kodi.log 
ge - Open - vc_cec could not be initialised
20:44:05 614.031494 T:1860838464   ERROR: CecLogMessage - could not open a connection (try 10)
20:44:06 615.031860 T:1852449856   ERROR: OpenConnection - could not opening a connection to the CEC adapter
20:44:06 615.032410 T:1860838464   ERROR: CecLogMessage - could not start CEC communications
20:44:16 625.033386 T:1860838464   ERROR: CecLogMessage - RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
20:44:16 625.033752 T:1860838464   ERROR: CecLogMessage - Open - vc_cec could not be initialised
20:44:16 625.033875 T:1860838464   ERROR: CecLogMessage - could not open a connection (try 1)
20:44:17 626.034546 T:1860838464   ERROR: CecLogMessage - RegisterLogicalAddress - vc_cec_set_logical_address(E) returned invalid arg (8)
20:44:17 626.034729 T:1860838464   ERROR: CecLogMessage - Open - vc_cec could not be initialised
20:44:17 626.034851 T:1860838464   ERROR: CecLogMessage - could not open a connection (try 2)

**Comment by brindosch** [comment]
hm, data curruption on your sd?
Maybe your sd card is on a certain way at the path do die?

**Comment by Povezi** [comment]
right after reboot? no errors in dmesg... any other idea?

**Comment by brindosch** [comment]
Due to the point i also use (and some others too) the current beta there is not much room. And Hyperion can´t kill your mediacenter (at least i think so)

**Comment by Povezi** [comment]
update & good news: after hard reset (unplug power) kodi worked ... had to manually start hyperion, it works!

constant color in menu (rxtx still blinks all the time)
but, when screensaver goes on, rxtx finally rests ;) thanks!

**Comment by tpmodding** [comment]
maybe the rss newsfeed on the bottom could be the reason for the blinks/led activity on the menu :)

**Comment by Povezi** [comment]
nope, whole screen is static... rxtx shouldn't blink if there is no change (and event if smoothing is linear)

but, I think that most important is that know when it is sleeping (all leds are off) rxtx is not blinking anymore - I can listen to radio ;)
