### ISSUE TITLE
Lightpack no lights and no clear issues

### ISSUE THREAD

**Issue by GMBrian** [tvdzwan/hyperion#320]
Hello,

I have hyperion seemingly correctly installed but the lights aren't turning on at all.

I bought lightpack about a year ago and have switched on my Raspberry Pi B+ to OSMC recently. I wanted to get lightpack working again and just followed the installation guide but the lights aren't responding. I used to config tool to get a default Lightpack hyperion config and it's loaded without errors:

> osmc@osmc:~$ sudo hyperiond /etc/hyperion1.config.json
Application build time: Mar  6 2015 20:57:44
QCoreApplication initialised
Selected configuration file: /etc/hyperion1.config.json
ColorTransform 'default' => [0; 49]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "/dev/spidev0.0",
        "rate" : 250000,
        "type" : "lightpack"
}

> USB context initialized
Found a lightpack device. Retrieving more information...
Lightpack device found: bus=1 address=7 serial=95230303231351F09160
No Lightpack device has been found
Black border threshold set to 0.01 (3)
Not creating any smoothing
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Initializing Python interpreter

And when I try the sample command it also gives to errors:

> osmc@osmc:~$ sudo hyperion-remote --priority 50 --color red --duration 5000
Connected to localhost:19444
Set color to 255 0 0

Same goes for the Android Hyperion Free remote you guys released. It seems to connect just fine but no light are turning on what-so-ever.

I've tried restarted the service and all but I'm not sure what to do or where to start resolving this.

**Comment by Gamadril** [comment]
I guess you have to put the serial number to your config file:
```
{
"colorOrder" : "rgb",
"name" : "MyPi",
"output" : "95230303231351F09160",
"rate" : 250000,
"type" : "lightpack"
}
```

**Comment by brindosch** [comment]
Should be done

Just open a new issue if not
Thank you
