### ISSUE TITLE
OPENELEC, Rasplex, Hyperion ---> Adalight

### ISSUE THREAD

**Issue by sticilface** [tvdzwan/hyperion#321]
Im running hyperion in serial Adalight mode, really well.   I have some WS2912B connected to an arduino running an adalight sketch.  And it is almost perfect...  there is a bit of gitter...

I've tried to boost the baud rate from 115200, to say 240000...  but it doesn't work.  the arduino works fine at that baud rate taking to my mac, so the question is... does the pi support that over usb, using openelec? I've adjusted the hyperion files accordingly. 

Cheers

A

**Comment by iLLiac4** [comment]
It can work if you will use https://github.com/poljvd/script.service.hyperion but then memory will be eaten.

Or. did you find any other solution?

**Comment by NicoHood** [comment]
You also need to push the serial speed of the arduino. Also depending on what arduino you use, there are limitations:

* Linux does not support all baud rates. This causes me so many trouble, just stick with 115200 for linux in general.
* The Arduino Uno has a pretty bad usb-serial implementation. See my HoodLoader2 Project with a full duplex 2M usb-serial
* The Arduino Leonardo is maybe still too slow for this
* The Arduino serial buffer is only 64 byte. With a bad coded Adalight sketch (and non spi leds) this is impossible to get in sync without data corruption.
* Use SPI leds and fastled library. I will publish a sketch for this sooner or later somewhere in one of my libraries.

115200 is fairly enough and avoids lots of problems. Also you set the speed to 20fps anyways in the settings. So you can shuffe a frame faster, but in the end you still wait for the next frame. I guess you adalight sketch for this chipset isnt perfect. It took me a long time to fix this problem in my sketch.

**Comment by brindosch** [comment]
This should be done, i will close it
Thank you
