### ISSUE TITLE
Raspberry pi and hyperion v4l2 leds crazy 

### ISSUE THREAD

**Issue by BTopbas** [tvdzwan/hyperion#322]
Hi all;
I used hdmi splitter and hdmi2av convert. I used stk1160 chipset video grabber. Hyperion is working great. I control effects and etc. But I try v4l2 screenshot file comes black and white. And I change mode PAL to NTSC. And colours comes. Screenshot is very nice. Working. But I start hyperion v4l2 leds is crazy. Mostly not work and sometimes flickering true colours. I deleted framegrabber in configuration restarted and still same. What's wrong?

**Comment by BTopbas** [comment]
And when i start hyperiond in ssh terminal. Boot effect is very nice. then grabber start and i see a lot of this messages..
Frame too small: 686286 != 691200
Frame too small: 686608 != 691200
Frame too small: 686384 != 691200
Frame too small: 686306 != 691200
Frame too small: 687390 != 691200
Frame too small: 688114 != 691200
Frame too small: 687034 != 691200
Frame too small: 687654 != 691200
Frame too small: 687182 != 691200
Frame too small: 686928 != 691200
Frame too small: 687334 != 691200
Frame too small: 687410 != 691200
Frame too small: 686782 != 691200
Frame too small: 688332 != 691200
Frame too small: 688088 != 691200
Frame too small: 687460 != 691200
Frame too small: 686522 != 691200
Frame too small: 686716 != 691200
Frame too small: 686620 != 691200
Frame too small: 686950 != 691200
Frame too small: 686290 != 691200
Frame too small: 687098 != 691200
Frame too small: 687598 != 691200
Frame too small: 688554 != 691200
Frame too small: 687014 != 691200
Frame too small: 686214 != 691200
Frame too small: 687166 != 691200

**Comment by brindosch** [comment]
stk1160 is not compatible with never raspbian images. Stick with utv007

Closed, if you encounter any errors please open a new one
