### ISSUE TITLE
Hyperion - OpenElec - LightBerry - TV problem

### ISSUE THREAD

**Issue by keo95000** [tvdzwan/hyperion#323]
Hi everyone,

I've recently install my LightBerry on my TV with a OpenElec + Hyperion on my rasp.

I use the HDMI Premium Kit from Lightberry official website.

When I watch a video from my rasp, no problem, leds are good.

When I test a screenshot with the following command : 
LD_LIBRARY_PATH=/storage/hyperion/bin /storage/hyperion/bin/hyperion-v4l2 --screenshot

I've this result : 
V4L2 width=360 height=288
V4L2 pixel format=UYVY
V4L2 grabber signal threshold set to: {0,0,0}
V4L2 grabber started
V4L2 grabber stopped

So I can found my screenshot, 
![screenshot](https://cloud.githubusercontent.com/assets/12443771/7630574/ac79f544-fa37-11e4-8382-62282739c9ac.png)

I've 2 problems, is that screenshot is correct? Because it's seems very ugly too me...

And my leds don't do anything when I'm watching my TV.

Thank's for your help.

**Comment by BTopbas** [comment]
Which chipset your grabber? STK1160 or UTV007 ?

**Comment by keo95000** [comment]
Hi,

It's STK1160.

Thx

**Comment by tpmodding** [comment]
@keo95000 still need help or can be closed?

**Comment by keo95000** [comment]
Yes, can be closed.

Thanks.

**Comment by tpmodding** [comment]
Could you close it please? I have no rights. Thanks

Von meinem iPhone gesendet
