### ISSUE TITLE
Flashing LEDs on RPi2/OpenElec/Hyperion/LightBerry

### ISSUE THREAD

**Issue by influman** [tvdzwan/hyperion#325]
Hi everybody,

i've got an old 48-Leds LightBerry which used to work perfectly in my previous home, on a RPi B+ / OpenElec 5.0, directly connected on GPIO pins, for KODI exclusively (no hdmi grabber needed, etc..)

I recently move in an new home and reinstall it on a Rpi 2 / Openelec 5.08.
Hyperion has been installed manually, as usual, with my own classic hyperion.config.json file.
And LightBerry is still connected on GPIO pins.
No light, so i fixed a first issue with the add of "dtparam=spi=on" in my openelec config.txt file, and light appears (why do we have to do that now, not cool...)
There's no more specific issue when i launch hyperion on the command line.

But now, my LEDS are flashing when there are movements on screen. On KODI Menu, it stabilizes, but with the wrong colors. On boot, the rainbow swirld effect makes LEDs blinking violently !
It's a mess...

I put it on my old B+ Raspberry (wich has been yet updated with openelec 5.08), it's the same issue.
With the Hyperion Android App, same problem, LEDs are not colored as expected and are flashing.
I changed the baud rate to 250 000 : still flickering

Do you have an idea, i think i checked the entire Internet :(, still no solution...
Is that an electric or power supply issue ?
Is the Lightberry converter ko ?
Is that interference ?
It works fine for some users with the same softwares package (Openelec 5.08 / hyperion / lightberry)
The LightBerry support didn't answer my request.

thx for your help

**Comment by tociek** [comment]
Greetings from Lightberry support, 

Please drop us an email. We always answer and make things work. 

Jacek

**Comment by c-o-m-m-a-n-d-e-r** [comment]
same here ... today installed ws2801 with 50 LEDs on a rpi2 running latest openelec.
Installed hyprion with script and make config file.... lights are working but with movements on screen the lights are more flashing than changing smooth ...

Think must something with the firmware / kernel ...

**Comment by influman** [comment]
For me, it's flickering even with hyperion native effects (no kodi movie played, so no image analysing)
A Knight Rider effect now makes leds flashing green while red movements...

**Comment by c-o-m-m-a-n-d-e-r** [comment]
yes i try knight rider effect right now ... its working most the time with some green / blue flashes between

**Comment by influman** [comment]
@c-o-m-m-a-n-d-e-r In the Hyperion Android App, can u just do this test 

Set All Gamma to 1, all HSV to 1, Threshold to 0
And in the colorwheel, choose color Red, and try first with a low luminosity.
Normaly, with that, it's ok with the good color, without flickering. It's like in the Kodi Menu. True colors, no flash.

Then, in my case, when i progressivly set a higher luminosity, LEDs are moving to different colors than red, finishing like a flickering rainbow...
I think that's producing the real issue we have, which appears suddenly.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
having the ios app ...
i can reproduce the problem with traffic on lan port ... when i watch tv or a movie from my nas and let the rainbow effect run i have flickering effect.

if i stop movie / live tv, so no traffic over lan port the rainbow effect runs perfect

**Comment by influman** [comment]
i turned off my ethernet switch (no lan traffic anymore).
After reboot hyperion, the intro effect is still bad...

2015-05-25 15:21 GMT+02:00 c-o-m-m-a-n-d-e-r <notifications@github.com>:

**Comment by c-o-m-m-a-n-d-e-r** [comment]
ok but you are using lightberry correct?
I have connected my WS2801directly on the GPIO

**Comment by influman** [comment]
yep, lightberry on GPIO SPI (it's like WS2801).

**Comment by c-o-m-m-a-n-d-e-r** [comment]
okay, checked openelec 5.0.3 on rpi2 ... same problem but with lower quantity of flashing...
testet same wiring on rpi1 with openelec 5.0.8 ... everything works fine without any problems...

**Comment by influman** [comment]
Great news !
Thx to Jacek (Lightberry), my actually hardware issue has been fixed !
So it wasn't a soft issue, neither hyperion.

**Comment by tomasxb** [comment]
Hi there
Could you please tell us what was the problem?
I think I get the same flashing lights as you..

**Comment by tomasxb** [comment]
After contacting lightberry support, they found out that my converter box had an issue.
Problem solved, great support, thanks again Tomek
