### ISSUE TITLE
ESP8266 support

### ISSUE THREAD

**Issue by iLLiac4** [tvdzwan/hyperion#326]
Did someone try to find out if it would be possible to create ESP8266 enabled ambilight with Hyperion or. replace Arduino with this module so it could work over wifi?

Some example:
http://forum.team-mediaportal.com/threads/diy-atmoorb-a-hue-like-mood-lamp-based-on-arduino-esp8266-wifi-module-and-ws2812b-rgb-leds.129229/

**Comment by sticilface** [comment]
I've been working on trying to get exactly this to work!  

I've got a rpi with rasplex that runs hyperion outputting by serial at 115200 baud to an arduino pro mini and controlling ws2812s using ADALIGHT.  Works very well.  Very well... 

BUT...  i want to be able to control it using sound and my own effects created in C...  so i was hoping to use the ESP8266 instead...  using a web or MQTT interface to switch between... hyperion on tv.. arduino effects...  but i can't get the serial streaming to work.  

All the versions of ADALIGHT for the arduino, use a blocking while loop, waiting for serial content to stay in sync... 

I have got UDP streaming to ESP to work, and controlling lights... and it looks awesome!  

Can hyperion get UDP streaming support... that would help?

**Comment by Povezi** [comment]
take a look on U(nofficial)DK project and these pages.. 
http://www.esp8266.com/viewtopic.php?f=6&t=2133&start=40
http://esp8266.ru/downloads/sdk/#wpfb-cat-5

**Comment by sticilface** [comment]
Forgot I'd left posts here. I've actually rewritten the adalight stuff to work on the arduino esp8266 IDE. Works great. Much better than on arduino as I've got a baud rate of 2,000,000 running. So it's much faster, no lag. I've also implemented udp streaming. 

Will post code once I've tidied it up.

**Comment by iLLiac4** [comment]
Could you paste the code in pin outputs and also the config of hyperion.
So basically this is like wireless arduino(adalight)?
TNX

**Comment by Povezi** [comment]
Sticilface, this sounds fantastic! please post code.

How did you interfaced ESP with computer? Is it via USB2TTL serial or mayne Raspberry GPIO? (I have setup RBP+Arduino driving WS2812b but would gladly try 2Mbps instead of 500Kbps :+1: )

**Comment by sticilface** [comment]
I've got a fairly monstrous code base, that is a total mess, but works for controlling WS2812 LEDs using an ESP8266.  It has a whole bunch of modes, including UDP and adalight.    I'm using the LEDs with only one data channel.  3 pins not 4. 

The adalight works via USB to serial converter, which plugs into a raspberry pi running RASPLEX.  this now has hyperion support which got me interested as before this release i'd never heard of it.  I quickly rigged up an arduino and got a sketch from adafruit and had it working.   configured hyperion to use serial port, and adalight.  The only tweak is the order of colours.  I've made it native to the WS2812 bus, in neopixelbus as it is faster.  GRB must be the order set in hyperion.   The nano is limited to 115200, any speed above that did not work for me.  So i rewrote the script to work as a ' mode ' on my esp8266 lights... using the correct USB to Serial, that does 2,000,000 baud i have no problems.  and the lag has gone...  The ESP still has web server and MQTT running.  

I can control the whole lot by web page or MQTT. and the bonus is I can write my own effects in C, and have them on the ESP.  I did not want to be tied to the hyperion effects.  

so... code... 

I need to test this code to see if it works, at home....  I have stripped out the adalight as a stand alone example.  My main code is definitely not ready for public display.  but it will be.... 

@iLLiac4 I have UDP streaming working from pixel controller on a lamp, but it seems to crash it after awhile not so reliable.  I've not tried UDP with hyperion at all.

**Comment by Povezi** [comment]
FYI I thought that nano is limited to 115200 until I tried 500.000! It works perfectly. Here is why:
it is related to Arduino clock frequency. Lets say my nano is running at 16Mhz, and baudrate is 0.5Mhz, each 32. time it will send data.. if baudrate is 115200, it becomes difficult to precisely send and sometimes WS2812b signal goes out of sync.

BTW WS2812b have 3 pins (only 1 data) and I  think that is best way to communicate ;) 

For sure it is easier to use "adalight" in hyperion setup... but I think that in setup Raspberry + ESP USB serial converter is not necessary, and we should be able to connect them via GPIO header ?

**Comment by sticilface** [comment]
I did try that baud rate, and it didn't work either.  I think you are dependent on what ever serial converter your board has.  I'm using the super cheap, knock off ones from china (the nano) and none of them work over 115200.  It is the same for my NODE-MCU V1 board.  It doesn't really matter though.  Whatever works for you.  

I'm not sure there has been any success in driving WS2812b using a single GPIO on the raspberry pi.  These things need very very precise timing.   There is a hack that uses the audio GPIO or something like that to drive these LEDs, but it only works on the pi1s.   Im also using pi2, so not an option.  This set up is working pretty smoothly now, and i have the added options of choosing effects, colours, and i have it plugged into my home automation system, being controlled by MQTT.  can't do much of this with hyperion alone. cost is not really an issue, $3 for an ESP, $2 for the serial adapter! ;)

**Comment by Povezi** [comment]
Yap, cheap nano @ 500.000 bps: 
http://ai.rs/wp-content/uploads//2015/03/RaspberryPiArduinoHyperionAmbilight_ArduinoNanoConnected.jpg

complete guide of setup: 
http://ai.rs/reviews/rgb-delight-raspberry-pi2-arduino-nano-ws2812b-using-hyperion-on-openelec/


I also use RPi2, but I think it cannot drive WS2812b directly via GPIO because it requires precise timing, but if we connect GPIO to ESP, ESP could drive led strip...

Nice to hear that you have MQTT controlled ESP + RGB :)

**Comment by sticilface** [comment]
Here is a working adalight sketch, just tested it and it works
My first piece of public software, so go easy ;) 

https://github.com/sticilface/Adalight-ESP8266.git

**Comment by brindosch** [comment]
Is this still ongoing or could we close?

**Comment by tpmodding** [comment]
@iLLiac4 @sticilface @Povezi 

It works! I use ONLY an esp8266
https://www.dropbox.com/s/dxnn1zr6dedx0qh/Datei%2016.03.16%2C%2018%2006%2032.mp4?dl=0

@SciLor is working on it, but still have to do some changes :)
http://www.forum-raspberrypi.de/Thread-hyperion-tutorial-esp8266-nodemcu-addon-wifi-led-controller-udp
https://github.com/SciLor/ESP8266_Hyperion_LED-Controller

**Comment by penfold42** [comment]
Here's my original code that I wrote to use my UDP driver if anyone's interested:
https://github.com/penfold42/stuff/blob/master/ESP-udp-neo.ino

**Comment by Povezi** [comment]
penfold42, it looks interesting...
so if I send
1222\n  
22111\n
333222\n

1 led will be hexcolor222, 22. led will be hexcolor111 and 333. led will be hexcolor222 ?

**Comment by penfold42** [comment]
Close!

The ascii stuff kinda grew and I never cleaned it up to the parse has to look for a few possibilities.

7ABE sets led 7 to colour A0B0E0

42FF7700 sets hex led 42 to FF7700 i.e. Full red with some green added

Then it some longer led atrips!
10CFF7700 sets hex led 10C to the same colour

*00F sets all LEDs to bright blue

**Comment by drc85** [comment]
im a noob i just managed to get ambilight running... also i already did a wemos (esp) led light with a web server... i also want to control ALL my LED over the web server... imanager to controll two diffrent esp over the webserver... but i would like to add the ambilight also... any easy ways :D thx happy new year

**Comment by penfold42** [comment]
The forums are a better place for discussing this 

https://hyperion-project.org/
