### ISSUE TITLE
Add UDP streaming

### ISSUE THREAD

**Issue by sticilface** [tvdzwan/hyperion#329]
simple... RGB packet stream? with IP + port -/+ multicast ?

**Comment by daaf84** [comment]
That would be nice! I'm looking for this option.

**Comment by sticilface** [comment]
so in the end i went a different route for this... i've written a 'fairly' advanced sketch in the arduino IDE for ESP8266 which can control a strip of WS2812s... I then re-wrote the adalight sketch for esp8266 that works in a non IO blocking way, plus around 20 difference effects, plus the option for UDP streaming... all in one ESP...  just google esp8266 to see what it is.. its an arduino + wifi - a few GPIOs.. but it can run up to 160Mz... 

I've got hyperion running to it at 2,000,000 baud rate, via a usb-uart.  it is much better performance than using an arduino nano, even matches lightning when watching TV.  it is also much easier to control it.  switch it to adalight and adalight works..,  switch to UDP that works, pick a colour, fade effect, dimming, speed of animations.  And it is all configured through a web page.   

If ur familiar with ESP, and can flash an ESP8266 with binaries i can send them to you.

**Comment by daaf84** [comment]
It looks like you are doing what I wanted to do! Great!! Last week is received my ESP's from eBay. ;) 
I wanted to make two wireless lights (1 left side, 1 right side of the screen)  in addition to my 50 WS2801's which directly are connected to my Raspberry Pi.
Do you have this all documented? Please, can you send me what you want to share with me to: 
daaf84 [at] kpnmail [dot] nl?

**Comment by YoBnEb** [comment]
Hi sticilface,

your work for ESP8266 sounds really great.
I'm also very interested in testing your current solution.

It would be great if you could also send me some details.

Thanks in advance

yobneb [at] googlemail.com

**Comment by sticilface** [comment]
see this post guys. 

http://www.esp8266.com/viewtopic.php?f=29&t=3470

**Comment by penfold42** [comment]
Is anyone interested in native UDP streaming ?

I've been playing with the existing "test" driver by catching its output with a small perl script to then udp it and it seems to work pretty well.

The target is an esp8266 with my own simple protocol.

**Comment by penfold42** [comment]
I've now written a basic udp led driver that works.

I need to add some parameter handling for host+port and ideally transmit speed.

It's a simple raw protocol - the packet is assumed to start with led0 and its 3 raw bytes per led RGB.

**Comment by tpmodding** [comment]
@sticilface udp added now, could you please close the issue?

**Comment by sticilface** [comment]
Sure thing. Does anyone know if this version is in rasplex?
