### ISSUE TITLE
no connection android hyperion app with Rpi2

### ISSUE THREAD

**Issue by thebul** [tvdzwan/hyperion#331]
I have a rpi 2 and I have a Lightberry HD connected.
Now i have managed to get the Lightberry to work, but I've been working on for a very long time to link the Android app Hyperion free but every time I get the message unable connect to.
I have my IP address from my Rpi also I have the port number 19445 filled in that was in the file I created with hypercon.
No data can also send to the rpi with the program hypercon ssh.
Only when I fill in port 9090 I get no error message from the app ,just nothing happens.
Please help me, then I can hopefully configure the Lightberry easier.

**Comment by thebul** [comment]
Its not needed enymore i have it working now

**Comment by tpmodding** [comment]
@thebul could you close this also? thanks
