### ISSUE TITLE
Just gotta ask this question

### ISSUE THREAD

**Issue by cbabbman** [tvdzwan/hyperion#332]
Is Hyperion being actively developed/updated at this time?

Seems like there is relatively little going on in terms of either, other than a couple of month ago update to the configuration tool...

**Comment by tvdzwan** [comment]
You are right at the moment we are not actively developing. We do not even have the time to regularly read the 'issues'/forum and reply to it.

**Comment by theceo95** [comment]
Given that Hyperion isn't being actively developed right now, would you know which was the latest OS+version (OSMC, Raspbmc, OpenELEC, etc) the current Hyperion code was developed for?

I've had a lot of trouble getting it to work at all on any current OS, so maybe going back to an earlier OS version would be the fastest way for me (and others with the same issues) to get up and running? Just an idea - thanks!

**Comment by ntim** [comment]
Compiles on raspbmc (no more maintained) and osmc following the compilehowto.

**Comment by tpmodding** [comment]
@cbabbman can this be closed?

**Comment by brindosch** [comment]
Should be done 

Closed
