### ISSUE TITLE
Unable to stream using Framebgrabber

### ISSUE THREAD

**Issue by chetanbele** [tvdzwan/hyperion#334]
Hi All,

I have a small setup of server PC, Client PC (both are Ubuntu 12.04) and Framegrabber. Camera is connected on input side of framegrabber. Framegrabber is connected to Server PC via Ethernet cable and i am trying to RTSP video stream on server PC ( using VLC, MPlayer, Gstreamer). I dont know why but it is not working out.

Instead of framegrabber, when I am connecting IP_camera to server PC and running the same script, it works perfectly fine. IP address of framegrabber and IP_camera are same.

Framegrabber details: VRMagic D3

Please suggest me what are the tests I can do for making it run using framegrabber.
Thanks in advance!!!

**Comment by brindosch** [comment]
Closed, if you have any error just open a new one
