### ISSUE TITLE
Hyperion not working when watching Live TV in Kodi

### ISSUE THREAD

**Issue by nurtext** [tvdzwan/hyperion#335]
Like the title says, everything works but Live TV in Kodi. Any ideas how to fix?

**Comment by oxhak** [comment]
I am using hyperion-X11 to capture the whole zone of my tv, with a vlc window from a dvb-t tuner.
I don't need Kodi at all, I don't know what is your configuration for Hyperion, but that works fine.

**Comment by tpmodding** [comment]
@nurtext can be closed?

**Comment by nurtext** [comment]
@tpmodding think so, must be a problem with Hyperion plugin for Kodi.

**Comment by tpmodding** [comment]
Could you close it please? I have no rights. Thanks

Von meinem iPhone gesendet
