### ISSUE TITLE
[SOLVED] Hyperion only works with EXACTLY 50 leds

### ISSUE THREAD

**Issue by killgriff** [tvdzwan/hyperion#336]
Hello, I have been using boblight and have decided to switch over to hyperion. I am running OSMC on a pi2 with a ws2812b led strip controlled via a arduino uno. As the headline says, I can get hyperion to work correctly, but only with 50 leds (0-49) and I need 212. I have tried everything I could think of in the /etc/hyperion.config.json file: editing the number of "indexes", changing the "id" and "leds", playing with "smoothing", editing the other config file in /opt/hyperion/config/... I'm out of ideas.

My files:
[**Hyperion**]
(https://drive.google.com/file/d/0B6h86LY88C4FLXZUbXl6VzBVZk0/view?usp=sharing)
[**Arduino Sketch**]
(https://drive.google.com/file/d/0B6h86LY88C4FV1otYmgzRDd3dDg/view?usp=sharing)

The hyperion file does not work with the exact configuration in the file above, but by deleting the "extra" led's so there are only 50 and not changing anything else does work. Doing this, however, essentially makes ~4 repeating patterns in the led strip, separated by 2 leds, since the arduino sketch calls for 212.

**Comment by Gamadril** [comment]
Google Drive says: "You need permission"

**Comment by Nico83500** [comment]
Same problem with Google Drive, but do you have modified Arduino sketch to manage 212 LEDs ?

**Comment by killgriff** [comment]
Sorry about the links, they should be working now.

**Comment by Nico83500** [comment]
What is your physical LEDs configuration ? What is your power supply ? How many power point do you have ?

**Comment by killgriff** [comment]
I have a 5V AC adapter powering the led strip directly. The Pi is powered from the usb port on my tv. Everything worked perfectly fine with boblight, so nothing external should be an issue. I must just be missing something in either the hyperion config or the arduino sketch.

**Comment by tvdzwan** [comment]
Your Arduino code has the number of leds fixed (in the prefix) at 0x31 (+1) which is 50 in decimal. You should modify the prefix to have the correct number (or remove checking the last few bytes of the prefix).

**Comment by killgriff** [comment]
I ended up finding another arduino sketch that worked with hyperion and any number of led's. Thank you though, @tvdzwan - your suggestion should work as well.

**Comment by NicoHood** [comment]
If its solved, close the issue.
