### ISSUE TITLE
WS2812B DI channel voltage

### ISSUE THREAD

**Issue by Apalasys** [tvdzwan/hyperion#337]
Hi. I have used a 74HCT125E IC to step up the voltage of the DI channel. How can I test that the voltage on that channel is in fact running at 5v now, instead of 3.3v?

**Comment by Povezi** [comment]
check with your scope? or read IC spec...

but, why should you do that? Try connect your arduino to PC/Raspberry and it will have 5V logic levels

**Comment by Apalasys** [comment]
I'm not using an arduino or PC. I'm using the 74HCT125E chip to do the level step from 3.3V to 5V on the GPIO out to the DI on the WS2812B strip ... I don't  have a scope. Can I just use my multimeter on the ground of the chip, and the DI output pin on the chip to check the voltage? Will that blow anything?

**Comment by Povezi** [comment]
Yes you need 5v levels for ws2812b. You cannot measure it with multimeter because it is 800khz digital signal, but you can make GPIO level "1" and then measure it when signal is constant. You will now blow anything with voltage meter but do not choose resistance or current meter position.

**Comment by Apalasys** [comment]
Thanks a lot. Will try that. The lights are all working with Hyperion, so I
assume the level shifter must be working, but I would just like to verify.

**Comment by tpmodding** [comment]
@Apalasys fixed? can be closed?

**Comment by brindosch** [comment]
I will close it, just open a new one!
Thank you
