### ISSUE TITLE
Hyperion and Grabber V4l2 - back led blinking in green

### ISSUE THREAD

**Issue by JulienStrasbourg** [tvdzwan/hyperion#339]
Hi, 
I use a RPi 2 with openelec 5.0.5 and hyperion. 
When i start my RaspPI, i have the middle buttom of the leds that are green (just a little, i think 30-40%). However, using this commande : 
"
killall hyperiond
/storage/hyperion/bin/hyperiond.sh  /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &
"
(founded on this site)
the problem is solved until the next reboot of RPi.

someone knows what's wrong with my config ?
I'm a noob in the openelec or rapsberry configuration but i'm very curious and i learn quicly :)

**Comment by tpmodding** [comment]
@JulienStrasbourg did you fixed your problem? or can this issue be closed?

**Comment by brindosch** [comment]
I will close it, just open a new one!
