### ISSUE TITLE
Hyperion + Raspberry Pi: Lights when not watching video

### ISSUE THREAD

**Issue by Abolfazl** [tvdzwan/hyperion#341]
On my Raspberry PI running OSMC + Hyperion, the automatic lights only seems to work when there is a movie/video playing. Is there anyway to have the automatic (ambilight) lights come on even when I am not watching a video?

**Comment by Liukkjan** [comment]
I am also interested in this. Like would it be possible to implement a "pause lights" to hyperion? E.g it sees that XBMC is paused and after a certain period (or immediately?) it turns all the lights to white or dim or off. Would be cool. I'll look into it

**Comment by tvdzwan** [comment]
Hyperion has a concept called 'priority channels'. Each input defines a certain priority number. The channel with the lowest number takes priority. For example if you start some kind of effect at priority channel 1000 and have the grabber running at 100. The effect should kick in when no video is detected.

**Comment by Abolfazl** [comment]
That does not answer my question.. I am not talking about running an effect from the effects folder, I want the ambient light effect to be running even when a video is not detected (i.e. show the OSMC/Kodi screen border when a video is not playing)

**Comment by tvdzwan** [comment]
There is an option in the hyperion configuration which disables/enables the grabber based on preferences. This is under the xbmcVideoChecker section.

**Comment by Abolfazl** [comment]
What would the option be when it is at the main screen? I saw there was a grabMenu but that makes me believe that is only for when you are in the actual menu and not just the main screen

**Comment by tvdzwan** [comment]
What is the main screen?

**Comment by Abolfazl** [comment]
Like 

![image](https://cloud.githubusercontent.com/assets/116760/8555602/02ca886c-24a6-11e5-99d1-8ed50a6d72fa.png)

**Comment by tvdzwan** [comment]
Oh, ok that is indeed switched with the 'menu' option.

**Comment by brindosch** [comment]
Should be answered

Closed
