### ISSUE TITLE
Colors suddenly reversed?

### ISSUE THREAD

**Issue by jjwilson4** [tvdzwan/hyperion#342]
Hi there,

I installed Hyperion and it worked flawlessly for about two weeks [RPi2 / OSMC / WS2801].

Last night for some reason the colors were mirrored across the vertical axis, and I cannot seem to find an answer to the problem.  Any insight on what may have happened?

**Comment by croftman** [comment]
Install WS2801 with RPI1 and hyperion todayand all is fine except this reversed colors ! Like you, to the vertical axis (blue instead green)

**Comment by brindosch** [comment]
Should be done

Closed due to age. Please open a new one, if problems still exists.
Thank you
