### ISSUE TITLE
(WS2801) No LED output on OSMC or OpenELEC

### ISSUE THREAD

**Issue by theceo95** [tvdzwan/hyperion#343]
I've been trying on and off for about two months to get a Raspberry Pi/Hyperion Ambilight clone up and running, and unfortunately I haven't gotten anywhere. I first tried Lightberry HD, and then I tried two individual 5m WS2801 strips and a WS2812 strip (with multiple separate power adapters). I've tried multiple releases of OSMC (RC1, 2, and 3) and multiple releases of OpenELEC 5, and I've tried two different Raspberry Pi B+ and two different Raspberry Pi 2 models with several different micro SD cards. I've tried reinstalling Hyperion at least a hundred times by now, and I've used a lot of different sets of instructions online. The farthest I've gotten is getting the strip to totally light up in an OSMC build, and send color commands to it. I couldn't get the effects commands to work though. Then it stopped working, so I reinstalled Hyperion, and now I'm back to being unable to get the LEDs to light. I've tested the strips with a multimeter and they're getting ~5v all the way through, and there's no difference in my wiring configuration now versus the one time it worked (and I've checked the soldered connections and the first few LEDs - nothing is lose and wiggling them didn't interrupt the signal when the lights worked). So the only thing I can figure is that there's some issue with the software or how I installed it. Because almost everyone else online seems to have this up and running in 15 minutes with no issues using the same instructions I figured either a hardware component was bad or I was doing something really stupid, but I've tried pretty much every possible option and looked through hundreds of sites and forums trying to find advice on this. The baffling thing is that I'm having the same issues on both OSMC and OpenELEC, so I don't know what software issue could explain this either.

Anyway, I'd be really grateful for any help you guys can provide in troubleshooting this. I desperately want to get this working and I'm driving myself crazy at this point trying to find a solution. Maybe someone could send me a known working image of OSMC/OpenELEC with Hyperion pre-configured and installed, or walk me through a fresh install and I'll tell you what happens? If you have any questions about my setup or the issues I've had, just let me know and I'll give you as much detail as possible. Thanks!

**Comment by welitonxd** [comment]
we are in the same boat friend, I am three days trying to light on these damn lights without success and all you said is what I'm going through right now, very disappointed with myself, already I tried almost everything.

**Comment by tvdzwan** [comment]
Did you run hyperion manually from the command-line? Maybe the command-line output will give an idea of what is going on.

**Comment by theceo95** [comment]
@welitonxd Glad to hear I'm not the only one! I was starting to feel like an idiot, because based on all the hyperion how to's on the Internet it seemed like I was the only one with this problem.

@tvdzwan I did run hyperion from the command line, and usually I wouldn't get any response from the lights. But one time, by plugging and unplugging the data wires in various orders eventually a few lights came on, and then the whole strip lit up and responded to the command line. I had to remove the priority commands for the strip to respond though. The hypercon tool wouldn't control them, but I assumed that was just because I was using OSMC and the commands in hypercon are for a different OS, like OpenELEC?

I can try running hyperion from the command line again tonight, but recently when I've tried installing it I get the "insserv: warning: script 'hyperion' missing LSB tags and overrides" error. None of the suggested for that online seemed to get rid of it for me.

**Comment by tvdzwan** [comment]
The 'insserv...' warning is not a major concern. It has to do with how the init script is formatted. The hyperion script is missing the required header tags.
What do you mean by priority commands?

**Comment by theceo95** [comment]
Ok, so hyperion should work the same even with that warning?

And, I meant that when I was running from command line, the code "hyperion-remote --priority 50 --color red --duration 5000" didn't seem to do anything, but "hyperion-remote --color red --duration 5000" worked.

**Comment by tvdzwan** [comment]
Running 'ps aux | grep hyperion' should tell you if hyperion is running.

**Comment by theceo95** [comment]
Ok I'll try that when I get home tonight - thanks.

Also, if you look at the last video in kiryl85's latest post in this thread (https://github.com/tvdzwan/hyperion/issues/6#issuecomment-119336359), I was having the exact same effect with the LEDs flashing wildly when I first got them to turn on at all. Also, the voltage throughout my strip is ~5.5V not an even 5V. I assumed the .5V difference was trivial and everything was fine, but based on that thread my power supply may be part of the problem.

**Comment by welitonxd** [comment]
I would post a large text motivation here, but now I'm almost back to square one, installed raspbian and downloaded the hyperion, as was already connected by default the lights came on, I marveled commands worked, the android application worked, was all going well, hung up and called the rasp, the lights went on and accepted the commands, turned off the power of the LEDs and when religuei worked again, everything was perfect, I turned off all to switch places and become more comodo for me the tests was doing there the LEDs did not light again, I tried all possible ways and so I came back to almost square one, redid the whole process of installing raspbian again and this time not worked, the lights do not light up when the lights lit, the power that was one 5V 3A that the multimeter marked her as 5.47V for 22 leds'm trying to make it work, but via software options have been exhausted.

sorry for my english I am using the translator .

**Comment by welitonxd** [comment]
My soldering iron arrived, and decided to cut the led for testing, and is not that worked without a hitch? what took this whole experience is that "never trust the welding of a Chinese" good, now is to continue the tutorial, thanks to you guys for supporting me to answer and hope, as I said earlier, software was not, the problem was in hardware.

**Comment by theceo95** [comment]
Sorry about the delay - was really sick for the past couple weeks and then spent a little more time playing around with the lights myself before coming back with an update. Anyway, I'm at the point where the lights work perfectly when grabbing frames from Kodi on the RPI, but when I try introducing an external source and using the v4l2 grabber, the lights don't work reliably. Most of the colors are generally correct, but with occasional random flickering, and a lot of flickering when displaying a still image. I've tried three HDMI to AV converters (one works a lot better than the other two, but still a decent amount of flickering), and removed the HDMI splitter for testing purposes with no fix. So it seems like it's most likely either the Easycap comp-to-usb grabber (I have two more arriving tomorrow for more testing), or some issue with the RPI/hyperion in processing the data it's receiving. Maybe changing some settings for the grabber in hypercon would help? Any ideas? Thanks for all the help - I feel like I'm so close!

**Comment by theceo95** [comment]
@tvdzwan Not sure if you've seen this yet, but any ideas what's causing the flickering? Two more UTV007 Easycaps and five different HDMI to composite converters later and still the same issue (some cause less flickering than others).

**Comment by Sabcoll** [comment]
Is your Pi connected via LAN?
If so, plug out the cable and try again.

**Comment by brindosch** [comment]
Closed due to age. Please open a new one, if problems still exists.
Thank you
