### ISSUE TITLE
So shy to commit a cmake issue

### ISSUE THREAD

**Issue by chaichenluo** [tvdzwan/hyperion#345]
I look through all the issues here, very few is about cmake. I am so shame to commit this kind issue.
1.  I ran cmake, and got this:
CMake Error at cmake/qt4/FindQt4.cmake:379 (include):
include could not find load file:
Call Stack (most recent call first):
CMakeLists.txt:52 (find_package)
CMake Error at cmake/qt4/FindQt4.cmake:743 (CHECK_CXX_SYMBOL_EXISTS):
Unknown CMake command "CHECK_CXX_SYMBOL_EXISTS".
Call Stack (most recent call first):
CMakeLists.txt:52 (find_package)
2.  "Google" taught me to remove the following line  from CMakeLists.txt in the root of the Hyperion repository:
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake/qt4)
It got a little further this time, but still got this:
CMake Error at libsrc/jsonserver/CMakeLists.txt:42 (qt4_use_modules):
Unknown CMake command "qt4_use_modules".
3.  "Google" told me to add "-DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF" to cmake flags, but there is no change.

 Anyone could give more advice, any reply would be appreciated.

**Comment by tvdzwan** [comment]
You should add a little bit more specification about your target platform, etc.
1) The indicated symbol is part of a standard cmake installation (http://www.cmake.org/cmake/help/v3.0/module/CheckCXXSymbolExists.html). You could try and locate the cmake-module (locate CheckCXXSymbolExists.cmake). 
2) Removing the custom find scripts for locating qt4 could have undesired consequences. There is a reason that Hyperion has its own version, as the standard version has trouble differentiating between qt5 and qt4.
3) Disabling DISPMANX makes sense if you are not building for the RPi. This is the video-grabber intended for that platform. However you do need to have some form of grabbing to capture screen content (X11, V4L, ...)
Disabling SPIDEV makes sense if the platform you are compiling for does not have a SPI-device.

**Comment by brindosch** [comment]
Should be done

Closed due to age. Please open a new one, if problems still exists.
Thank you
