### ISSUE TITLE
LED can change color with tv but still flashing(ws2801+hyperion+raspian)

### ISSUE THREAD

**Issue by jadore2008** [tvdzwan/hyperion#347]
Hi all:
I used vcd player(av signal) + stk1160 chipset video grabber+raspberry pi. Hyperion and ws2801 led strips works great .
But now I use AppeTV(hdmi signal)+hdmi splitter + hdmi2av convert + stk1160 chipset video grabber+raspberry pi. LED strips can chang the color with AppeTV video,but led still flashing.

I took this steps:
1.  change the PAL/NTSC in hdmi2av convert,and at the same time edit the hypercon.json.But it still flashing.
2.  I use AppeTV(hdmi signal)+hdmi2av convert + stk1160 chipset video grabber+raspberry pi.But it still flashing.
3.   use AppeTV(hdmi signal)+hdmi2av convert + stk1160 chipset video grabber+PC. In PC ,I install a video capture software to monitor video from  usv video grabber.In NTSC mode ,I can see the video from AppeTV.But in PAL mode,the video is just black and white.

My english is poor ,sorry for that.
Could someone teachs me to solve this problem?

**Comment by brindosch** [comment]
@jadore2008 
is this problem still present?

**Comment by brindosch** [comment]
closed, just open a new one if problem still persists
