### ISSUE TITLE
Hyperion not working

### ISSUE THREAD

**Issue by gilsport** [tvdzwan/hyperion#348]
Hello
First of I am a huge fan of your work!
So got my ws2801 strip (still one piece) connected it to raspberry pi2 (BTW you need to upload a picture of how to wire it correctly to pi2 since this is not the same pins)
Connected to the PowerPoint (5v 4a) I got 98 leds in total.
At first connection the first led blinked then I unplugged it and it didn't happen since.
Now my leds are connected but no light.
Started Hyperion manually and this is the log:
osmc@osmc:~$ /opt/hyperion/bin/hyperiond /etc/hyperion.config.json
Application build time: Mar  6 2015 20:57:44
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 97]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "/dev/spidev0.0",
        "rate" : 250000,
        "type" : "ws2801"
}

Black border threshold set to 0.01 (3)
Creating linear smoothing
Created linear-smoothing(interval_ms=40;settlingTime_ms=100;updateDelay=0
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Boot sequence(Rainbow swirl fast) created and started
XBMC video checker created and started
Display opened with resolution: 1360x768
Frame grabber created and started
Json server created and started on port 19444
Proto server created and started on port 19445
XBMC Connection error (0)
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
effect finished
XBMC Connection error (0)

**Comment by brindosch** [comment]
@gilsport 
Is this problem still present?

**Comment by gilsport** [comment]
Nope

**Comment by tpmodding** [comment]
@gilsport could you close it please if you fixed your problem? thanks! :)
