### ISSUE TITLE
turn off the hyperion when send command to turn off Raspbian

### ISSUE THREAD

**Issue by welitonxd** [tvdzwan/hyperion#349]
After breaking his head and search a lot, read everything here, I could make it work, now I need a light to turn off the hyperion when sending the command to turn off the raspbian, I was never good with linux, I think this is easy, just need the way.

**Comment by brindosch** [comment]
@welitonxd 
which Raspian version are you using?

**Comment by deennoo** [comment]
Maybe juste use hyperion remote and use "clear all" with good priority

**Comment by welitonxd** [comment]
i dont remember now what i'm did, but when the screen stay black the lights turn off, so, its all ok for me.

**Comment by brindosch** [comment]
alright, thank you for feedback

could be closed

**Comment by tpmodding** [comment]
@welitonxd could you close the issue please? :)
