### ISSUE TITLE
hyperion not getting video from easycap dc 60

### ISSUE THREAD

**Issue by pete111** [tvdzwan/hyperion#35]
Hello, 

I am trying to capture video over EasyCap DC60 stk1160 (yellow cable) but on my raspbian 3.10.25 (raspberry pi) in mplayer video looks like this (green and messed video, artefacts): 
http://www.youtube.com/watch?v=27YLQKNKZtw&feature=youtu.be

And after few seconds it ends with thi error: http://www.youtube.com/watch?v=5cgQFc0i6vo&feature=youtu.be

I tried many settings (as well as vlc) but result is the same. What am I doing wrong? :(

**Comment by dubkov** [comment]
Hi all!

I confirm, that power issue takes place here.

Stk1160-based grabber works perfect on my linux-desktop, but on Raspberry Pi I've got nothing but  green screen. After connecting grabber to RPi via externally powered hub, I've got the image from analog source. But that image is not perfect. Looks like it is separated to 16 big squares and these squares are randomly copied and displaced.

**Comment by tpmodding** [comment]
@pete111 can be closed?

**Comment by pete111** [comment]
@tpmodding yes.

**Comment by brindosch** [comment]
I am using the utv007 and i get a good picture qualitiy from my tv scart. Are you using a hdmi to cvbs converter?

**Comment by tpmodding** [comment]
@pete111 we dont need a "hd" quality...it can also be blured...the screen will be convertert in "frames" and then we only get the pictures...i have utv007 and stk1160 and both are working fine!

**Comment by brindosch** [comment]
@pete111 
You will never get a perfect picture it´s a low budget (D->A) and  A->D processing.
I am using the default values for frame/size dezimation, the picture output is just am small pixel mess after this, but it is working perfect. It may be possible to create a second config for your grabber, if you need another gamma value.
It is no issue and no ongoing discussion. The last real post was Jul 2014.

I close it now. If you have any problems don´t hesitate to ask.

Thank you for your understanding
