### ISSUE TITLE
Cannot open the Serial port under Ubuntu (Adalight)

### ISSUE THREAD

**Issue by NicoHood** [tvdzwan/hyperion#351]
I recompiled hyperion for Ubuntu or better Elementary OS.
I added my user to the group dialout which is needed to access the serial ports with the arduino ide and without root access.

However I cannot open the serial port with hyperion. I want to use adalight for my ambilight. If I start the application with root access there is no such error. I am wondering why this happens because my user is in the group. Any idea?

```
hyperiond ~/Documents/hyperion/hyperion.config.json

Opening UART: /dev/ttyACM0
Unable to open RS232 device (IO Exception (95): Operation not supported, file /home/user/Downloads/hyperion/hyperion/dependencies/build/serial/src/impl/unix.cc, line 278.)
```

Edit:
By the way there is a typo (because):
```
The dispmanx framegrabber can not be instantiated, becuse it has been left out from the build
The framebuffer grabber can not be instantiated, becuse it has been left out from the build
```

**Comment by NicoHood** [comment]
I found the cause of this error:
I had a typo in the baud rate: 115000 rather 1152000.

The funny thing is that opening non standard baud rates works with sudo. But it didnt change the baud rate on the Serial port. After some trouble afterwards I noticed my baud setting was wrong. Because Adalight only worked when I opened the Serial port with the IDE at 115200.

So the bug is not that critical, it was rather my fault. There should be a warning for using non standard baud rates though.

**Comment by NicoHood** [comment]
I also want to mention that the reconnect doesnt work even though the replugged device has the same number (ACM0 still)
```
Serial exception caught while writing to device: SerialException device reports readiness to write but returned no data (device disconnected?) failed.
Attempting to re-open the device.
```

**Comment by tpmodding** [comment]
@NicoHood can be closed?

**Comment by NicoHood** [comment]
Well hyperion should warn about non standard baud rates if possible. However if you dont have this typo it should work. So its more or less a tiny feature for simpler debugging/error correction.

I think I can close the issue, while a fix for this would still be nice though.
