### ISSUE TITLE
Compile for Wetek Play 

### ISSUE THREAD

**Issue by tomaszszczerba** [tvdzwan/hyperion#355]
Hi,

I've been trying different configurations for compilation to use with wetek but with no luck, every time I have Segmentation fault when running new build. Could you please point me to some debuging log or things to try to make this working? Thank you in advance.

Regards,
Tomek.

**Comment by brindosch** [comment]
@tomaszszczerba 
you could try the new install script
https://github.com/tvdzwan/hyperion/issues/493

**Comment by brindosch** [comment]
No response

closed
