### ISSUE TITLE
no video with hyperion screengrabber on rPi2 B with openelec and hardware acceleration

### ISSUE THREAD

**Issue by mrgreywater** [tvdzwan/hyperion#357]
setup: hyperion on rPi2 with screengrabber input and adalight output to arduino (using usb with the /dev/ttyACM0 serial interface)

Everything works fine when disabling the video hardware acceleration in the kodi settings (except for the expected stuttering). As soon as you enable the hardware acceleration, and have hyperiond in the background executed, one of the following happens (depending on the video).

1. The video plays as it should with no issues
2. There appear random artifacts in single frames, and the hdmi video/audio drops out for a few seconds from time to time
3. There is no audio/video at all over hdmi. As soon as you stop either the video, or hyperiond, the hdmi output comes back up.

All of those issues disappear immediately and the video playback continues working flawlessly after killing the hyperiond process.

**Comment by mrgreywater** [comment]
I cannot reproduce it with the current alpha build of openelec, so I'm closing it here.

**Comment by benjy3gg** [comment]
I have the same problems on OSMC. Using Arduino and Adalight leds through ACM0 too.

**Comment by mrgreywater** [comment]
Can you try the Milhouse build? http://forum.kodi.tv/showthread.php?tid=231092
