### ISSUE TITLE
Raspberry Pi 2 Flickering with HD content playback.

### ISSUE THREAD

**Issue by BETEP-ok** [tvdzwan/hyperion#359]
Hi, guys.
ISSUE: for a very long time i was getting a very annoying flickering of the LED string that never happens while watching something from internet (by cable if it is important) but was ALWAYS happening if some local content was played from the HDD (WD MyBook USB 3.0) connected to the router. A long testing highlighted the fact that the more HD the movie goes - more frequent flickering becomes. With real low-res movies leds could be blinking once or twice per minute, with FullHD films - flickering was almost constant. Initially I was cursing the pad power supply and tried to lower the CPU frequency, play with the baud rate of Hyperion itself with 0 result. I also walked all the road from the cheapest phone-charger PSU to a 20-Euro HAMA PSU. result was the same- flickering.

Until yesterday I switched off the PSU of the external HDD, and by occasion that was the

SOLUTION: for some unexplainable reason - being connected to the Timecapsule, the HDD was the source of flickering LEDs. Being connected to the Raspberri PI directly - i get a cool solid ambilight with !!0!! flickering (tested one whole evening.)

PS read a lot of discussions on hte net, but didnt find that kind of suggestion anywhere- so decided to share my experience. So if you suffer from unexplainable led flickering and cable shielding. PSU replacement, frequency change doesnt help- try to connect the source HDD to the Rpi directly. there are chances it will help.

**Comment by brindosch** [comment]
@BETEP-ok 
People reported that problem.
For some people the solution is to use a levelshifter (3,3V to 5V)
others could not use the RJ45 (the higher the bitrate the higher the flickering)
In my case i have no problems with apa102 i am not sure if this is related to this.

**Comment by brindosch** [comment]
No response
Closed
