### ISSUE TITLE
Is there a limit on how many LEDs can be addressed?

### ISSUE THREAD

**Issue by KenV99** [tvdzwan/hyperion#360]
I am considering a setup using a RPi2 connected to an Arduino Leonardo to drive 4 chained 144 LEDs/m WS2812b strips. I was wondering what the software/hardware limitations might be in driving a larger number of LEDs.
Thanks.

**Comment by mrgreywater** [comment]
As the datasheet says, the operation speed of the WS2811 in highspeed mode is fixed at 800Khz.
Therefore you can drive no less than 1024LEDs in chained mode at 30Fps 

```
30*(s^-1) * 1024Leds * 24Bits + Frame Overhead < 800Khz 
```

At 60Fps, you can therefore drive around 512 Leds etc.

I don't know of any other hardware limitiation.

**Comment by KenV99** [comment]
Thanks for the reply! I was concerned that either on the RPi software side or in the arduino sketch that there might be an upper limit of 255 somewhere due to expecting a byte (one of the windows implementations has this limitation). I really appreciate you taking the time.

**Comment by tpmodding** [comment]
@KenV99 can be closed?

**Comment by KenV99** [comment]
Yes thx. 

- Ken

**Comment by tpmodding** [comment]
@KenV99 could you close it please? :) i cant

thanks!
