### ISSUE TITLE
Automatic Ambilight source change for Openelec

### ISSUE THREAD

**Issue by cmvac** [tvdzwan/hyperion#362]
Hi Tvdzwan. I've found a script on a german forum about the Raspberry Pi that sounds very promissing. It is a tutorial with a script on how to change automatically the ambilight source on OpenELEC [Hyperion]. 

http://www.forum-raspberrypi.de/Thread-hyperion-openelec-mit-automatisierter-ambilight-quellenumschaltung-milhouse-25-07-15-2

I don't know if you've heard about it. If you don't know German, I'd be happy to translate it for you. It would be a precious addition to the main Hyperion code!

**Comment by tpmodding** [comment]
@cmvac this is not an issue from hyperion. bismarck has patched the CEC part not hyperion :) 
could you close it please?
