### ISSUE TITLE
Philips Hue error

### ISSUE THREAD

**Issue by ro8in** [tvdzwan/hyperion#366]
Philips Hue on RBP gives me the following error when i run the deamon

hyperiond: /home/tvdzwan/hyperion/dependencies/build/jsoncpp/json_value.cpp:1136: Json::Value& Json::Value::resolveReference(const char*, bool): Assertion `type_ == nullValue || type_ == objectValue' failed.
Aborted

**Comment by ro8in** [comment]
My config

// Automatically generated configuration file for 'Hyperion daemon'
// Generated by: HyperCon (The Hyperion deamon configuration file builder

{
	/// Device configuration contains the following fields: 
	/// * 'name'       : The user friendly name of the device (only used for display purposes)
	/// * 'type'       : The type of the device or leds (known types for now are 'ws2801', 'ldp8806',
	///                  'lpd6803', 'sedu', 'adalight', 'lightpack', 'test' and 'none')
	/// * 'output'     : The output specification depends on selected device. This can for example be the
	///                  device specifier, device serial number, or the output file name
	/// * 'rate'       : The baudrate of the output to the device
	/// * 'colorOrder' : The order of the color bytes ('rgb', 'rbg', 'bgr', etc.).
	"device" :
	{
		"name"       : "MyPi",
		"type"       : "philipshue",
		"output"     : "192.168.178.66",
		"colorOrder" : "grb"
	},

	/// Color manipulation configuration used to tune the output colors to specific surroundings. 
	/// The configuration contains a list of color-transforms. Each transform contains the 
	/// following fields:
	///  * 'id'   : The unique identifier of the color transformation (eg 'device_1')	///  * 'leds' : The indices (or index ranges) of the leds to which this color transform applies
	///             (eg '0-5, 9, 11, 12-17'). The indices are zero based.	///  * 'hsv' : The manipulation in the Hue-Saturation-Value color domain with the following 
	///            tuning parameters:
	///            - 'saturationGain'  The gain adjustement of the saturation
	///            - 'valueGain'       The gain adjustement of the value
	///  * 'red'/'green'/'blue' : The manipulation in the Red-Green-Blue color domain with the 
	///                           following tuning parameters for each channel:
	///            - 'threshold'       The minimum required input value for the channel to be on 
	///                                (else zero)
	///            - 'gamma'           The gamma-curve correction factor
	///            - 'blacklevel'      The lowest possible value (when the channel is black)
	///            - 'whitelevel'      The highest possible value (when the channel is white)
	///
	/// Next to the list with color transforms there is also a smoothing option.
	///  * 'smoothing' : Smoothing of the colors in the time-domain with the following tuning 
	///                  parameters:
	///            - 'type'            The type of smoothing algorithm ('linear' or 'none')
	///            - 'time_ms'         The time constant for smoothing algorithm in milliseconds
	///            - 'updateFrequency' The update frequency of the leds in Hz
	"color" :
	{
		"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"hsv" :
				{
					"saturationGain" : 1.0000,
					"valueGain"      : 0.5000
				},
				"red" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"green" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"blue" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				}
			}
		],
		"smoothing" :
		{
			"type"            : "linear",
			"time_ms"         : 200,
			"updateFrequency" : 20.0000
		}
	},

	///  The configuration for each individual led. This contains the specification of the area 
	///  averaged of an input image for each led to determine its color. Each item in the list 
	///  contains the following fields:
	///  * index: The index of the led. This determines its location in the string of leds; zero 
	///           being the first led.
	///  * hscan: The fractional part of the image along the horizontal used for the averaging 
	///           (minimum and maximum inclusive)
	///  * vscan: The fractional part of the image along the vertical used for the averaging 
	///           (minimum and maximum inclusive)
	"leds" : 
	[
		{
			"index" : 0,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.1000 },
			"vscan" : { "minimum" : 0.9524, "maximum" : 1.0000 }
		}
	],

	/// The black border configuration, contains the following items: 
	///  * enable    : true if the detector should be activated
	///  * threshold : Value below which a pixel is regarded as black (value between 0.0 and 1.0)
	"blackborderdetector" : 
	{
		"enable" : true,
		"threshold" : 0.01
	},

	/// The configuration of the effect engine, contains the following items: 
	///  * paths        : An array with absolute location(s) of directories with effects 
	///  * bootsequence : The effect selected as 'boot sequence'
	"effects" : 
	{
		"paths" : 
		[
			"/opt/hyperion/effects"
		]
	},

	"bootsequence" : 
	{
		"effect" : "Rainbow swirl fast",
		"duration_ms" : 3000
	},

	///  The configuration for the frame-grabber, contains the following items: 
	///   * width        : The width of the grabbed frames [pixels]
	///   * height       : The height of the grabbed frames [pixels]
	///   * frequency_Hz : The frequency of the frame grab [Hz]
	"framegrabber" : 
	{
		"width" : 64,
		"height" : 64,
		"frequency_Hz" : 10.0
	},

	/// The configuration of the XBMC connection used to enable and disable the frame-grabber. Contains the following fields: 
	///  * xbmcAddress       : The IP address of the XBMC-host
	///  * xbmcTcpPort       : The TCP-port of the XBMC-server
	///  * grabVideo         : Flag indicating that the frame-grabber is on(true) during video playback
	///  * grabPictures      : Flag indicating that the frame-grabber is on(true) during picture show
	///  * grabAudio         : Flag indicating that the frame-grabber is on(true) during audio playback
	///  * grabMenu          : Flag indicating that the frame-grabber is on(true) in the XBMC menu
	///  * grabScreensaver   : Flag indicating that the frame-grabber is on(true) when XBMC is on screensaver
	///  * enable3DDetection : Flag indicating that the frame-grabber should switch to a 3D compatible modus if a 3D video is playing
	"xbmcVideoChecker" : 
	{
		"xbmcAddress" : "127.0.0.1",
		"xbmcTcpPort" : 9090,
		"grabVideo" : true,
		"grabPictures" : true,
		"grabAudio" : true,
		"grabMenu" : false,
		"grabScreensaver" : true,
		"enable3DDetection" : true
	},

	/// The configuration of the Json server which enables the json remote interface
	///  * port : Port at which the json server is started
	"jsonServer" : 
	{
		"port" : 19446
	},

	/// The configuration of the Proto server which enables the protobuffer remote interface
	///  * port : Port at which the protobuffer server is started
	"protoServer" : 
	{
		"port" : 19447
	},

	/// The configuration of the boblight server which enables the boblight remote interface
	///  * port : Port at which the boblight server is started
// 	"boblightServer" : 
// 	{
// 		"port" : 19333
// 	},

	"endOfJson" : "endOfJson"
}

**Comment by ntim** [comment]
Can you post a stack-trace to see which variable resolve fails? I am not sure about the color order.

My device configuration looks like this:

"device" :
	{
		"name"       : "MyPi",
		"type"       : "philipshue",
		"output"     : "192.168.178.33",
		"transitiontime"     : 2,
		"switchOffOnBlack"     : false,
		"username"     : "newdeveloper",
		"colorOrder" : "rgb"
	},

**Comment by ro8in** [comment]
Where can i find the stack trace?

I basically just startup the deamon and then it exits with the error above..

**Comment by ntim** [comment]
You can compile Hyperion with debugging symbols and execute the daemon binary through gdb.

**Comment by ro8in** [comment]
You know i'm stupid... I forget to make an authorized user first.. After I did that the error is gone :D

**Comment by ntim** [comment]
Ok, but weird error though. Nice to have would be to properly implement the auth mechanism of the hue system.

**Comment by ro8in** [comment]
Yeah but i guess the way its done now is kinda ok in combination how hyperion is setup anyways..

**Comment by EvilBuu** [comment]
Hey guys, 

Ive been reading these issuethreads and you both seem to know alot about Hyperion and Philips Hue support. Im stuck with some very expensive hardware and could really use your help because hyperion+ Philips hue bridge isnt working for me.

This is my config file. I want to have ambilight effect on both my ws2801leds an Philips hue bloom lamps. Ledstrip is working but the second daemon config isnt showing any love: 



{
    "framegrabber": {
        "width": 64,
        "frequency_Hz": 5.0,
        "height": 64
    },
    "leds": [
        {
            "vscan": {
                "minimum": 0.95450000000000002,
                "maximum": 1.0
            },
            "index": 0,
            "hscan": {
                "minimum": 0.71050000000000002,
                "maximum": 0.73680000000000001
            }
        },
        {
            "vscan": {
                "minimum": 0.95450000000000002,
                "maximum": 1.0
            },
            "index": 1,
            "hscan": {
                "minimum": 0.73680000000000001,
                "maximum": 0.76319999999999999
            }
        },
        {
            "vscan": {
                "minimum": 0.95450000000000002,
                "maximum": 1.0
            }
          
        }
    ],
    "blackborderdetector": {
        "threshold": 0.10000000000000001,
        "enable": true
    },
    "endOfJson": "endOfJson",
   
"color" :
    {
        "transform" :
        [
            {
                "id"   : "default",
                "leds" : "*",
                "hsv" :
                {
                    "saturationGain" : 1.0000,
                    "valueGain"      : 1.0000
                },
                "red" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                },
                "green" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                },
                "blue" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                }
            }
       
   
   
     ],
   
   
                
            
        
        "smoothing": {
            "updateFrequency": 20,
            "time_ms": 100,
            "type": "none"
        }
    },
    "bootsequence": {
        "duration_ms": 3000,
        "effect": "Rainbow swirl fast"
    },
    "protoServer": {
        "port": 19448
    },
    "effects": {
        "paths": [
            "/storage/hyperion/effects"
        ]
    },
    "device": {
        "name" : "MyPi",
        "type" : "philipshue",
        "output" : "192.168.1.12/",
        "username"     : "5ca7e606d465c053feb2dd172fd5e26",  
        "colorOrder" : "rgb"
    },
    "xbmcVideoChecker": {
        "grabVideo": true,
        "grabPictures": true,
        "xbmcTcpPort": 9090,
        "grabAudio": true,
        "grabMenu": false,
        "enable3DDetection": true,
        "xbmcAddress": "127.0.0.1",
        "grabScreensaver": true
    },
    "jsonServer": {
        "port": 19447
    },
    "grabber-v4l2": {
        "cropLeft": 5,
        "cropTop": 5,
        "cropRight": 5,
        "width": 720,
        "blueSignalThreshold": 0.20000000000000001,
        "redSignalThreshold": 0.20000000000000001,
        "height": 576,
        "priority": 1200,
        "frameDecimation": 2,
        "sizeDecimation": 8,
        "mode": "2D",
        "device": "/dev/video0",
        "input": 0,
        "standard": "no-change",
        "cropBottom": 5,
        "greenSignalThreshold": 0.20000000000000001
    }
}

Some notes i made: 

I had to use the direct outputted Username ID since my Bridge isnt supporting self declared useraccounts. Changed everything in config according to your guidelines and example config files. The Ip addres of the bridge under device settings gives on error without the "  / " on the end. 


If i use the command in putty for loading the daemon with this config file nothing happens. It freezes on me and i have to force quite to stop the command. 

Without the changes i get the same error R08in had with his setup. 

I hope you guys can help me out @ntim , ro8in (i will compensate for your time and efforts)

**Comment by ntim** [comment]
@EvilBuu 

what is the error you get without putting the "/" to the end of the address?

**Comment by polykoma** [comment]
Did you created a user on the bridge with getting started philips api?

There you get a unique bridge id!

**Comment by EvilBuu** [comment]
@ntim Hi ntim, this is the error:


hyperiond: /home/pi/fix_do_apa/hyperion/dependencies/build/jsoncpp/json_value.cpp:1136: Json::Value& Json::Value::resolveReference(const char*, bool): Assertion `type_ == nullValue || type_ == objectValue' failed.
Aborted

**Comment by EvilBuu** [comment]
@polykoma hi poly. Yes I made a new user on the bridge however its creating a random string of characters as a user identifier.  So I just directly inputted the string of characters.

**Comment by ntim** [comment]
@EvilBuu this is a json error and does not come from the hue implementation. Having said that, the extra slash at the end of the ip address leads to a malformed url, thus the bridge will not understand the commands.  Can you post a pastebin or something like that with your two config files?

**Comment by ntim** [comment]
@EvilBuu and the bridge is the new one with home-kit enabled? maybe they changed something there regarding user management...

**Comment by EvilBuu** [comment]
@ntim 

Link to both configs. 
http://www.jsoneditoronline.org/?id=625aed6ec57b5c9f4a7c2b635bd811b2

**Comment by EvilBuu** [comment]
@ntim Yes on the documentation of the bridge manual it says "works with apple homekit".

**Comment by polykoma** [comment]
Hi
I first had the v1 bridge.
Now using the v2 bridge succesfully with ambilight programms for pc and with ambi on kodi via my tv.
Everything works as with the v1

The problem is probably not the bridge!

**Comment by EvilBuu** [comment]
@polykoma Hi stefan, glad to hear its compatible with your setup. Maybe the problem exists within my setup. Im using an raspberry pi b+ with openelec. I installed Hyperion on it and a videograbber to capture videofeed from my xbox one and playstation 4. Ambilight is working great on my ledstrips but just cant connect the bridge to the Pi somehow....

**Comment by polykoma** [comment]
@evilbuu i will check tomorrow. Im using same setup. Which plugin you use on kodi to communicate with hue?

Btw. I have 144 lpd's behind my tv. A standalone mediacenter. And 50 ws2801 behind my pc with an arduino. :)
All working with the hue.
And i built a own hue lamp with 800 leds. :)

**Comment by ntim** [comment]
Offtopic: can you share a picture of your custom made hue lamp?

**Comment by EvilBuu** [comment]
@polykoma Hi poly, thanks for taking the effort to help me, really appreciate it. You'll have to be patience with me since im not a coder and haven't got a lot of experience with this kind of hardware.

Im not using any plugin for kodi to communicate with Hue lambs (didn't knew this was necessary to for my setup). 

I found this  thread which has most of the hue plugins available listed for kodi:
https://www.reddit.com/r/huelights/comments/1budgt/xbmc_plugins_list/

But im reading ambilight mode isnt supporting on a Raspberry pi :(... How did you managed to get it working on your Pi (and if possible with ambilight mode support)?

**Comment by ntim** [comment]
Lets not get confused here. 

Hyperion is not a kodi plugin but works standalone. Nothing else is required to get the Hue lights working since it uses the RESTApi of the bridge. 

It is correct that the script.xbmc.hue.ambilight plugin for Kodi does not support the Pi since it uses a legacy component of xbmc to capture the screen.

**Comment by EvilBuu** [comment]
Hi @ntim if you want me to try anything else of have any suggestions with the setup im running please let me know. Kinda desperate for a solution right now.

**Comment by polykoma** [comment]
@ntim sure, here you go: http://www.forum-raspberrypi.de/Thread-hue-project-blow-your-mind-800-led-panel-ceiling-alu-lamp   i would be happy for your feedback :)

@evilbuu yeah. its right it says it doesnt work with kodi. The real ambi mode.
you can find the github plugins here:
https://github.com/cees-elzinga

somehow when i put the ambi on there my lights are changing colours but the host of the plugin says that it doesnt work.

i want to include the hue control into my hyperion-pi via v2loopback and second instance. But didnt had time to do so yet....

**Comment by polykoma** [comment]
@ntim appreciating your feedback!

@evilbuu how things going ? :)

**Comment by ntim** [comment]
@polykoma looks very cool ;-) I was also looking forward to build something with the NeoPixels: https://www.adafruit.com/category/168
What is the model of the ZigBee controller?
