### ISSUE TITLE
Hyperion fails to build with on RPi2

### ISSUE THREAD

**Issue by mrgreywater** [tvdzwan/hyperion#368]
When compiling the source on the latest Raspbian using the [instructions provided](https://github.com/tvdzwan/hyperion/blob/master/CompileHowto.txt), it fails to build here:

```
[ 46%] Building CXX object libsrc/leddevice/CMakeFiles/leddevice.dir/moc_LedDevicePhilipsHue.cxx.o
In file included from /home/pi/hyperion/build/libsrc/leddevice/moc_LedDevicePhilipsHue.cxx:10:0:
/home/pi/hyperion/build/libsrc/leddevice/../../../libsrc/leddevice/LedDevicePhilipsHue.h:137:72: error: expected primary-expression before ‘{’ token
libsrc/leddevice/CMakeFiles/leddevice.dir/build.make:143: recipe for target 'libsrc/leddevice/CMakeFiles/leddevice.dir/moc_LedDevicePhilipsHue.cxx.o' failed
make[2]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/moc_LedDevicePhilipsHue.cxx.o] Error 1
CMakeFiles/Makefile2:832: recipe for target 'libsrc/leddevice/CMakeFiles/leddevice.dir/all' failed
make[1]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
```

The culprit is the following line: [LedDevicePhilipsHue.h:137](https://github.com/tvdzwan/hyperion/blob/e93bd2fb303be6b91e0c241efb30dc0a1bf04b2f/libsrc/leddevice/LedDevicePhilipsHue.h#L137)

It could be fixed by replacing it with
```cpp
			false, int transitiontime = 1, std::vector<unsigned int> lightIds = std::vector<unsigned int>());
```

Maybe I'll create a pull request later.

**Comment by ntim** [comment]
Ok, this requires C++0x compatibility which should be supported by Raspbian by now. But keeping it downwards compatible does not hurt.

**Comment by mrgreywater** [comment]
@ntim I was using the latest Raspbian, I downloaded it yesterday. It still uses a relatively outdated GCC4.6 though, and [doesn't fully support c++11](https://gcc.gnu.org/gcc-4.6/cxx0x_status.html).
Either the instructions should be fixed to include updating to some newer gcc version, or (which would be simpler) keep gcc4.6 compatibility.

**Comment by ntim** [comment]
Extended initializer lists are supported by version 4.6. Can you check if you compiled using the --std=c++0x option?

**Comment by mrgreywater** [comment]
https://gist.github.com/mrgreywater/33949c82dd356b6bcdb8

**Comment by ntim** [comment]
Ok, maybe then the old gcc has not the full menu yet regarding the extended initializer lists although the manual suggests something else.

**Comment by NicoHood** [comment]
Is this now fixed?

**Comment by mrgreywater** [comment]
I assume so, since this was the only change I had to do to get it to compile. Thanks for the reminder to close the issue.
