### ISSUE TITLE
Kodi script to update config.json after making changes with remote

### ISSUE THREAD

**Issue by KenV99** [tvdzwan/hyperion#371]
Hi.
I don't know that this is the best place to post about this, but I wrote a small Kodi addon that reads in the settings that hyperion is currently using, including any on-the-fly changes made using a remote program (i.e. the Android Hyperion Free) and writes them into the hyperion.config.json file. It is written as a Kodi Program addon, so it can be accessed via 'Programs' (or you could map it to a key on your remote, which what I did). There a few settings - which id in the transform section to write into (right now you need to specify which and it only handles one - if there is interest I can fix it to handle more than one), whether to date/time stamp the backup of the json file (a backup of the current is always made) and whether or not to restart hyperiond. I have tested it on an RPi2 running OpenELEC. Some small changes may need to be made for other platforms especially for the restart.

The program expects that the json file is formatted more or less like the file produced by hypercon. It should preserve the formatting and comments by not directly using the python json library, but parsing the file line-by-line.

It can be found here:
https://github.com/KenV99/script.hyperion_conf_update

Feel free to raise issues on github if there are problems.

**Comment by brindosch** [comment]
You could attach a article to the wiki that describes the usage.
Thank you.

/Closed
