### ISSUE TITLE
LED's don't dim, either on or off depending on whats on the screen

### ISSUE THREAD

**Issue by rittzy** [tvdzwan/hyperion#374]
As the title says the LED's I have attached to my screen don't dim on certain scenes in films. When the screen hits whatever threshold the LED will just turns off instead off dim out on that colour. They are either on full brightness of else they are off depending what values I have on my hyperion.config.json file. 

I can send commands to have the LED's lit lower through the app but just not when it comes to playing movies off the Pi2. Running OSMC latest version. Pictures attached below to show all LED's full brightness and the last LEDs not lit at all. I thought the LED's varied on brightness depending on what was on the screen.

Thanks

![imag0755](https://cloud.githubusercontent.com/assets/10226066/9294834/e40c9bca-4450-11e5-8969-905de53d0129.jpg)
![imag0756](https://cloud.githubusercontent.com/assets/10226066/9294835/e5b80a36-4450-11e5-8464-c5a96fd42f96.jpg)

**Comment by mrgreywater** [comment]
Try running effects like 'Knight rider' to see if the screengrabber or the led output is the reason for this behaviour.

**Comment by rittzy** [comment]
Link for what I think the log file is? http://www.xbmclogs.com/pvrdouhsx

Hyperion config - https://github.com/rittzy/log/blob/master/hyperionconfig.md

And when I ran knight rider it did not seem like any LED's where fading. Just one solid block of 6 or so LED's moving across the top strip.

Thanks

**Comment by mrgreywater** [comment]
To get a log file, I was expecting you to start the service like this:
<code>/bin/killall -9 hyperiond
/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json > /storage/hyperion/log &</code>

As for for the 'Knight rider' effect, it should fade the LED's, which makes me think your problem cannot be in the Framegrabber part of hyperion.

I will try your config on my setup tomorrow to make sure your color transform settings work for me and report back.

**Comment by mrgreywater** [comment]
So I tried your config, but on my setup your color transform pretty much makes them all light up white. Can you use the default transform and report back?

```
	"color" :
	{
		"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"hsv" :
				{
					"saturationGain" : 1.0000,
					"valueGain"      : 1.0000
				},
				"red" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"green" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"blue" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				}
			}
		],
		"smoothing" :
		{
			"type"            : "none",
			"time_ms"         : 200,
			"updateFrequency" : 20.0000,
			"updateDelay"     : 0
		}
	},
```

**Comment by rittzy** [comment]
Sorry I haven't manged to get back to you. Thanks for taking the time to diagnose this for me. After you said about the knight rider effect I tested the LED's with the app and noticed that the colours just jumped and wernt smooth at all. For example when going from red to purple, there is no transition, once I pass a certain threshold the blue element in the LEDs just flick on without any gradual increase in brightness. Don't know why they do it but it now points to the LEDs being the problem. 

Can I ask what LEDs you use? I will see if I can test them some more with the arduino and possibly order new LEDs.  Possibly might try the APA102 for a bit of change. 

Thanks
Chris

**Comment by mrgreywater** [comment]
I myself use some WS2812b 60pcs strips from aliexpress, but I don't really think you need to change yours.
If I were you, I would make sure your grounds of the RPi is connected with the ground of the strips, and that the strips are getting enough voltage (measure the voltage drop aswell). Also make sure you use the default color transform in hyperion I linked before.

If you checked your setup over and it still doesn't work, you might consider getting an Arduino/Teensy which gives you more control over the LEDs and allows you to debug them more easily.

**Comment by rittzy** [comment]
Well just need to say thanks for the help. Re-installed OSMC and had problems with the LED's flickering and giving out weird values even with the default settings so I decided to take your advice and use an Ardunio to drive the WS2801 and after farting about with them for a while and learning a bit they finally work and work brilliantly.

Thanks for the help

**Comment by meekaah** [comment]
@rittzy  how did you fix your issue please? i'm having the same problem and can't make sense of it

**Comment by rittzy** [comment]
I had to use an arduino in between the LEDs and the Pi. I couldn't get them to act normal but the arduino worked fine even though it was an extra bit of kit unfortunately

**Comment by meekaah** [comment]
hmm damn, i really want to make this work. by fiddling with parameters i found out that the leds DO dim if i turn down the baudrate (but then the animations dont work...) :( thanks anyways im gonna continue searching
