### ISSUE TITLE
Support on center of tv

### ISSUE THREAD

**Issue by lotordure** [tvdzwan/hyperion#375]
Hi,
Does hyperion support leds on center of tv ? 
When there is only some light in center of the screen it would be great to have it.

Thx

**Comment by mrgreywater** [comment]
Look into the config file. You can enter the exact area where each individual LED gets the color information from. 

Instead of e.g
```
    {
        "index" : 2,
        "hscan" : { "minimum" : 0.9400, "maximum" : 1.0000 },
        "vscan" : { "minimum" : 0.8125, "maximum" : 0.8750 }
    },
```

You could do something like
```
    {
        "index" : 2,
        "hscan" : { "minimum" : 0.4, "maximum" : 0.6 },
        "vscan" : { "minimum" : 0.4, "maximum" : 0.6 }
    },
```

To display the color of some area in the middle of the screen to LED no.2

**Comment by penfold42** [comment]
This works great - I've  used a  concentric  set of ws2812b rings and made an ultra low res screen !

**Comment by lotordure** [comment]
Thx worked great but a bit difficult to configure.

Do you mean this kind of ring ?
 http://www.amazon.com/Adafruit-NeoPixel-60-Ring-Integrated/dp/B00QSIZ3PU/ref=pd_sim_147_2?ie=UTF8&refRID=1XQ90NFX8F8PQV6ZZT2B

Wish the configuration java tool allow this kind of configuration

**Comment by penfold42** [comment]
I used the set of concentric rings http://pages.ebay.com/link/?nav=item.view&alt=web&id=141689486290&globalID=EBAY-AU

I used excel to calculate the angles and radius of each led to then use sin/cos to find the X and Y coordinate for each led.
Then a simple perl script to reprint it in the Json format needed by the config file.

**Comment by Systemdir** [comment]
I have a bit of a different issue. I wish to have the average of the screen center weighted added to all leds. 

Using my ambilight system mainly for video games, I noticed that for some games, most important effects are in the center of the screen. For example, if someone summons a meteor in Diablo 3, hitting the center of the screen, hyperion based ambi light is completly unaffected. This reduces the immersion since there is no light reaction for the players action.

**Comment by tpmodding** [comment]
@lotordure could you close this issue please? think your problem is solved?

**Comment by brindosch** [comment]
@Systemdir 
just look into the config and play around with the hscan vscan value. you could grab the whole screen.

I will close this
Thank you
