### ISSUE TITLE
Hyperion on IMX6 no longer working with video playback only with XBMC menu

### ISSUE THREAD

**Issue by zarboz** [tvdzwan/hyperion#376]
I can get hyperion working just fine with menu color reflection but upon playing a video the LED's go a dim pink/blue color and will not react to what is going on screen

Does not matter if live TV or if saved TV

**Comment by zarboz** [comment]
./hyperiond /etc/hyperion.config.json 
Application build time: Jan 24 2015 17:56:52
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 171]
Device configuration: 
{
	"colorOrder" : "rgb",
	"name" : "MyPi",
	"output" : "/dev/serial/by-id/usb-Teensyduino_USB_Serial_528720-if00",
	"rate" : 115200,
	"type" : "adalight"
}

Opening UART: /dev/serial/by-id/usb-Teensyduino_USB_Serial_528720-if00
Black border threshold set to 0.01 (3)
Not creating any smoothing
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Boot sequence(Rainbow swirl fast) created and started
XBMC video checker created and started
Framebuffer opened with resolution: 1920x1080@32bit
Framebuffer grabber created and started
Json server created and started on port 19444
Proto server created and started on port 19445
Boblight server created and started on port 19333
XBMC Connected
Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
XBMC checker: switching to VIDEO mode
Message from XBMC: {"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":false}}
Message from XBMC: {"id":667,"jsonrpc":"2.0","result":{"item":{"id":284,"label":"History HD","type":"channel"}}}
Message from XBMC: {"id":670,"jsonrpc":"2.0","result":{"version":{"major":15,"minor":1,"revision":"2015-08-09-f72255d","tag":"releasecandidate","tagversion":"1"}}}
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
effect finished
Message from XBMC: {"jsonrpc":"2.0","method":"Player.OnStop","params":{"data":{"end":false,"item":{"channeltype":"tv","id":284,"title":"History HD","type":"channel"}},"sender":"xbmc"}}
XBMC checker: switching to MENU mode
Message from XBMC: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"channeltype":"tv","id":284,"title":"History HD","type":"channel"},"player":{"playerid":1,"speed":1}},"sender":"xbmc"}}
Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
XBMC checker: switching to VIDEO mode
Message from XBMC: {"id":667,"jsonrpc":"2.0","result":{"item":{"id":284,"label":"History HD","type":"channel"}}}
Message from XBMC: {"id":669,"jsonrpc":"2.0","result":{"stereoscopicmode":{"label":"Disabled","mode":"off"}}}

**Comment by derechtedude** [comment]
Hey zarboz,
Check my post from Couple of months ago

https://github.com/tvdzwan/hyperion/issues/298
This happens with openelec versions newer than 5.0.3
Gamadrils posted a fix that gives you back ambilight during playback (then ambilght during menu is lost though)
I am sticking to 5.0.0 at the moment because I prefer the complete ambilight feeling.
Hope an alternative fix comes sooner or later but it seems to be not highest priority (which I kind of understand though don't like ;-)

Hope that helps.

Cheerio

Mat

**Comment by zarboz** [comment]
can you link the fix?

**Comment by derechtedude** [comment]
Check #298

**Comment by tpmodding** [comment]
@zarboz any updates? is this fixed?

**Comment by brindosch** [comment]
14 days now. May be done.
If not, just write it :)
