### ISSUE TITLE
Issue with Kodi menu and LEDs not off

### ISSUE THREAD

**Issue by Nico83500** [tvdzwan/hyperion#378]
Hi,
I have an issue with Hyperion and OSMC.
On HyperCon, I choose XBMC Menu Off but LEDs are on with Kodi menu. So I can't let my RPI 2 started without getting light.
Is it a bug or have I missed anything ?
Thank you.

**Comment by masterxilef** [comment]
Settings -> Services (or Network depending on skin) -> Remote control -> *Enable all
Reboot
It should work now.

**Comment by Nico83500** [comment]
Yes it's OK thank you !

**Comment by NicoHood** [comment]
Please close the issue then.
