### ISSUE TITLE
Unable to connect to host

### ISSUE THREAD

**Issue by Xnorky** [tvdzwan/hyperion#379]
Hello, 

I try to use Hyperion but I have "unable to connect to host"...

$ sudo netstat -ntl

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8070            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8334            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8019            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN

AND 

$ sudo hyperiond /etc/hyperion.config.json : 

Application build time: Mar  6 2015 20:57:44
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 49]
Device configuration: 
{
	"colorOrder" : "rgb",
	"name" : "MyPi",
	"output" : "/dev/spidev0.0",
	"rate" : 250000,
	"type" : "ws2801"
}

Black border threshold set to 0.01 (3)
Not creating any smoothing
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Boot sequence(Rainbow swirl fast) created and started
XBMC video checker created and started
hyperiond: /home/tvdzwan/hyperion/libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp:23: DispmanxFrameGrabber::DispmanxFrameGrabber(unsigned int, unsigned int): Assertion `_vc_display > 0' failed.

What it means to the last line ?

**Comment by Xnorky** [comment]
I solved the problem...

I comment in hyperion json config file : 

///"framegrabber" :
        ///{
        ///     "width" : 64,
        ///     "height" : 64,
        ///     "frequency_Hz" : 20.0
        ///},


And it work !

**Comment by penfold42** [comment]
Are you running it on a raspberry pi ?

**Comment by Xnorky** [comment]
Yes, Raspberry Pi 2

**Comment by penfold42** [comment]
I've seen that error sometimes if I have 2 instances running . Restarting both has always fixed it for me.

Is there anything else running which is also grabbing from the dispmanx display ?
