### ISSUE TITLE
Is hyperion supporting SPI shortcut?

### ISSUE THREAD

**Issue by ctugt** [tvdzwan/hyperion#381]
I got a question,
Having hyperion on a rpi2 is great but its sooooo slow (rpi with kodi) so i i tooked a core2 pc and installed kodibuntu on it, muchhh faster. Im using the tool XBMC addon (not for RPi) and send it to the rpi2 hyperion deamon its woring, cant cap the normal screen use only video, but its ok. I do see little lags sometimes cause its going over network. so i went to google and found this little chip:

https://github.com/sparkfun/SPI_Shortcut/tree/V_1.6

Does hyperion will work with this or is it hardcoded to something in the rpi2 spi controller?
If so, is ther any developer that wanne work with me for this, you can script, i can test.
this would be a cheap solution for those using a htcp and wanne use spi connection to usb.

Thanks!

**Comment by penfold42** [comment]
I don't think r will work without changes to Hyperion.
It will probably need a ew driver written - pretty easy to do as it already support serial and SPI.

But I its not worth it as it seems an expensive adaptor for what appears less equipped than a regular arduino board ($3 from China )

I'd either hang a cheap arduino nano off USB and use some existing code

**Comment by ctugt** [comment]
Arduino has clock and mosi? so correcet me if im wrongm
buy a arduino, connect to htpc, install hyperion to htpc, then install arduino driver on kodibuntu? maybe not needit and then it works? thanks for the great advice, i wanne get rid of rpi2 its to slow to many freezes when OC to 1Ghz.

**Comment by penfold42** [comment]
Yes, arduino has SPI.
That's the most common way to program bare chips with no bootloader.

Get a cheap arduino nano
Find a sketch that implements something like the adaloght protocol
Find a library that supports your led strip (which do you have ?)
Arduino looks like a serial port to the PC
Configure Hyperion to use that "aerial" port

**Comment by ctugt** [comment]
Nice thanks for the explaination, wich arduine is fit to do the job? is suppose the Uno R3.
Anyway im usung ws2801

		"name"       : "MyPi",
		"type"       : "ws2801",
		"output"     : "/dev/spidev0.0",
		"rate"       : 1000000,
		"colorOrder" : "rgb"

**Comment by ctugt** [comment]
I got it working today, thank you very much!

**Comment by penfold42** [comment]
Great to head !
What did you settle on for a setup ?

**Comment by ctugt** [comment]
Arduino Nano with a sketch founded online, that together with hyperion and hyperion xmbc addon
