### ISSUE TITLE
LED not in sync when 16:9 source is used // work around found

### ISSUE THREAD

**Issue by lobocobra** [tvdzwan/hyperion#382]
Issue description:
As described in issue #266, the LED are not in sync (vertically) with the displayed picture when using a 16:9 source. I could replicate the issue on other RPI by feeding a 16:9 source to the EasyCap SDK1160. The main issue is, that the EasyCap SDK1160 can not be set into 16:9 mode by hyperion-v4l2 player. Logic consequence is that Hyperion calculates the LED position wrongly. Issue is the best visible, if you connect a PC as source.

Who is affected:
As far as I could test it on 3 systems, everyone that has a 16:9 source over HDMI splitter with my hw setup (see below)

Needed fix:
Either find a way to set with hyperion-v4l2 the aspect ratio (currently not possible) or change position calculation of hyperion when a 16:9 source is connected (would be preferred). 

Work around to solve the issue:
1) before the work-around "v4l2-ctl -all" shows that EasyCap is in 4:3 mode AND LED are not in sync: 
    => http://pastebin.com/yPP83Jvu 
2) start MPLAYER with following commands (mplayer will crash but switch mode to 16:9):
#/usr/bin/mplayer -tv driver=v4l2:width=96:height=54:device=/dev/video0 -vo fbdev -fs -fps 24 -aspect 16:9 -nosound tv://
3) v4l2-ctl -all shows that EasyCap is now in 16:9 mode: 
    => http://pastebin.com/a0ZhGdvJ
4) now start V4l with following command and enjoy 1:1 matching of LED with the picture:
/usr/bin/hyperion-v4l2 --frame-decimator 1 --size-decimator 6 --crop-height 5 --crop-width 5 --skip-reply --signal-threshold 0.11 >/dev/null 2>&1 &
5) the work around will be working until you reboot

!!!!! do not launch the mplayer command with rc.local at startup. It will leave you with a crashing kernel and you will need to mount your rc.local in another linux system, as GRUB2 SHIFT key at boot does not give you access to grub menu (at least for me, see related bugswith my configuration). But if you launch the above commands after the system is up, all works fine. As soon I have a way to automate this process, I will update this Issue

My HW setup:
    RaspPi standard installation v7.8 (all works well)
    Kernel: 3.18.7+ #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015 armv6l GNU/Linux
    LED stripe with 100 LED lpd8806
    recommended HDMI2AV converter and 4x HDMI splitter with separate power
    EasyCap SDK1160 (!! they do not support well heat)
    5 Ampere power supply connected with shielded (USB) power cable
Cabling
16:9 source => HDMI Switch => HDMI 4x splitter => HDMI2AV => EasyCap SDK1160 => RPI => LED

My .jonson file (extract of relevant sections)
http://pastebin.com/rA1y9uTX

Positive side effect.... mplayer is changing the frequency of easycap to 25mhz. By adusting the jonson to 25mhz, I have eliminated the last rarely flickering I had from time to time with a steady picture
==> I AM COMPLETLY HAPPY NOW WITH MY PERFECT SETUP

**Comment by lobocobra** [comment]
bump... nobody?

**Comment by JustEndo** [comment]
Have you tried setting the video standard to PAL? Looking at your v4l2-ctl outputs it seems that mplayer essentially just switches from NTSC to PAL.

Append "-v PAL" to your hyperion-v4l2 command or add "standard" : "PAL" to your "grabber-v4l2" configuration in the config file. That should fix your issue.

Cheers!

**Comment by lobocobra** [comment]
THANKS... JustEndo
That is the solution.  I can confirm that it works now!!!!
