### ISSUE TITLE
Issue with having XBMC addon (not for rpi)

### ISSUE THREAD

**Issue by ctugt** [tvdzwan/hyperion#383]
Hi,

Im using this plugin on my HTPC to send colour details over network to my rpi hyperion server.

Now it works ok but in my startup script i have an effect, so when rpi2 start the static colour is an loaded effect.
But when i start a movie, when an static colour or effect on my rpi runs, it doesnt switch source.
Yes i can make a workaround a killall hyperion script then start again without a effect, but thats not the way, any other iddeas?

sry for the bad englisch

here the startup script of my rpi2:: (from remote button in keymap.xml it starts this)

import subprocess
subprocess.call('/opt/hyperion/bin/hyperiond /etc/hyperion.config.json </dev/null >/dev/null 2>&1 &', shell=True)

import time
time.sleep(8)
subprocess.call('/opt/hyperion/bin/hyperion-remote --priority 100 --duration 86400 --effect "Blue mood blobs"', shell=True,)

**Comment by ctugt** [comment]
Anyone!?

**Comment by ctugt** [comment]
2 weeks ago....

**Comment by brindosch** [comment]
@ctugt 
Is the priority higher in kodi?

**Comment by ctugt** [comment]
hi, i fixed it in autoxec.py ;) thanks
