### ISSUE TITLE
APA102 last LEDs in string have wrong colors.

### ISSUE THREAD

**Issue by JackBerkhout** [tvdzwan/hyperion#385]
Hi TVdzan,

I'm using Hyperion with APA102 LED strip with 240 LEDs (4 meter).
The last three LEDs are not updated and display wrong colors.
This is because the “End frame” needs to supply more clock pulses to the string until the data has permeated to the last LEDs. The total number op clock pulses needed for the END frame is the number of used LEDs divided by two. So for a string with 240 LEDs, 120 clock pulses are needed in the END frame.
I know, the datasheet is not clear on that. I have tested it, and this works.
More information:
https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/
Hope this helps.
I happen to have this LED strip and can test it. Once there is an update, I will test it and give you feedback.
I hope this gets fixed soon. :-)

Regards,
Jack.

**Comment by mrgreywater** [comment]
It's already been fixed and merged.
https://github.com/tvdzwan/hyperion/commit/44107997d92d729f84adee368d12e35f1b5be6f1

**Comment by brindosch** [comment]
should be closed
