### ISSUE TITLE
RPI - OSMC - Hyperion - Hue Light ID's

### ISSUE THREAD

**Issue by Kenny-JTK** [tvdzwan/hyperion#387]
Hey guys, I've been toying around with this and i'm very pleased with the results. The only thing that has been bothering me is that I cant change the output to a single HUE light bulb ( pref ID "2") all other things work perfect. Are there any log files or debug mode ? so i could maybe find a clue what's the problem. Thx in advance guys. 

Kenny

**Comment by mattbrian2012** [comment]
I dont get this either I find if i change the channel on the android app from 9000 to like, 2 for instance it will effect my hue light ID 2 etc

**Comment by ntim** [comment]
Check this: https://github.com/tvdzwan/hyperion/pull/538

You can also supply an array with specific light ids as explained in the wiki.

**Comment by brindosch** [comment]
Thank you @ntim 

I will close this.
