### ISSUE TITLE
Limit frame grabber to number of leds

### ISSUE THREAD

**Issue by gekkegerrit101** [tvdzwan/hyperion#389]
I have a 25 LED setup working perfectly at my computer desk. I have another 50 LED's lying around which I would like to use as a lighting strip fixed to my wall which I can control with hyperion web app/android app. 

I'm already kinda sure that what I want is not possible, but here goes:

If I connect the 50 LED strip to my current 25 setup, is it possible to use only the first 25 LED's for the frame grabber output while still being able to control all 75 at once using the app?

**Comment by brindosch** [comment]
@gekkegerrit101 
As far as i know. No

**Comment by redPanther** [comment]
It is possible in another way. You need a second hyperion deamon and connect the 50 leds to the second hyperion. It depends how you connect your leds perhaps you need a second rpi or an arduino or other led controller (e.g. a fadecandy could be nice in your case)

On the "25 leds hyperion" configure  the new forwarder (not yet in master, but PR is pending) and forward only json messages to second hyperion with 50 leds.

Connect your android app with the "25 led hyperion" then both led stripes show your color/effect. Connect your android app with the "50 led hyperion" then only the 50 leds  show your color/effect. 
When using ambilight only the 25 led strip changes the colors and the 50 leds maintain the previously  selected color/effect.

more info #518 #486

**Comment by brindosch** [comment]
This should be done

**Comment by penfold42** [comment]
possibly a bit late, but if you define nonsensical values for hscan or scan the framegrabber won't illuminate those LEDs.
This may meet the requirement but there are some limitations:
1 Any effects that uses hyperion.setImage will also fail to illuminate those LEDs (eg: knight rider) but effects that use hyperion.setColor to reference LEDs by number will work fine.
2 You cant use them independently. either you have no effect running and the grabber will drive the 25 LEDs with the other 50 being black or you have an effect driving all of them
