### ISSUE TITLE
Place the precompiled files into github releases

### ISSUE THREAD

**Issue by NicoHood** [tvdzwan/hyperion#392]
This gives us a few pros:
* Better version tagging
* Smaller git repository with more speed
* Same functionality

**Comment by NicoHood** [comment]
Any chance to see this? This would really reduce the git package size.

**Comment by NicoHood** [comment]
I just wanted to upload a PR and it takes me forever with my uploading speed. If the releases would move to the releases we can save this memory and performance issue. You can still upload all other releases to github and also switch back to them if desired.

It would also make sense to force clean the current git from the last releases, so cloning and modifying is faster.

**Comment by NicoHood** [comment]
It seems that @tvdzwan is merging all PRs. Just a quick question:
Do you review them or just merge them? I like that you support community stuff, but maybe we should then make a special community branch or add a new tag, so we can keep track of the changes, if something breaks because a not good reviewed patch. I am affraid that just merging all patches will end in a big mess, if noone reviews them. Can we expect a statement about that?

**Comment by brindosch** [comment]
@NicoHood 
You are right, this is a problem. Versioning and changelog are big problems. Do you want to help maintaining this project?

**Comment by NicoHood** [comment]
I gave my statement here:
https://github.com/tvdzwan/hyperion/issues/497#issuecomment-184267255

**Comment by tpmodding** [comment]
@NicoHood the binaries are updated now? can be closed?

**Comment by NicoHood** [comment]
The binaries should be removed from here:
https://github.com/tvdzwan/hyperion/tree/master/deploy

Also the whole git history should be cleared somehow. Cloning the git takes forever.
However I am so glad at least a single release was made now.

**Comment by brindosch** [comment]
Could you give me a command that is working on raspian and openelec to download the files?
Just tested around some findings but unsuccessful.

**Comment by NicoHood** [comment]
Huh? I tried on my x64 PC, just a simple
wget https://github.com/tvdzwan/hyperion/releases/download/v0.1.42/hyperion_rpi.tar.gz

**Comment by brindosch** [comment]
yes, i won´t update every time the script :) I don´t want to go a step back in comfort :)

**Comment by brindosch** [comment]
Like mentioned, as long there is no easy solution that don´t produce more work. But maybe we will get a bigger change here in the next weeks.
