### ISSUE TITLE
No WS2801

### ISSUE THREAD

**Issue by pablinho10** [tvdzwan/hyperion#394]
Hi!, i just bought a led strip to make a ambilight with my raspberry pi and openelec. The problem is i dont have a WS2801 led strip, my strip its a normal led resister strip, how can i use it with hyperion?? i tried to use pi-blaster but when i use "git clone https://github.com/mwilliams03/pi-blaster.gitt" the answer is "-sh: git: not found" so... i dont know what to do now... can i use this strip?

**Comment by brindosch** [comment]
@pablinho10 
You need a supported strip
I could recommend the APA102

**Comment by tpmodding** [comment]
No feedback, think we can close this.
