### ISSUE TITLE
Raspberry Pi 2, Openelec and ws2801

### ISSUE THREAD

**Issue by Yariv-h** [tvdzwan/hyperion#395]
Using OpenELEC-RPi2.arm-5.0.8.img, added to config file dtparam=spi=on param 

"device" :
	{
		"name"       : "MyPi",
		"type"       : "ws2801",
		"output"     : "/dev/spidev0.0",
		"rate"       : 250000,
		"colorOrder" : "rgb"
	},

	"effects" : 
	{
		"paths" : 
		[
			"/storage/hyperion/effects"
		]
	},

while restarting the pi, the leds start working, now seems like it is working just fine i can see the color changes and blinking.

what should i do to make it into "production ready" for kodi? should i stop anything? to use another settings?

what do i miss here?

**Comment by brindosch** [comment]
@Yariv-h 
Could you please tell, what do you mean with "production ready". All is working fine?

**Comment by brindosch** [comment]
Will close it
thank you
