### ISSUE TITLE
LEDs not turning off when OSMC is shut down

### ISSUE THREAD

**Issue by Spaddel** [tvdzwan/hyperion#396]
Worked perfectly in Raspbmc, but after installing OSMC the LEDs don't turn off when shutting down the Raspberry Pi

**Comment by Newan** [comment]
+1
Have the same problem. Perfect switching off the LEDs would also be in idle?

**Comment by Sabcoll** [comment]
Simply write a shutdown script to set the colors to black before shutting down.
You should find enough tutorials for it on the web. It's not an Hyperion issue, imho.

**Comment by Newan** [comment]
change the stop section by the initscript under /etc/init.d/hyperion
```
stop)
        if [ -f $PIDFILE ]
        then
                printf "%s\n" "Set LEDs off"
                hyperion-remote -c black
                sleep 1
                printf "%-50s" "Stopping $NAME"
                    PID=`cat $PIDFILE`
                    cd $DAEMON_PATH
                if [ -f $PIDFILE ]; then
                    kill -HUP $PID
                    printf "%s\n" "Ok"
                    rm -f $PIDFILE
                else
                    printf "%s\n" "pidfile not found"
                fi
        else
                printf "%-50s\n" "No PID file $NAME not running?"
        fi
;;
```

**Comment by Sabcoll** [comment]
Where is the like button?
+1 for it to make it a standard function!

**Comment by Newan** [comment]
I don´t know to create a pull request, but the initscript is located under github:
 hyperion/bin/hyperion.init.sh

**Comment by brindosch** [comment]
I will submit this, with the new install script, thanks

**Comment by tpmodding** [comment]
@Spaddel can be closed?

**Comment by brindosch** [comment]
OSMC uses systemd and the new script will install this accordingly. If you push the shutdown button, the lights will be set to off. (But it is better so power off the leds (at least) over night).

Thank you
