### ISSUE TITLE
wrong link to Raspbmc forum topic

### ISSUE THREAD

**Issue by AlexBGoode** [tvdzwan/hyperion#397]
Hello

It is not actually a bug of the software but rather a wrong description
The text describes the link:

"Raspbmc forum topic: http://forum.stmlabs.com/showthread.php?tid=11053"

which is not actual anymore so I would recommend to update it to point right location

Does it make sense?

**Comment by brindosch** [comment]
@AlexBGoode 
I could not find that link (page). Is this changed or still present?

**Comment by tpmodding** [comment]
can anyone post the new url? i can't find it

**Comment by brindosch** [comment]
this was maybe just a guide? google ->
Hyperion site:discourse.osmc.tv

**Comment by brindosch** [comment]
I will close it. I found no releveant topic. - Removed from the wiki
