### ISSUE TITLE
API: Get current color

### ISSUE THREAD

**Issue by MakeMeASandwich** [tvdzwan/hyperion#398]
This is a feature request:
At the moment, it does not seem to be possible to retrieve the active color(s) using the JSON API.
A client needs to keep track of it by itself, but since another one with a higher priority can override the setting you do not really know the Ambilight's active colors.

**Comment by brindosch** [comment]
There are more comments anyway ;)

**Comment by brindosch** [comment]
@MakeMeASandwich 
#622

/will be merged soon, active effects is already available in V1.02.0
thank you
