### ISSUE TITLE
Not all hyperion leds lighting only 50 will light up

### ISSUE THREAD

**Issue by bre34** [tvdzwan/hyperion#399]
I’m having trouble with the leds ws2801 I have a 5v 10a 50 watt power supply a 5v 8a power supply and a raspberry pi power supply but no matter which power supply I use I cant get more than 50 leds to light up at one time even more strange is 5v 10a and 5v 8a are displaying the under voltage rainbow on top of screen in osmc when the pi power supply doesn’t do this is anybody else having the same trouble lighting up all the leds they need and what is the fix I have even tried power on both ends of the strip but to no avail thanks I followed this guide https://christianmoser.me/how-to-build-your-own-tv-ambilight-with-raspberry-pi-and-xbmc/comment-page-2/#comment-10860

**Comment by strunkie30** [comment]
Same issue here.

**Comment by bre34** [comment]
hi m8 you having the same probs as me. I have a few tvs in house but only able to power 50 leds with the different power supplys I have even a pi lead will power 50 same as a 5 volt 10 amp very strange I'm using ws2801 leds ive tried powering from both ends but same result whats your setup thanks ?

**Comment by strunkie30** [comment]
I've fixed the issue for me. My problem was that i have wrong permissions on this folder and file:
/opt/hyperion/config/hyperion.config.json

Fix you permissions and it will work.

**Comment by bre34** [comment]
what do you mean m8 fix the permissions i don't understand to can give me some more help on this thanks

**Comment by brindosch** [comment]
@bre34 
Is your problem still present?

**Comment by bre34** [comment]
no mate have fixed the problem by making own json file and using sudo cp hyperion/hyperion.config.json /etc/ via ssh

**Comment by brindosch** [comment]
glad that it´s fixed
Thank you for feedback

**Comment by tpmodding** [comment]
@bre34 can be closed?
