### ISSUE TITLE
LED Colours dont match Colours chosen on Hyperion Remote

### ISSUE THREAD

**Issue by adamnmcc** [tvdzwan/hyperion#403]
Hi, 

I am currently using Hyperion to run some Arduino driven WS2812B that i use as mood lighting in my living room. Everything works fine apart from the fact that when i select a colour on my Remote (currently Hyperion Remote for Android, but all apps have the same problem) the LED colour doesn't match what i've chosen. Red comes out as blue, blue as red and yellow as turquoise. 

is this likely something i've got wrong in the code for the Arduino? i have two sets of 51 leds. 

i've pasted the Arduino code here: http://pastebin.com/wYHf17dp

Thanks, 

Adam

**Comment by alex240188** [comment]
I also use WS2812B via Arduino.
Here is the sketch I have adapted (Also uses FastLED like yours) http://pastebin.com/Z0aJYEZ4
Set the following values to your config
#define NUM_LEDS
#define DATA_PIN
#define serialRate

I've added the variables from your setup into my Sketch. Just copy and paste this one below and upload to your arduino
http://pastebin.com/Ny5qVUSV


The arduino Handles the Changeover to GRB make sure your hyperion.json.conf has
"colorOrder" : "rgb"

**Comment by adamnmcc** [comment]
Hey, Many thanks for that, I think I tried this Sketch otiginally, but it didn't work but i'll try again when i get home.

**Comment by adamnmcc** [comment]
Only just got round to uploading this. it worked perfectly. Thanks a lot mate.. :)
