### ISSUE TITLE
Match colors of TV with colors of RGB stripe and define custom color values for R,G and B

### ISSUE THREAD

**Issue by emc02** [tvdzwan/hyperion#405]
The colors from the LED-Stripes never matches the color from the TV perfectly. For me the TV-red is a mixture of red and green on the LED-Stripes but I can not set the transformation between TV-red and Stripe-red.

For example in boblight you can set the color value for red as FF0301 to match the color of the red on the TV. If this feature can be included in hyperion it would be perfect!

**Comment by Sabcoll** [comment]
+1

It would be awesome to set Hex Values to define the colors.

**Comment by emc02** [comment]
well, it doesn't have to be in HEX format, it could also be like that in config file:

                "red" :
				{
					"red       " : 1.0000,
					"green     " : 0.0000,
					"blue      " : 0.0000,
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"green" :
				{
					"red       " : 0.0000,
					"green     " : 1.0000,
					"blue      " : 0.0000,
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"blue" :
				{
					"red       " : 0.0000,
					"green     " : 0.0000,
					"blue      " : 1.0000,
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				}

and I found something in the ColorRgb.h file:

    /// 'Red' RgbColor (255, 0, 0)
	static ColorRgb RED;
	/// 'Green' RgbColor (0, 255, 0)
	static ColorRgb GREEN;
	/// 'Blue' RgbColor (0, 0, 255)
	static ColorRgb BLUE;

maybe there is some way to change hyperion to define standard colors to match TV

**Comment by emc02** [comment]
I think adding of Color correction should be done after grabber when RGB values of the single fields that are related to the LEDs on the stripe are known

Calculation should maybe look like this:

    // get values from config (see post above)
	// values from red
	const double red_red = colorConfig.get("red", 1.0).asDouble();
	const double red_green = colorConfig.get("green", 1.0).asDouble();
	const double red_blue = colorConfig.get("blue", 1.0).asDouble();
	// values from green
	const double green_red = colorConfig.get("red", 1.0).asDouble();
	const double green_green = colorConfig.get("green", 1.0).asDouble();
	const double green_blue = colorConfig.get("blue", 1.0).asDouble();
	// values from blue
	const double blue_red = colorConfig.get("red", 1.0).asDouble();
	const double blue_green = colorConfig.get("green", 1.0).asDouble();
	const double blue_blue = colorConfig.get("blue", 1.0).asDouble();
	
	// RGB Value from grabber (don't know where I get them from)
	const double grabber_red, grabber_green, grabber_blue
	
	// calculation
	red   = red_red   * grabber_red + green_red   * grabber_green + blue_red   * grabber_blue;
	green = red_green * grabber_red + green_green * grabber_green + blue_green * grabber_blue;
	blue  = red_blue  * grabber_red + green_blue  * grabber_green + blue_blue  * grabber_blue;
	
	// correction of max value
	max=red;
	if (green>max) max = green;
	if (blue>max)  max = blue;	
	red   = red   / max;
	green = green / max;
	blue  = blue  / max;


Maybe this can help adding this feature?

**Comment by rv112** [comment]
+1

Need to calibrate the RGB colors in hyperion.

**Comment by MarcDahlem** [comment]
I wrote a small tool a  year ago, which can be used to adjust the colors: https://github.com/MarcDahlem/RGB-CAT

**Comment by rv112** [comment]
Thanks! I will check if it works with Raspberry Pi 2 and OpenELEC. But the main problem, the missing setting for RGB colors in Hyperion, will not be fixed with this.

**Comment by stst1234** [comment]
+1

Yes, please make the RGB-colors adjustable by the config-file.

**Comment by Fizzle2704** [comment]
+1

**Comment by Sigfrodr** [comment]
+1

**Comment by tevey** [comment]
+1

**Comment by emc02** [comment]
A lot of progress is going on in hyperion, that's cool. Maybe this Issue will be fixed soon. I am ready to help as much as I can (if needed).

**Comment by brindosch** [comment]
@AEtHeLsYn 
Colors? Colors! This - may - be your part of interest
Adjust red green and blue like your whitelevel correction
If/How is up to you :)

**Comment by AEtHeLsYn** [comment]
@brindosch 
I already saw the issue some time ago. Having a color correction matrix (CCM) would involve higher cpu usage as we would need to do all the math on the fly. Current correction and transform does all the math before and when we set colors it's only a matter of getting the already computed value. My first approach around color correction was about using CCM, but we have limited computing resources. Anyway, I'll take another look.

**Comment by brindosch** [comment]
If you could find a future proof and not too cpu intensive way. I am sure people will like it :)

**Comment by tpmodding** [comment]
Dont know if this is Really needed... If you dont buy the cheapest usb grabber you have the right Color... People buy the cheapest usb grabber and the cheapest leds (f...ing ws2812b) and then Open millions of issues... I never(!) had Problems with my Setup (stk1160 grabber and lpd8806) sure May i paid more but my hyperion runs with 3 devices (leds behind my tv and two forwarded ikea lamps with leds) with 6-9% cpu... If the only solution is too cpu intensiv WE shouldnt invest time for to parsimonious People!!

Von meinem iPhone gesendet

**Comment by emc02** [comment]
@tpmodding I think you don't understand what is all about here. I am not using any hardware color grabber. It's just software inside hyperion with OpenELEC and the issue here is, that the color from TV and LED-Stripes is not matching, because for example LED-Red is not exactly the same then TV-Red and needs some modification (maybe a little bit blue and green) to match exactly.
Maybe you know something about color calibration on displays? Each display shows different colors.

About CPU-Power: maybe this feature can be added and you can choose to use or not. So everyone with RPi2 and lower can disable and maybe RPi3+ can handle it.

**Comment by brindosch** [comment]
I am using a Plasma TV and red is ok, blue too, but my green is very very bad.
And i failed to correct this with tv settings.
@tpmodding 
i see this more like the tv whitelvl. With this you could adjust redlvl bluelvl greenlvl to matching colors of your TV.

@emc02 
A disable option may be not that good. It is just one more point to open issue because "everything is sluggish"

**Comment by AEtHeLsYn** [comment]
@brindosch @emc02
I already have this proposed modification coded and tested, I managed to avoid high cpu usage ;)
Anyway i still have not coded remote management of the new commands. Do you want me to commit my changes to beta version or do you prefer to test everything at the same time?
Btw, hyperion is almost perfect now ;)

**Comment by brindosch** [comment]
I would prefer to test everything at the same time, saves you and us time :)
You could also have a look at led index (hyperion-remote) ;)
Don´t hurry. We have enough to do at the background :)

**Comment by emc02** [comment]
I will test everything if it's available.
Don't hurry, I've seen wrong colors for month, so a few weeks more doesn't matter ;)

**Comment by AEtHeLsYn** [comment]
#576

**Comment by brindosch** [comment]
part of the BETA branch, you need to compile your own hyperiond
follow the "Feedback BETA XXX" issue for feedback and a little how to.
/Closed
