### ISSUE TITLE
Useless timer in adalight?

### ISSUE THREAD

**Issue by NicoHood** [tvdzwan/hyperion#406]
Why do we need to update the leds of adalight every 5 seconds? My hyperion sends 20 frames per second anyways, even if all leds are off.

https://github.com/tvdzwan/hyperion/blob/master/libsrc/leddevice/LedDeviceAdalight.cpp#L20-L22

**Comment by tpmodding** [comment]
@NicoHood can be closed?

**Comment by NicoHood** [comment]
The question is still valid. I'd like to have an answer if possible.

**Comment by penfold42** [comment]
Does yours still update the LEDs if it's set to a static colour ?

Mine doesn't seem to with the 2801 device type.

**Comment by NicoHood** [comment]
I tried with
```
hyperion-remote --color red
```
But it still updates every few seconds. It also does this if the screen is blank. It sends the data over and over to the device. I do not think that this is different with other devices.

And this timer ensures to write the frame ever 5 seconds or whatsoever. No idea why though.

**Comment by brindosch** [comment]
You still have no answer, and it seems no one knows. The dev should answer this ;)
I will close this. You could fork hyperion and remove the value and test again. I am sure this is the fastest solution.

I will close this
