### ISSUE TITLE
hyperiond hangs at "Initializing Python interpreter"

### ISSUE THREAD

**Issue by and1g** [tvdzwan/hyperion#408]
Hello,
I have compiled Hyperion from source on a RPi2 running Gentoo Linux using the How To. 
Unfortunately, it fails to start. To be more precise, it just hangs when "Initializing Python interpreter". Python 3.4 is the default python interpreter on the system and 2.7 is also installed. Could this be related to some dependency issue? I would have assumed that these would be found by cmake... (log is attached)
I would be glad, if you could help me with this... How could I address this issue? Is there a possibility to get a more precise output to the console when running hyperiond?
Yours, Andreas

[cmake.txt](https://github.com/tvdzwan/hyperion/files/32368/cmake.txt)
[hyperion.config.json.txt](https://github.com/tvdzwan/hyperion/files/32384/hyperion.config.json.txt)

**Comment by Blenderpics** [comment]
I've got the same problem. I am using an adalight apa102, flashed with the newest 'firmware', and a raspberry pi 2 b running the latest openelec, with the newest version of hyperion (master of 20.11.2015). On startup it hangs on "Initializing Python interpreter" . It's most likely a issue of the adalight device 'driver'. On older versions of hyperion, bootup works, but hyperion hangs up after or during the bootsequence (which was a known bug in the adalight driver). Sadly i can't really specify since which commit the "Initializing Python interpreter" is present

**Comment by and1g** [comment]
Thanks for the reply. Good to know that I am not the only one with the problem. The Hyperion version I used was the current master, when I opened the issue. What Linux did you use?
In the meantime, I have set up Arch Linux ARM as an alternative and it is running with the same Hyperion version. This makes me think it is not really an issue on the Hyperion side.

**Comment by Blenderpics** [comment]
Right now i am using "Linux OpenELEC 4.1.12 #1 SMP Sun Nov 1 16:44:41 CET 2015 armv7l GNU/Linux".
But i did try several different openelec versions, and even switched to my raspberry pi b+ with the same result.
does arch linux has UTV007 grabber support build into the kernel? if so, i might just switch to arch linux as well, if you say it works fine on it

**Comment by and1g** [comment]
I am using a Fushicai grabber and it works out of the box. But since I bought a faulty HDMI converter which makes a flickery green image, I have currently stripped my setup and can not have a deeper look. If you know the name of the kernel module, you could have a look at the config file: https://github.com/archlinuxarm/PKGBUILDs/blob/master/core/linux-raspberrypi/config.v7
But to be warned, Arch Linux is not even close to the install and be happy approach of Openelec. (This is intentional)

**Comment by Blenderpics** [comment]
so... i spend all day installing arch linux on my pi 2 and compiling hyperion from source, but for me the error remains the same.
It still hangs on Initializing Python interpreter....
did you compile from source? 

>alarm@alarmpi bin]$ sudo ./hyperiond /home/alarm/hyperion.config.json
>Application build time: Nov 21 2015 15:27:54
>QCoreApplication initialised
>Selected configuration file: /home/alarm/hyperion.config.json
>ColorTransform 'default' => [0; 87]
>Device configuration:
>{
>        "colorOrder" : "bgr",
>        "name" : "MyPi",
>        "output" : "/dev/ttyACM0",
>        "rate" : 500000,
>        "type" : "adalightapa102"
>}
>
>Opening UART: /dev/ttyACM0
>Black border threshold set to 0.01 (3)
>Not creating any smoothing
>Effect loaded: Knight rider
>Effect loaded: Blue mood blobs
>Effect loaded: Cold mood blobs
>Effect loaded: Full color mood blobs
>Effect loaded: Green mood blobs
>Effect loaded: Red mood blobs
>Effect loaded: Warm mood blobs
>Effect loaded: Rainbow mood
>Effect loaded: Rainbow swirl fast
>Effect loaded: Rainbow swirl
>Effect loaded: Snake
>Effect loaded: Strobe blue
>Effect loaded: Strobe Raspbmc
>Effect loaded: Strobe white
>Initializing Python interpreter

**Comment by and1g** [comment]
Yes, I compiled from source. I can explore this further in a couple of days, when I have rearranged my hyperion setup.
Is your Arch up to date?

**Comment by Blenderpics** [comment]
>Linux alarmpi 4.1.13-1-ARCH #1 SMP PREEMPT Fri Nov 13 20:11:44 MST 2015 armv7l GNU/Linux
yep, just installed it and updated all packages

**Comment by Blenderpics** [comment]
Nevermind. Now it works. The actual problem was the usb adalightapa102 device itself, or to be more precise the 'firmware' (its an arduino leonardo). i got the Lightberry 4k kit as a gift, and this adapter was included. The instructions said i need to update the firmware in order to work with the newest version of hyperion, which i did. However that firmware is so broken, you would not believe.

just a best of:
>      if((t - lastByteTime) > serialTimeout) {
>        for(c=0; c<32767; c++) {
>          for(c=0; c<25000; c++) {
>            for(i=0; i<3; i++) {

so basicly, whenever the timeout of 15 seconds was reached, the device is stuck in a inifity loop. great...
because i didn't put hyperion into autostart, it took way longer than those 15 seconds because i had to start hyperion myself.

Actually i am pretty sure, that even without the timout the led's would not work at all. I got myself the datasheet of those led's and the protocol of those is not nearly near the implementation of that in the firmware.

So i just wrote my own which is now 100% adalight compatible, which means i can use the standart adalight device in my hyperion config, instead of the adalightapa102. And now everything works like a charm. (At least with arch linux, havn't tried it with openelec yet)

**Comment by tociek** [comment]
First of all, nobody's perfect :p I would argue that there are funnier parts of code, eg: 

for(i=0; i<1; i++) {
                for(SPDR = 0xFF; !(SPSR & _BV(SPIF)); );
            }

I am still learning :)

Secondly, the part you pasted is from original adalight code and was not modified for APA102. You are right that after 15 sec inactivity hyperion arduino will stop responding...

Thirdly, could you explain how this 'hang' of arduino could cause problems with python interpreter? As far as I know hyperion does not wait for any data from adalight. Furthermore, I started hyperion after long inactivity and it was still able to initialize.

Fourthly, adalight protocol is realized in hyperion, not in arduino - arduino is simply USB->SPI interface.

I am happy to accept all critics as long as it comes along with 'correct' solution...

Regards' from Lightberry

**Comment by Blenderpics** [comment]
The part i posted was modified. I did a compare to the original adalight source to find the difference. In adalight the outer "for" does not exist.
With protocol i mean the protocol of the apa102 LEDs. Each frame needs to be introduced by 32 zeros and ended with 32 ones. There is nothing like that in your source, and I belief it isn't handled software wise as well. (I know that the brightness byte is handled on the Hyperion part, but I don't think those header fields are).

The firmware was the only thing I changed in my setup, and now everything works fine, even on openelec. Just tested the same setup with with your firmware again -> not working anymore.

So its definetly the firmware. 

After all I'm quite happy now, but it was a pain in the ass to get it running. If you wish I can post the source of my implementation.

**Comment by tociek** [comment]
Right about the outer for. Copy/paste error...

Dataframe is handled in hyperion as adalightapa102.cpp.

**Comment by Blenderpics** [comment]
ok then. Yesterday i took a quick look into the adalightapa102.cpp and i thought that it's not handled there. But i just skimmed the source, so it's possible i just didn't saw it. I'm posting my source anyways in case someone stumbles across the same issues i did. feel free to use it.
[LightberryHDUSBAPA1021.1.txt](https://github.com/tvdzwan/hyperion/files/41120/LightberryHDUSBAPA1021.1.txt)

also, remember the config should be adjusted as well, if you are using my 'fix':
>	"device" :
>	{
>		"name"       : "MyPi",
>		"type"       : "adalight",
>		"output"     : "/dev/ttyACM0",
>		"rate"       : 1000000,
>		"colorOrder" : "bgr"
>	},

**Comment by traufeisen** [comment]
Thank you very much Blenderpics.
"Initializing Python interpreter" worked for me, but hyperiond wasn´t doing anything.
Even manual json commands didn´t work.
After using your modified firmware everything works :)

**Comment by tpmodding** [comment]
@and1g issue fixed? can be closed?

**Comment by and1g** [comment]
Sorry, I have completely forgotten about this issue. At least for me it is closed. The main cause of the problem seemed to be a completely faulty Hyperion Arduino Sketch.
