### ISSUE TITLE
bug : APA102 is BGR Led

### ISSUE THREAD

**Issue by fcarlier** [tvdzwan/hyperion#410]
Hello, 
in file https://github.com/tvdzwan/hyperion/blob/master/libsrc/leddevice/LedDeviceAPA102.cpp#L38-L40, in write function is programming with RGB value but normally is BGR (https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/)
edit: https://www.adafruit.com/datasheets/APA102.pdf, page 3, BGR coding value

Replace : 
                _ledBuffer[iLed*4]   = 0xFF;
		_ledBuffer[iLed*4+1] = rgb.red;
		_ledBuffer[iLed*4+2] = rgb.green;
		_ledBuffer[iLed*4+3] = rgb.blue;
by:
                _ledBuffer[iLed*4]   = 0xFF;
		_ledBuffer[iLed*4+1] = rgb.blue;
		_ledBuffer[iLed*4+2] = rgb.green;
		_ledBuffer[iLed*4+3] = rgb.red;

You can confirme this modification ? or hyperion modify the order color before this call ?

My test use TestSpi.cpp with fixed color
THX

**Comment by fcarlier** [comment]
OK https://github.com/tvdzwan/hyperion/commit/2a77b551c5b504f4ce9b0a179d4c20eaf6128f6b
But I think : 
-> Hardware is defined with data sheet and protocole
-> Software is the function to realize
-> Driver is wapper beetwen H and S

**Comment by tpmodding** [comment]
@fcarlier is that fixed? can be closed?

**Comment by brindosch** [comment]
Should be done
