### ISSUE TITLE
v4l2 does not dim properly

### ISSUE THREAD

**Issue by packruler** [tvdzwan/hyperion#412]
I have been trying to get the LEDs to go darker on black screens. I noticed that if I restart hyperion when the input is dark it will make the LEDs dark but if the screen goes bright again and then back to dark the LEDs dim but not nearly as much as they were. 
I've tried setting the input signal thresholds as high as .6 with no effect. Any ideas what is going on?

**Comment by keshav2609** [comment]
Can you put your hyperion.config.json for us to have a look

**Comment by tpmodding** [comment]
No answer within 3months, i will close this.
