### ISSUE TITLE
Add start/stop script for other linux distributions

### ISSUE THREAD

**Issue by NicoHood** [tvdzwan/hyperion#413]
I am running hyperion on Elementary OS (based on ubuntu LTS). Its working pretty good so far, and I am playing a lot with hyperion.

Now I was looking for a way to automatically start hyperion at startup, but not always. Like a service which you can enable/disable/start/stop.

This script looked very promising:
https://github.com/tvdzwan/hyperion/blob/master/bin/install_hyperion.sh

I then looked at the install script and tried to copy the script to my directories (from the build directoty):
```
sudo cp ../bin/hyperion.init.sh /etc/init.d/hyperion
sudo chmod 755 /etc/init.d/hyperion
sudo update-rc.d hyperion defaults 98 02
```

I first had the problem that I had \r\n linefeeds, which I needed to destroy (could be caused by my git settings).

It seems to work now, I just have some problems:
* `sudo /usr/sbin/service hyperion restart` Does stop, but not start the service again. I think the flushing takes a tiny bit too long and the script reports `Already running...`.
* I need sudo to start/stop the script
* I cannot enable/disable the hyperion as a service properly. I want to enable/disable autostart, so I dont need to always edit my autostart setting with adding/removing commands. So maybe the script isnt perfect and there is a better way to enable/disable such scripts/services?

Any suggestions? Maybe @Gamadril can help me, since I saw you were working on this quite some time?

**Comment by brindosch** [comment]
@NicoHood 
The new install scipt supports systemd init.d and initctl

**Comment by NicoHood** [comment]
Where is the script? Is it merged yet?

**Comment by brindosch** [comment]
Just read your post again. Not sure if this fit your needs.
Supports your ubuntu lts systemd? There you could easily start/stop/enable/disable hyperion service

**Comment by NicoHood** [comment]
I posted my issues there.
What I asked for was a link to this issue:
https://github.com/tvdzwan/hyperion/issues/493

**Comment by brindosch** [comment]
Could be closed
