### ISSUE TITLE
snake.py effect dimming

### ISSUE THREAD

**Issue by kesteraernoudt** [tvdzwan/hyperion#415]
Hi all,

Shouldn't line 26 of snake.py be this:

    rgb = colorsys.hsv_to_rgb(hsv[0], hsv[1], hsv[2]*(snakeLeds-i)/snakeLeds)

That gives a longer tail for the snake with higher 'percentage' input.

Regards

**Comment by brindosch** [comment]
@kesteraernoudt 
you will be free to improve effects. just make a pull request ;)

**Comment by brindosch** [comment]
Is added

**Comment by redPanther** [comment]
see pr #520
