### ISSUE TITLE
ability to add multiple color transform?

### ISSUE THREAD

**Issue by b2un0** [tvdzwan/hyperion#417]
hi,

is it possible to add multiple color transform blocks for multiple devices? how the ```id``` field work/used?

my ```hyperion.config.json``` looks like this so i have only one configuration for Kodi and the grabber.
but i need to set a different color transformation for the grabber

```
{
	"device" :
	{
		"name"       : "MyPi",
		"type"       : "ws2801",
		"output"     : "/dev/spidev0.0",
		"rate"       : 250000,
		"colorOrder" : "bgr"
	},

	"color" :
	{
		"transform" :
		[
			{
				"id"   : "default", // for xbmcVideoChecker
				"leds" : "*",
				"hsv" :
				{
					"saturationGain" : 1.0000,
					"valueGain"      : 1.0000
				},
				/// ...
			},
			{
				"id"   : "grabber", // for grabber-v4l2
				"leds" : "*",
				"hsv" :
				{
					"saturationGain" : 0.5000,
					"valueGain"      : 1.0000
				},
				/// ...
			}
		],
		"smoothing" :
		{
			 /// ....
		}
	},

    "leds" : 
	[
		{
		/// ...
		}
        ],


    "xbmcVideoChecker" : 
	{
		"xbmcAddress" : "127.0.0.1",
		"xbmcTcpPort" : 9090,
		"grabVideo" : true,
		"grabPictures" : false,
		"grabAudio" : false,
		"grabMenu" : false,
		"grabScreensaver" : false,
		"enable3DDetection" : true
	},

	"grabber-v4l2" :
    {
        "device" : "/dev/video0",
        "input" : 0,
        "standard" : "NTSC",
        "width" : -1,
        "height" : -1,
        "frameDecimation" : 2,
        "sizeDecimation" : 4,
        "priority" : 1200,
        "mode" : "2D",
        "cropLeft" : 6,
        "cropRight" : 6,
        "cropTop" : 2,
        "cropBottom" : 2,
        "redSignalThreshold" : 0.1,
        "greenSignalThreshold" : 0.1,
        "blueSignalThreshold" : 1.0
    },
}
```

**Comment by b2un0** [comment]
i found only this line where the ```id = default``` value are used?

https://github.com/tvdzwan/hyperion/blob/f594935c9a6a2f1818dd3acfdb0fddfac6ad76cb/libsrc/hyperion/Hyperion.cpp#L73

**Comment by rv112** [comment]
+1

**Comment by tpmodding** [comment]
you can use different transforms.

just give them a name with "id", and set with "leds" wich leds use which transform 
eg
				"id"   : "VIDEOGRABBER",
				"leds" : "*",

"*" means for all available leds

if you wonna turn for example the last 10 leds from 150 leds off you can select only the last 10 leds with the specific numbers from the leds
				"id"   : "off",
				"leds" : "140-149",

**Comment by brindosch** [comment]
10 days, just open a new one, if necessary
Thank you

**Comment by brindosch** [comment]
@b2un0 
It is currently impossible to split between v4l2 and framegraber inside the same .json
As tpmodding written above you could just use this to transform some of the leds.
- be aware that you need to assign all leds you use!
HyperCon is not able to create it currently. Need to fix this.

A working pattern with the new calibration is here:
https://hyperion-project.org/threads/2-sets-of-lights.62/
