### ISSUE TITLE
Openelec 6.0 + Rpi2 + PaintPack : Failed to open HID

### ISSUE THREAD

**Issue by Shampra** [tvdzwan/hyperion#418]
Hello!

Please... help!
After days of research, analysis, testing ... it still does not work.
With :
*Openelec 6.0
*Raspberry 2 b
*Paintpack
*Last Hyperion master (28nov)

I've : 
**lsusb**
*Bus 001 Device 007: ID 0e8f:0025 GreenAsia Inc.
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub*

**LD_LIBRARY_PATH=/storage/hyperion/bin /storage/hyperion/bin/hyperiond /storage/.config/hyperion.config.json**
...
*Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "type" : "Paintpack"
}
Hidapi initialized
Failed to open HID Paintpakc device
Black border threshold set to 0.01 (3)
...
Effect loaded: Strobe white
Initializing Python interpreter
Segmentation fault*

So nothing happens. Paintpack blink on Rpi startup, nothing else. And it work perfectly on Windows PC.

I there any problem with Openelec 6.0?
Does it work with another version? 
Thanks for your help!

**Comment by penfold42** [comment]
The source has a different default usb product id;
auto VendorIdString       = deviceConfig.get("VID", "0x0EBF").asString();
		auto ProductIdString      = deviceConfig.get("PID", "0x0025").asString();

Maybe try specifying yours in the config ?

**Comment by Shampra** [comment]
Oh, the source has "B" instead of "8".
Someone managed to run Paintpack with this version??

So... I will try to understand how to compile with the right code, but having never done that and without a linux (besides Openelec ^^), an help is really welcome.
Thanks

**Comment by penfold42** [comment]
You can just edit your Hyperion.conf.
The source code just has the _default_ value.
Add this to the config 
"VID" : "0x0e8f"

**Comment by Shampra** [comment]
Not better :(

*Device configuration:
{
        "PID" : "0x0025",
        "VID" : "0x0e8f",
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "type" : "paintpack"
}
Hidapi initialized
Failed to open HID Paintpakc device
Black border threshold set to 0.01 (3)
Not creating any smoothing
Effect loaded: Knight rider*

**Comment by penfold42** [comment]
It looks Like the code was refactored to use a common USB HID layer.

Are you running as root ? Does the use have permission to the use hid device ?
One of the other commits suggests this when it fails to open the usb device

**Comment by Shampra** [comment]
I tried as root.
For permission... i suppose. Is there any possible test?

**Comment by penfold42** [comment]
I would try the latest version first.

**Comment by Shampra** [comment]
Same result.

Connected as root
all removed.
Deployment like this : https://github.com/tvdzwan/hyperion/wiki/Installation-on-RPi-with-OpenELEC
-> no "Adding Hyperion to autostart script" at end
If I launch like wiki said, *"Unable to connect to host"*
I I launch with LD_LIBRARY_PATH line, same result (and always **paintpakc**)

**Comment by penfold42** [comment]
You need to re get the install.sh script.

**Comment by brindosch** [comment]
@penfold42 
Awww, yes you are right... I can´t see the trees at the forest

@Shampra 
Please retry

**Comment by NicoHood** [comment]
I was the guy who refactored the HID devices. If the problem is not solved in a week, remind me and I will have a look (currently extremely busy).

**Comment by penfold42** [comment]
It was fixed - I tested this a while back and the cause was the install.sh still using the year old tar file
