### ISSUE TITLE
Print out feedbacks from Arduino connected to RPi (Adalight config)

### ISSUE THREAD

**Issue by AlexBGoode** [tvdzwan/hyperion#419]
Hello

I wonder if it's possible to print out feedbacks received from Arduino by serial port.
I mean the device type Adalight when PRi connected to WS2812b via Arduino.
My sketch at Arduino may provide feedbacks using Serial.write(status) however I don't understand how to read such the feedback and print it out at screen or log file at RPi

Any ideas would be much appreciated

**Comment by penfold42** [comment]
Looking at the low level rs232 driver, I can't see any "read" calls anywhere.

You could try a simple "cat /dev/ttyUSB" while Hyperion is running

**Comment by AlexBGoode** [comment]
Hm... nether thought that it could be so easy
:-)

It works that way, thanks
