### ISSUE TITLE
question: how to format json commands

### ISSUE THREAD

**Issue by pete111** [tvdzwan/hyperion#422]
Hello, I would like to send json requests from my online script. But I don't know how json request are formated. I would like to make my scripts to send requests similar as mobile app (color changes, effects, settings, etc)
So how can I get the examples of commands for each request? Thank you.

**Comment by penfold42** [comment]
https://github.com/tvdzwan/hyperion/wiki/Command-line-utility

**Comment by pete111** [comment]
Thanks penfold42! I know this utility but I don't know how it gets for example list of available effects?

**Comment by p1n9** [comment]
Use your command with hyperion-remote and option --print to get the json format
$ hyperion-remote --list --print

**Comment by pete111** [comment]
thank you! btw in android app on the screen with color wheel I see two sliders at the bottom (one is for "radiation power" and one for "saturation" - sorry if  my word are not proper fot this). But I found out app is sending json for color. This wondered me because I thought it manipulates saturation/gain values.

**Comment by tpmodding** [comment]
@pete111 can be closed?
