### ISSUE TITLE
Possible to create a Wake-Up effect with increasing Brightness?

### ISSUE THREAD

**Issue by sheggy012** [tvdzwan/hyperion#424]
Hello,
is it possible to change an Effect so that it gains Brightness over time?
I want to change the Mood blobs Effect so that it starts with like 20% Brightness and gains Brightness over time until 100%.

**Comment by penfold42** [comment]
What are your Python skills like ?

**Comment by sheggy012** [comment]
My Phyton skills are pretty bad. Is there a script which uses similar functions already? Maybe i can copy it out.

**Comment by brindosch** [comment]
@sheggy012 
There ist new cinema fade in fade out effect vom redPanther.
Just use this as a base.

https://github.com/tvdzwan/hyperion/pull/520/files#

I will close it, thank you
