### ISSUE TITLE
Hyperion not respecting the grabMenu in OSMC

### ISSUE THREAD

**Issue by swetoast** [tvdzwan/hyperion#425]
Hey noticed a peculiar problem running a lightberry gpio pack in OSMC and for some reason hyperion doesnt respect the grabMenu: False paramter in my config it insists on using leds when im in the menu of Kodi, included my hyperion.config incase im too blame :)

[hyperion.config.txt](https://github.com/tvdzwan/hyperion/files/59189/hyperion.config.txt)

**Comment by brindosch** [comment]
@swetoast 
I am using osmc too, and the grabMenu parameter is working as it should. The video true is working?
Maybe an update would help (both)
You could use this
#493 
Please report back, thank you

**Comment by swetoast** [comment]
http://paste.osmc.io/ranicilona

here is my full config

**Comment by swetoast** [comment]
http://paste.osmc.io/eziteceyid

got my systemlog to see alot of errors in it

**Comment by brindosch** [comment]
I catched it. In Kodi
Enable "Allow remote control by programs on this system"
and "Allow remote control by programs on other systems" (you need both, tested this)

navigate ->System->Services->Remote control

Pictures are working too

Feb 17 11:54:27 osmc hyperiond[238]: Message from XBMC: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"file":"smb://NAS/XXX.jpg","type":"picture"},"pla
Feb 17 11:54:27 osmc hyperiond[238]: Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[{"playerid":2,"type":"picture"}]}
Feb 17 11:54:27 osmc hyperiond[238]: XBMC checker: switching to PHOTO mode
Feb 17 11:54:28 osmc hyperiond[238]: V4L2 grabber stopped

**Comment by swetoast** [comment]
cool tnx for the help :) will add it to osmc forums so that users gets the info if they miss it on the wiki

**Comment by tpmodding** [comment]
@swetoast can be closed?
