### ISSUE TITLE
Python script includes don't work inside Hyperion

### ISSUE THREAD

**Issue by roblcampbell** [tvdzwan/hyperion#427]
I am new to both Python and C++, so I can't seem to figure this out myself. I created some effects in the effect development kit, and I created a script called ledutils.py with a bunch of common utility functions and classes used by the scripts I am creating.

The scripts run fine in the GUI simulator, but when I copy them to my Pi running hyperion, they don't work. I took out the 'import ledutils' line and copied over the common code right into each script and it works fine then. So I'd like to know why the python engine running inside Hyperion won't pick up includes from the working directory of the effects.

I'd really like to be able to keep my common code in the included script, so please let me know if there is a way to get this to work. Keep up the great work. I am really enjoying using Hyperion. Thanks!
Rob

**Comment by roblcampbell** [comment]
Also, is there a way to see errors from the python effect script? I don't see a log file or anything.
Thanks.

**Comment by penfold42** [comment]
I Start Hyperion binary directly from the command line and I see my Python errors logged to stdout.

Re: your original problem - try printing sys.path.
This is supposed to be the paths Python  looks at for imported modules.

**Comment by roblcampbell** [comment]
Thanks for the info. That will be very helpful!

**Comment by tpmodding** [comment]
@roblcampbell can be closed?
