### ISSUE TITLE
Repeating white flashes during V4L2 Grabber signal detection

### ISSUE THREAD

**Issue by RickDB** [tvdzwan/hyperion#431]
With the latest version of Hyperion I get short white flashes on all led on every "Signal detected" when it has no video grabber signal as the composite device is off which feeds its with a valid signal.
The output lists:

```
V4L2 Grabber: Signal lost
V4L2 Grabber: Signal detected
V4L2 Grabber: Signal lost
V4L2 Grabber: Signal detected
V4L2 Grabber: Signal lost
V4L2 Grabber: Signal detected
V4L2 Grabber: Signal lost
V4L2 Grabber: Signal detected
```
With the old version (March 2015) I never experienced this as it didn't keep on searching, when I turn on the composite box so that Hyperion gets a signal it works perfectly fine.
Is there anyway to fix this or disable the auto-detection?

Current config: https://gist.github.com/RickDB/ccf080a0c11fa1ba7f56

// Update

The white flashing seems to stop on its own after 2 minutes or so.

**Comment by brindosch** [comment]
@RickDB 
Have you found a "fix"?

**Comment by RickDB** [comment]
@brindosch Sadly no, only other workaround was setting the threshold to 0.0001 for RGB but sometimes it would still flash with that just not as often.

Not sure why it's reading the V4L2 interface so randomly as the grabber on the other end isn't even connected to an HDMI signal, this used to work fine before upgrading to the newest version.
Scrolled thru the commit log but couldn't find any obvious changes to could have caused this.

**Comment by brindosch** [comment]
Maybe your grabber is "damaged", try another one ;)

**Comment by RickDB** [comment]
Don't have another grabber to try out sadly (using Fushicai UT007), since older Hyperion versions worked it must be something that has changed in Hyperion since then or that Raspbian has issues with it.
Even when nothing is connected to the USB grabber composite connectors it detects a signal for some reason.

**Comment by brindosch** [comment]
I also use a Fushicai. No problems with my newest images.

**Comment by brindosch** [comment]
Should be done, if not please open a new issue.
/closed
