### ISSUE TITLE
Automatic reconnect USB Arduino

### ISSUE THREAD

**Issue by charsome** [tvdzwan/hyperion#432]
Hi,

I noticed that when my Rpi loses connection with my USB Arduino, a restart is needed to get Hyperion back working again. Simply plugging back the USB Arduino won't help.

I tried to get some logging with the following command:

/bin/killall -9 hyperiond
/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json > /storage/hyperion/log &

When I disconnect the USB Arduino and plug it back in again, I get this output:

Serial exception caught while writing to device: SerialException device reports readiness to write but returned no data (device disconnected?) failed.

Is there a solution to het this working? My Rpi is running 24/7 and sometimes loses connection with the USB Arduino. I would like to see Hyperion handle this restart automatically.

**Comment by penfold42** [comment]
What device type are you using in Hyperion ?

What type of arduino is it ?

Looking at the source, there is some attempt to catch errors and re open the device.

**Comment by charsome** [comment]
I am using a Pro Micro microcontroller board. When i plug it in, it gets recognized as ttyACM0. When i plug it in again, it gets recognized as ttyACM0 again. So the serial port number does not change.

Hyperion is configures with Adalight as device type. 

I saw that there is a serial reconnect part in the code, but this does not work in my case.

**Comment by penfold42** [comment]
Does the log output match the source ?
I don't see "attempting to reopen..." In your output.

Did you build from latest source ?

**Comment by charsome** [comment]
I installed Hyperion as following:

curl -L --output install_hyperion.sh --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
sh ./install_hyperion.sh

Does that result in the latest version? I will check the lig when i het home.

**Comment by penfold42** [comment]
It will get the latest binary build that as of now is 2 months ago.

That should be ok tho - the rs232 driver was last updated 5 months ago.

Maybe the arduino is slow to properly start up ?
We could try extending the wait time a bit.

**Comment by penfold42** [comment]
I just noticed the "delayAfterConnect" device config option. It's in milliseconds.

Try 5000

**Comment by charsome** [comment]
Nope, this does not help.

**Comment by penfold42** [comment]
I'll try to replicate your problem this week.

What is the URL to the sketch you are running on the arduino ?
Is it a pro micro with an atmega 32u4 ?

**Comment by charsome** [comment]
Yes, it is a pro micro with a 32u4. This is my Arduino sketch: http://pastebin.com/5K3mt7kX. I am using Openelec 6.0 on a Rpi B.

**Comment by AlexBGoode** [comment]
As for me, the value is too high 

#define serialRate 460800

Did it work previously well?

**Comment by charsome** [comment]
Everything works fine except for the reconnecting part when I plugin the usb cable (after unplugging it while running). So no issues with the baudrate or whatsoever.

**Comment by penfold42** [comment]
It looks like the install script needs updating - its referring to a really old build.
```
root@rpi512:~# diff install_hyperion.sh install_hyperion.sh.new
43c43
<       curl -L --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hyperion.tar.gz | tar -C /storage -xz
---
>       curl -L --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hyperion_rpi.tar.gz | tar -C /storage -xz
```

After installing with this modified script I at least now get:
```
Serial exception caught while writing to device: SerialException device reports readiness to write but returned no data (device disconnected?) failed.
Attempting to re-open the device.
```
It appears that the attempt fails - an lsof /dev/ttyACM0 shows hyperion no longer has it open.

**Comment by charsome** [comment]
I changed "hyperion.tar.gz" into "hyperion_rpi.tar.gz" in the install_hyperion.sh file and it now it works. 

However, I am getting the following output when i remove the usb cable:

> Serial exception caught while writing to device: SerialException device reports readiness to write but returned no data (device disconnected?) failed.
>Unable to open RS232 device (IO Exception (2): No such file or directory, file /home/tvdzwan/Projects/hyperion-git/dependencies/build/serial/src/impl/unix.cc, line 100.)

When plug it in again, Hyperion reconnects to the serial port. So i guess it works, but doesn't this error fill up the log file with garbish when i leave the usb unplugged?

**Comment by penfold42** [comment]
I'll look into the init.d script to see if it logs to disk.

Does it fill the screen with spam when you run it directly ?

**Comment by charsome** [comment]
It does fill the screen with garbisch when I run Hyperion with the following command:

/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null

With the additional "2>&1 &" at the end it doesn't:

/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &

**Comment by penfold42** [comment]
Good - it's all redirected to /dev/null

We should still look at reducing the spam tho

**Comment by brindosch** [comment]
Any news on this?

**Comment by penfold42** [comment]
This can probably be closed

**Comment by brindosch** [comment]
Thank you

**Comment by NicoHood** [comment]
Yes i posted a PR that fixed this issue i think.
