### ISSUE TITLE
Upcoming Kodi Api changes

### ISSUE THREAD

**Issue by Razzeee** [tvdzwan/hyperion#433]
You might want to be aware of this:

https://github.com/xbmc/xbmc/pull/8613#event-496601515

Just so you know.

**Comment by meowmoo** [comment]
is this still an issue or can i upgrade to OE7 ?

**Comment by Razzeee** [comment]
Shouldn't that only affect OE8? If OE7 is Jarvis your fine.

**Comment by ntim** [comment]
Next version of OSMC is Jarvis

**Comment by meowmoo** [comment]
@Razzeee
I'm using fritsch builds and the oe7 version  mess up my Hyperion, running the last oe6 build from him at the moment, I guess because he is using  krypton, so basically its oe8?

**Comment by Razzeee** [comment]
Fritschs build is basically OE8 yes

**Comment by meowmoo** [comment]
Than let's wait till it get fixed for oe8 :D

**Comment by brindosch** [comment]
This is related to the official kodi hyperion addon from poljvd repo? A fix for V17 was commited and i merged it.

**Comment by brindosch** [comment]
As long as we have no Krypton Alpha. I am not sure if this make sense to fix. (More changes?!)
@iLLiac4
Could you have a look?
I will close this issue.
