### ISSUE TITLE
Problem with OpenELEC 6

### ISSUE THREAD

**Issue by Megachip** [tvdzwan/hyperion#434]
Seems that hyperion will not work properly with OpenELEC 6 (5 works fine) on RPi

On my test (WS2812B) the 4 first leds will flicker on random colors, only white works (on these four), other colors scrambled up and also found [forums](http://www.forum-raspberrypi.de/Thread-hyperion-nach-update-auf-openelec-6-0-0-leuchtet-nur-noch-eine-led) where same (only the first led works) reported for WS2801.

**Comment by Megachip** [comment]
Possible its the same problem like in https://github.com/tvdzwan/hyperion/issues/416

**Comment by castaway1** [comment]
im running hyperion on pi2 and using kodi17 krypton(alpha) with ws2812b and it works nice. If this can help.

**Comment by Megachip** [comment]
@castaway1 Interesting. [wiki](https://github.com/tvdzwan/hyperion/wiki/WS2812b-PWM) told me, that rpi2 not supported. Which operating system do you use? OpenELEC Millhouse build?
Which hyperion version/build do you use?

**Comment by castaway1** [comment]
using millhouse http://forum.kodi.tv/showthread.php?tid=250817 build #1216
im folowed steps to install here in install section for rpi.

**Comment by Megachip** [comment]
@castaway1 thx... will give it a try when I get access again to the RPi B. Will also test with RPi2. Would be awesome if it will support the ws2812b too. Possible someone should update the wikipages here.

**Comment by brindosch** [comment]
@castaway1  We need the changes in the Hyperion code
This should be "done" refer to the other issue for investigation. 
Wiki: No update until the code is in the repo that is working for every pi.
