### ISSUE TITLE
hyperiond as addon?

### ISSUE THREAD

**Issue by Megachip** [tvdzwan/hyperion#435]
Could the hyperiond provided as an addon like the boblightd?

**Comment by brindosch** [comment]
@Megachip 
There is a addon for Kodi.

**Comment by Megachip** [comment]
@brindosch I mean the deamon, not the client.

**Comment by brindosch** [comment]
Added your wish to the wishlist. I will close it

Thank you

**Comment by Megachip** [comment]
Is there a public wishlist/feature request anywhere? So things will not requested again and again and again?

**Comment by tpmodding** [comment]
toDo/wishlist will come soon :)
