### ISSUE TITLE
Install_hyperion.sh references really old build

### ISSUE THREAD

**Issue by penfold42** [tvdzwan/hyperion#436]
This fixed it for me:
```
root@rpi512:~# diff install_hyperion.sh install_hyperion.sh.new
43c43
<       curl -L --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hyperion.tar.gz | tar -C /storage -xz
---
>       curl -L --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/deploy/hyperion_rpi.tar.gz | tar -C /storage -xz
```

**Comment by Megachip** [comment]
got an segmentation fault on openelec 6.0 with ws2812b with this build.

**Comment by NicoHood** [comment]
It looks like this project is somewhat not actively developed anymore. Maybe @tvdzwan could ask for volunteers who would want to update hyperion more often?

**Comment by penfold42** [comment]
Note, there's another url in the script that need changing too

**Comment by garfty** [comment]
Thanks for this, which url? Is it the *DAEMONOPTS* path?

**Comment by penfold42** [comment]
It was another curl line  - same url needs changing.

**Comment by sanex3339** [comment]
penfold42, thank you!

**Comment by penfold42** [comment]
Now I know how to use 2% of git I'll do a commit and pull request

**Comment by tpmodding** [comment]
@penfold42 i think tvdzwan fixed that with the last merges? or am i wrong?
