### ISSUE TITLE
Question: what does the power button (top right) do in Android App

### ISSUE THREAD

**Issue by dannixDanny** [tvdzwan/hyperion#437]
Hi, I'm trying to integrate Hyperion into Samsung SmartThings. So far so good, I can set colour, saturtion, and dimmer. But I need to replicate the Power button in the android App as it switches the kodi screen grabber on instead of a solid colour. I'm just not sure how to do that using the Json interface. Any pointers?

**Comment by Megachip** [comment]
I think it resets to default. (disable effect etc)

**Comment by p1n9** [comment]
The power button on the app turn off all leds and terminate effects.
In json : 
`{"command":"clear","priority":100}`
will reset the process with priority 100 (turn off solid colour or end effect)
`{"command":"clearall"}`
will reset all process (all priority)

the remote process like kodi addon or a config file with grabber/checker enabled will restart automaticaly

For the switch grabber thing, i don't understand very well so here is my config : 
* on my pi an hyperion service is running with grabber and checker disabled
* only my apps and kodi (on another machine with hyperion addon) send data to hyperion over the network.
* when I want hyperion to grab other signal (like my tv or console) I switch between the "legacy" hyperion service and the "v4l2" hyperion service that I've added ([wiki](https://github.com/tvdzwan/hyperion/wiki/Controlling-multiple-devices))
* the hyperionv4l2 servie will run hyperion with an v4l2 grabber enabled config file. ([wiki](https://github.com/tvdzwan/hyperion/wiki/V412-Grabber)) 

As far as I know hyperion we can't switch on/off the grabber and checker things with the json interface.
So I have to start/stop system services to run hyperion with a different config file.

you can also use the hyperion-v4l2 bin to start the grabber separatly but it use a lot more cpu ressources

ps the grabber part is : source => hdmi spliter + hdmi to rca converter + usb video grabber => rpi-hyperion

**Comment by solidewebservices** [comment]
I have the same kind of question. I have a Raspberry Pi with Hyperion Server and APA102 LED's connected. When powered on Hyperion sets the cold mood blobs effect with a duration of 0 (infinite) as bootsequence through hyperion.config.json. This is just some nice light effect which Hyperion starts with for when I'm not watching something from Kodi.

But when I do want to watch somehting from Kodi I want the Ambilight functionality to kick in. I have an Intel Nuc with Kodi and the Hyperion add on. When I do not set an effect to start on the Hyperion server the add on just starts the Ambilight functionality on starting video playback. But when I do have an effect set this does not work and I have to clear the effect through the app.

I'd like to see the Hyperion add-on send the clear command on video playback for Kodi. Or even some directions how I can configure Kodi itself to send this command to Hyperion server so the effect is cleared and the Ambilight feature can take over without the need of manual interaction.

**Comment by redPanther** [comment]
It sounds like your boot effect has higher priority than your ambi light.
I take a quick look into sources and I found out, that the priority in boot sequence is hard coded to "0". hyperion-remote --help says "the lower the number, the higher the priority" that results in boot effect has the highest possible prio.
Best Solution would be that the priority is taken from the effect args in hyperion.config - or the quick way: set to a higher value like "1000" directly instead of "0".

for adjustable boot efx prio we need a change in src/hyperiond/hyperiond.cpp line 129.
change this:
``` const int priority = 0;```
to this:
``` const int priority =  effectConfig["priority"].asUInt(); ```
and set "priority" in hyperion.config
```
"bootsequence" : 
	{
		"effect" : "Rainbow swirl",
		"duration_ms" : 0
		"priority" : 1000
	},
```

I haven’t tested it yet, but I'm sure this works in that way.

**Comment by solidewebservices** [comment]
@redPanther Although I understand what you are saying I unfortunately have no clue on how the edit source and compile myself. I followed the tutorial for installation on OSMC which just downloads one of the deployables and installs it. I'm a newb concerning compilation so I guess I'm out of luck. Thank you for the effort though.

**Comment by redPanther** [comment]
I've tested it and made a pull request on master branch. When my patch is accepted, the ability to adjust boot efx prio comes with  the  next release

**Comment by solidewebservices** [comment]
@redPanther Thank you. I'll keep an eye out for the next release!

**Comment by brindosch** [comment]
@redPanther 
Why is this inverted. make this sense? I am sure everyone expect that higher number -> higher priority?

**Comment by redPanther** [comment]
the prio system is deep in hyperion source. I didn't invent it. When I looked around in the code every grabber has it's own prio. This is should be fixed to make behaviour more predictable.

The order "the lower the number, the higher the priority" ( <- this is a quote from source code) is made by the hyperion founders. The reason why we have to ask him.
But I think we should provide better defaults. The bootsequence was prio 0 originally. This should be set to something higher like 1000 as I suggested.

The current prio system can be seen as a kind of ticket system. The first becomes ticket number "0" the second "1" ...
Then the source with the first (smallest) number can show its content. When this source is finished with drawing (e.g. effect is turned of) the second can show its content ...

If we want to make it dummy proof we had to add some kind of visualization in hypercon. Especially with the abilities of forwarding (or what you can build with that) makes it important to keep an eye on the prios. In bigger setups (usage of hyperion for your complete home lighting) the prio setup is essential and not trivial.

On thing is important - before we even plan to change the prio behaviour we have to understand why this was made and then we have to discuss why to change.
My Opinion: do not change, but provide better documentation and tools.

**Comment by brindosch** [comment]
Thank you for clarify
It is no problem to rename this in HyperCon and document this.
I added the priority 990 as default value (like you wished)
hmm. we need another name for it. Or i modify just tooltips.

**Comment by brindosch** [comment]
Is it possible to create a priority for internal grabber? Then it would be possible to lay (in my case) the external grabber over the internal. And it would be better understandable.

**Comment by redPanther** [comment]
here is an overview about the current state regarding prios. the "not implemented" stuff is easily implementable, but nobody have done it yet. This table assumes my forwarder stuff is merged. (otherwise there would be more "not implemented")

```
source           | intern | extern | Default prio | how to set           | source code
=================|========|========|==============|======================|===================================================
v4l              |   x    |        |      800     | hyperion.config.json | src/hyperiond/hyperiond.cpp
v4l              |        |    x   |      800     | command line         | src/hyperion-v4l2/hyperion-v4l2.cpp
amlogic          |   x    |        |      999     | not implemented      | libsrc/grabber/amlogic/AmlogicWrapper.cpp
amlogic          |        |    x   |      800     | command line         | src/hyperion-aml/hyperion-aml.cpp
dispmanx         |   x    |        |     1000     | not implemented      | libsrc/grabber/dispmanx/DispmanxWrapper.cpp
dispmanx         |        |    x   |      800     | command line         | src/hyperion-dispmanx/hyperion-dispmanx.cpp
x11              |   x    |        |              | not implemented      | not implemented
x11              |        |    x   |      800     | command line         | src/hyperion-x11/hyperion-x11.cpp
framebuffer      |   x    |        |     1000     | not implemented      | libsrc/grabber/framebuffer/FramebufferWrapper.cpp
framebuffer      |        |    x   |              | not implemented      | not implemented
osx              |   x    |        |     1000     | not implemented      | libsrc/grabber/osx/OsxWrapper.cpp
osx              |        |    x   |              | not implemented      | not implemented
bootsequence     |   x    |        |        0     | hyperion.config.json | src/hyperiond/hyperiond.cpp
Json (effects)   |        |    x   |      100     | command line         | src/hyperion-remote/hyperion-remote.cpp
Proto (grabbers) |        |    x   |              | def. by ext. source  | 
boblight         |   x    |        |      255     | not implemented      | libsrc/boblightserver/BoblightClientConnection.cpp
```

**Comment by brindosch** [comment]
@redPanther 
I have no words for your commitment!
Thank you very much for all (ALLLLLLLL!) efforts!

It should be a good decision to make it realiable though the project. If you would implement that i won´t hold you back ;) HyperCon is faster even with this as you thought :)

**Comment by redPanther** [comment]
I will implement those stuff no prob, but no hurry. I will go on after pending PRs are accepted, otherwise I have to invest to much time in merging.
Resolve all "not impl" should be not more than one or two hours. After that we can decide good default values in config. (/hypercon)

**Comment by brindosch** [comment]
Merged ;) New binarys will follow later
