### ISSUE TITLE
LED Matrix APA102

### ISSUE THREAD

**Issue by gadjodilo83** [tvdzwan/hyperion#438]
The DOTSTAR 8x32 Matrix works very well with Hyperion and Rpi2.
https://www.adafruit.com/product/2736

It is possible to make scroll texts with a effect on it? 

Any ideas?

Thanks
Gadjo

**Comment by penfold42** [comment]
Yep - you can even make it act like a lo-res  TV.

The Hyperion config file needs to map Rachel's index to the correct hscan and vscan percentages.

Excel is your friend here to compute the appropriate ranges.

Check out the effects folder - you'll need Python script to either put bitmap images or manipulate individual LEDs.

For a font, check out the Commodore 64 character rom.

**Comment by RanzQ** [comment]
I created a simple js script to do the calculation. My matrix uses "snake" indexing from bottom right, so adjust the loops to your needs. Didn't test yet on hyperion but the output seemed correct.

https://raw.githubusercontent.com/RanzQ/hyperion-audio-effects/master/matrix-config.js

**Comment by brindosch** [comment]
@RanzQ 
Could you add a wiki article for this? I am sure the people would be thankful for this

**Comment by RanzQ** [comment]
@brindosch sure, I'll do it when I find some time. I'll improve the script  a bit to take in cmdline arguments so it can be run using node.js. I also tested it on my led table and confirmed it works. :)

**Comment by brindosch** [comment]
Great news!
Thank you for your help, i will close this

**Comment by RanzQ** [comment]
@brindosch So here it is: https://github.com/tvdzwan/hyperion/wiki/Matrix-configuration

It should work for any matrix. :)

**Comment by brindosch** [comment]
Thank you very much :)
