### ISSUE TITLE
Ambilight only on bottem?

### ISSUE THREAD

**Issue by Megachip** [tvdzwan/hyperion#439]
Is it possible to configure Hyperion (with Hyperion config tool) to only use leds on the bottom? (not top and bottom)?

**Comment by penfold42** [comment]
No, you'll have to build your config manually.

**Comment by AlexBGoode** [comment]
However you may build the config using the HyperCon.jar for top and bottom, and then simply remove the second half of led definitions manually from leds: sections of hyperion.config.json

Be sure that you set counter-wise direction also 1 for "1st LED offset" and 0 for "Bottom Gap"

Wouldn't it work as desired?

Another idea: just build the config for top and buttom only and the second half of the transmitted data will be simply wasted (at least in my case when I use Arduino as the proxy for ws2812b it works this way)

**Comment by tpmodding** [comment]
you can do that with
https://github.com/brindosch/hypercon/tree/master/deploy with the new HyperCon.jar
:)
can be closed now :+1:

**Comment by brindosch** [comment]
Huh, you stolen my files :dancer:
