### ISSUE TITLE
Connect to second hyperion in local network

### ISSUE THREAD

**Issue by jebos** [tvdzwan/hyperion#443]
I have the following setup:

Two Rpi both with there own LED Connected, both running a hyperion, while Rpi "one" is only controlling an static room light (realized through some custom written effects), Rpi "two" is setuped to create a tv ambilight.

Now I want to mirror the tv ambilight on my Rpi "one", or better said I want either:

 1) send the TV Grabbed Image from Rpi "two" to Rpi "one"
 2) run a second hyperion on Rpi "two" that sends the color data through network to my Rpi "one". (in that case the led config of Rpi "one" needs to be available on "two")

As a solution I was thinking that either 
 for 1) I could use the Protoserver Interface (which would mean - if i understand correctly - that I would have to create a ProtoServer - Server that sends the image from within hyperion to another hyperion...)

 for 2) I was wondering to either create a special effect that can read color data from network or to create a network color grabber in c++ .

In general I would rather not send images through network. I know there is boblight and so on, but I would like not go down this road since I have hyperion solid running in my setup.

Is there any available solution to this setup?

**Comment by penfold42** [comment]
You could send just the LED data.
I've just done a pull request to add sending led data to a UDP device.
I have a couple of wifi connected led strips but you could also send it to an "effect" on the second pi that listens on the network.

**Comment by jebos** [comment]
Would be great to have a network reader - like a videograbber. But a Python script would be fine for me.

Du you have a Hyperion for each led strip running? Currently the code looks like that it connects to a specific client.

Maybe in an other Iteration the Hyperion should just be a Server and Clients can connect  to it.

**Comment by penfold42** [comment]
Yes, I have 3 instances running on my "main" pi at the moment.
The first drives a SPI attach arduino with the less around the tv
The second is driving a nightlight on the kids room with an ESP 8266
The third is driving my xmas decorations also with an ESP 8266.

I was looking at the code last night to see how hard it would be to extend Hyperion to drive multiple led devices from single instance

**Comment by AlexBGoode** [comment]
**penfold42**, let me ask you on your setup, I wonder what is the source of inspiration for the last two Hyperion instances? As I understand Hyperion is aimed to grab video signal to transform it into color effects. So I wonder what kind of video do you use as the basis for driving nightlight in the kids room and xmas decoration. 

Maybe I seriously underestimate the potential of Hyperion

**Comment by penfold42** [comment]
3 main reasons:
The remote control apps on iOS and android work great
It  has a simple to use Python scriptable effects interface so is easily extendable
It was a natural extension of the existing led strip around the tv.

**Comment by AlexBGoode** [comment]
Aha! So you don't use any video source to drive nightlight in the kids room - instead you probably used Python to script interesting color transformations 

And the same for xmas decoration, right?

Cool. I obviously had too much focus on video grabber and absolutely overlooked such the potential tool like scripted effects powered by Python

**Comment by penfold42** [comment]
Yep!

The nightlight is just a colour all the time.
It's made of those concentric rings - 60 LEDs in all plus one in the middle. 
I even wrote the mother of all Hyperion config files to map the led positions to the screen and had ultra low definition TV on it.

**Comment by giovanne123** [comment]
Hi penfold42,
you wrote that you have 3 instances on the pi running. I'm interested in the two which are driving the ESP8266.
Which firmware is on the ESP?
I think it is in AP mode, right?
Do you have to compile two different configured firmwares (with different IPs) to the ESP?
Is the Pi connecting via Wifi to the ESP directly? Pi not connected to your local network?

How can I handle this, if 
- my Pi is only connected to my local network via the router in subnet 192.168.0.x (no wifi on the Pi)
- the ESP are in AP mode with different sub 192.168.1.*

What is the best way? 

Thanks for telling me the right direction ;-)
giovanne

**Comment by penfold42** [comment]
My ESPs are all stations, not AP and use DHCP to get separate IP addresses from my local network.

**Comment by giovanne123** [comment]
Great, can you please link me to your firmware you are using.
Or can you send me the firmware/sources that I am able to flash them to my ESPs.
Station fw is where I am looking for ;-)

**Comment by penfold42** [comment]
Here is the firmware I've been using on the ESP.
https://github.com/penfold42/stuff/blob/master/ESP-udp-neo.ino

You'll need arduino IDE and the ESP8266 board configured.

I cant send you a prebuilt binary because it has the WiFi SSID and password hard coded in it and I havent yet gotten around to adding a config GUI.

I need to clean up the pull request - It wont merge at the moment due to some other merged pull requests.

**Comment by jebos** [comment]
Hi, since this really fix my case i will try to have a look at it and will help to geht this in.

320 LEDs and two raspberry PiS. (One rp1 and one rp2)

https://m.youtube.com/watch?v=Wf1oFt-nhc8

Here its in action. Thanks

**Comment by penfold42** [comment]
Hey ! That looks cool.

Thanks for the offer - I'll sort it out cos I need to get my head around git!

**Comment by tpmodding** [comment]
hey @penfold42 ,

do you use your esp without arduino? if yes which pin i have to connect to the ws2812b?

i want to use my esp-01 with the forwarder from @redPanther, but never had a esp before.

i compiled the version from redpanther with the forwarder and added the UDP protocoll, whats the next step?

use your https://github.com/penfold42/stuff/blob/master/ESP-udp-neo.ino for esp and just define the number of leds and the wifi ssid/pw? but dont know which pin to use...and how to the edit the config for udp?

		   			"name"       : "MyPi",
					"type"       : "udp",
					"output"     : "esp201-0.home:2392", "protocol" : 2, "maxpacket" : 1450,
					"rate"       : 1000000,
					"colorOrder" : "rgb"
				},

but dont know how to config the output part. could you help me?

thanks!

**Comment by penfold42** [comment]
I use the esp8266 with native arduino support - no additional hardware.
This defines the gpio number:
#define NeoPin 2 

The output in hyperion config is the host name/ip address and port number of your esp8266

I will try to consolidate some better doco in a wiki page rather than in the source !

**Comment by redPanther** [comment]
Hi @penfold42 did you see my efforts in forwarding proto messages in issue #486 ? 

This is exactly for the issue you described in the first post. The persons who tested my proto json forwarder said that it worked good. Perhaps this could work for you too.

I send images through the net. This is the esiest way to get correct image to led color mapping.

**Comment by penfold42** [comment]
Yep, I saw it. it looks good.

In my case, the LED device is a cheap esp8266 wifi module so UDP led data is more appropriate for this use case.

I guess we need to document all the "distributed" options and architecture options hyperion now supports.

**Comment by tpmodding** [comment]
new forwarder will be merged the next days, than you can use a server/client hyperion.
