### ISSUE TITLE
Openelec: Syntax Error in hyperion-remote

### ISSUE THREAD

**Issue by simonszu** [tvdzwan/hyperion#446]
Hi,

i am trying to install hyperion on my OpenELEC HTPC (non-raspi, it is an Intel Pentium CPU built in 2014). It should access an arduino with modified adalight script and WS2811 LEDs. 
So far, i have a problem with hyperion remote. I start hyperion with `/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &` as mentioned [here](https://github.com/tvdzwan/hyperion/wiki/Installation-on-RPi-with-OpenELEC). This seems to work as the output of `ps` states. But then, to test if hyperion is working correctly, i execute the hyperion-remote command from the wiki page above. And i get an error:
```
# /storage/hyperion/bin/hyperion-remote.sh  --effect "Rainbow swirl fast" --duration 3000
/storage/hyperion/bin/hyperion-remote: line 1: syntax error: unexpected word (expecting ")")
```

Which also results in a complete crash of the hyperion daemon like ps states. What is wrong here?

**Comment by simonszu** [comment]
No idea? Sad one. So i will use boblight instead.

**Comment by Megachip** [comment]
Copy&Paste error? Did you try other quotations?

**Comment by simonszu** [comment]
I Copy&Pasted directly out of the wiki. 
I am not sure about this error, because the .sh-scripts show no closing brackets, and the rest are compiled binaries - and how can hyperion crash when you use the wrong CLI flags?

However, i checked my setup with boblight to have some quick results - will check with hyperion tomorrow, since boblight has some weird saturated colors.

**Comment by simonszu** [comment]
So i have reinstalled hyperion, works now.
