### ISSUE TITLE
x32 release seems to contain 64b binaries

### ISSUE THREAD

**Issue by maxenced** [tvdzwan/hyperion#449]
Hi,

just trying to get a working version on wetek box running openelec 6 : 

```
wget https://github.com/tvdzwan/hyperion/raw/master/deploy/hyperion_x32.tar.gz
tar xvzf hyperion_x32.tar.gz
file hyperion/bin/hyperiond
hyperion/bin/hyperiond: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=5dd1095f2963a46ff5b21ba386f6b9bafea8ac11, not stripped
```

It looks like the x32 part in  ./bin/create_all_releases.sh is missing the -DCMAKE_TOOLCHAIN_FILE="../Toolchain-x32.cmake" part.

**Comment by brindosch** [comment]
@maxenced 
There is a Wetek release. Could you test it?
For this, could you test my install/update script? That would be great. You were the first wetek user i found after a long time ;)
#493 

If this image also won´t work, please open a pull request with the fix.
Thank you!

**Comment by brindosch** [comment]
I tested this with the toolchain too, nothing changed on "file hyperiond".
We will have a deeper look on this.
/closed
