### ISSUE TITLE
[Question] Turn off hdmi then leds go blue

### ISSUE THREAD

**Issue by pete111** [tvdzwan/hyperion#45]
Hello, I found out when I turn off my hdmi device connected to leds hyperion detects whole blue screen and changes color of leds to blue (that's correct because when any hdmi device is turned off blue is probably default screen when no input signal is present). How could I set hyperion to turn off all leds in this case and not blue? Thank you.

**Comment by Sp4rtan** [comment]
For me the threshold doesnt work completely.
Every now and then the LEDs turn on (blue) despite the threshold.

As Im using WS2812b with arduino I use a GPIO Pin of it to measure the Voltange of an USB Port from my TV and wrote 2 lines of code into the Arduino Sketch.

When the TV is turned off, the USB voltage drops low and I stop the LED output from the arduino.
For me that works perfect.

Next step is to write a python script on the raspberry that measures the USB voltage and start and stops the hyperion service depending on the voltage signal :) 👍

**Comment by redPanther** [comment]
problem is we talking about analog signals. When the (blue) video signal gets a distortion, then it is recognized as signal and leds will turn on.
The method how we get the video signal splitter -> converter -> grabber is more a hack than a real solution.
Our way of evaluating the input video signal is more or less reliable and heavily depends on the quality of hardware components.
The safest way to prevent leds from turning on accidently is a switchable power socket for power supply of the leds. This works in almost every setup. BTW there are usb controlled power sockets out there (https://www.amazon.de/EnerGenie-PCW-MS2G-Steckdosenleiste-Master-Slave-%C3%9Cberspannungsschutz/dp/B004FVAFJ6)
connect usb plug with e.g. your TV or pi and the leds power supply with this power socket. The led power will be switched with the power state of usb plug - no arduino tinkering needed.
