### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by hyzami** [tvdzwan/hyperion#450]
Hello 
Any idea how to manage following behaviour. 
I want leave my Kodi all time running due to TV backend. But I don't want what my led is all time working. 

So is any way how to switch off LED in Kodi dim mode? I doesn't mean to stop Hyperion service but just switch off led. So I can still any-time use wonderful android app to control lights if I want make cosy atmosphere :) 

Forward thanks for any hint.

Kind regards
Michael

**Comment by p1n9** [comment]
In the Kodi plugin you have to set the priority, admit you use the priority 1000.
To turn off yours leds you can launch another process with highter priority, like 999.
```hyperion-remote -c black -p 999````
It will turn off all your leds.
After that you can still play with hyperion while you use the right priority order (all priority below 999 will be displayed)

**Comment by hyzami** [comment]
Thanks a lot for quick hint!!! Now I must found how to run script in Kodi on din off / on event.

**Comment by v0d0r** [comment]
Hyzami not sure if this will help you but I have a cron that checks if my kodi is idle if it is then I execute the same as p1n9 suggested. (btw thanks p1n9 for giving me the idea)

See my issue for more details.  https://github.com/tvdzwan/hyperion/issues/452

**Comment by p1n9** [comment]
Give a try to this plugin : https://github.com/pilluli/service.xbmc.callbacks
(I didn't tested it)

**Comment by ntim** [comment]
For philips hue system I implemented a feature which switches off all lights if no new color was received for 3 sec (does not work with smoothing). This feature could be implemented generically in LedDevice but requires QT.

**Comment by brindosch** [comment]
I added this as feature request for kodi hyperion addon

Closed 
Thank you
