### ISSUE TITLE
Lightpack + Hyperion Not Powering LED's

### ISSUE THREAD

**Issue by garfty** [tvdzwan/hyperion#453]
Hi,

I've recently setup Hyperion on my Raspberry Pi Model B+, everything appears to be set up correctly, the Lightpack is plugged in to the Pi, and the blue strip on the box is lit up.

If I try to run the comand:

```shell
/storage/hyperion//bin/hyperion-remote.sh --priority 50 --color red --duration 5000
```

I get the following output:

```shell
Connected to localhost:19444
Set color to 255 0 0
```

This is my config:

```json
"device" :
	{
		"name"       : "MyPi",
		"type"       : "lightpack",
		"output"     : "95330313939351B0B1A1",
		"rate"       : 250000,
		"colorOrder" : "rgb"
	},
```

However, none of the LED's actually light up. Just wondering if anyone else has had this problem?

**Comment by penfold42** [comment]
how did you install ?

The install script downloads a really old build.

**Comment by garfty** [comment]
I installed by running:

```shell
curl -L --output install_hyperion.sh --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
sh ./install_hyperion.sh
```

However, I've just formatted my device and installed *Rasbian*. What would be the best method to install?

**Comment by penfold42** [comment]
#436

**Comment by brindosch** [comment]
Should be solved. If not just open a new one.

Thank you

Closed
