### ISSUE TITLE
Possible to provide OS X binaries?

### ISSUE THREAD

**Issue by cribskip** [tvdzwan/hyperion#457]
Hi,

I really enjoy Hyperion on my Raspberry with a adalight. Really delightful!

However, sometimes I like to watch movies with an attached Macbook as some movies just do stream ;)
Then it'd be great if I could simply change the wiring to the Macbook and run Hyperion from there.

I saw there are some build instructions. As my Mac is already really cluttered I don't like getting Xcode with like 2 GB space requirements.

So I'd pledge for a binary release for OS X, thank you.

Regards,
Sascha

**Comment by brindosch** [comment]
@cribskip 
I am sure you need a mac to compile. So i could not help you, sorry
Have you compiled your own version?

**Comment by brindosch** [comment]
I added your wish to the wishlist

Closed
