### ISSUE TITLE
Switching to QT5 results in CMake error

### ISSUE THREAD

**Issue by ntim** [tvdzwan/hyperion#459]
On my OSMC (most current version) I have QT4 and QT5, switching to QT5 results in the following CMake error: 

>CMake Error at test/dispmanx2png/CMakeLists.txt:9 (include):
>  include called with wrong number of arguments.  include() only takes one
>  file.

Seems the variable ${QT_USE_FILE} is empty. Starting from scratch and directly enabling QT5 does not work either. 

OSMC has gcc 4.9.2 and cmake 3.0.2.

**Comment by brindosch** [comment]
@ntim 
So this could be closed?

**Comment by ntim** [comment]
Will check again later.

**Comment by ntim** [comment]
Fixd in 0e586ed
