### ISSUE TITLE
Strange rate issue with Lightberry

### ISSUE THREAD

**Issue by Fire69** [tvdzwan/hyperion#46]
Hi,
(me again, I'm sorry :-/ )

I'm having kind of a strange issue with my Lightberry.
When I use the config-file provided on the Lightberry-site, my leds flash horribly.
I'll try to make a long story a little shorter:
The asked my to test with an image they created to exclude software issues.  I still had the problem.
They sent me a new convertor-box thinking it was broken.
I reinstalled Raspbmc and Hyperion to my SD (instead of their image) and that seemed to work OK.
But then I remembered I had not replaced the default config-file after reinstalling Hyperion.
I replaced the file with the Lightberry-version and Bam!  Flashing started again...
After some trial and error I found that the rate of 1000000 is causing the problem.
When I set it to 250000 (Hyperion-default) it works pretty much OK (just a couple of flashes over an entire movie).
So I contacted them and they told me they always use 1000000 and never had problems with it. They asked to contact you about it...

What makes it even stranger is that when I first had the Lightberry it worked ok.
Then it gradually started getting worse.
First it was like this (when playing a movie):
https://www.youtube.com/watch?v=YhfGeEPHmvg
Then it got like this (static color set with android):
https://www.youtube.com/watch?v=YhfGeEPHmvg

Any ideas?

Thanks!

**Comment by tpmodding** [comment]
@Fire69 can be closed?

**Comment by Fire69** [comment]
Yep, everything has been running perfectly here! :)

I'd like to take the opportunity to thank you guys for this great software, I still enjoy it every day! :+1:

**Comment by tpmodding** [comment]
@Fire69 could you close it? i cant :) thx
