### ISSUE TITLE
Artnet Support possible?

### ISSUE THREAD

**Issue by giovanne123** [tvdzwan/hyperion#463]
Is it possible to add "artnet" support in hyperion? So that the data is send to network in artnet-protocol?
[maybe also "tpm2net" support]

Why: For receiving the data there are two ESP8266-01 Wifi module running, connected to my local network and receiving the data with the flashed firmware. Currently I have ws2801 LED strips connected to the ESP-01.

Something similiar was already started by someone. Sorry it is in german (http://www.forum-raspberrypi.de/Thread-ambi-tv-ambi-tv-selberbauen-grosses-beleuchtungsprojekt?pid=170413#pid170413), but he doesn't answer to my questions :-(

**Comment by redPanther** [comment]
In short: yes it's possible - but have to be implemented.

Sending from hyperion to your Led-Strips via network is quite easy. you have to implement a new LedDevice for artnet. There are others "LedDevices" that use network:
- philipsHue (http)
- FadeCandy (tcp)
- Tinkerforge (tcp via external library)
- LedDeviceUDP (udp) (pending pull request #444 )

Art-Net is UDP based, so LedDeviceUDP could be a good start. Perhaps in a longrun it make sense to implement a UDP base class to avoid code duplication.
(links to spec: https://en.wikipedia.org/wiki/Art-Net )

There are other implementations for artnet where you can look how it works:
https://github.com/hobbyquaker/artnet (js)
https://github.com/Gregwar/ArtNet-Console (c++/Qt)
https://github.com/OpenLightingProject/libartnet

A possibility could be to use "libartnet" as external lib as it is done in TinkerForge LedDevice.
usage of libartnet is demonstrated in "ArtNet-Console" (yeah and it is qt based like hyperion - what a luck)

I think the main problem is the configuration. You have to manage the translation from hyperion led-data stream to art-net address and channel of your fixtures. In the forum thread you mentioned "cert" solved the problem by extending the hyperion config with lots of parameters. I can imagine that is not the best way. I think having a special artnet config could be a better idea. In hyperion config you can link to the artnet config (perhaps the output param could be used).

The cool thing having Artnet support is you can build a "stage ambi light". Imagine you project your movie to a big screen and illuminate the sourrounding with some stage fixtures. 

BTW I'm interested in the other way around. I want hyperion act as artnet-node. For the first run quick and dirty as effect and later on as separate application for the proto-buf interface (like hyperion-x11). Then I can control my hyperion led installation via OLC and other artnet/dmx controllers.

**Comment by giovanne123** [comment]
Thanks for the answer. I will have a look to the infos. But implementing it should be to hard for me :-( 

Currently for testing I us OpenLightingProjekt (ola) on a Pi because it looks quite good and is directly running with my ESP8266-01 (art-net) nodes ;-)
Ola sends the art-net data (defined output device) to the ESP/Led-Strips/Network. That works great. Maybe there is a workaround for me with ola possible. Defining an input device in ola which gets (redirected) the data from hyperion in some way, but like you have already told, the configuration/translation between both is the hardest part...

**Comment by redPanther** [comment]
I see ola can send/receive OPC (openpixel protocol) messages. I recently implemented the fadecandy driver.  Communication with fadecandy is done via opc. So I guess you can setup hyperion to send to ola via fadecandy driver.

I do something similar, but instead of ola I use the official fadcandy server ... performance on my rpi1  is quite good.

**Comment by penfold42** [comment]
Which esp8266 code are you running ?

I found the quickest way to implement the network receiver is as an "effect". I've already written one to match my UDP led device that's the in the pull request I need to clean up.

**Comment by giovanne123** [comment]
@redPanther, thanks for the info. Sound interesting and I will try it. Let me know about your findings.

@penfold42, currently I use EspLightNode (v0.2), because I was looking for an Client/Station firmware instead of AP mode firmware. And I EspLightNode you can configure in the running system via Website which mode to use (beside wifi params, protocol (art-net or tpm2net - tpm2net isn't working for me at the moment), LED type, ...) https://github.com/Frans-Willem/EspLightNode/releases 
Will your UDP/effect solution (pull request) work for the firmware?

**Comment by penfold42** [comment]
No, my UDP led driver and UDP "effect" will not work with that firmware.

Why? probably due to travel, a day job that pays the bills, a family....

I have now

**Comment by giovanne123** [comment]
@redPanther, can you please 
- post an example how the hyperion.conf should look for defining the fadecandy driver/openpixel output? 
- Is your driver already in the current hyperion?
- how do I update already installed hyperion? Call again ./hyperion_install.sh ? 

On OLA site I have set up for testing an universe with OPC (input) to Art-Net (output). Will see if the conversation between both will work ;-)

**Comment by redPanther** [comment]
the device section should look like that:
```
"device" :
	{
		"name"       : "MyPi",
		"type"       : "fadecandy",
		"output"     : "127.0.0.1",
		"port"       : 7890,
		"colorOrder" : "rgb"
	},
```
of course a have to adapt the ip if hyperion and ola didn't run on the same machine and make sure the port is the right one.
The data is send in order of the configured leds ("leds "section). This order should be the same as your artnet addressing on your real leds

the driver is in current hyperion (fix for supporting more than 512 leds is pending). I didn't know if this changes already in precompiled binaries. I never used precompiled binaries and the hyperion_install.sh. I use archlinux on my pi's and the whole installation process in hyperion_install.sh is more or less useless for me. 

compilation the short version (I assume you use the raspbian-ola image):
```
sudo apt-get update
sudo apt-get install git cmake build-essential libQt4-dev libusb-1.0-0-dev python-dev
git clone --recursive https://github.com/tvdzwan/hyperion.git hyperion
cd hyperion
mkdir build
cd build
cmake ..
make
(this will take some tome)
sudo cp ./bin/hyperiond /usr/bin/
sudo cp ./bin/hyperion-remote /usr/bin/

```

more info: https://github.com/tvdzwan/hyperion/blob/master/CompileHowto.txt

ATM I try to build OLA on my system. Unfortunately there is no package/aur in archlinux for ola so I think it will take a while until I have a repeatable good installation process for my system.

**Comment by giovanne123** [comment]
Thanks,
I was already on this config way ;-)
It is in the pre bins. Used mod "install_hyperion.sh" (#436)

my config:
   "device" :
        {
                "name"       : "MyPi",
                "type"       : "fadecandy",
                "output"     : "127.0.0.1",
                "port"       : 9091,
                "colorOrder" : "rgb"
        },
and after starting hyperion:
...
Initializing Python interpreter
connecting to 127.0.0.1 9091
connected
Hyperion created and initialised
...

But I have to debug, currently can't see something going to OLA, configured like in the attachment.
I think I have to analyse first if hyperion send data... which can OLA receive ...
Do you know some debugging possibilities in the hyperion/fadecandy?

![ola](https://cloud.githubusercontent.com/assets/16689453/12590519/b147d752-c463-11e5-8fe2-f82e680ecee1.JPG)

**Comment by redPanther** [comment]
"color wheel" sends only one time. Perhaps use an effect that sends constantly data like the "rainbow swirl fast". 

Using tcpdump for debugging should be sufficient. You can use wireshark from your desktop too ...

BTW is it possible to select channel 0/broadcast in OLA for OPC? I made fadecandy send on broadcast channel 0. Perhaps it is a good idea to make that available in config.

**Comment by redPanther** [comment]
after quick'n'dirty testing - it works with hyperion + ola via opc.

ola-openpixelcontrol.conf:
```
enabled = true
listen = 127.0.0.1:7890
listen_127.0.0.1:7890_channel = 0
```
I let the port on 7890, because it is default by fadecandy server

+ my hyperion config above

the ola config:
![bildschirmfoto1](https://cloud.githubusercontent.com/assets/6893049/12603699/4610e030-c4b5-11e5-88b8-55c1d751bf62.jpg)

with ola+artnet I can't help yet, because I havn't any device yet. But after this going so well, I will try my arduino mega + ethernet shield dmx shield for my dmx fixtures :-)

**Comment by giovanne123** [comment]
@redPanther,
you are so great !!! ;-) It is working for me.
I think it was a question of config.

Now it is working from hyperion -> ola -> art-net node (ESP8266-01)

**Comment by redPanther** [comment]
cool :-) in my pending pull request i added the ability to change the opc channel in hyperion config. That makes it more flexible. 

After we found this solution I think it's not a good idea to add artnet/dmx to hyperion. Dealing with DMX in hyperion means dealing with universes, channels, fixture specific mappings ... 
If somebody needs pro/stage-grade protocols the OLA way is the best. There you can handle all that stuff and hyperion can send his pixelstream to ola ..

Last question, which esp board do you use? did you have a link for me? (i have some ikea led strips that wait for wifi-ing)

I think this issue can be closed.

**Comment by giovanne123** [comment]
at the moment from here because can't way so long (germany): http://www.ebay.de/itm/181981185025
some from china like this are also on the way: http://de.aliexpress.com/item/1pcs-ESP8266-remote-serial-Port-WIFI-wireless-module-through-walls-best/32280714838.html?isOrigTitle=true

**Comment by giovanne123** [comment]
From my side closed. 
Using hyperion with fadecandy/OPC driver -> OLA -> ART-NET is working well ;-)
