### ISSUE TITLE
Cuboxi & adalightapa102

### ISSUE THREAD

**Issue by tomaszszczerba** [tvdzwan/hyperion#464]
Hi,

I tried newest release from hyperion for cubox-i and it seams to miss adalightapa102 leddevice. Could it be a case? Is there anything specific to the raspberry pi that would prevent this leddevice to work with cubox-i? I've looked at the code and I don't see that.

Here is the output that I'm getting:
OpenELEC:~/.config # ../hyperion/bin/hyperiond.sh hyperion.config.json
Application build time: Sep  9 2015 21:54:50
QCoreApplication initialised
Selected configuration file: hyperion.config.json
ColorTransform 'leds' => [0; 259]
Device configuration:
{
        "colorOrder" : "bgr",
        "name" : "MyPi",
        "output" : "/dev/ttyACM0",
        "rate" : 500000,
        "type" : "adalightapa102"
}

Unable to create device adalightapa102
Black border threshold set to 0.05 (13)
Creating linear smoothing
Created linear-smoothing(interval_ms=50;settlingTime_ms=100;updateDelay=0
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Effect loaded: X-Mas
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Boot sequence(Rainbow swirl fast) created and started
Framebuffer opened with resolution: 1920x1080@32bit
Framebuffer grabber created and started
Json server created and started on port 19444
Proto server created and started on port 19445
Segmentation fault
OpenELEC:~/.config #

Thank you in advance!

Tomek.

**Comment by eXsio** [comment]
Hi

I'm having the same problem: OSMC + hyperion master. Could you please advise what to do?

**Comment by brindosch** [comment]
@tomaszszczerba 
> I tried newest release from hyperion for cubox-i
Which one? hyperion_imx6.tar.gz?

**Comment by tomaszszczerba** [comment]
I used hyperion installator (a standard one). It has a logic that will install tar.gz that you mentioned on cuboxi.

**Comment by brindosch** [comment]
Try this one to update and report back
https://github.com/tvdzwan/hyperion/issues/493

Thank you

**Comment by brindosch** [comment]
@tomaszszczerba 
Any news on this?

**Comment by tomaszszczerba** [comment]
yes, I got my cuboxi a few days ago, I'll check on that.

Right now I tested your script on rpi3 (but you know that one works). Sorry about the wetek - I don't have this one anymore, but will try to test on my friends.

**Comment by brindosch** [comment]
I tested your problem on rpi3
i don´t get the `Unable to create device adalightapa102`
message in the log. So i am sure it is working with the latest images.
Also i added the AdalightAPA102 device to HyperCon.
Will be published soon

**Comment by brindosch** [comment]
Is it ok if i close this?

**Comment by tomaszszczerba** [comment]
Yes, I did that too and works beautifully. Thank you for this!
