### ISSUE TITLE
Hyperion maxing out cpu on Pi2

### ISSUE THREAD

**Issue by theMPstig** [tvdzwan/hyperion#465]
Hi,

first I have to say I am absolute newbie so please forgive any dumb questions or missing infos. I recently build a Ambilight with Pi2, 186 Apa102 LEDs and using this on raspian Jesse, controlled via atmolight plugin from Mediaportal.

I am currently seeing a high cpu load for my Pi2. After a while (sometimes an hour, sometimes only a few minutes) one core is at 100% CPU load, and temperatures and mem usage are increasing too. See attached pic of htop.
![clipboard03](https://cloud.githubusercontent.com/assets/16834237/12506574/4bb395fa-c0f0-11e5-87f1-7811916b2b94.jpg)

strace shows the following:
<code>
poll([{fd=3, events=POLLIN}, {fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=7, events=POLLIN}], 4, 0) = 2 ([{fd=3, revents=POLLIN}, {fd=7, revents=POLLIN}])
read(3, "\2\0\0\0\0\0\0\0", 16)         = 8
ioctl(7, FIONREAD, [911458])            = 0
mmap2(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x577b1000
read(7, "\0\0000\31\10\2Z\224`\0102\20@\30@\"\200`1 \0223\"\21,\30\0100\36\6\22\v"..., 911458) = 911458
mmap2(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x576b0000
mremap(0x577b1000, 1052672, 69632, MREMAP_MAYMOVE) = 0x577b1000
munmap(0x577b1000, 69632)               = 0
mremap(0x578b2000, 460644352, 536875008, MREMAP_MAYMOVE) = 0x376af000
munmap(0x576b0000, 1052672)             = 0
gettimeofday({1453452189, 441913}, NULL) = 0
gettimeofday({1453452189, 442405}, NULL) = 0
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
write(7, "\0\0\0\2\10\1", 6)            = 6
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
mmap2(NULL, 461545472, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x577d6000
munmap(0x376af000, 536875008)           = 0
poll([{fd=3, events=POLLIN}, {fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=7, events=POLLIN}], 4, 0) = 2 ([{fd=3, revents=POLLIN}, {fd=7, revents=POLLIN}])
read(3, "\2\0\0\0\0\0\0\0", 16)         = 8
ioctl(7, FIONREAD, [911447])            = 0
mmap2(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x576d5000
read(7, "\0\0000\31\10\2Z\224`\0102\20@\30@\"\200`'\32!%\31\31&\32\35!\31\31%\""..., 911447) = 911447
mmap2(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x575d4000
mremap(0x576d5000, 1052672, 69632, MREMAP_MAYMOVE) = 0x576d5000
munmap(0x576d5000, 69632)               = 0
mremap(0x577d6000, 461545472, 536875008, MREMAP_MAYMOVE) = 0x375d3000
munmap(0x575d4000, 1052672)             = 0
gettimeofday({1453452190, 928819}, NULL) = 0
gettimeofday({1453452190, 929478}, NULL) = 0
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
write(7, "\0\0\0\2\10\1", 6)            = 6
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
mmap2(NULL, 462442496, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x576fb000
munmap(0x375d3000, 536875008)           = 0
poll([{fd=3, events=POLLIN}, {fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=7, events=POLLIN}], 4, 0) = 2 ([{fd=3, revents=POLLIN}, {fd=7, revents=POLLIN}])
read(3, "\2\0\0\0\0\0\0\0", 16)         = 8
ioctl(7, FIONREAD, [1046956])           = 0
mmap2(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x575fa000
read(7, "(\377\377\377\377\377\377\377\377\377\1\0\0000\31\10\2Z\224`\0102\20@\30@\"\200`E1\""..., 1046956) = 1046956
mmap2(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x574f9000
mremap(0x574f9000, 1052672, 2101248, MREMAP_MAYMOVE) = 0x572f8000
mremap(0x575fa000, 1052672, 69632, MREMAP_MAYMOVE) = 0x575fa000
munmap(0x575fa000, 69632)               = 0
mremap(0x572f8000, 2101248, 1052672, MREMAP_MAYMOVE) = 0x572f8000
mremap(0x576fb000, 462442496, 536875008, MREMAP_MAYMOVE) = 0x372f7000
munmap(0x572f8000, 1052672)             = 0
gettimeofday({1453452192, 640949}, NULL) = 0
gettimeofday({1453452192, 641449}, NULL) = 0
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
write(7, "\0\0\0\2\10\1", 6)            = 6
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
mmap2(NULL, 463478784, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x575fe000
munmap(0x372f7000, 536875008)           = 0
poll([{fd=3, events=POLLIN}, {fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=7, events=POLLIN}], 4, 0) = 2 ([{fd=3, revents=POLLIN}, {fd=7, revents=POLLIN}])
read(3, "\2\0\0\0\0\0\0\0", 16)         = 8
ioctl(7, FIONREAD, [3395655])           = 0
mmap2(NULL, 4198400, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x571fd000
read(7, "\0\0000\31\10\2Z\224`\0102\20@\30@\"\200`\21\24\30!\33\37 \27\35\36\31\33\32\30"..., 3395655) = 3395655
mmap2(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x570fc000
mremap(0x570fc000, 1052672, 2101248, MREMAP_MAYMOVE) = 0x56efb000
mremap(0x56efb000, 2101248, 4198400, MREMAP_MAYMOVE) = 0x56afa000
mremap(0x571fd000, 4198400, 69632, MREMAP_MAYMOVE) = 0x571fd000
munmap(0x571fd000, 69632)               = 0
mremap(0x575fe000, 463478784, 536875008, MREMAP_MAYMOVE) = 0x36af9000
munmap(0x56afa000, 4198400)             = 0
gettimeofday({1453452201, 111827}, NULL) = 0
gettimeofday({1453452201, 112419}, NULL) = 0
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
write(7, "\0\0\0\2\10\1", 6)            = 6
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
mmap2(NULL, 466862080, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x572c4000
????( <unfinished ...>
+++ killed by SIGKILL +++
</code>

Do you have any pointer for me how to solve this?

**Comment by theMPstig** [comment]
Ok, seems to be settled. I've raised the bitrate from 250.000 to 750.000. No problems since then...

**Comment by smileyn64** [comment]
Hi,
Check also the resolution of the frame grabber, if you have changed to a bigger size than 64x64 it will consume more CPU/MEM.

**Comment by theMPstig** [comment]
I haven't even enabled framegrabber. But as said, raising the bitrate did the trick. Tho I still think this is a bug, shouldn't max out CPU if bitrate is too low.

**Comment by tpmodding** [comment]
@theMPstig can it be closed?
