### ISSUE TITLE
hyperion on Raspberry pi 2 with vc4 raspbian build

### ISSUE THREAD

**Issue by alexpro** [tvdzwan/hyperion#467]
Good time of the day.
My English is not very good, excuse me if I said something wrong.

I using LED strip ws2811b with to Arduino board (tested with nano and uno), connected to my Raspberry pi2 via /dev/ttyUSB0 (ch341).

I added vc4 driver for hardware acceleration to raspbian by using project vc4-buildbot (gohai/vc4-buildbot on github).
Installed hyperion using two ways, by install_hyperion.sh and by manually building. hyperiond seems to hang after loading, leds are lighting but like a static rainbow. I don't see active data exchange, and if I stop hyperion service, hyperiond remaining in processes as zombie defunct.
With default raspbian image all works pretty well, above problem appears only after I add vc4 driver.

vc4-buildbot rebuilds X server and mesa and installs them into /usr/local instead of /usr. Also, rebuilds kernel and modules.
Can you suggest me what could possibly goes wrong? Maybe I should build hyperion by some other way or maybe something is missing? Is there a way to enable debug log or something like that?
Thanks in advance.

**Comment by brindosch** [comment]
I am sorry but we can´t help you. And no other one left a feedback so i would close it.
Thank you
