### ISSUE TITLE
hyperion video grabber fushicai flashes sometime

### ISSUE THREAD

**Issue by keshav2609** [tvdzwan/hyperion#471]
Hello,

I just setup Raspilight with Raspberry Pi, WS2801 LED ( 92), fushicai video grabber, Raspbian. IT WORKS LIKE CHARM THANKING YOU. 
BUT
I am having a strange problem, everything is working perfectly, meanwhile, sometime there is a kind of flash can you help please? Is this a known bug or a something to do with my configs?

Not all LED flashes there is one or two which flashes intensely it's very annoying nothing to do with the image of the tv.

Thanks for your help.

**Comment by penfold42** [comment]
So they have issues of you are using an effect rather than capturing video ?

**Comment by keshav2609** [comment]
Hello thanks for your answer it's only when i'm capturing image from the TV

**Comment by keshav2609** [comment]
anyone :(

**Comment by tociek** [comment]
Try different (better) power supply for the leds. You can also try different version of the system as sometimes they change firmware in a way that it impacts signal levels on gpio pins.

**Comment by redPanther** [comment]
When I used fushicai grabber the captured video signal was a bit noisy. I had 2 thin horizontal green strips in the upper screen area. That video noise created flickering leds.
I used raspbian and opened the video device ( /dev/video0  ) with mplayer to see live video from the grabber - and then I saw the bad video quality. Things got a bit  better when I used better and shorter composite video cable. 

Perhaps your captured video generate the noise?

**Comment by keshav2609** [comment]
Hello i'd already tried raspbian it flashes even more ! Openelec 6  seems more stable and flashes almost disappered but still present sometime... Otherwise my captured image is really clear with fushicai video grabber don't think it's the grabber i'll probably add one more ground and the end of the LED strip

**Comment by tociek** [comment]
That sounds like power supply's fault

**Comment by redPanther** [comment]
it's always a good idea to connect ground and power to both sites of the stripe. 

Another possibillity are loose contacts / bad solder junctions.

**Comment by AlexBGoode** [comment]
Okay, let me share my experience

First of all - all grounds of all components should be interconnected! I mean the ground of PI, LEDs and Arduino is used = all should have the common ground. I had funny effects of flickering until I realized that rule, which is a kind of  basis for electricity

Secondly, yes, you'd better to provide LED strip with a power at both sides and ideally even additionally every approx. one meter of LED (for example I have more that 200 LEDs in my strip so I had to inject the power into the LED strip at every corner of my TV)

And regarding green lines of the grabber - if you have few if doesn't influence really - there are few parameters to play with if you really want to get rid of those green lines but it doesn't worth - hyperion approximate the image anyway

**Comment by keshav2609** [comment]
Hello, thanks for your answer I was thinking to do the exact same thing powering the LED at both end.

I am just waiting for the weekend to do the necessary soldering ( Because i'm a father it is not so easy to do soldering with kids nearby :-) ). I have one last question do you think a 5V 3A is enough for 92 LEDS ( 3 meter  WS2801 led strip) because I tried a 5V 10 A the wires heats a lot and no LED light up.

My architecture is as follow I have a USB HUB ( 5V 10A) which powers the PI, the HDMI splitter and the HDMI AV converter. The fushicai video grabber is connected to the pi.

The LEDs uses a 5V 3A power supply seperately. Do you think it's a good configuration?

Thanks

**Comment by polykoma** [comment]
It simple as math.
Every pixel needs 60 mA total .  so 150x 60mA  will be 9A total for the leds only

please use a 20-30% bigger power supply as needed.

**Comment by emms007** [comment]
Also had the issue with WS2801 controlled remotely with a [ESP8266 + TPM.Net protocol] combo. 

Pushing direct extra power connections onto the led line helped. I added one at the very end.. didn't do much. Then added one half-way and it is now OK.  This was required for  51 leds.

Thanks for the hint!

**Comment by AlexBGoode** [comment]
That's my way to go! :-)
![Principle schema](http://forum.cxem.net/uploads/monthly_10_2015/post-195092-0-08265100-1446103286.jpg)
![Physical topology](http://forum.cxem.net/uploads/monthly_10_2015/post-195092-0-60421600-1446115877.jpg)

**Comment by AlexBGoode** [comment]
And I used the wires like 11AWG with the area about 4 sq. mm to avoid voltage drops and heating!

**Comment by keshav2609** [comment]
nice that's the way I wanna to it ;-) cheers man

**Comment by keshav2609** [comment]
hello i just finished i used your second figure it is just a disaster now it flickers everytime even when using effects help please :-(

**Comment by bouwew** [comment]
Have you used a level-shifter 3.3V-5V between the Pi and the LED-strip? Pi is 3.3V out, the LED-strip expects 5V in. When I build mine (82 leds), I had the same problem. After putting one in, no more flickering LEDS :)
I used the Texas Instruments CD40109. Datasheet here: http://www.ti.com/lit/ds/symlink/cd40109b.pdf

**Comment by keshav2609** [comment]
Hello, thanks for your answer.

No i didn't use a level shifter

Ho to we set it up with RPI2

2016-01-31 10:27 GMT+01:00 bouwew <notifications@github.com>:

**Comment by emms007** [comment]
Did you check the voltage around the leds that are flickering ?
In reference to this thread, maybe the wire you are using cannot carry that Amp load (http://forum.arduino.cc/index.php?topic=211088.0)

**Comment by bouwew** [comment]
Sorry, I don't have a drawing or a picture. I'll describe this pins and connections:
Pinning, see below fig.14 in the datasheet.
Pin 1, 2 and 7: connect to 3.3V pin of Pi GPIO connector (See [](http://www.forum-raspberrypi.de/Thread-hyperion-raspbian-jessie-21-11-15-hyperion-fushicai-grabber-pi-b-b-2-anleitung) scroll down until you find the pictures of the pinning of the Pi and Pi2 GPIO connectors)
Pin 3: connect to Pi MOSI pin
Pin 4: connect to DI input of the LED-strip
Pin 5: connect to CI input of the LED-strip
Pin 6: connect to Pi SCLK pin
Pin 8: connect to Pi Ground pin and to LED powersupply ground lead (black wire)
Pin 16: connect to the +5V of the LED powersupply (red wire)
Others: not connecte

**Comment by keshav2609** [comment]
Hello I am using wires that can carry up to 20A  and I have been checking
power randomly all across the strip there is between 5.4 v and 5.3 v
everywhere. I have been checking the LED with a normal LED controller
everything is working it I guess that it is related with hyperion
Thanks

Did you check the voltage around the leds that are flickering ?
In reference to this thread, maybe the wire you are using cannot carry that
Amp load (http://forum.arduino.cc/index.php?topic=211088.0)

—
Reply to this email directly or view it on GitHub
<https://github.com/tvdzwan/hyperion/issues/471#issuecomment-177471392>.

**Comment by keshav2609** [comment]
Hello
I finished by putting back the 3A power supply for the LED back to original
situation hyperion is working back with couple of flickering sometime
always at the end of the strip I also added also ground at the end of the
strip connected to the pi so now I have 2 ground connected to the pi I
don't really know where the flickerings are coming... :-(

**Comment by redPanther** [comment]
Only a guess, but are you sure that your amount of configured leds matches with the real amount of leds? 
If not, the flickering could be an result of an unconfigured led.

Btw please use sufficent power supply. Every led draw 60 mA maximum. 3A is not enough as mentioned before.

**Comment by keshav2609** [comment]
Hello,

Yes 92 led till now I was using a dc adaptor I am going to buy  a genuine
LED power supply it is cheap I am going to let toi know

Thanks

**Comment by tociek** [comment]
If it's only certain part of the strip that flashes, you most likely have a broken strip (one of the leds/chips messes up the rest). Try removing the first led of the flashing part of the strip.

**Comment by keshav2609** [comment]
Hello,

I don't think it's a broken strip I have been trying with an LED controller
there's no flickering at all thanks anyway

2016-02-01 7:41 GMT+01:00 tociek <notifications@github.com>:

**Comment by bouwew** [comment]
Guys, come on! Too thin wires don't make the LEDs flicker, the light intensity will diminish towards the end of the strip. You power-wiring and your power supply are fine!
As I said, the problem is in the voltages of the DI- and CI-signals. The Pi provides a "1"-level of 3.3V while the LED strip expects a "1"-level of 5V. If the strip is short, this will mostly work, when the strip is long, you will have the flicker-problem. If you want to spend money, I suggest you buy a level-shifter instead, if you don't want to build one yourself you can always look on Ebay, or go here: [https://lightberry.eu/shop/shop/converter-box/]

**Comment by keshav2609** [comment]
Hi,

Thats an interesting suggestion.

Ok i'll buy a level shifter then thanks for your time I let you guys know,
it make more sense

Do you have drawing about how to integrate the level shifter with RPI2?

thanks man

2016-02-01 8:37 GMT+01:00 bouwew <notifications@github.com>:

**Comment by bouwew** [comment]
The one from lightberry.eu (the shop is in Poland) is just "plug and play". The connectors on the unit fit exactly to the one on the LED-strip.

**Comment by redPanther** [comment]
I use this: http://www.exp-tech.de/shields-module/schnittstellen/pololu-logic-level-shifter-4-channel-bidirectional
wiring diagram is also shown there

**Comment by bouwew** [comment]
Nice find! That will work as well, and is much cheaper :)
Keep in mind that you would only need to use two of the "channels": one for Pi MOSC to DI on the LED-strip, 2nd for SCLK to CI.

**Comment by keshav2609** [comment]
thanks lads i just ordered one of those it is very cheap it worth a try

2016-02-01 10:25 GMT+01:00 bouwew <notifications@github.com>:

**Comment by oCanna** [comment]
If you can adjust the volatge at ur 10A power supply, then try to lower it to 4.75V.
Also, to ensure that each led is driven at the same voltage you should connect ground to one side of each stripe and pwr to the other side. No need to connect both ground and power at both sides if a stripe has less than 50-60 leds.

A friend of mine had a similar problem with randomly flickering leds. Lowering the supply voltage was the solution.

**Comment by keshav2609** [comment]
Hello thanks for your answer but this my configuration and I have 92 LED 3m
WS2801 strip

thanks

2016-02-01 16:50 GMT+01:00 oCanna <notifications@github.com>:

**Comment by oCanna** [comment]
A 3m long piece, really? You should cut your strip in smaller segments. 
Then, if you have segments with max. 50 leds it would be enough to connect ground to one and power to the other end of each segment. This wouldensure, that each led is driven at the same voltage.

And if your 10 power supply has the ability to adjust the output voltage,I would lower it to 4.75V (mesured at one of the leds).

**Comment by redPanther** [comment]
@oCanna 3m yes but only 92 leds. This is 30 leds/m - there isn't the need to cut it into pieces. powering from both sides should be enough. 

I'm curios if the level shifter will solve the problem. 

@keshav2609 if you want you can try my "hyperion led simulator". 
If that works we can exclude that the problem is related to hyperion (excluding the WS2801 driver).
That means you have some electrical, WS2801 driver or raspberry issues ...

https://github.com/redPanther/hypersim

on windows:
- get your hyperion config from raspi
- install python3 (not 2!)
- download hypersim
- open src folder and launch "hypersim.py"
- file -> open hyperion ... and search your hyperion.config.json

on raspi:
- change your hyperion.config.json device described on hypersim page (fadecandy driver ...) and set as output your ip address of the computer that runs hypersim (the windows machine)
- restart hyperion
 
- activate effects/ambilight as usual
- now you should see your "virtual leds" blinking 
-> watch out for flickering ...

**Comment by polykoma** [comment]
I got 144 leds running (means 3+ meters) flawless powered from only 1 side. But powering it from at least 2 ends is the wise way. If you use 60led/m i recommend 3+ inputs

**Comment by keshav2609** [comment]
Hello guys,

I just received the level shifter  i'll you know if it works tomorrow or
this weekend.

I'll probably have a look of hypersim l'm à linux system administrator  I'm
curious about your hypersim :-)

**Comment by keshav2609** [comment]
Hello,

The Level Shifter solved the problem!!!. There no flickering at all... :-)

I can't understand there's like hundreds of tutorials out there but no one suggest to use a Level Shifter. 

Thank you everyone for your times trying to help me.

**Comment by bouwew** [comment]
Glad to read that, and, I was exactly wondering the same :)
Enjoy your flicker-free ambilight!

**Comment by keshav2609** [comment]
Thanks to you
