### ISSUE TITLE
WS2812B LEDs not working with Wheezy-2013-09-25

### ISSUE THREAD

**Issue by michaelleuker** [tvdzwan/hyperion#472]
Hello!
I own a 4-channel STK1160 video grabber and therefore have to use an old version of Raspbian. The Grabber itself works perfectly, but the LEDs are not working. When I do upgrade with "sudo apt-get update && apt-get upgrade" the LEDs start working immediately, but because of the known driver issue with the STK1160 I can't grab any video signal.

So what could possibly be missing in my version of Wheezy that I can't get the LEDs working? I am deeply greatful for every hint or help. Thank you!

**Comment by penfold42** [comment]
Is it running on a pi ? 1 or 2 ?

How did you install Hyperion ?

The install script references a really old Hyperion build.

**Comment by redPanther** [comment]
you could use an arduino or other micro controller via usb and use gpio from the controller. In issue #447 you find some hints for using arduino with hyperion over adalight protocol. Nice thing is that driving ws2812 strips from microcontroller is more reliable than driving it from raspi, because those strips have one-wire protocol with strict timing.

**Comment by michaelleuker** [comment]
@penfold42: I am running a Pi 1 B. I tried installing it via wget and ran the install script. How do I install a newer build?

@redPanther: I've heard of that solution before, but the LEDs are working nicely with  Rasbian Jessie for example... effect and everything via hyperion-remote.

**Comment by penfold42** [comment]
#436 describes how to fix the install.sh to get a more recent build

**Comment by michaelleuker** [comment]
Thank you, I appreciate your help. Unfortunately, it seems like i am to new to get the new install files. May I ask you to provide the exact commands.

**Comment by tpmodding** [comment]
can you paste us the complete ouput? and your config maybe (pls post your config on pastebin.com and give us the pastebin-url)

**Comment by brindosch** [comment]
@michaelleuker 
Any news?
