### ISSUE TITLE
SPI Speed instability or Rpi1 + Hyperion

### ISSUE THREAD

**Issue by penfold42** [tvdzwan/hyperion#473]
https://discourse.osmc.tv/t/spi-speed-instability-or-rpi1-hyperion/12581/3

Hi all,

I'm using a recent build of Hyperion on a RPi 1 configured to use SPI and WS2801 type.

I'm developing an attiny based converter to take SPI 2801 led data and resend it as ws2812 data.
Using a logic analyzer in seeing the SPI speed change every few seconds from the requested speed (800000) to 2/3 of that speed (533.333) bits per second and back again. It happens with other speeds too
As best I can tell nothing else has spidev0.0 open and Hyperion has no code to change it dynamically.
Kernel bug ?

**Comment by brindosch** [comment]
I could not help you with this but
Are they similar to ws2812B? Hyperion supports that.

**Comment by penfold42** [comment]
I need PWM output so can't use the native direct 2812 support.

My tiny protocol converter works great - I'll post more details when I've cleaned up the code.

The SPI speed changes are concerning me tho. Somethings not right there.

**Comment by tpmodding** [comment]
@penfold42 think you can close this :)
use your other issue :)
https://github.com/tvdzwan/hyperion/issues/516

and dont ask! release it :) maybe someone needs it

**Comment by penfold42** [comment]
This appears to be related to the core clock speed changing.
