### ISSUE TITLE
hyperion addon error

### ISSUE THREAD

**Issue by lnix1988** [tvdzwan/hyperion#474]
Hello,
I'm confused with hyperion on my intel nuc (not RPi) because of the installation and configuration.

On my Intel NUC runs Openelec with boblight and the amilight lightpack. It works fantastic but I would like to try out hyperion.

First I disabled boblight and installed the addon from the zip file and hyperion via command-line (https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh) 

The installation path was /storage/hyperion/

After the installation of both components I created the config file via HyperCon.jar but I don't know my device. I selected "lightpack" and selected all other settings to default. 

After it I copied the config file to /storage/hyperion/config/ and overwritted the old file but my amilight doesn't work.

If I start a movie I will get an error that it can't find hyperion...

Could you help me?

Thank you.

Regards
lnix

**Comment by lnix1988** [comment]
no idea?

**Comment by tpmodding** [comment]
could you start hyperion with the command line and post your ouput?

**Comment by brindosch** [comment]
@lnix1988 
any news on this?

**Comment by brindosch** [comment]
I will close this, just open a new one, if problems persist

Thank you
