### ISSUE TITLE
update_hyperion.sh osmc rpi

### ISSUE THREAD

**Issue by fape** [tvdzwan/hyperion#476]
Hi!

I found some problem with update_hyperion.sh on osmc, rpi1.
There is no RPI string in the /proc/cpuinfo

> osmc@osmc:~/tmp$ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 847.52
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7
Hardware	: BCM2708
Revision	: 000f
Serial		: 0000000028d56ddc

Perhaps we can use the Hardware section. But I dont know what is the best solution :S

The other issue is there is no [[ found. So I need to change L18 
from: `if [[ $CPU_RPI -ne 1 && $CPU_IMX6 -ne 1 && $CPU_WETEK -ne 1 && $CPU_X64 -ne 1 && $CPU_X32 -ne 1 ]]; then`
to: `if [ $CPU_RPI -ne 1 -a $CPU_IMX6 -ne 1 -a $CPU_WETEK -ne 1 -a $CPU_X64 -ne 1 -a $CPU_X32 -ne 1 ]; then` 

cheers,
 fape

**Comment by brindosch** [comment]
You could use my install/update scipt, i will commit it, if people give positive feedback
#493

**Comment by fape** [comment]
Thx. i'm gonna try it out ;)

**Comment by tpmodding** [comment]
@fape can it be closed?

**Comment by fape** [comment]
I closed it ;)
