### ISSUE TITLE
Kodi on Minix Z64A, Hyperion on RPi, connection lost every once in a while

### ISSUE THREAD

**Issue by jilleb** [tvdzwan/hyperion#478]
Hi all,

I installed Hyperion on OSMC, running on a Raspberry Pi B, connected to the network through wifi.
From my Minix Z64A, I'm running Kodi with the Hyperion addin. All runs fine, except with HD movies, sometimes the connection between Kodi and Hyperion is lost, which can get quite annoying, because the lights will go off, back on, off, "Connection Error" message in Kodi, etc.
After some time, the connection comes back online. 

Here's some output when I run hyperion in the console:

```
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "/dev/spidev0.0",
        "rate" : 1000000,
        "type" : "lpd6803"
}

Black border threshold set to 0.01 (3)
Creating linear smoothing
Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Effect loaded: X-Mas
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Boot sequence(Rainbow swirl fast) created and started
Display opened with resolution: 720x480
Frame grabber created and started
Json server created and started on port 19444
Proto server created and started on port 19445
effect finished
New proto connection
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
Proto connection closed
New proto connection
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
Proto connection closed
New proto connection
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
Proto connection closed
New proto connection
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
Proto connection closed
New proto connection
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
Proto connection closed
New proto connection
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0


```

Any ideas what I should look at to fix this?

**Comment by brindosch** [comment]
@jilleb 
Could you test this with LAN instead WLAN? Maybe this was a bug and is fixed. Just do an update to be sure
https://github.com/tvdzwan/hyperion/issues/493

**Comment by brindosch** [comment]
@jilleb 
Any news on this?

**Comment by redPanther** [comment]
The time I switched from my rpi1 to rpi2 for my media center stuff I used my edimax wlan dongle from rpi1. This seems to work - first - but after some time connection was lost and I wasn't able to stream movies. Using good old cable works perfectly.

Some of my friends found out that sometimes there is a problem with the device power saving mode (from usb or the wifi dongle), but nobody found a solution yet. I mean another solution as cable or another (not the same type) wifi device. 

You can also try to use a powerd usb hub between wifi an rpi. 
I'm very sure hyperion is not the problem here.

**Comment by brindosch** [comment]
Yes, it is no real issue on hyperion side. I will close it
