### ISSUE TITLE
Windows / OS-X client

### ISSUE THREAD

**Issue by john-dev** [tvdzwan/hyperion#479]
Hello,

i guess its a little bit out of topic, but since i love hyperion, im looking for a WORKING way to set the led's according to my tft screen signal from my pc, using SOFTWARE over network, not an hdmi splitter.
Any ideas?

Thanks,
John

**Comment by deennoo** [comment]
follow this, and enjoy

**Comment by john-dev** [comment]
That's exactly what i'm NOT talking about.. I don't want to switch to a different led-control software like in your link. Further im not using arduino but raspberry pi, i should've mention that.

**Comment by tpmodding** [comment]
@john-dev try the new forwarder :)
think can be closed now

**Comment by john-dev** [comment]
@tpmodding it's early here, can you be more specific pleas? :)

**Comment by john-dev** [comment]
Ok, you mean i should compile it for OS-X / Windows and forward the result to the raspberry wiht the led's attachted?

**Comment by tpmodding** [comment]
Yes, https://github.com/tvdzwan/hyperion/pull/518 try this one! You can forward your screen with proto-forwarder :)

**Comment by brindosch** [comment]
This should be done, if not, just open a nw issue

Thank you
