### ISSUE TITLE
Merging APA102 end frame fix

### ISSUE THREAD

**Issue by RickDB** [tvdzwan/hyperion#480]
Hi,

Noticed that even in the current master build it's missing a APA102 end frame fix made by @pcaffardi in the 2nd post here:

https://github.com/tvdzwan/hyperion/pull/364

Without his patch the last led issue remains so would be great if this change could be merged :+1:

**Comment by redPanther** [comment]
@pcaffardi didn't make a pull request to upstream master. He has to do it, if he wants to include the patch ...

**Comment by NicoHood** [comment]
You can do this yourself. Download it, create a hyperion fork, patch and create a PR. You can give credits to him via comments.

**Comment by RickDB** [comment]
Thanks guys, will wait a bit and if @pcaffardi doesn't create a PR gonna create one.

**Comment by AEtHeLsYn** [comment]
PR is commited and approved, if u compile the code everything will work as expected. Binary still needs to be updated tho.

**Comment by wisc17** [comment]
As you pulled me into this .. :)
@AEtHeLsYn i dont see a new PR
it would be good to finaly have this APA fix included

P.S. could you approve my current PR as working ( #470 ) - i see you merged it into your repo 
and the comments in my PR make it look like there is a problem (which i cant see)

**Comment by RickDB** [comment]
Compiled from master and indeed works like a charm, here's hoping it will get a new binary release as this bug has been in there for a while now :)

**Comment by wisc17** [comment]
I made a pull request with pcaffardi's fix

**Comment by solidewebservices** [comment]
What triggers the creation of the new binaries? Is this up to @tvdzwan to do so? I need this fix and another recently approved pull request but I lack the skills to compile from master myself. Would be great to be able to update from new binaries which include these fixes.

**Comment by wisc17** [comment]
- yes; so far tvdzwan updates the binaries
- you dont need this one; we are just trying to get rid of this commit because it was already working.
- its not hard to compile it .. check that txt file in the main directory "CompileHowto.txt"

**Comment by RickDB** [comment]
Have the compiled ones also posted here with manual install instructions:

http://forum.team-mediaportal.com/threads/diy-amblight-project-guide-hyperion-ws2801-ws2812b-apa102.128526/page-24#post-1174260

Had a few users upgrading to APA102 and ran into it a while back and as they lack the expertise this was easier at least until it makes it to the official binary release :)

**Comment by solidewebservices** [comment]
@wisc17 

- The last LED of my APA102 strip is a steady light purple color. I used the latest deploy binary file when setting it up so I assumed that the mentioned bug was still present in those binaries and that caused this issue. Perhaps it's an hardware issue then?!!?
- I'll have a go at compiling it myself as I'd still like to have another recent pull request. Compiling doesnt indeed seem that hard with those instructions.

**Comment by wisc17** [comment]
its kind of hard to tell for me since i dont own apa102 i did this in behalf of a friend
and he reported that the previous master and the current master are both working with APA102
but now people here say that the last commit reintroduced the endframe bug - im a bit helpless and i will let you people owning those leds sort it out.
see #491

**Comment by RickDB** [comment]
Just tried it here with current master and not getting the endframe bug with APA102, attached the updated compiled ones in the link from the previous post.

**Comment by wisc17** [comment]
- so the current tvdzwan master has no endframe bug ?
- how about the revert request i made ? can you confirm that this one also works please (https://github.com/wisc17/hyperion/tree/revert-484-apa102)

**Comment by RickDB** [comment]
Correct it's from the tvdzwan master branch, will test it with revert request branch and report back.

**Comment by RickDB** [comment]
Works fine with revert-484-apa102 branch as well.

**Comment by wisc17** [comment]
good :) so we dont have to worry or panic about that "useless" commit of mine
ty so much

**Comment by RickDB** [comment]
@wisc17 spotted the error in issue #491 and created PR #492.

Reason was that the official Hyperion install script linked to an old binary release, so even when the APA102 fix was in the master branch it would use outdated binary release on install (11 month old one).

**Comment by tpmodding** [comment]
Merged, can be closed?

**Comment by RickDB** [comment]
Yeah tested and can be closed :+1:
