### ISSUE TITLE
installing on rasbian jessie Pi rev. B

### ISSUE THREAD

**Issue by pigbait** [tvdzwan/hyperion#481]
Hello, is anyone having proplems getting hyperion installed on rasbian jessie? I get an error running wget -N https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh

It says somthing about not passing verification

Ill post the error later today

**Comment by keshav2609** [comment]
hello,

if you are talking about "missing LSB tags and overrides" this is not a problem
First of all
activate root then

cd /tmp

wget -N raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh

chmod 765 install_hyperion.sh

sudo ./install_hyperion.sh

It should work

**Comment by pigbait** [comment]
Thanks ill give this a try.

**Comment by pigbait** [comment]
this is the error i get?

`root@raspberrypi:/tmp# wget -N raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
--2015-11-21 21:48:52--  http://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
Resolving raw.github.com (raw.github.com)... 23.235.40.133
Connecting to raw.github.com (raw.github.com)|23.235.40.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh [following]
--2015-11-21 21:48:52--  https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
Connecting to raw.github.com (raw.github.com)|23.235.40.133|:443... connected.
ERROR: The certificate of ‘raw.github.com’ is not trusted.
ERROR: The certificate of ‘raw.github.com’ is not yet activated.
The certificate has not yet been activated
`

**Comment by redPanther** [comment]
1. update your OS (sudo apt-get update; sudo apt-get upgrade)
2. try again.
if you have the same erorr, then try this:
wget --no-check-certificate -N https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh

if that works edit install_hyperion.sh and add after every wget this: --no-check-certificate

**Comment by pigbait** [comment]
HMM i guess Im to new for this, trying to find a good tutorial but nothing really available,

tried following this but doesn't work http://bite-in.com/?p=9

**Comment by pigbait** [comment]
im going to try with wheezy.

**Comment by keshav2609** [comment]
Here you go have a look at this tutorial it's in German but if you use chrome or chromium you can translate in English

http://www.forum-raspberrypi.de/Thread-hyperion-raspbian-jessie-21-11-15-hyperion-fushicai-grabber-pi-b-b-2-anleitung

**Comment by pigbait** [comment]
My stupid time wasn't correct... how embarrassing lol. got it working good now :)
