### ISSUE TITLE
Pi 2, OSMC, STK1160, LEDs showing OSMC colors

### ISSUE THREAD

**Issue by mharrison310** [tvdzwan/hyperion#482]
I am so close to having this all working but I have run into one large issue. Hyperion controls the LEDs according to what is shown on the Pi, not what is picked up by the grabber. I have full control of the LEDs from the android app, but it does not seem to be utilizing the video grabber. I have verified I got an stk1160 video grabber.
Below is the settings I am using in the hyperion.config.json file.
![20160204_112641](https://cloud.githubusercontent.com/assets/17068703/12821688/66f50ff0-cb32-11e5-9900-f15fa6be0ac6.jpg)
 Could it be any of those settings? I also did a clean install with the device plugged in and that did not seem to change anything. Any help would be appreciated!

EDIT: I should also add that by using WinSCP and looking under /dev I can see video0.

**Comment by brindosch** [comment]
the framegrabber itself have a higher priority then the GrabberV4l2 and you could not change this.
As a workaround, use the xbmc checker and set "menu" to off.

Not the best solution, but the only one i found, for a "smooth" transition.

**Comment by mharrison310** [comment]
Would you leave both grabbers still enabled? or just the normal and not the GrabberV412?

**Comment by brindosch** [comment]
both enabled, like in your screenshot.
if the kodi menu is shown, i could change the input at the tv from hdmi (kodi) to the internal dvb device and watch tv with ambilight (through the SCART, it is "black" until i go tv dvb)

**Comment by mharrison310** [comment]
Oh, so if I don't ever plan on using Kodi on the Pi, is there a way I could disable it so it would never grab from the Pi? I have a PC and Fire TV connected to a receiver that has the splitter between it and the TV, so the Pi will never be displayed on the screen.

**Comment by mharrison310** [comment]
I just used 
`hyperion-v4l2 --screenshot`
and I got the error 
`VIDIOC_S_FMT error 16, Device or resource busy`

**Comment by mharrison310** [comment]
New update, that error is what happens when you don't stop Hyperion first! But unfortunately it still only show what is running in osmc.

**Comment by brindosch** [comment]
Yes, you have to disable hyperion, if you want to grab a screenshot. Could you get a screenshot now?

**Comment by mharrison310** [comment]
It just hung while saying capturing screenshot, so I tested every component I could and found the hdmi2av converter would only output green static so I am I  the process of getting a new one.

**Comment by mharrison310** [comment]
Below are screenshots of my config settings

![hyperion config 1](https://cloud.githubusercontent.com/assets/17068703/12995324/8ffc259c-d0f4-11e5-8094-eafd7817a37a.png)
![hyperion config 2](https://cloud.githubusercontent.com/assets/17068703/12995326/9001869a-d0f4-11e5-9944-72aa91a69064.png)
![hyperion config 3](https://cloud.githubusercontent.com/assets/17068703/12995327/900f65b2-d0f4-11e5-817c-713d56ea3692.png)
![hyperion config 4](https://cloud.githubusercontent.com/assets/17068703/12995325/8ffe8396-d0f4-11e5-9418-0b4cc36bd1b0.png)

Below is the content of my config file:

`// Automatically generated configuration file for 'Hyperion daemon'
// Generated by: HyperCon (The Hyperion deamon configuration file builder

{
	/// Device configuration contains the following fields: 
	/// * 'name'       : The user friendly name of the device (only used for display purposes)
	/// * 'type'       : The type of the device or leds (known types for now are
	/// APA102, Adalight, AmbiLed, Atmo, Hyperion-USBASP-WS2801, Hyperion-USBASP-WS2812, Lightberry, Lightpack, LPD6803, LPD8806, Multi-Lightpack, P9813, Paintpack, PhilipsHUE, PiBlaster, SEDU, Test, ThinkerForge, TPM2, WS2801, WS2812b, None)
	/// * [device type specific configuration]
	/// * 'colorOrder' : The order of the color bytes ('rgb', 'rbg', 'bgr', etc.).
	"device" :
	{
		"name"       : "MyPi",
		"type"       : "ws2801",
		"output"     : "/dev/spidev0.0",
		"rate"     : 1000000,
		"colorOrder" : "rbg"
	},

	/// Color manipulation configuration used to tune the output colors to specific surroundings. 
	/// The configuration contains a list of color-transforms. Each transform contains the 
	/// following fields:
	///  * 'id'   : The unique identifier of the color transformation (eg 'device_1')	///  * 'leds' : The indices (or index ranges) of the leds to which this color transform applies
	///             (eg '0-5, 9, 11, 12-17'). The indices are zero based.	///  * 'hsv' : The manipulation in the Hue-Saturation-Value color domain with the following 
	///            tuning parameters:
	///            - 'saturationGain'  The gain adjustement of the saturation
	///            - 'valueGain'       The gain adjustement of the value
	///  * 'red'/'green'/'blue' : The manipulation in the Red-Green-Blue color domain with the 
	///                           following tuning parameters for each channel:
	///            - 'threshold'       The minimum required input value for the channel to be on 
	///                                (else zero)
	///            - 'gamma'           The gamma-curve correction factor
	///            - 'blacklevel'      The lowest possible value (when the channel is black)
	///            - 'whitelevel'      The highest possible value (when the channel is white)
	///
	/// Next to the list with color transforms there is also a smoothing option.
	///  * 'smoothing' : Smoothing of the colors in the time-domain with the following tuning 
	///                  parameters:
	///            - 'type'            The type of smoothing algorithm ('linear' or 'none')
	///            - 'time_ms'         The time constant for smoothing algorithm in milliseconds
	///            - 'updateFrequency' The update frequency of the leds in Hz
	///            - 'updateDelay'     The delay of the output to leds (in periods of smoothing)
	"color" :
	{
		"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"hsv" :
				{
					"saturationGain" : 1.0000,
					"valueGain"      : 1.0000
				},
				"red" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"green" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"blue" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				}
			}
		],
		"smoothing" :
		{
			"type"            : "linear",
			"time_ms"         : 200,
			"updateFrequency" : 30.0000,
			"updateDelay"     : 0
		}
	},

	/// The black border configuration, contains the following items: 
	///  * enable    : true if the detector should be activated
	///  * threshold : Value below which a pixel is regarded as black (value between 0.0 and 1.0)
	"blackborderdetector" : 
	{
		"enable" : true,
		"threshold" : 0.01
	},

	/// The configuration of the effect engine, contains the following items: 
	///  * paths        : An array with absolute location(s) of directories with effects 
	///  * bootsequence : The effect selected as 'boot sequence'
	"effects" : 
	{
		"paths" : 
		[
			"/opt/hyperion/effects"
		]
	},

	"bootsequence" : 
	{
		"effect" : "Rainbow swirl fast",
		"duration_ms" : 3000
	},

	///  The configuration for the frame-grabber, contains the following items: 
	///   * width        : The width of the grabbed frames [pixels]
	///   * height       : The height of the grabbed frames [pixels]
	///   * frequency_Hz : The frequency of the frame grab [Hz]
	"framegrabber" : 
	{
		"width" : 96,
		"height" : 54,
		"frequency_Hz" : 10.0
	},

	/// The configuration of the XBMC connection used to enable and disable the frame-grabber. Contains the following fields: 
	///  * xbmcAddress       : The IP address of the XBMC-host
	///  * xbmcTcpPort       : The TCP-port of the XBMC-server
	///  * grabVideo         : Flag indicating that the frame-grabber is on(true) during video playback
	///  * grabPictures      : Flag indicating that the frame-grabber is on(true) during picture show
	///  * grabAudio         : Flag indicating that the frame-grabber is on(true) during audio playback
	///  * grabMenu          : Flag indicating that the frame-grabber is on(true) in the XBMC menu
	///  * grabScreensaver   : Flag indicating that the frame-grabber is on(true) when XBMC is on screensaver
	///  * enable3DDetection : Flag indicating that the frame-grabber should switch to a 3D compatible modus if a 3D video is playing
	"xbmcVideoChecker" : 
	{
		"xbmcAddress" : "127.0.0.1",
		"xbmcTcpPort" : 9090,
		"grabVideo" : true,
		"grabPictures" : true,
		"grabAudio" : true,
		"grabMenu" : false,
		"grabScreensaver" : true,
		"enable3DDetection" : true
	},

	/// The configuration of the Json server which enables the json remote interface
	///  * port : Port at which the json server is started
	"jsonServer" : 
	{
		"port" : 19444
	},

	/// The configuration of the Proto server which enables the protobuffer remote interface
	///  * port : Port at which the protobuffer server is started
	"protoServer" : 
	{
		"port" : 19445
	},

	/// The configuration of the boblight server which enables the boblight remote interface
	///  * port : Port at which the boblight server is started
// 	"boblightServer" : 
// 	{
// 		"port" : 19333
// 	},

	/// Configuration for the embedded V4L2 grabber
	///  * device          : V4L2 Device to use [default="/dev/video0"]
	///  * input           : V4L2 input to use [default=0]
	///  * standard        : Video standard (no-change/PAL/NTSC) [default="no-change"]
	///  * width                : V4L2 width to set [default=-1]
	///  * height               : V4L2 height to set [default=-1]
	///  * frameDecimation      : Frame decimation factor [default=2]
	///  * sizeDecimation       : Size decimation factor [default=8]
	///  * priority             : Hyperion priority channel [default=800]
	///  * mode                 : 3D mode to use 2D/3DSBS/3DTAB (note: no autodetection) [default="2D"]
	///  * cropLeft             : Cropping from the left [default=0]
	///  * cropRight            : Cropping from the right [default=0]
	///  * cropTop              : Cropping from the top [default=0]
	///  * cropBottom           : Cropping from the bottom [default=0]
	///  * redSignalThreshold   : Signal threshold for the red channel between 0.0 and 1.0 [default=0.0]
	///  * greenSignalThreshold : Signal threshold for the green channel between 0.0 and 1.0 [default=0.0]
	///  * blueSignalThreshold  : Signal threshold for the blue channel between 0.0 and 1.0 [default=0.0]
	"grabber-v4l2" : 
	{
		"device" : "/dev/video0",
		"input" : 0,
		"standard" : "NTSC",
		"width" : -1,
		"height" : -1,
		"frameDecimation" : 2,
		"sizeDecimation" : 8,
		"priority" : 800,
		"mode" : "2D",
		"cropLeft" : 0,
		"cropRight" : 0,
		"cropTop" : 0,
		"cropBottom" : 0,
		"redSignalThreshold" : 0.0,
		"greenSignalThreshold" : 0.0,
		"blueSignalThreshold" : 0.0
	},

	///  The configuration for each individual led. This contains the specification of the area 
	///  averaged of an input image for each led to determine its color. Each item in the list 
	///  contains the following fields:
	///  * index: The index of the led. This determines its location in the string of leds; zero 
	///           being the first led.
	///  * hscan: The fractional part of the image along the horizontal used for the averaging 
	///           (minimum and maximum inclusive)
	///  * vscan: The fractional part of the image along the vertical used for the averaging 
	///           (minimum and maximum inclusive)
	"leds" : 
	[
		{
			"index" : 0,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.9545, "maximum" : 1.0000 }
		},
		{
			"index" : 1,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.9091, "maximum" : 0.9545 }
`
I can see the grabber, but whenever I try to screenshot it just hangs.

**Comment by mharrison310** [comment]
I have decided to return the grabber after trying to use it as it was originally designed, and it returned green static on a macbook and an error message on a PC. Everything else seems to work, so I will try a new grabber. Any recommendations on where to buy a new grabber at would be greatly appreciated.

**Comment by brindosch** [comment]
Good decision, there are serveral problems with the stk1160 video grabber

I could recommend a Fushicai UTV007-Chip

I know that the Basetech [BR116 USB 2.0 Video Grabber](https://www.conrad.de/de/basetech-br116-usb-20-video-grabber-1168633.html?sc.queryFromSuggest=true) use it
also the [LogiLink Audio and Video Grabber USB 2.0](http://www.amazon.de/LogiLink-Audio-Video-Grabber-USB/dp/B0013BXFLG)
Notice: pictures the same, brand another but both UTV007, just look at your preferred shop

brindosch

**Comment by mharrison310** [comment]
Today I received a new video grabber, and the problem is resolved!
