### ISSUE TITLE
WS2812B PI 1 vs. PI 2

### ISSUE THREAD

**Issue by derdigge** [tvdzwan/hyperion#485]
Hello !

I have a working setup with 226 WS2812B leds using hyperion + PWM control as mentioned here:
https://github.com/tvdzwan/hyperion/wiki/WS2812b-PWM
Pi 1 is connected by gpio18(pin12) to the strip and gnd is connected to powersupply. 

It works great but from time to time the PI cpu is underpowerd. So i decided to upgrade to PI2. People here mentioned that this will also work for PI2 B+ and so on.
https://github.com/tvdzwan/hyperion/issues/6
It took a day to gather all informations of that Monsterthread :)

Do i cloned my sdcard an bootet up the pi2. All stuff worked ootb like on the pi1. But i was not able to control the ws2812B strib by gpio18 of the pi2. here information about the running OS:

` ;) Meister_Lampe ~ $ uname -a
Linux Meister_Lampe 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux
 ;) Meister_Lampe ~ $ cat /etc/issue
Raspbian GNU/Linux 8 \n \l`

It seams several users are running into this: (example)
https://github.com/tvdzwan/hyperion/issues/6
Tester0815 18. Apr 2015

I do not want a complete "mediacentre" distro like openelec. I need a "slim" distro as a ambilight/loungelight Server. What do i have to fix here?

May be this guy is stombelin into the same sitiuation. But he does not have a pi1 to check this
https://github.com/tvdzwan/hyperion/issues/47

Thanks!

**Comment by trackdork** [comment]
I'm stuck here too, I have fresh installs of OSMC and Raspbian on RPI B+ and RPI2 and neither seem to get GPIO18 to output the proper signal, even though Hyperion reports that it is successfully animating (and accepting my commands both local and from android).  Hopefully we can find an answer, there are more than one of us with this problem.

**Comment by derdigge** [comment]
I switched to arduino nano and hyperions adalight Protokoll. Arduino nano costs 4€ inclusive shipping, so no big deal and it works great.

**Comment by trackdork** [comment]
Cool, thanks for the response.  I didn't have an arduino but I had a spare Photon laying around.  It took me several iterations to find a sketch that worked... i almost gave up.  Apparently the adalight protocol has some handshaking that I wasn't taking into account.  

230 LEDs working reliably!

For the Hyperion config I am using:
```
----------------- Hyperion.conf -----------------
                "name"       : "MyPi",
                "type"       : "adalight",
                "output"     : "/dev/ttyACM0",
                "rate"       : 115200,

then the rest of the conf fle generated from hyperion tool
---------------------------------------------------
```
(I think Arduinos show up as /dev/ttyAMA0, fyi)

This Photon/Core sketch works for anyone struggling like I was.


```
// Utilize the FastLED library for WS2812 control
#include "FastLED/FastLED.h"
FASTLED_USING_NAMESPACE;

#define NUM_LEDS 230
#define LED_PIN D2
CRGB leds[NUM_LEDS];

uint8_t prefix[] = {'A', 'd', 'a'}, hi, lo, chk, i;

// set up FastLED and start Serial interface
void setup() {
    // tell FastLED how many pixels to use
    // strip is connected on D2
    FastLED.addLeds<NEOPIXEL,LED_PIN>(leds, NUM_LEDS);
    
    // I couldn't find documentation on the Photon supporting higher baud rates than this,
    // though it does auto-negotiate.  115200 is is a slow baud rate compared to some examples
    // but the refresh rate on the stip is totally acceptable
    Serial.begin(115200);
  
    // initial RGB flash for testing, remove later
    LEDS.showColor(CRGB(255, 0, 0));
    delay(20);
    LEDS.showColor(CRGB(0, 255, 0));
    delay(20);
    LEDS.showColor(CRGB(0, 0, 255));
    delay(20);
    LEDS.showColor(CRGB(0, 0, 0));
    
    Serial.print("Ada\n"); // Send "Magic Word" string to host
}

// WARNING: you are about to see c++ with a  "GOTO" statement
// I almost vomited when I first copied and pasted, but this was the first
// sketch that I got to actually work with Hyperion.  At some point I will 
// refactor it out, but for now it's out of sight out of mind.
void loop() {
  // wait for first byte of Magic Word
  for(i = 0; i < sizeof prefix; ++i) {
    waitLoop: while (!Serial.available()) ;;
    // Check next byte in Magic Word
    if(prefix[i] == Serial.read()) continue;
    // otherwise, start over
    i = 0;
    goto waitLoop;
  }

  // Hi, Lo, Checksum

  while (!Serial.available()) ;;
  hi=Serial.read();
  while (!Serial.available()) ;;
  lo=Serial.read();
  while (!Serial.available()) ;;
  chk=Serial.read();

  // if checksum does not match go back to wait
  if (chk != (hi ^ lo ^ 0x55))
  {
    i=0;
    goto waitLoop;
  }

  memset(leds, 0, NUM_LEDS * sizeof(struct CRGB));
  // read the transmission data and set LED values
  for (uint8_t i = 0; i < NUM_LEDS; i++) {
    byte r, g, b;    
    while(!Serial.available());
    r = Serial.read();
    while(!Serial.available());
    g = Serial.read();
    while(!Serial.available());
    b = Serial.read();
    leds[i].r = r;
    leds[i].g = g;
    leds[i].b = b;
  }
  // shows new values
FastLED.show();
}
```

**Comment by tpmodding** [comment]
@derdigge can be closeD?

**Comment by derdigge** [comment]
for sure, works for me with arduiono.
dosent work with pi2 pwm.

**Comment by tpmodding** [comment]
Could you close it please? I have no rights. Thanks

Von meinem iPhone gesendet
