### ISSUE TITLE
forward proto and json messages to other hyperiond

### ISSUE THREAD

**Issue by redPanther** [tvdzwan/hyperion#486]
Hi,
I often saw the request for multiple devices or hyperiond sends data to another hyperion.
Now I need this feature too and I decided to implement that. 

My idea is to forward incomming proto and json messages to a list of configured clients. This approch has the advantage that all needed network stuff is already there.

The first step is reached - the proto-forwarder is  implemented and usabe for ambilight.
Next steps are:
- boblight and other grabber in hyperiond sends proto messages -> to use all image sources directly in hyperiond
- json forwarder -> needed for forwarding effects

I develop this in my [proto_json_forwarder branch](https://github.com/redPanther/hyperion/tree/proto_json_forwarder)

If you need more explanations or you have hints, wishes .. drop a message

**Comment by brindosch** [comment]
Well, this would be a great feature!
So it would be possible to send from one hyperion instance (with internal and external grabber) to more than one client at same time without start hyperion twice or more (on the grabber device)?

Keep up the good work! I would test it, if it is "test able".

**Comment by redPanther** [comment]
at the moment I can forward incoming  proto messages to a list of other hyperions (on the same or on other hosts).
here is a example configuration where one hyperion sends to 2 other hyperions. one is on the same machine, other is remote. This setup can drive 3 led devices  simultaneously. 
```
"protoServer" : 
{
  "port" : 19445, 
  "forward": [ "127.0.0.1:18445",  "192.168.0.11:19445" ]
},
```

my test setup:
I use hyperion-x11 (or hyperion-v4l2) to grab screen and send to my master hyperiond. The master hyperion drives standard ambi-light via ws2801 on a rpi2. HypM forwards the proto message to another rasPi (a pi 1b) for a lightwall behind my couch.
You can chain the hyperions as you like. one to many or daisy chained or mix both methods ...

ATM I implemented the json forwarder. Changes are not commited yet, there is some cleanup tbd.

I've already took a look how I can make sending proto messages from internal grabbers, but for that I have to make a separate protoForwarder class where all services can send raw proto messages or image data. This is a bit more complex, but it is managable ....

BTW for developing and testing I use my led simulator  [hypersim](https://github.com/redPanther/hypersim). Make thinks much easier ;-) 


I will

**Comment by bimsarck** [comment]
Thanks. Proto forward works excellent. :-)

**Comment by redPanther** [comment]
next step is reached - see my prot_json_forwarding branch

Proto Forwarding is now implemented in a more general way, but forwarding data of hyperiond internal grabber  isn't implemented yet.

Json message forwarding works now. This is used for effects. Keep in mind that only the effect triggering is forwarded. That means every hyperion must have the same effects available.

The configuration is changed. The above config isn't valid anymore. The forwarding config is in a separate section. I put an example and a description in the hyperion example config.

```
"forwarder" :
{
	"proto" : [ "127.0.0.1:19445","192.168.178.88:19445" ],
	"json"  : [ "127.0.0.1:19444","192.168.178.88:19444" ]
},

```

Can somebody test it?

**Comment by BooStars** [comment]
Hi redPanther,
thanks a lot for this great idea.. this is exactly what i'm looking for, but here is somthing wrong with the compiler, mayby sombody can help me out?
`[ 64%] Building CXX object libsrc/effectengine/CMakeFiles/effectengine.dir/__/__/include/effectengine/moc_EffectEngine.cxx.o
In file included from /home/andreas/hyperion/hyperion/include/hyperion/Hyperion.h:16:0,
                 from /home/andreas/hyperion/hyperion/build/libsrc/effectengine/__/__/include/effectengine/../../../../../../../include/effectengine/EffectEngine.h:10,
                 from /home/andreas/hyperion/hyperion/build/libsrc/effectengine/__/__/include/effectengine/moc_EffectEngine.cxx:10:
/home/andreas/hyperion/hyperion/include/hyperion/MessageForwarder.h:22:18: sorry, unimplemented: non-static data member initializers
/home/andreas/hyperion/hyperion/include/hyperion/MessageForwarder.h:22:18: error: ISO C++ forbids in-class initialization of non-const static member âportâ
libsrc/effectengine/CMakeFiles/effectengine.dir/build.make:71: recipe for target 'libsrc/effectengine/CMakeFiles/effectengine.dir/__/__/include/effectengine/moc_EffectEngine.cxx.o' failed
make[2]: *** [libsrc/effectengine/CMakeFiles/effectengine.dir/__/__/include/effectengine/moc_EffectEngine.cxx.o] Error 1
CMakeFiles/Makefile2:986: recipe for target 'libsrc/effectengine/CMakeFiles/effectengine.dir/all' failed
make[1]: *** [libsrc/effectengine/CMakeFiles/effectengine.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
`

Did i miss anything ?

**Comment by redPanther** [comment]
thanks for testing!

which compiler do you use?
I tested it with gcc  5.3.0 and it worked.

can you try something:
edit include/hyperion/MessageForwarder.h
and replace
quint16 port = 19444;
with
quint16 port;

and then try compile again.

**Comment by BooStars** [comment]
Hi... gettin a little closer, this time it stucks at:
`[ 73%] Building CXX object libsrc/hyperion/CMakeFiles/hyperion.dir/MessageForwarder.cpp.o
/home/andreas/hyperion/hyperion/libsrc/hyperion/MessageForwarder.cpp: In member function âvoid MessageForwarder::addJsonSlave(std::string)â:
/home/andreas/hyperion/hyperion/libsrc/hyperion/MessageForwarder.cpp:17:9: error: âruntime_errorâ is not a member of âstdâ
/home/andreas/hyperion/hyperion/libsrc/hyperion/MessageForwarder.cpp:22:9: error: âruntime_errorâ is not a member of âstdâ
libsrc/hyperion/CMakeFiles/hyperion.dir/build.make:329: recipe for target 'libsrc/hyperion/CMakeFiles/hyperion.dir/MessageForwarder.cpp.o' failed
make[2]: *** [libsrc/hyperion/CMakeFiles/hyperion.dir/MessageForwarder.cpp.o] Error 1
CMakeFiles/Makefile2:573: recipe for target 'libsrc/hyperion/CMakeFiles/hyperion.dir/all' failed
make[1]: *** [libsrc/hyperion/CMakeFiles/hyperion.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
`
my gcc is:
`root@raspberrypi:/home/andreas/hyperion/hyperion/build# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-14+rpi1)
`
Thanks
booStar

**Comment by redPanther** [comment]
ok i updated my branch. can you do a "git pull" to get the latest version.

**Comment by BooStars** [comment]
Hi, thanks for that,
now i gettin another error:
`[ 73%] Building CXX object libsrc/hyperion/CMakeFiles/hyperion.dir/MessageForwarder.cpp.o
/home/andreas/hyperion/hyperion/libsrc/hyperion/MessageForwarder.cpp: In member function âvoid MessageForwarder::addJsonSlave(std::string)â:
/home/andreas/hyperion/hyperion/libsrc/hyperion/MessageForwarder.cpp:20:9: error: âruntime_errorâ is not a member of âstdâ
/home/andreas/hyperion/hyperion/libsrc/hyperion/MessageForwarder.cpp:25:9: error: âruntime_errorâ is not a member of âstdâ
libsrc/hyperion/CMakeFiles/hyperion.dir/build.make:329: recipe for target 'libsrc/hyperion/CMakeFiles/hyperion.dir/MessageForwarder.cpp.o' failed
make[2]: *** [libsrc/hyperion/CMakeFiles/hyperion.dir/MessageForwarder.cpp.o] Error 1
CMakeFiles/Makefile2:573: recipe for target 'libsrc/hyperion/CMakeFiles/hyperion.dir/all' failed
make[1]: *** [libsrc/hyperion/CMakeFiles/hyperion.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by redPanther** [comment]
ok I think I got it. std::runtime_erorr is defined in <stdexceptions> not in <exceptions> .... it seems my system adds this include automatically

**Comment by BooStars** [comment]
OK, thank you... hyperion is compiling now...
I also did a quick test of the json-forwarder, looks like it woks, when I hit:
`hyperion-remote --address 192.168.10.2:19444 --effect "Flames" --duration 4000`
I see: 
`run effect Flames on channel 100`
on both hyperion instances (19444 AND 19544 on the same host) but I can't say if its really working, because I'm not at home now...
I will report again later...

Thanks a lot..

BooStar

**Comment by BooStars** [comment]
Hi... 
I was able make a real test now,
json and proto forwarding works perfectly...
Would be nice to forward boblight-connections too but I think you already working on it...
Thank you...

**Comment by redPanther** [comment]
Thx.for testing and I'm glad that it worked so good.

Yes you are right I m working on it. I will make proto forwarding for all internal grabbers and boblight. My current way to do it makes it quite easy to do so. My only problem is the osx grabber. I haven't osx available so i can only add experimental support for it.

**Comment by tpmodding** [comment]
hey redpanther!

first: thanks for your work! i tried with my setup... i have a rpi2 with openelec, first led stripes are behind my tv, and i try now to use your forwarder to add 2 "led bulbs". but when i use the forwarder hyperion works verry laggy...i have videos to show you the problem:

1. lpd8806 stripes (132 leds) behind my tv, controlled with teh SPI port from the rpi 
https://www.dropbox.com/home?preview=Video+17.02.16%2C+19+03+14.mov
2. adalight with arduino uno with 12x ws2812b only the led bulb without portforwarding
https://www.dropbox.com/s/8rlvibmy8fmnv3q/Video%2017.02.16%2C%2016%2004%2047.mp4?dl=0
3. when i start the lpd8806 (from 1.) and add those lines for forwarding
	"forwarder" :
	{
	    "proto" : [ "127.0.0.1:19445","127.0.0.1:19447" ],
	    "json"  : [ "127.0.0.1:19444","127.0.0.1:19446" ]
	},
the bulbs get the commands from forwarding, but the clompete ambilight is very laggy and not smooth
https://www.dropbox.com/s/vduka2a3sbxphyt/Video%2017.02.16%2C%2019%2005%2044.mov?dl=0

is there a performance problem?

If you need more infos or something doent hesitate to contact or ask me!

**Comment by redPanther** [comment]
Thx for testing.
Yes indeed there are possible issues i can imagine.

But i need some info. Which grabber do you use? integrated in hyperiond or standalone e.g. hyperion-v4l2

Best performance should be with external grabber.

A question to your setup. The config says that you use 3 hyperiond instances on the same rpi. Is it right? Thinks go laggy when ip settings not correct or ports are wrong.
Ip checks not impleted yet. You can create a loop connection when e.g. your hyperion server is at 19445 and in same instance you forward to 19445.
If any doubt, post your configs (best via dropbox)

Btw cool setup you have :-)

**Comment by redPanther** [comment]
I've implemented a basic loop connection check to prevent for some address settings issues in config. 
I also implemented proto forwarding for internal grabbers "framebuffer" and "OSX" but I couldn't test.

I looked into the boblight code. hmmm I would say, good forwarding of boblight is not possible, because boblight didn't transfer frames. Boblight sends the colors for that particular led stripe. It is possible to reconstruct the image from the leds and send this image, but if your first hyperion uses only a few leds/areas from the picture (e.g. the led bulb from @tpmodding ) then the second hyperion can't have higher resolutions ...

Other thing is dispmanx and amlogic grabber. They have no RGB color order. @tvdzwan / others abort on implementing the adaption for the proto interface for this grabbers. You can see this in the src/hyperion-amlogic code, there is a TODO comment to this topic.
ATM I try to solve that issue

**Comment by tpmodding** [comment]
Hey redPanther, good to so your progress!

You are wrong, i only use 2 instances!
1. hyperion.config_VIDEOGRABBER_lpd8806.json
http://pastebin.com/9LjsKEPn
2.hyperion.config_VIDEOGRABBER_arduino.json
http://pastebin.com/rwnHDKWA

in video 1. i only started the first config (without the forwarder part, it would flood me my terminal with no connections :D)
in video 2. i started only the second (arduino) config
and in video 3, i first started the arduino config and after thati started the first config (lpd8806) (with the forwarder part), so the forwarder can directly connect to the arduino 

do you need any other infos?

**Comment by redPanther** [comment]
Just a quick mesaage from the phone. Remove in first config the 127.0.0.1:19445 and 127.0.0.1:19444
As I thought you created a loop. This shouldn't be possible with my latest version.

The forward section contains only addresses where you want to send to.

Greetz rP

**Comment by tpmodding** [comment]
than it is my failure, i thought i must write source ip+port, destination ip+port. i will try it and give you feedback as soon as possible! Thanks again! love to see how the last 1-2 weeks this community grows!

**Comment by redPanther** [comment]
i updated the deploy/hyperion_rpi.tar.gz But I don't know if it wrks for you. I use archlinux on my rapspi

**Comment by redPanther** [comment]
just to keep you up to date. I implemented a method to convert an image of any color order type to rgb color order.
This flattens the way to make forwarding of dispmanx and amlogic grabbers possible.

Would be cool if anybody with coding experience can have a look to my last [commit](https://github.com/redPanther/hyperion/commit/c814651ec4973fe3b2bfca7c0370a0bac752f025) and tell me if there is a faster/better way to implement "toRgb()"

:-)

**Comment by redPanther** [comment]
so it's done, all internal and external grabbers, json and proto server support message forwarding for interconnecting multiple hyperiond.

Whats missing is the forwarding of boblight due to the problems described earlier. 
For boblight I have a new idea. I make an Option where you can set the resolution of boblight frame. Then you add the width/height for your maximum led device. E.g. you have a screen with 30x50 leds and a wall behind with 100x300 leds. Than set  "100x300". The boblight connector creates a virtual led config with "100x300" led matrix and boblight will send the frame in that resolution. Then this image is feed into hyperion as it came from e.g. v4l2 grabber ... Perhaps this works and hopefully this wont kill the power of my rpi1. ... we will see.

so long I would be happy if someone can test my newest achievements. I updated the deploy/hyperion_rpi.tar.gz archive. 

BTW I discovered that the binaries in the build directory (at least the original rpi) are build in debug without compiler optimizations. Also the build config (cmakelists.txt) is set to "debug". This is wasted performance. I will make a separate commit to fix the default and documantion on this topic.

**Comment by tpmodding** [comment]
You are awesome! I'm at work. I will give you feedback when i'm back at home!

**Comment by tpmodding** [comment]
Sure you updated the rpi archive? its the same i downloaded 2 days ago :D i compared the files :)

**Comment by emms007** [comment]
Thanks Panther, latest compiled source works perfectly!  I am very happy and grateful. Running different config allow to have a single source, and in my case eventhough some leds are RGB or RBG instructions mode!

FYI example system is as follow:

**Capture:**
  > TV HDMI signal [1 RPI capturing and pushing wifi Proto data with hyperion-v4l2]
  > A few remote control and tablets, allowing easy effect/color switching [pushing JSON commands]
  > Automation scripts [pushing JSON commands]

**Central Server **
   > 3 hyperion daemon running, one master Forwarding to the two others. All sending led data over wifi to Leds drivers.

**Leds devices**
  > TV back: WS2801 leds, driven wireless by an ESP8266 (ESPLightNode firmware) 
  > Room furniture: same setup
  > Leds inside Ikea papper lamp: same setup

Amazing experience!

**Comment by redPanther** [comment]
@emms007
Great to see that it works! How is the performance? Is there a noticable lag?

When I fone some cleanup a separate dispmanx grabber I will push it to main hyperion branch.

**Comment by tpmodding** [comment]
https://www.dropbox.com/s/r3druzkdzekhl6f/Video%2022.02.16%2C%2000%2011%2019.mov?dl=0

for me there is no noticeable lag! its awesome! i've found out how to compile, but dindt noticed that i used the old binaries :D :D but now with the new version it works very fast! the loop-detector works too!

but i dont know if there are noticable lags over network, i use at the moment a arduino with usb connected...i must now figure out how to add the "udp device"(protocoll) then test the forwarder over network :+1: :+1:

**Comment by redPanther** [comment]
@emms007 you wrote you had esp with esplightnode firmware. Which leddevice do you use to send the leddata?

Thx!

**Comment by emms007** [comment]
Just created a pull request for the basic Leddevice created for tpm2.net protocol.
Let me know if it works ok for you.

https://github.com/redPanther/hyperion/commit/1d58da240252237f2aab86dfe33ef35982be6849

**Comment by tpmodding** [comment]
@redPanther your code works fine! Wont you do a pull request?

**Comment by redPanther** [comment]
@tpmodding I'm implementing a standalone hyperion-dispmanx grabber. This makes it possible - at least for me - to drop usage of boblight. Because boblight forwarding is missing I want provide an alternative. Perhaps someday we can drop the whole boblight stuff and provide a solutution that satisfy current boblight users.

The other thing is, every available standalone grabber is a good direction to cleanup the core. From my viewpoint there is no real need to keep the grabbers inside libsrc and hyperiond. The usage of standalone grabbers are the cleanest way for forwarding, thatswhy I want to provide a solution for not using the integrated.

**Comment by giovanne123** [comment]
@emms007 which version of the esplightnode firmware firmware are you using?
**If you use version 0.1, can you please post a precompiled binary. **
Because with the v0.2 esplightnode firmware I only get it running in art-net mode (maybe a tpm2net bug in it?) :-(

**Comment by tpmodding** [comment]
@redPanther ok, i get it. i'm new on github is it possible to load the nem files with the many merged things from tvdzwan and combine with your forwarder? or must you update your fork and add your files for the forwarder?

Thanks!

**Comment by redPanther** [comment]
@tpmodding I've merge current changes from tvdzwan/master into my branch.
I didn't know if it  compiles on rpi (I'll try it out later, when I have time for that)

I'm nearly finished with my changes. I think I will make a PR in next days.

**Comment by redPanther** [comment]
Question to all who are interested in multi daemon/device/forwarding things.
The current state of this feature is much better then the method described in wiki page "Controlling multiple devices".
Who is willing to write a new wiki page "Controlling multiple devices - new method"?

**Comment by tpmodding** [comment]
I Can do that

Von meinem iPhone gesendet

**Comment by emms007** [comment]
@giovanne123: I got success running EspLightNode using precomplied binaries available here: https://github.com/Frans-Willem/EspLightNode/releases/download/v0.2/EspLightNode-v0.2-2015-10-25.zip

**Comment by brindosch** [comment]
@redPanther 
Do you want/need/worldbecool/unnecessary
boolean "enabled : true/false" in the config?
Maybe you could shutdown your extension 
I have no problem to add it.

**Comment by redPanther** [comment]
If you do not enter hosts to forward or you comment out entire section forwarding is not enabled. Its the same thing like the xbmc section or bootsequence or boblight server or .....

I have to do some final tests before i make a PR.

**Comment by giovanne123** [comment]
@emms007 ,
ok version 0.2.
I wasn't able to get the v0.2 running in tpm2net mode for my ws2801 or ws2812. Only artnet is working for me with my ws2801 strips.
Have you configured something special (which led type)?
I will try it again...
Thanks

**Comment by brindosch** [comment]
Let´s say i would suggest a value on HyperCon startup (like many other pre configured values), this value will be merged to the config.
To prevent the start it would be useful to add a enable true/false.
Or the user decide to stop using it. He could disable it in HyperCon. But the value is not removed and my personal throught: comment out is ugly.

**Comment by redPanther** [comment]
ok, than leave then set the lists to [ ] That means no forward destinations defined. This will disable forwarding.
Add enable checkbox to hypercon ui and add/remove forward section to config. People who use hypercon didn't look much often in the output config.

I never productively used hypercon, because the led config is not able to generate my hardware config. I'm very happy about any comment and example in the config file.

**Comment by tpmodding** [comment]
Hi redPanther, i posted the forwarder in the german rpi-forum, to test it and get feedback.
http://www.forum-raspberrypi.de/Thread-hyperion-hyperion-mit-forwarder-funktion

sigi28 commented that the server lags when the client is not connected.

i've figured out that when i start the server manually and close the client,
i got nonstop connection errors. is it possible to fix that problem? but i dont
know how to fix it, may a delay after connection error of 10 seconds? and after 10
connection errors to delay it to 10minutes or stop forwarding? dont know..may you have a better idea

or maybe the server stops after 10 trys to connect to a client if there is no client available and if the a client is online again the client sends a reset signal for the 10 connection trys

**Comment by redPanther** [comment]
I try to optimize the reconnection event. My solution is not the best here (best would be an own connection thread), but this solution fits better into current code.

Hint: the binary in my branch is not updated and I didn't want to update it, because I use - latest and greatest - archlinux. My binaries arn't compatible to raspbian and others (missing dependencies due to newer lib versions ...)

@tpmodding can you / raspi.de people  test if it is ok now.
BTW nice to see the "knight rider" effect in your video.

**Comment by tpmodding** [comment]
You updated your github? I only must recompile it? if yes, i will do it later and post it in our forum to test it :+1:

**Comment by redPanther** [comment]
yes I updated my branch. commit [e7a89c8](https://github.com/redPanther/hyperion/commit/e7a89c87b15fbe9809ec63468b59ecc55c6d3e72)

**Comment by redPanther** [comment]
@tpmodding

Hint for compiling:
Edit main cmakelists.txt and remove the set(cmake_build_type debug) line.
On commandline add a
 -DCMAKE_BUILD_TYPE=Release
to your cmake .. call.
after that cd into the bin dir (where hyperiond is) and type
strip *

the compiles with all optimizations and removes all unnecessary stuff from the binaries.
BTW the size of the bins are smaller.

Happy compiling :-)

**Comment by BooStars** [comment]
looks good... thank you...
if i kill one client I see
"No connection to Hyperion: 192.168.10.2:20445" on the main instance
after starting that client again:
"Connected to Hyperion: 192.168.10.2:20445"
The client says:
"Proto connection closed
New proto connection"
and starts working again immediately

I've Tested with two clients on the same host (20445 and 30445)
Soo works fine...thx

**Comment by tpmodding** [comment]
i posted it in our forum, the file size is damn small... :) i like that! 2 users said it works very good, the cpu usage dropped from 5-7% to 2,5-5%!!

**Comment by tpmodding** [comment]
hey @redPanther there was a question:

when we set with hyperion-remote an effect on the server(forwarder), all devices (server+client) do the same effect. if we set the effect only on clients, the server will do his ambilight and for example the clients do a effect. but we cant now say ONLY the server do an effect, cause the it forwards everything? :D did you understand it? is it possible to control ONLY the server/forwarder :)

**Comment by redPanther** [comment]
perhaps such a config would do:

![hyperion](https://cloud.githubusercontent.com/assets/6893049/13375100/2f39ffcc-dd97-11e5-8a1f-ed2f948f24d4.png)
just a quick draw, perhaps later more

**Comment by tpmodding** [comment]
get it :D would that not be easier:
http://imgur.com/DQqKJFt
the bottom is the TV with 2 configs. server(red) and client(blue)
and 2 configs for ikea?
or is it possible to implement code that the forwarder has a own port, i mean the "serve" has is own json/proto port and the forwarder has a own port? or is it to much?

**Comment by redPanther** [comment]
I don't get your idea, but we have countless possibilities now to interconnect hyperions. You can also build groups hyperion for ever room .... I'm sure you will find some combination that fulfil your needs. 

It is possible to make separate ports for controlling the forwareder/server. I have to think a bit to get a good solution. For now I want to  settle down this topic and wait for feedback/desires/hints/...
When my PR gets in main code branch Everybody can open a new issue.

I will close this topic soon. If there are bugs or other things to report, we can write in PR #518

**Comment by redPanther** [comment]
@tpmodding you offered to write a tutorial - this would be cool if you can do so.

cheers redPanther

**Comment by apurbas** [comment]
@redPanther I have a Raspberry Pi-1 (with Lightberry APA LED & external USB grabber) as server. I want to control another Philips hue lamp. How do I achieve this using proto/json forwarder? Should the forwarder IP be bridge IP (with ports)?

**Comment by redPanther** [comment]
You need a second hyperion with configured hue lamp.

Then forward from the first to secend. See wiki for more info. (Network distributed features)

**Comment by apurbas** [comment]
Thanks @redPanther. 

I think I did the same, however can't locate what's the mistake here.

This is my first hyperion running on Raspberry Pi -1 & USB grabber ( IP 192.168.1.3). This config sends instruction to LED strips. I forward the proto/json to ports 19447 & 19446.

http://www.jsoneditoronline.org/?id=a112ab80547ab61d7377b25179fffc7e

This is the second hyperion config I have created for Hue.on Pi-1( IP 192.168.1.3). The bridge (v1) is on IP 192.168.1.4. The Proto/Json picks up info from 19447 & 19446.
http://www.jsoneditoronline.org/?id=655e6c5ecd045a73e67cdce73bfb5bee

Sadly I don't see the effects on Hue lamp. Can you guide me whats wrong?

**Comment by redPanther** [comment]
your first link contains no data. can you provide your config again. second config looks good. Can you check if this is working, when you send an effect or color via hyperion-remote to second hyperiond.

hyperion-remote -a "192.168.1.3:19446" -e "Rainbow swirl fast"

**Comment by apurbas** [comment]
@redPanther Oops, here is config1 at Raspeberry Pi / IP (192.168.1.3).
http://www.jsoneditoronline.org/?id=a112ab80547ab61d7377b25179fffc7e
The forwarder is at the last of the json.
Just for our reference - this is my existing layout. 
![layout](https://cloud.githubusercontent.com/assets/16624176/14060577/46c42bdc-f38f-11e5-8b35-608b183d8ad7.PNG)
Could you suggest now what I'm doing wrong?

**Comment by redPanther** [comment]
config looks good. just the priority value of the v4l2 grabber looks a bit high. try to set them to 900.

does the boot effect (9 seconds rainbow) work for your hue lights? 

BTW nice drawing!

**Comment by apurbas** [comment]
Ok, reduced the grabber priority to suggested value.But yet no effect on Hue.
On booting - I see a static red mostly (not a rainbow) on the hue lights which goes off after 9 sec.May be this log can help you..
[log.txt](https://github.com/tvdzwan/hyperion/files/190785/log.txt)

**Comment by redPanther** [comment]
Your hyperion is to old. Its from 2015. Forwarder is from 2016. Please use latest verdion

**Comment by apurbas** [comment]
Hey @redPanther ..big thank you. Updated hyperion. Hue ran with lags for some time & then stopped with "Segmentation fault". This is new to me. 
[log2.txt](https://github.com/tvdzwan/hyperion/files/190812/log2.txt)
Do you suggest any changes in hscan/vscan? Any recommendations? I want the Hue to pick up colors on right bottom side (from front).

**Comment by redPanther** [comment]
what puzzels me is that you have 4 lightIDs (hues) configured but only one lamp in leds section. I never used hue lights nor I read the config details. I think every hue lamp should have a corresponding led (or better say an entry for a rectangular area of the screen)

from my understanding your hscan/scan setting means "average color value of  rectangular region 10% wide from left and 100% hight"
0|0 is top left and 1|1 is bottom right. You values must something like
hscan: min: 0.9 max:1
vscan: min: 0.9 max: 1

you can visualize your config with my led simulator: https://github.com/redPanther/hypersim
this python3 app can load hyperion config files and visualize the leds

**Comment by apurbas** [comment]
Sure thanks ! As of now - I wish to control only 1 hue ( bloom), hence the config. Surely I will experiment with more lamps & keep you posted.
I'm facing a new issue now. yesterday - I created the new configs with latest hyperions. The main hyperion starts fine. When I start the 2nd one from command prompt- that also starts. Effects are with lags on Hue ( that I plan fix later). After sometime both the Hyperion hangs & I got an error

*** Error in `/storage/hyperion/bin/hyperiond': corrupted double-linked list: 0x                                                                         01da5ac8 ***
This is something new & I don't know the possible cause & how to fix it?

**Comment by redPanther** [comment]
when using hyperion daemons on same host I recommend using 127.0.0.1 instead of real IP for forwarder settings. This prevents some problems.
I also recommend getting every single hyperiond work before connecting them. In your case this means getting the hue devices work. Add your grabber to second hyperion config and look how this performs. If this performs with a lag then you have issues with your hue's otherwise other prob ...

the erros you get looks interresting open a new issue if problem persistens.

good luck :-)
