### ISSUE TITLE
[Hyperion] NEW INSTALL/UPDATE SCRIPT! [RC]

### ISSUE THREAD

**Issue by brindosch** [tvdzwan/hyperion#493]
Hello all, i wrote a new install/update script.
To hold it short

## Tested platforms and distributions

- Raspberry Pi 1/Zero/Pi 2 /Pi 3(all versions)
- Linux 32 and 64bit (Debian, Ubuntu etc)
- OSMC
- OpenELEC 5 and 6 (maybe 4, untested)
- Raspbian
- Wetek

## Features

- More feedback for the user and less spam
- Script just starts with root privileges
- Installs dependencies automatically
- Support for init.d initctl and systemd
- OSMC: Hyperion user will be changed to "osmc" and hyperion waits for kodi to be started (xbmc checker)
- Raspberry Pi: It doesn´t matter if you use raspian/osmc/openelec or any other distribution* it will check if dtparam=spi=on is placed in config.txt if not, it will be placed and tell the user to reboot at the end of installation
- Automatically creates a backup of your .conf files and place it back after update
- If you use your own modified init.d/initctl/systemd file, they won´t be overwritten!

*untested, please report if you test it - success or unsuccessful. Thank you

## Not Tested
It would be great if someone could test it on these devices and give some feedback.

- i.MX6

## Download
Check the Hyperion wiki

**Comment by bouwew** [comment]
I've just tested your installation script.
Found a problem: I can't run /etc/init.d/hyperion.
The link is there, but automatic file completion doesn't see the file/link.
And when typed manually,on root, the result is "bash: /etc/init.d/hyperion: Permission denied"

**Comment by solidewebservices** [comment]
This install script worked perfect for me when updating my OSMC install which had used old binaries that still had the APA102 end frame bug. However, these updated binaries still miss another fix I'd like to use ( #475 ) which has been pulled recently. Would it be possible to create updated binaries so I can update again? I tried compiling myself on the Raspberry Pi with OSMC but it wont work as I get the following error.

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
BCM_INCLUDE_DIR
   used as include directory in directory /home/osmc/hyperion/hyperion-source/hyperion/libsrc/grabber/dispmanx
   used as include directory in directory /home/osmc/hyperion/hyperion-source/hyperion/test/dispmanx2png
`

**Comment by brindosch** [comment]
@bouwew 
I investigated this and found the following

the original script does this

	echo 'Installing startup script in init.d'
	# place startup script in init.d and add it to upstart
	ln -fs /opt/hyperion/init.d/hyperion.init.sh /etc/init.d/hyperion
	chmod +x /etc/init.d/hyperion
	update-rc.d hyperion defaults 98 02

the new this

	echo '---> Installing startup script in init.d'
	# place startup script in init.d and add it to upstart (-s to respect user modified scripts)
	ln -s /opt/hyperion/init.d/hyperion.init.sh /etc/init.d/hyperion 2>/dev/null
	chmod +x /etc/init.d/hyperion
	update-rc.d hyperion defaults 98 02
---------------------
So there is nothing changed with the permission handling

I will retest on an RPi 1 with wheezy these days

thank you for your time

**Comment by bouwew** [comment]
The issue is with the permission settings of the file hyperion.init.sh in the /opt/hyperion/init.d/ directory. I had to change these by hand to get it to work.

**Comment by solidewebservices** [comment]
@brindosch You are right, just tested it by editing the hyperion.config.json and the fix is included. Thanx again for your install script!

**Comment by brindosch** [comment]
@bouwew 
There is one mistake

Raspbian Jessie use systemd (default)
And you use init.d?

At least on Wheezy, the permission is set (tested with rpi1 wheezy = (init.d default))
![init d](https://cloud.githubusercontent.com/assets/15967679/13077808/644b8bf2-d4bb-11e5-93e5-148134cce20e.JPG)
And systemd is working on Jessie
![systemd](https://cloud.githubusercontent.com/assets/15967679/13077849/aae0fdfe-d4bb-11e5-8b9e-884979a81c6f.JPG)

Could you give me the output of this
`grep -m1 -c systemd /proc/1/comm`
`which /sbin/initctl | wc -l`
`which /usr/sbin/service | wc -l`

Thank you

**Comment by bouwew** [comment]
No problem :)
cat /proc/1/comm: systemd
which /sbin/initctl | wc -l: 0
which /usr/sbin/service | wc -l: 1

**Comment by bouwew** [comment]
After install on my system x was not set for hyperion.init.sh

**Comment by brindosch** [comment]
Did you run the script as root?
At least it should force you to do.

I´m sorry, i have no idea why
`cat /proc/1/comm: systemd`
not triggered what it do usually

**Comment by bouwew** [comment]
Yes, I did.
I'm using this guys image as a basis: [http://www.forum-raspberrypi.de/Thread-hyperion-raspbian-jessie-21-11-15-hyperion-fushicai-grabber-pi-b-b-2-anleitung]
Maybe the reason is in there.

Anyway, doesn't matter too much, I got it working in the end :)

**Comment by brindosch** [comment]
I will contact sigi28,

thank you

**Comment by pigbait** [comment]
@bouwew, just a shot in the dark. i had lots of problems installing hyperion on jessie and my problem ended up being a date and time issue. for some reason jessie on my PI was stuck on 1970

**Comment by brindosch** [comment]
UPDATE: Script will no longer run, if system date (year) is <=2015
Thank you for the hint

**Comment by cptnyehy0** [comment]
This worked for installing on a Wetek Core with OpenElec. The install detected the amlogic chip and correctly installed the binaries and everythign to run on a wetek. As per usual with the core, the framegrabber works when you are in the OE Gui, but the /dev/amvideocap0 device is not present, so hyperion is still not working during playback (this is not a fault of the installer, just need to find a version of  OE with the videocap enabled and available in /dev.)

Thanks! this saves some manual fudging around I had to do to not get a segmenation fault.

**Comment by brindosch** [comment]
I am very glad that someone tested this on Wetek!
thank you @cptnyehy0  for feedback

**Comment by ziggy73701** [comment]
Hi, does this script support the WS2812b driver? I can install etc.. and with a default config the service runs. Soon as I  put in the config for the ws2812b the service wont start.

**Comment by cptnyehy0** [comment]
I believe it is the same source, so its install content should be the same as the original hyperion install. I think that the main point of the update to the installer was to make it compatible with other O/Ses outside of openelec and other pieces of HW outside of the RPi. what is your hyperion output if you dont run it with the /dev/null & at the end?

**Comment by ziggy73701** [comment]
Thanks for coming back to me, sorry but am new to all this so my knowledge is limited. when you say don't run it with dev/null at the end I have no idea what that means. I can stop start and get the status, that's pretty much it. What ever I set the device to, in my config works... unless I put ws2812b then the service fails to start. Is there a way to generate an additional log etc?

**Comment by cptnyehy0** [comment]
what system / os are you on? Under openelec, if you execute the script without the /dev/null & parameter it will run in the foreground and you can see what is going on.

https://github.com/tvdzwan/hyperion/wiki/Installation-on-RPi-with-OpenELEC

Instead of running this, which will dev null the output and run in the background:
/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 & 
run it like this:
/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json 

then you should be able to see output in your session about what may be causing the error. Im not sure what the correct stanza is for ws2812b, as I use the APA102 strips, but make sure you are matching this example:

"device" :
{
    "name"       : "MyPi",
    "type"       : "ws2812b",
    "colorOrder" : "rgb"
},

hope this helps.

**Comment by ziggy73701** [comment]
The main element is
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 175]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "type" : "ws2812b"
}

Unable to create device ws2812b
Not creating any smoothing

**Comment by brindosch** [comment]
I´m sorry to say, the images were 16 days old.
At least the old one had no compile flag for ws2812b pwm support.
Now they are even with hyperion master! But i don´t know if this is compiled with that flag
Sorry for the trouble.

**Comment by brindosch** [comment]
@cptnyehy0 
yes you are right, but my images contain additional files for the services

**Comment by ziggy73701** [comment]
Ok so thanks for the feed back, very much appreciated! Let's all pretend I am a idiot noob with little understanding (I learn fast normally!) essentially the build here is different and didn't have the flags when you compiled it for ws2812b? From what I read this is something you believe you have resolved and I can just... Run again?

**Comment by brindosch** [comment]
The builds were not compiled by myself. i have no answer for that :)
Just try and report ;)

**Comment by ziggy73701** [comment]
I'll go wwith th a clean install today and see what occurs. Looks like I may have to compile a version... Can't see anything going wrong!

**Comment by ziggy73701** [comment]
Compiled using the how to and all good, your script works fine just missed the bits I need.

Is there a way to combine the 2? Your install seems to introduce more information from the status.

**Comment by jOhnyy5** [comment]
> osmc@osmc:~$ sudo /usr/bin/hyperiond /etc/hyperion.config.json                  Application build time: Feb 10 2016 01:50:15
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 49]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "/dev/spidev0.0",
        "rate" : 250000,
        "type" : "ws2801"
}

Not creating any smoothing
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Police Lights Single
Effect loaded: Police Lights Solid
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Effect loaded: X-Mas
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Black border threshold set to 0.01 (3)
DETECTION MODE:default
Boot sequence(Rainbow swirl fast) created and started
XBMC video checker created and started
Display opened with resolution: 1920x1080
Black border threshold set to 0.01 (3)
DETECTION MODE:default
Frame grabber created and started
terminate called after throwing an instance of 'std::runtime_error'
  what():  Json server could not bind to port

**Comment by brindosch** [comment]
Above is "Done"
Not related to this

**Comment by kiryl85** [comment]
Hi guys,
I think I have noticed an error in hyperion.service, Shouldn't parameters After be placed in Description section? If I leave them in Service than I have some errors saying After is not recognized

Also, I'm using OSMC and I have noticed that in general putting hyperion as service is not so great solution. 
Anyway Im not able to start this service

```
osmc@osmc:/usr/bin$ sudo systemctl start hyperion
osmc@osmc:/usr/bin$ sudo systemctl status hyperion
* hyperion.service - Hyperion systemd service
   Loaded: loaded (/etc/systemd/system/hyperion.service; enabled)
   Active: failed (Result: start-limit) since Thu 2016-03-03 00:25:05 CET; 2s ago
  Process: 972 ExecStart=/opt/hyperion/bin/hyperiond /etc/hyperion.config.json (code=killed, signal=SEGV)
 Main PID: 972 (code=killed, signal=SEGV)

Mar 03 00:25:04 osmc hyperiond[972]: "rate" : 115200,
Mar 03 00:25:04 osmc hyperiond[972]: "type" : "ws2812b"
Mar 03 00:25:04 osmc hyperiond[972]: }
Mar 03 00:25:04 osmc hyperiond[972]: Failed to open /dev/mem: Permission denied
Mar 03 00:25:04 osmc systemd[1]: hyperion.service: main process exited, code=killed, status=11/SEGV
Mar 03 00:25:04 osmc systemd[1]: Unit hyperion.service entered failed state.
Mar 03 00:25:05 osmc systemd[1]: hyperion.service start request repeated too quickly, refusing to start.
Mar 03 00:25:05 osmc systemd[1]: Failed to start Hyperion systemd service.
Mar 03 00:25:05 osmc systemd[1]: Unit hyperion.service entered failed state.
```
This is my hyperion.service
```
[Unit]
Description=Hyperion systemd service
After=mediacenter.service
After=mediacenter.service
[Service]
Type=simple
User=osmc
Group=osmc
UMask=007
ExecStart=/opt/hyperion/bin/hyperiond /opt/hyperion/config/hyperion.config.json
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target
```

and also mentioned /dev/mem
```
osmc@osmc:/usr/bin$ ll /dev/mem
crw-r----- 1 root kmem 1, 1 Mar  3 00:05 /dev/mem
```

regarding ws2812b, unfortunately by default hyperion is compiled with w2812b_pwm flag turned off

**Comment by brindosch** [comment]
> After be placed in Description section?
Yes you are right - but never got a error message in the log - will fix this | also the duplicates

> /dev/mem error  
This is new. Never saw this. Could you test without ws2812b_pwm flag?

**Comment by brindosch** [comment]
Update:
- the next run will remove every duplicates and add the "After = mediacenter.service" in the Unit section.

**Comment by NicoHood** [comment]
On my elementary os x64 (based on ubuntu14.04):
```
sudo ./install_hyperion.sh 
[sudo] password for linuxuser: 
*******************************************************************************
This script will install/update Hyperion and it´s services
Version 0.1
*******************************************************************************
---> Stop Hyperion, if necessary
---> Install/Update Hyperion dependencies (This may take a while)
---> Backup Hyperion configuration(s), if present
---> Downloading the appropriate Hyperion release
2016-03-03 19:32:00 URL:https://raw.githubusercontent.com/brindosch/hyperionbeta/master/deploy/hyperion_x64.tar.gz [8038391/8038391] -> "-" [1]
---> Restore Hyperion configuration(s), if present
---> Installing initctl script
---> Starting Hyperion
initctl: Job failed to start
*******************************************************************************
Installation/Update finished!
Path to your configuration -> /etc/hyperion.config.json
*******************************************************************************
./install_hyperion.sh: 214: [: -ne: unexpected operator
```

**Comment by brindosch** [comment]
Well i never could lean back, right? :)

i checked your points on a elementaryos x64 VM

> initctl: Job failed to start

I get the following output when starting in the upstart log
`/proc/self/fd/9: 3: /proc/self/fd/9: /usr/bin/gpio2spi: not found`
I have to investigate why it searches for gpio2spi

> I guess one problem also is that both of them are true on my system.

This is no problem /usr/sbin/service is always true. It is just used, if no systemd/initctl is found

> And the other problem is the SPIOK is not set on my system, as it has no SPI?

My fault, never tested back/ thought about it after the latest implementation. Fixed -> just triggered on rpi now

>Also you should link to those binaries now

They have no service files added, also i could react if something went wrong (just for the moment)
And for Rpi users, the image is ahead master (effects and proto forward)

> Ask the user to overwrite the data

The whole data is by design always overwritten. If not, no new Hyperion will be installed.

> If overwrite, do a backup and tell the user the backup location

I don´t know what you have done with your *.conf (s)
All *.conf get backed and placed back after update. (just in /opt/hyperion/conf (!))
Where was your *.conf?

Thank you for reporting!

**Comment by kiryl85** [comment]
hi Brindosch. regarding my issue with ws2812b leds I think you've already found the reason.
Some modifications have to be done in code before compiling hyperion from source -> [changes done by Zappatron](https://github.com/tvdzwan/hyperion/compare/master...Zappatron:pi2_ws2812b)
I will try tomorrow and let you know.

cheers

**Comment by brindosch** [comment]
@NicoHood 
Tested on Debian x64 (systemd) -> working
Tested on Ubuntu 14.04.4 (initctl) -> same problem
I am sure it is the script. Will have a look

@kiryl85 
Yes i also don´t know this

**Comment by NicoHood** [comment]
> I don´t know what you have done with your *.conf (s)
All *.conf get backed and placed back after update. (just in /opt/hyperion/conf (!))
Where was your *.conf?

This should be noted in the output above. I mean i could have looked this up, but imagine I am a noob user and i dont want too search through a very complex installation script where it backs up my data after i've realized i lost it wven though it was (somehere??) backed up. (I recovered my settings though)

**Comment by brindosch** [comment]
If you setting up hyperion like in the wiki you will never lost your config. At least i have no idea where you saved yours. If your tutorial (or anything)  that you followed changed the location inside /opt/hyperion/. Well there is no reason why and a bash scipt like this is limited.

**Comment by brindosch** [comment]
One idea. If you overwritten the symlink (/etc/hyperion.config.json) with your file, the config will be lost, because the symlink will be forced to overwrite it

**Comment by NicoHood** [comment]
I normally copy my config directly to `/etc/hyperion.config.json`. That is all.

**Comment by brindosch** [comment]
@NicoHood 
you could update again
But now you will run into following error
![unbenannt](https://cloud.githubusercontent.com/assets/15967679/13536362/c285725a-e23f-11e5-9c6a-c447fda02dae.JPG)
You need newer libs than ubuntu 14.04 could provide. Just have a look at the internet how you could get them.
You could "debug" yourself with the following command
`tail -f /var/log/upstart/hyperion.log`
There is the hyperion log located

Good luck and thank you

**Comment by NicoHood** [comment]
Why do I need those libraries? If I manually run the hyperiond it just works as expected. So why does the service require this? I do not understand.

**Comment by RanzQ** [comment]
@brindosch @NicoHood I ran into that issue as well on my latest elementary os. Earlier I had hyperion manually compiled but the provided binary uses newer libraries. This solved it for me: http://askubuntu.com/a/581497

The script installed initctl file instead of service, cause I had a custom service file earlier. After removing it the service link was added correctly.

**Comment by brindosch** [comment]
@NicoHood 
I have no idea. I will have a look later.

@RanzQ 
Glad that you found a solution to udpate gcc!
Yes, the install script "searches" for the prefered method. The old script just use service - doesn´t matter what system you are using cause it is always true.

**Comment by meowmoo** [comment]
Im Using the x11 file on my OE Chromebox, only way to get light in menu, and its missing in this install
any chance you add it?

**Comment by brindosch** [comment]
The builds are from tvdzwan and due to the script he used it is very limited what is inside the tar.gz
We publish new official images (with the platform depending grabbers) this evening  (i have no time, maybe @tpmodding could) or tomorrow.
This script will be part of it. Also a new HyperCon version which support all latest Hyperion features!
We have problems to setting up the crosscompile fully working. Sorry for the delay!
I am sure this worth the waiting :)

**Comment by meowmoo** [comment]
Where should I keep an eye on for the chances, tvdzwas Hyperion or your hyperionbeta?

So just I get it right, in a few days, no stress here, I got a working setup, I can install with this method, and get the latest x11 and Hyperion stuff, running in my OE chromebox.

**Comment by brindosch** [comment]
The tvdzwan branch, i asked him for rights to help him manage his project. He is very busy.

**Comment by meowmoo** [comment]
Thanks,

And thanks for keep  this nice project up to date

**Comment by brindosch** [comment]
@meowmoo 
New Rpi/x32/x64 images are online. Please advice me, in which way the installations process should be changed to support a working x11 right away after install.

Thank you

**Comment by meowmoo** [comment]
can get it to work,
wiped everthing hyperion related + autostart and did a fresh install 
get this
```
---> Stop Hyperion, if necessary
sh: 1: unknown operand
sh: 1: unknown operand
```


but everything looks good.
but i cant start hyperion.
when i replace the libs with the "old on it works"
http://i.imgur.com/UEPqk4o.jpg
this are all libs i use at the moment
if i should provide more info, you need to tell me how :>

about the x11 autostart, Ask if the user wanna use x11, if yes change the autostart to 
```
/storage/hyperion/bin/hyperiond.sh /storage/hyperion/config/hyperion.config.json </dev/null >/dev/null 2>&1 &
DISPLAY=:0.0 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/storage/hyperion/bin /storage/hyperion/bin/hyperion-x11 </dev/null >/dev/null 2>&1 &
```

i use the hyperion/config folder so everything is in one place

**Comment by brindosch** [comment]
@meowmoo 
From where did you gather your libs?
I will talk with tpmodding that we provide a x32x64 lib package, the install script is capable to handle this.

Is there a negativ side effect, if we start it by default? I would prefer a "user failsave" method.
Do we need the `DISPLAY=:0.0 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:` call? Or it is workin without too?
Is this call on all x11 platforms the same?

**Comment by meowmoo** [comment]
illiac4 provided them in the kodi Forum http://forum.kodi.tv/showthread.php?tid=180472&pid=2005414#pid2005414 --> http://bite-in.com/hyperion/Hyperion_OpenELEC_x64.tgz

I'm not aware of any negativ side effect, since i switch to hyperion, i always run it with x11

yes you need the `DISPLAY=:0.0 LD_LIBRARY_PATH=$LD_LIBRARY_PATH: call`
I cant tell if its on all x11 platforms the same

**Comment by brindosch** [comment]
Thank you for the information. I added the libs as new dependencies for OE x32x64. They will be used automatically on next install.

The x11 startup modification is not implemented yet, but you could update without destroying your autostart.sh.

**Comment by brindosch** [comment]
I will close this now. To prevent confusion.
/done

**Comment by NicoHood** [comment]
It would be nice to separate the download script from the installation script though. I personally always recompile the source myself. So it would be nice to copy the effects, config file, binaries and install the service from the local git folder instead of downloading them.

The download script could just call the install script afterwards. Or maybe a parameter for the install script like ./install --git or --local to use the binaries in the local folder.
