### ISSUE TITLE
MacOSX (BSD style compiling)

### ISSUE THREAD

**Issue by zarboz** [tvdzwan/hyperion#5]
I can't seem to get a compile with any version of Darwin QT

i only know enough to troubleshoot compiler errors etc not recode your work for mac

if this is to much to ask for i understand I would love an alternative to the crappy prismatik software and this is the BEST ambilight software i have found yet

-- ENABLE_DISPMANX = OFF
CMake Error at cmake/qt4/FindPackageHandleStandardArgs.cmake:97 (message):
  Could NOT find Qt4 (missing: QT_QMAKE_EXECUTABLE QT_MOC_EXECUTABLE
  QT_RCC_EXECUTABLE QT_INCLUDE_DIR QT_LIBRARY_DIR QT_QTCORE_INCLUDE_DIR
  QT_QTCORE_LIBRARY QT_QTGUI_INCLUDE_DIR QT_QTGUI_LIBRARY
  QT_QTNETWORK_INCLUDE_DIR QT_QTNETWORK_LIBRARY QT_UIC_EXECUTABLE)
Call Stack (most recent call first):
  cmake/qt4/FindPackageHandleStandardArgs.cmake:291 (_FPHSA_FAILURE_MESSAGE)
  cmake/qt4/FindQt4.cmake:1223 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:45 (find_package)

**Comment by rhammons** [comment]
I'm interested in running hyperion on my mac (using it on a pi currently), could someone provide instructions to compile it and get it running? I've very little experience using XCode.

**Comment by zarboz** [comment]
SUPER easy now a days 

just open a terminal and type git clone
xcode will prompt you to install some command line utils 

# for OSX build you need XCode, qt4 libraries and cmake. You can use macport (homebrew might work too) to install them
sudo port install qt4-mac
sudo port install cmake
cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_V4L2=OFF -DENABLE_OSX=ON

**Comment by rhammons** [comment]
Thanks for the help Zarboz, I was able to get macport to  install qt4-mac and cmake, then cloned the repository, but I get an error on cmake:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files: LIBUSB_1_INCLUDE_DIR
use as included directory in /hyperion/libsrc/leddevice
LIBUSB_1_LIBRARY
linked by target "leddevice" in directory /hyperion/libsrc/leddevice

Any advice?

**Comment by zarboz** [comment]
sudo port install libusb

try again :-p

**Comment by rhammons** [comment]
Nice! That all worked -- unfortunately upon launching hyperiond, I get an error about not being able to create device ws2801 then a segmentation fault: 11 after Initializing Python Interpreter.

**Comment by zarboz** [comment]
Sounds like the hyperion.config.json you have in /etc/ is not setup properly


Mac only supports an "adalight" style connection
with my yosemite mac pro I am using a Teensy 3.1 with an Octows2811 shield and 240 LED's @ 30 leds per meter with my 40 inch tv
I will upload my config for you to check out but its rather easy to setup
you just have to determine what the /dev/***** is for your serial connected device and define it in your hyperion configuration

Mac is a BSD style OS and therefore is somewhat POSIX compliant in the fact that the devices are still all under /dev/devicenameconnectionetc << just an example
