### ISSUE TITLE
Hyperion Questions - Looking to Help

### ISSUE THREAD

**Issue by werkkrew** [tvdzwan/hyperion#500]
Hello All, 

I know this is not the correct place to post this but I am not aware of anywhere else I might be able to get the answer I am looking for.

I have had an Ambilight setup I built several years ago that has been working flawlessly, as such I have not kept up on all of the latest developments in the area.  I am now looking to make some upgrades to my current setup and I have some questions.

My current setup runs a custom version of boblight I forked and wrote myself on an original RPi Model B and is fed by the Kodi boblight plugin.  It drives about 256 LED's / 48 LED/m LPD8806 around a 60" panel.

I am looking to be able to extend the functionality past Kodi and while I am aware of the various ways of doing the HDMI split/capture method I have a couple questions before I start to buy for this project.

1) What is currently regarded as the best strip to use?  APA102?  WS2812B?  RGB or RGBW?  I am looking for a bit better color rendition and higher pixel density.  I found that on my current setup the old RPi had trouble as it is keeping up so I want to make sure I choose the highest performing strips for my new build.  Is a 144 led/m density regarded as too high, either from a visual perspective or a memory/performance perspective?

2) My main reason for wanting to upgrade relates to wanting to have the ambilight functionality extend beyond just content playing in Kodi, those of you who have done the HDMI split/capture method, how is the real-world latency of that setup?  

3) Finally, and perhaps my most important question - as Smart TV's become better and more popular the content is moving off of the HDMI cable for many things and into the TV itself, which means that we either opt to not use any of the smart features for the benefit of being able to have our Ambilight work or most of the content we watch cannot work with the Ambilight.  

I am not sure if the Plex app or any other smart TV apps support hyperion but regardless, if I wanted to start using a smart TV I am wondering what are the realistic possibilities of having an app directly on the TV itself drive a hyperion setup such that any content being displayed could be backlit?  Before I go too far down the rabbit hole of trying to research this does anyone who is smarter than I am have any idea of the realistic possibility of having, for example, a Hyperion app for Samsung Tizen that would enable literally 100% of the content being shown on the tv to potentially feed a hyperion setup?

Thanks in advance, and if there is another place I can post this please let me know!

**Comment by tpmodding** [comment]
1) i prefer not to many LEDs, cause you have "too much" light and it doesn't look "smooth" anymore. i have 48leds/m lpd8806 too and i'm happy with them, i think more then 60 leds/m is to much flickering. but that's a matter of opinion.

2) if you use the xbmc grabber its fantastic! latency is barely visible. with the right config with your usb grabber (grab frame/size) the latency is so small you need a good eye to see the latency!

3) That's just what I was thinking too. i googled for my samsungTV and found samyGo (hack for SamsungTV firmware) but i found nohting to grab the screen directly from TV..there are different things we have to consider e.g. HDCP. the easiest method to use youre ambilight with the smarttv functions is to install different plugins in kodi like netflix for example...

I apologize for my english and hope i could help you.

**Comment by brindosch** [comment]
@werkkrew 
Are your question answered? If yes please close your issue
Thank you
