### ISSUE TITLE
Nvidia shield TV problem with Hyperion

### ISSUE THREAD

**Issue by riddleace** [tvdzwan/hyperion#501]
Hi, i have problem on my Nvidia shield TV and KODI(16.0 BETA) Hyperion addons. I instaled on Pi2 last version Raspbian jesle and instar Hyperion, all was working with no problem but when i connect directly to Shield over KODI and activate Hyperion addons nothink haped. In terminal command i can see thats Shield its connected but with no lights efect. With externat USB grabrer is all working but not with internal frame graber over lan. Can you plz help me found some solution?
thanks

**Comment by riddleace** [comment]
I think they must changed RenderCapture api in new version KODI 16+

**Comment by riddleace** [comment]
From KODI support i got answer about this problem, somethink thats Hyperion must fix they addon for they new RenderCapture api.

**Comment by brindosch** [comment]
@riddleace 
I couldn´t find any official message for an android support

But there is a pending fix for v17
Maybe this helps
I forked and added it. Just download like from the official repo
https://github.com/brindosch/script.service.hyperion

**Comment by riddleace** [comment]
Thanks i will try it to day later...

**Comment by riddleace** [comment]
Hi, just try it and dont works, somethinking still missing

**Comment by brindosch** [comment]
We need someone who could fix this (with that platform)

**Comment by iLLiac4** [comment]
This one works on x64 https://github.com/iLLiac4/script.service.hyperion and v17 kodi. Do not know Nvidia shield.

**Comment by brindosch** [comment]
@iLLiac4 
Yes, in my link i merged your support vor v17. Sad, it won´t work.
It would be great i you could investigate the "kodi android specific player changes" maybe you could get this working too!

**Comment by iLLiac4** [comment]
Sorry no interests into android ATM.

**Comment by riddleace** [comment]
@iLLiac4
I think this problem will be some on others operating system, like Openelec or linux.

**Comment by brindosch** [comment]
@riddleace 
could you verify, that it is working with V15?
I tested myself with a nexus 4 and can confirm that v15 is working, v16 not
I will put this on my list

**Comment by riddleace** [comment]
@brindosch 
yes on V15 it works

**Comment by ziggy73701** [comment]
Just set up on new install with Shield running Kodi 16... I had to disabled Mediacore (Surface) hardware acceleration and then all was good and works a treat.

**Comment by riddleace** [comment]
@ziggy73701 
Hi, whats verzion of KODI 16 you are using on Shield?

**Comment by ziggy73701** [comment]
Using the final build of V16 released... Today. Same version on the Google play store.

Seems to work with V17 nightlie as well.

**Comment by riddleace** [comment]
Yes on alfa v17 all works... :-)

**Comment by tpmodding** [comment]
@riddleace you reopened again?

**Comment by riddleace** [comment]
Nop all if for now working by disabled Mediacore (Surface) in KODI
