### ISSUE TITLE
Controlling multiple devices

### ISSUE THREAD

**Issue by vratixan** [tvdzwan/hyperion#503]
When I follow the tutorial about controlling multiple devices, hyperion wont work anymore :/ 

How does controlling multiple devices work? I am trying to control an apa102 led strip and secondly pwm output via pi-blaster. Could someone please help me, I would appreciate it very much. 
Thank you for your time!

**Comment by brindosch** [comment]
> When I follow the tutorial about controlling multiple devices

Which tutorial? You should ask that person for help?

**Comment by vratixan** [comment]
This tutorial: https://github.com/tvdzwan/hyperion/wiki/Controlling-multiple-devices

**Comment by brindosch** [comment]
Could you start at least one hyperion? What happen if you start the second? Could you start the second?
Note: there is no external grabber support for both at the same time

**Comment by tpmodding** [comment]
you must loop the video0(usb grabber) to for example video1, on that virtual videosource you can start multiple times hyperion. i have the exact same problem

found somthing, but couldnt start it
/usr/bin/gst-launch-1.0 v4l2src device=/dev/video0 io-mode=2 ! video/x-raw,format=UYVY, framerate=25/1,width=240,height=192 ! deinterlace ! v4l2sink device=/dev/video1

may it helps you a little bit

**Comment by vratixan** [comment]
Before I followed the steps in the wiki the first one worked fine. Now hyperion isn't workiln at all and to be honest I don't really know why. I have to admit, I am not a professional :/ if I try to start it, it says: "Job for hyperion.service failed. See 'systemctl status hyperion.service' and 'journalctl -xn' for details."

systemctl gives:
* hyperion.service - SYSV: Hyperion daemon
   Loaded: loaded (/etc/init.d/hyperion)
   Active: failed (Result: exit-code) since Thu 2016-02-18 00:52:30 CET; 37s ago
  Process: 497 ExecStart=/etc/init.d/hyperion start (code=exited, status=203/EXEC)

I think I might have to start over and reconfigure the first one. (I backed up the config file before I started.) But nevertheless I still need both of them to work. 
The grabber is not a problem, for these two I don't really need it, I just want to control the lights via the smartphone app for now. 

btw thank you for your quick replies, thats very nice to see :)

**Comment by brindosch** [comment]
yes, people are waiting up to 12 months for feedback ;)
For the moment i could not help you. Cause i never tested. Will see if i could gather more information

**Comment by vratixan** [comment]
Could this be a problem: in the wiki it says where to put the second config file and init.d file. But the files for the first hyperion are actually located somewhere else and there are just links to their locations. 

also, I think the command to create a hardlink in the wiki has the source switched with the destination. 
Sorry, I am not really that good at these things, but I would love to have it work. 
Maybe the author of the wiki article, @ro8in could also help?

**Comment by brindosch** [comment]
@vratixan 
Please have a look here, the wiki method is deprecated now
https://github.com/tvdzwan/hyperion/issues/486

Please close this issue, if this fit your needs. We could not.

**Comment by redPanther** [comment]
The pull request #518 regarding issue #486 have also hints how to setup multi led devices

**Comment by vratixan** [comment]
thanks, I'll look into that in a few days. Thank you!

**Comment by penfold42** [comment]
@vratixan   Are you using pi-blaster ?

The code looks buggy to me and im considering fixing it

**Comment by vratixan** [comment]
Yeah, I am using it. 
Would be cool if you'd work on that :) keep me up to date if you have any improvements. 
thanks

**Comment by penfold42** [comment]
#600

I've made some improvements
