### ISSUE TITLE
Problem with hyperion on my PI2

### ISSUE THREAD

**Issue by Bootscreen** [tvdzwan/hyperion#504]
Hy, 

i have a problem with hyperion on my PI 2 with OSMC. The SPI Devices exists and hyperion doesn't show any problems.
On my PI B it works without problems. 
and i don't find any differences except the following:

PI 2 gpio readall
    | BCM | wPi | Name | Mode | V | Physical
    | 11 | 14 | SCLK | ALT0 | 1 | 23 

PI B gpio readall
    | BCM | wPi | Name | Mode | V | Physical
    | 11 | 14 | SCLK | ALT0 | 0 | 23

could that be the problem or is my PI2 broken? I already testet a freash clean install but nothing changed.

or is it possible to use OSMC and KODI on the PI 2 and hyperion on the PI B ?

Greetings Bootscreen

**Comment by brindosch** [comment]
You followed all instructions at the wiki?
Please post the following output

journalctl -u hyperion.service

**Comment by Bootscreen** [comment]
Yes, on the PI B it works Finesse only on my PI 2 it doesn't work.

I'll post the output of the command when i'm back at home in a few hours.
Am 18.02.2016 10:39 vorm. schrieb "brindosch" <notifications@github.com>:

**Comment by Bootscreen** [comment]
the command output:
> journalctl -u hyperion.service
> No journal files were found.

**Comment by brindosch** [comment]
this is bad. or good
try this

systemctl enable hyperion.service

**Comment by Bootscreen** [comment]
What does the command? Hyperion already runs as User osmc automaticly
Am 18.02.2016 4:10 nachm. schrieb "brindosch" <notifications@github.com>:

**Comment by brindosch** [comment]
the first enables the services and the second output the status of hyperion

**Comment by Bootscreen** [comment]
the second?

**Comment by brindosch** [comment]
shows the status of hyperion

**Comment by Bootscreen** [comment]
sorry, i doesn't see the second command.

here is the output:

 hyperion.service - Hyperion
   Loaded: loaded (/etc/systemd/system/hyperion.service; enabled)
   Active: active (running) since Thu 2016-02-18 09:30:59 CET; 10h ago
 Main PID: 279 (hyperiond)
   CGroup: /system.slice/hyperion.service
           -279 /opt/hyperion/bin/hyperiond /etc/hyperion.config.json

**Comment by brindosch** [comment]
To be honest. I really could not see what is wrong here. You should get an output of hyperion.
One last idea. It is harsh!

Do the following
remove the crap from init.d, that the official script will install.

`update-rc.d -f hyperion remove`

Remove Hyperion with my remove_hyperion.sh script.

`wget -nv -N https://raw.github.com/brindosch/hyperionbeta/master/bin/remove_hyperion.sh`
`chmod +x remo*`
`./remo*`

Now install the latest build with my install script
Please have a look here. All questions should be answered there.
https://github.com/tvdzwan/hyperion/issues/493

Now all should running! There is no space that it shouldn´t! Please check your .config file if you encounter problems.

**Comment by penfold42** [comment]
What led type do you have ?

**Comment by Bootscreen** [comment]
@brindosch : i do what you say and nothing changed :(

@penfold42 : i use LPD8806

and i think the config is ok, because on my PI B it works fine.

**Comment by brindosch** [comment]
Nothing changed?
`service hyperion status`
just dead? nothing?

I am sure something is wrong with your config.
How do you copied your config to the Pi?
If you used putty, your file may be "corrupt"
Please try to copy it with WinSCP or similar program

**Comment by Bootscreen** [comment]
here is the status output:

> hyperion.service - Hyperion systemd service
   Loaded: loaded (/etc/systemd/system/hyperion.service; enabled)
   Active: active (running) since Fri 2016-02-19 22:21:52 CET; 17min ago
 Main PID: 284 (hyperiond)
   CGroup: /system.slice/hyperion.service
           -284 /opt/hyperion/bin/hyperiond /opt/hyperion/config/hyperion.config.json

and when i execute the command manually:
> Application build time: Feb 10 2016 01:50:15
QCoreApplication initialised
Selected configuration file: /opt/hyperion/config/hyperion.config.json
ColorTransform 'default' => [0; 147]
Device configuration:
{
        "colorOrder" : "brg",
        "name" : "MyPi",
        "output" : "/dev/spidev0.0",
        "rate" : 250000,
        "type" : "lpd8806"
}
Creating linear smoothing
Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Police Lights Single
Effect loaded: Police Lights Solid
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Effect loaded: X-Mas
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Black border threshold set to 0.01 (3)
DETECTION MODE:default
Boot sequence(Rainbow swirl fast) created and started
XBMC video checker created and started
Display opened with resolution: 1920x1080
Black border threshold set to 0.01 (3)
DETECTION MODE:default
Frame grabber created and started
Json server created and started on port 19444
Proto server created and started on port 19445
XBMC Connected
Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[]}
XBMC checker: switching to MENU mode
Message from XBMC: {"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":true}}
Message from XBMC: {"id":670,"jsonrpc":"2.0","result":{"version":{"major":15,"minor":2,"revision":"Unknown","tag":"stable"}}}
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
effect finished


and i copied the config normaly via explorer to an smb share on the pi, but i also tested it with filezilla.
Here is my config: http://pastebin.com/zAp6KL3G

**Comment by brindosch** [comment]
Looks better than yesterday ;)
Hyperion is running and even the kodi connection is online.
I have no more ideas at the moment. Are you sure this is no hardware problem?
Like you see, all is running fine.

**Comment by Bootscreen** [comment]
i hoped not but i already say it in my opening post. i'll test it next month with a new PI2.

a few minutes ago i tested the kodi plugin on my pi2 and it looks like it works.

**Comment by brindosch** [comment]
@Bootscreen 
Could this be closed? If yes, please close yourself - sad we could not

**Comment by brindosch** [comment]
I will close this, just open a new one!
Thank you

**Comment by chanyin** [comment]
Ok.. Been searching for hours, and I finally landed on this. 
It appears that I am having the same issue.

Hyperion does not appear to start.
But once OSMC starts, and I run this SSH command, then lightpack works.
`/opt/hyperion/bin/hyperiond /etc/hyperion.config.json`

Here is my log after a restart:

> root@osmc-Humphrey:/home/osmc# systemctl status hyperion.service
● hyperion.service - Hyperion Systemd service
   Loaded: loaded (/etc/systemd/system/hyperion.service; enabled)
   Active: failed (Result: start-limit) since Wed 2016-03-23 03:04:09 EDT; 14min ago
  Process: 421 ExecStart=/opt/hyperion/bin/hyperiond /etc/hyperion.config.json (code=killed, signal=SEGV)
 Main PID: 421 (code=killed, signal=SEGV)
Mar 23 03:04:08 osmc-Humphrey systemd[1]: Unit hyperion.service entered failed state.
Mar 23 03:04:09 osmc-Humphrey systemd[1]: hyperion.service start request repeated too quickly, refusing to start.
Mar 23 03:04:09 osmc-Humphrey systemd[1]: Failed to start Hyperion Systemd service.
Mar 23 03:04:09 osmc-Humphrey systemd[1]: Unit hyperion.service entered failed state.

This also appears at the top left of my tv on boot (pretty much telling me to look at the log):

![img_4511](https://cloud.githubusercontent.com/assets/4990683/13978316/6d51647c-f0a6-11e5-86f2-6fdbe3b6b85b.JPG)

**Comment by brindosch** [comment]
We need the complete log
try this
`journalctl -u hyperion.service`

**Comment by chanyin** [comment]
@brindosch 

> 


Logs begin at Wed 2016-03-23 03:04:00 EDT, end at Wed 2016-03-23 17:16:46 EDT. --
Mar 23 03:04:04 osmc-Humphrey hyperiond[288]: Hyperiond:
Mar 23 03:04:04 osmc-Humphrey hyperiond[288]: version   : V1.01.0 (brindosch-442731a/3c6ac5d-1458604914
Mar 23 03:04:04 osmc-Humphrey hyperiond[288]: build time: Mar 22 2016 01:17:13
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Selected configuration file: /etc/hyperion.config.json
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: ColorTransform 'default' => [0; 45]
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: ColorCorrection 'default' => [0; 45]
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: ColorCorrection 'default' => [0; 45]
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Device configuration:
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: {
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: "colorOrder" : "rgb",
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: "name" : "MyPi",
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: "output" : "95230303231351B0E032",
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: "rate" : 1000000,
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: "type" : "Lightpack"
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: }
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: USB context initialized
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Found a lightpack device. Retrieving more information...
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: unable to retrieve serial number from Lightpack device(-3): LIBUSB_ERROR_ACCESS
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Lightpack device found: bus=1 address=6 serial=
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: No Lightpack device has been found
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Creating linear smoothing
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Cinema brighten lights
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Cinema dim lights
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Knight rider
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Blue mood blobs
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Cold mood blobs
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Full color mood blobs
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Green mood blobs
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Red mood blobs
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Warm mood blobs
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Police Lights Single
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Police Lights Solid
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Rainbow mood
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Rainbow swirl fast
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Rainbow swirl
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Random
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Running dots
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: System Shutdown
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Snake
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Sparks Color
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Sparks
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Strobe blue
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Strobe Raspbmc
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Strobe white
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: Color traces
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: UDP listener
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Effect loaded: X-Mas
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Initializing Python interpreter
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Hyperion created and initialised
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Boot sequence 'Rainbow swirl fast' run effect Rainbow swirl fast on channel 0
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Black border threshold set to 0 (0)
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: DETECTION MODE:default
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: started
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Json server created and started on port 19444
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Proto server created and started on port 19445
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Display opened with resolution: 1920x1080
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Black border threshold set to 0 (0)
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: DETECTION MODE:default
Mar 23 03:04:05 osmc-Humphrey hyperiond[288]: Frame grabber created and started
Mar 23 03:04:05 osmc-Humphrey systemd[1]: hyperion.service: main process exited, code=killed, status=11/SEGV
Mar 23 03:04:05 osmc-Humphrey systemd[1]: Unit hyperion.service entered failed state.
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Hyperiond:
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: version   : V1.01.0 (brindosch-442731a/3c6ac5d-1458604914
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: build time: Mar 22 2016 01:17:13
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Selected configuration file: /etc/hyperion.config.json
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: ColorTransform 'default' => [0; 45]
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: ColorCorrection 'default' => [0; 45]
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: ColorCorrection 'default' => [0; 45]
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Device configuration:
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: {
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: "colorOrder" : "rgb",
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: "name" : "MyPi",
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: "output" : "95230303231351B0E032",
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: "rate" : 1000000,
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: "type" : "Lightpack"
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: }
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: USB context initialized
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Found a lightpack device. Retrieving more information...
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: unable to retrieve serial number from Lightpack device(-3): LIBUSB_ERROR_ACCESS
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Lightpack device found: bus=1 address=6 serial=
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: No Lightpack device has been found
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Creating linear smoothing
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Cinema brighten lights
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Cinema dim lights
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Knight rider
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Blue mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Cold mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Full color mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Green mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Red mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Warm mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Police Lights Single
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Police Lights Solid
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Rainbow mood
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Rainbow swirl fast
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Rainbow swirl
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Random
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Running dots
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: System Shutdown
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Snake
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Sparks Color
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Sparks
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Strobe blue
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Strobe Raspbmc
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Strobe white
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: Color traces
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: UDP listener
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Effect loaded: X-Mas
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Initializing Python interpreter
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Hyperion created and initialised
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Boot sequence 'Rainbow swirl fast' run effect Rainbow swirl fast on channel 0
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Black border threshold set to 0 (0)
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: DETECTION MODE:default
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: started
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Json server created and started on port 19444
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Proto server created and started on port 19445
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Display opened with resolution: 1920x1080
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Black border threshold set to 0 (0)
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: DETECTION MODE:default
Mar 23 03:04:06 osmc-Humphrey hyperiond[385]: Frame grabber created and started
Mar 23 03:04:06 osmc-Humphrey systemd[1]: hyperion.service: main process exited, code=killed, status=11/SEGV
Mar 23 03:04:06 osmc-Humphrey systemd[1]: Unit hyperion.service entered failed state.
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Hyperiond:
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: version   : V1.01.0 (brindosch-442731a/3c6ac5d-1458604914
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: build time: Mar 22 2016 01:17:13
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Selected configuration file: /etc/hyperion.config.json
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: ColorTransform 'default' => [0; 45]
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: ColorCorrection 'default' => [0; 45]
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: ColorCorrection 'default' => [0; 45]
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Device configuration:
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: {
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: "colorOrder" : "rgb",
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: "name" : "MyPi",
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: "output" : "95230303231351B0E032",
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: "rate" : 1000000,
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: "type" : "Lightpack"
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: }
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: USB context initialized
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Found a lightpack device. Retrieving more information...
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: unable to retrieve serial number from Lightpack device(-3): LIBUSB_ERROR_ACCESS
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Lightpack device found: bus=1 address=6 serial=
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: No Lightpack device has been found
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Creating linear smoothing
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Cinema brighten lights
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Cinema dim lights
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Knight rider
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Blue mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Cold mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Full color mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Green mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Red mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Warm mood blobs
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Police Lights Single
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Police Lights Solid
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Rainbow mood
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Rainbow swirl fast
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Rainbow swirl
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Random
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Running dots
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: System Shutdown
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Snake
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Sparks Color
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Sparks
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Strobe blue
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Strobe Raspbmc
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Strobe white
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: Color traces
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Effect loaded: UDP listener

**Comment by brindosch** [comment]
You are using another device, and there are some problems
```
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: "type" : "Lightpack"
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: }
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: USB context initialized
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Found a lightpack device. Retrieving more information...
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: unable to retrieve serial number from Lightpack device(-3): LIBUSB_ERROR_ACCESS
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: Lightpack device found: bus=1 address=6 serial=
Mar 23 03:04:06 osmc-Humphrey hyperiond[394]: No Lightpack device has been found
```
I just can redirect you to the lightpack support. I´m sorry
