### ISSUE TITLE
Unable to control multiple devices when using a capture card

### ISSUE THREAD

**Issue by metalshark** [tvdzwan/hyperion#507]
Does this require major re-coding to allow multiple devices to share a capture card or is there a solution?

https://github.com/tvdzwan/hyperion/wiki/Controlling-multiple-devices

**Comment by redPanther** [comment]
Look into issue #486 I'm implementing a solution for multiple hyperions (devices) over network. More details in the issue ...

**Comment by brindosch** [comment]
@metalshark 
Could this be closed?
Would be great if you could close this issue. If you have more question don´t hesitate to ask!
