### ISSUE TITLE
Compilation cmake error

### ISSUE THREAD

**Issue by hgch** [tvdzwan/hyperion#508]
Hi,

i'm trying to compile hyperion with ws2812b led comptability but i have always the same error.

-DENABLE_WS2812BPWM=ON

i'm following the tuto https://github.com/tvdzwan/hyperion/blob/master/CompileHowto.txt

Can anyone help me.

Run Build Command:"/usr/bin/make" "cmTryCompileExec843429402/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec843429402.dir/build.make CMakeFiles/cmTryCompileExec843429402.dir/build
make[1]: Entering directory '/home/osmc/test/hyperion1/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/osmc/test/hyperion1/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec843429402.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec843429402.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.0/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec843429402
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec843429402.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec843429402.dir/CheckFunctionExists.c.o  -o cmTryCompileExec843429402 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTryCompileExec843429402.dir/build.make:88: recipe for target 'cmTryCompileExec843429402' failed
make[1]: Leaving directory '/home/osmc/test/hyperion1/CMakeFiles/CMakeTmp'
Makefile:118: recipe for target 'cmTryCompileExec843429402/fast' failed
make[1]: *** [cmTryCompileExec843429402] Error 1
make: *** [cmTryCompileExec843429402/fast] Error 2

Thkx

**Comment by brindosch** [comment]
Things i learned:
It is never a good idea to compile on osmc.

Please use a Raspian Jessie instead. (tested it myself: working)
Thank you

**Comment by ntim** [comment]
I successfully compile hyperion on osmc. You maybe have to check if you met all prerequisites.

**Comment by ziggy73701** [comment]
I ran through the tutorial earlier as I needed for the same strip, followed word for word and worked 1st time using Raspian Jessie. Can only imagine you have something funky going on with the OS

**Comment by brindosch** [comment]
Would be great if you could close this issue. If you have more question don´t hesitate to ask!

**Comment by ziggy73701** [comment]
It's got me pondering I will be honest!  To my mind there must be a way to MAKE it work :)

**Comment by tpmodding** [comment]
i will try it in a few hours, i give you feedback!

**Comment by ziggy73701** [comment]
Legend!!!

If I can assist let me know, am good at moral support. Some say I even look pretty!

**Comment by hgch** [comment]
Hi,

Thanks everyone.

Compile accomplished....

:)
