### ISSUE TITLE
'No such file or directory' (OSError)

### ISSUE THREAD

**Issue by rjb1101** [tvdzwan/hyperion#511]
I'm using OpenELEC 6.0.1 and Hyperion 1.2.0

I get the following error when I use the Hyperion Config Creator:

OSError (2, 'No such file or directory')
Please report an error at github issue list

I'm getting this error after the screen,
"Compatible video grabber has been detected.  Do you want to enable video grabber in hyperion?"  Get the error when selecting both yes and no.

**Comment by rjb1101** [comment]
Also if it helps I'm using a Raspberry Pi 2.

**Comment by tpmodding** [comment]
could you post your config on pastebin and give us the link?

**Comment by rjb1101** [comment]
What is pastebin?  What do you mean by my config?

**Comment by rjb1101** [comment]
Here is the url for the pastebin:
http://pastebin.com/AyfKqUpc

This is the hyperion.config.new file that I downloaded.  I don't know if there is a file on the Pi in openELEC that you are looking for.

**Comment by brindosch** [comment]
As far as i know, Hyperion is not responsible for Lightberry plugins.
Please redirect your question to the lightberry support.
Thank you

-would be great if you could close this issue

**Comment by rjb1101** [comment]
My problem is that I can't get hyperion to finish installing.

**Comment by brindosch** [comment]
I recommend to ask the lightberry support. You payed for it.

**Comment by acognard** [comment]
hello, do you a have solution with this issue ? Having same pb on RPI3 OpenElec. tks in advance.

**Comment by brindosch** [comment]
Not our addon, please ask the devs for a fix

**Comment by acognard** [comment]
tks for your reply, the question was for rjb1101 ;)

**Comment by tociek** [comment]
Just kind reminder, that kodi addon is also on github and all  issues should be reported there. I will be happy to provide the fix, if needed.
