### ISSUE TITLE
XBMCVideoChecker - Remote KODI

### ISSUE THREAD

**Issue by ziggy73701** [tvdzwan/hyperion#513]
Hi, am I correct in thinking I should be able to connect to a remote kodi installation using the configuration below, or will it only work with a localhost? Am running KODI 16 on a NVIDIA Shield, if I use the service addon it works. So am happy the system is ok, I was just wondering if I could use the below to get audio etc as well... or am I missing something!?!

 	"xbmcVideoChecker" : 
 	{
 		"xbmcAddress" : "10.12.0.65",
 		"xbmcTcpPort" : 9090,
 		"grabVideo" : true,
 		"grabPictures" : true,
 		"grabAudio" : true,
 		"grabMenu" : false,
 		"grabScreensaver" : true,
 		"enable3DDetection" : true
 	},

**Comment by p1n9** [comment]
hi,
I have the same issue as you, my kodi is on a nuc.
My config : 
```
"xbmcVideoChecker" : 
{
    "xbmcAddress" : "192.168.0.39",
    "xbmcTcpPort" : 7070,
    "grabVideo" : true,
    "grabPictures" : true,
    "grabAudio" : true,
    "grabMenu" : true,
    "grabScreensaver" : true,
    "enable3DDetection" : true
},

```
hyperiond log show "XBMC Connected" but that's all and no led light up.
I've set http password in kodi but with or without it's the same result.

Any one have an idea ?

**Comment by brindosch** [comment]
As far as i know, there is was never support for other targets than localhost.
I´m sorry

Would be great if you could close this issue. If you have more question don´t hesitate to ask!

**Comment by p1n9** [comment]
So why put `xbmcAddress` in config file if the only valid option is `127.0.0.1` ??
