### ISSUE TITLE
Any interest in a new ws2801/SPI to ws2812 converter?

### ISSUE THREAD

**Issue by penfold42** [tvdzwan/hyperion#516]
I've been testing a new high speed 2801 to 2812 converter. 

It supports attiny13. Attiny85 and atmega328 chips but will probably run on any tiny or mega with a clock speed > 8mhz.

It's designed to be fast.... Like wire speed fast with no limit to the number of leds.

**Comment by brindosch** [comment]
Any news on this?

**Comment by penfold42** [comment]
Now that I've tracked down the SPI speed problem on the pi, I'll upload this to my github repo soon.

**Comment by brindosch** [comment]
Great! Please add this to wiki ;)
I will close it
