### ISSUE TITLE
Raspberry Pi 2 B+ - LED 2801

### ISSUE THREAD

**Issue by jOhnyy5** [tvdzwan/hyperion#519]
I've got: OSMC + RPi2 B+ + WS2801 + LIRC(IR). After an OSMC upgrade (not sure exactly), the LEDs just stopped working. One site is lighting white(?). 

I've reinstalled Hyperion, then entire OSMC using the latest version, then using older OSMC images, then different combinations in config.txt

My wiring setup is: a separate PSU for the LEDs and the RPi, with sharing the LEDs' ground to Rpi and with RPi's GPIO18 connected to the LEDs. 

osmc@osmc:~$ sudo service hyperion status   

```
 * hyperion.service - SYSV: Hyperion daemon
   Loaded: loaded (/etc/init.d/hyperion)
   Active: active (running) since Sun 2016-02-28 17:28:19 CET; 51min ago
  Process: 188 ExecStart=/etc/init.d/hyperion start (code=exited, status=0/SUCCE          SS)
   CGroup: /system.slice/hyperion.service
           `-197 hyperiond /etc/hyperion.config.json

Feb 28 17:28:19 osmc hyperion[188]: Starting hyperiond...                  ...Ok
Hint: Some lines were ellipsized, use -l to show in full.

```
osmc@osmc:~$ hyperion-remote --priority 50 --color red --duration 5000                    Connected ```
to localhost:19444
Set color to 255 0 0
```
osmc@osmc:~$ sudo service hyperion stop && sudo /usr/bin/hyperiond /etc/hyperion.config.json
```
```
Application build time: Feb 23 2016 21:14:12
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 49]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "/dev/spidev0.0",
        "rate" : 250000,
        "type" : "ws2801"
}

Not creating any smoothing
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Police Lights Single
Effect loaded: Police Lights Solid
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Effect loaded: UDP listener
Effect loaded: X-Mas
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Black border threshold set to 0.01 (3)
DETECTION MODE:default
Boot sequence(Rainbow swirl fast) created and started
XBMC video checker created and started
Display opened with resolution: 1920x1080
Black border threshold set to 0.01 (3)
DETECTION MODE:default
Frame grabber created and started
Json server created and started on port 19444
Proto server created and started on port 19445
XBMC Connected
Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
XBMC checker: switching to VIDEO mode
Message from XBMC: {"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":false}}
Message from XBMC: {"id":667,"jsonrpc":"2.0","result":{"item":{"file":"rtmp://95.211.141.2                                                                              25/channel/1258/liveHI live=true pageUrl=token swfUrl=275223200","label":"HBO 2 HD","type"                                                                              :"unknown"}}}
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
Message from XBMC: {"id":670,"jsonrpc":"2.0","result":{"version":{"major":15,"minor":2,"re                                                                              vision":"Unknown","tag":"stable"}}}
effect finished

```

osmc@osmc:~$ sudo systemctl enable hyperion.service
Synchronizing state for hyperion.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d hyperion defaults
insserv: warning: script 'K01hyperion' missing LSB tags and overrides
insserv: warning: script 'hyperion' missing LSB tags and overrides
Executing /usr/sbin/update-rc.d hyperion enable
update-rc.d: error: hyperion Default-Start contains no runlevels, aborting.
```



osmc@osmc:~$ sudo nano /etc/hyperion.config.json
[http://pastebin.com/EKuBvXuz]

**Comment by tpmodding** [comment]
could you try this one pls http://pastebin.com/3dWdA3Hm

**Comment by brindosch** [comment]
As a last suggestion. Try from the beginning


to start from scrath, do the following. Type in line by line
remove the crap from init.d, that the official script will install.

`update-rc.d -f hyperion remove`

Remove Hyperion with my remove_hyperion.sh script.

`wget -nv -N https://raw.github.com/brindosch/hyperionbeta/master/bin/remove_hyperion.sh`
`chmod +x remo*`
`./remo*`

Now install the latest build with my install script (osmc support)
Please have a look here. All questions should be answered there.
https://github.com/tvdzwan/hyperion/issues/493

**Comment by jOhnyy5** [comment]
> 
could you try this one pls http://pastebin.com/3dWdA3Hm
> 
Nothings change.

**Comment by brindosch** [comment]
All possible software errors should be solved now.
Sad to say. This may be a hardware fault.

**Comment by jOhnyy5** [comment]
Tommorow i will test it with Arduino Thanks

**Comment by tpmodding** [comment]
@jOhnyy5 does it work? can be closed? :)

**Comment by brindosch** [comment]
/Closed
Just open a new one if you have problems.
