### ISSUE TITLE
Hyperion (on x86 linux) with WS2812B and Arduino UNO R3 clone - large number of LEDs stops working after a few minutes

### ISSUE THREAD

**Issue by Kleeo** [tvdzwan/hyperion#521]
Hi, I don't really consider this a Hyperion issue, but I'm hoping to benefit from your experience with Hyperion and different hardware setups.

Regarding my issue:
I have built an Ambilight with Hyperion, which is in use with Kodi and the corresponding add-on. 
The components are:
- 3.50m WS2812B LED Strip (a total of 200 LEDs in 4 sub strips)
- Arduino Uno R3 clone for driving the LED Strip (connected via USB to the x86 pc running Kodi)
- Kodi on a standard x86 computer running Ubuntu 14.04
- Hyperion compiled from GIT for x86 (running on the same computer as Kodi)
- Power is provided from the ATX power supply of the Kodi computer

In the first few days everything went fine. After tweaking the config (smoothing, etc.) the speed and quality of the ambient lighting was awesome.

Then the issue started. Some LEDs stopped to respond a few minutes after powering on. This means, for example, up to the 50th LED everything was normal, from the 51st including all
following the last color got "stuck". A reboot fixes the problem for some time. Then it happens again. I then tinkered with the speed settings (for the USB serial connection) and with the serial buffer of the Arduino. But all of this didn't help. After that I replaced the LEDs starting with the 50th (in my example) until the end of that sub-strip (it's a total of four sub-strips). That helped for a few days. Then the same thing happened again starting at another LED index. 

I changed that section of the affected sub-strip again. Today it has happened again after powering up the strip for just a few minutes. The first 30 LEDs are working normally (following the screen content). The others remain "stuck". Sometimes they come back for a short period of time, only to get stuck again showing the last color. After restarting the computer (incl. USB connected Arduino) it works again for a few minutes.

I have tried a few things including putting a resistor in the data line to protect the first LED, trying different 'adalight' Arduino sketches, increasing the serial buffer of the Arduino, replacing the UNO R3 clone with an original Arduino Duemilanove and I want to add the recommended 1000 mikrofarad capacitor in the 5V power line next. However, I am not optimistic.

Maybe someone here has seen something like this and has an advice what the issue might be or what else I can try to narrow it down.

Thanks, Kleo

**Comment by ziggy73701** [comment]
How are you powering your LEDs? I use the same strips and found my early issues all came down to lack of power... Similar setup, 4 strips totalling sound 170 LEDs. In the end I went for separate power for the LEDs, 5v 10a and that sorted it. This site contains a pretty good write up https://www.pololu.com/product/2547

**Comment by Kleeo** [comment]
Thanks, I'll try that. I'm powering the strip from one side with a connection to the KODI computer's power supply. I've connected the strip to a 5V drive connector. But thinking about it, I never checked the specs of the power supply and whether it can handle up to 10A or 12A on the 5V rail. Probably not. There's not many drives around, that consume that kind of power. ;) Therefore thanks for the advise.

**Comment by tpmodding** [comment]
@Kleeo can this be closed?

**Comment by Kleeo** [comment]
Since it's not a real software issue and probably no Hyperion issue at all...yes, please go ahead and close it. Thanks

Am 2. März 2016 23:11:59 MEZ, schrieb tpmodding <notifications@github.com>:
>@Kleeo can this be closed?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tvdzwan/hyperion/issues/521#issuecomment-191456111

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by tpmodding** [comment]
@Kleeo i cant, could you close it please

**Comment by Kleeo** [comment]
Okay, will do it tonight.

Am 2. März 2016 23:45:45 MEZ, schrieb tpmodding <notifications@github.com>:
>@Kleeo i cant, could you close it please
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/tvdzwan/hyperion/issues/521#issuecomment-191476400

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Floyddotnet** [comment]
@Kleeo: Can you please report your **working** steps for compiling hyperion für x86. I would build the same Setup with 160 LEDs and switch to hyperion from boblight. Especially your cmake-Settings?

**Comment by redPanther** [comment]
please read:
https://github.com/hyperion-project/hyperion/blob/master/CompileHowto.txt
there are the opts for x86. Or you use latest development hyperion:
https://github.com/hyperion-project/hyperion.ng

and do it like that:
```
mkdir build
cd build
cmake -DPLATFORM=x86 -DCMAKE_BUILD_TYPE=Release ..
make -j $(nproc)

```
