### ISSUE TITLE
RPi B+ Random Color Flashes

### ISSUE THREAD

**Issue by NemsMole** [tvdzwan/hyperion#522]
I've recently gotten Hyperion up and running on my LED set up which was previously running Boblight.

Since switching over, I'm having an issue (which I've seen documented here somewhat) where lights on all sides of the strip will randomly flash colors rapidly. It seems related to the frame-grabber, the colors are often close to whatever is actually on screen (I.E. if I leave it at OSMC's home page, its blue with random flashes of green) and are very rapid.

I've fiddled with various config arrangements, adjusting Baudrate, width, height and intervals and so far I've not been able to figure out a root cause. If I lower the Width and Height of the grabber, it seems to help some, but I can only lower it so far before the lights stop responding or it becomes pointless.

I've also replaced the data wires, though I may redo that also just to be sure, but I'm pretty certain that the hardware isn't at fault, boblight worked without flashes.

I've attached a video of an example of the flashes - https://www.youtube.com/watch?v=Z4K5hKJ_JKc

I've heard there's a solution regarding kernal versions, could anyone illuminate me on that or anything else for me to try? Perhaps someone could send me a clean and functional .config file for me to try?

**Comment by penfold42** [comment]
Does it happen when plying an effect rather than grabbing ?

What led strip is it and how is it connected ?

**Comment by NemsMole** [comment]
Functions perfectly nicely when playing effects and displaying solid colors from the app.

The strip is a WS2801, I have it connected directly to the pi via GPIO and powered by its own 5v 2A psu.

**Comment by penfold42** [comment]
Is 2A enough ? How many LEDs and what current are they each rated at ?

If this were a ws2812 you would only have enough power for 2/.06 = 33 LEDs

**Comment by NemsMole** [comment]
50 LEDs total, adafruit ( https://www.adafruit.com/products/322)  says that
2A is plenty for a single set, and it runs fine both during effects and
when I have boblight running instead of Hyperion.

**Comment by tpmodding** [comment]
do you use a usb grabber? if yes 2A isnt enough for all...i would recommended 2 different psu one only for rpi and one for the leds

**Comment by NemsMole** [comment]
I do not use a grabber yet, I already use two PSUs, one for the Pi and one for the LEDs. I can see if hooking up something with more amps will work but I'm still doubting this is a power issue.

**Comment by tpmodding** [comment]
ok, could you post your config on pastebin.com and give us the url pls

**Comment by NemsMole** [comment]
Sure thing.
I've gone through a couple, but this is my current one;
http://pastebin.com/wNUXNVxC

And thanks for the help! This is a brilliant project, even just the ability to control the backlight via phone app is pretty dang cool.

**Comment by tpmodding** [comment]
http://pastebin.com/sZfA4GLx

try this pls

**Comment by NemsMole** [comment]
Thanks!
Still the same green blinks. Slightly reduced in how often but still
happening.

On Mon, Feb 29, 2016 at 7:09 PM, tpmodding <notifications@github.com> wrote:

> http://pastebin.com/sZfA4GLx
>
> try this pls
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tvdzwan/hyperion/issues/522#issuecomment-190459312>.
>



-- 
-L

**Comment by tpmodding** [comment]
did you tested the   "xbmcVideoChecker" ?

**Comment by NemsMole** [comment]
I'm not sure what you mean by that, test it how?

On Mon, Feb 29, 2016 at 7:15 PM, tpmodding <notifications@github.com> wrote:

> did you tested the "xbmcVideoChecker" ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tvdzwan/hyperion/issues/522#issuecomment-190462259>.
>



-- 
-L

**Comment by tpmodding** [comment]
http://pastebin.com/mTM5TSdY try this :)

**Comment by NemsMole** [comment]
That activated a hereto-unseen SUPER DISCO MODE I was unaware of in the
hardware. Very nice for my nightly raves but on the downside, I am now
blind.

Seriously though, significantly more blinking and crazy colors than before.

On Mon, Feb 29, 2016 at 7:22 PM, tpmodding <notifications@github.com> wrote:

> http://pastebin.com/mTM5TSdY try this :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tvdzwan/hyperion/issues/522#issuecomment-190465854>.
>



-- 
-L

**Comment by NemsMole** [comment]
Ok, so I was fiddling with the phone app, and I've managed to replicate the blinking in that too, but only at a very specific part of the brightness bar option, I'd say around 10-15% of the bar? The minute I bump it up to around 30%+ it stops and is entirely stable.

Unless I'm mistaken I'd say that confirms an issue with my PSU?

**Comment by tpmodding** [comment]
try and error...think its the best to try another one or maybe switch the to

**Comment by redPanther** [comment]
Just a hint. We already discovered strange behaviour of leds. One solution was a level shifter between leds signal and raspi. 
The leds have 5v signal and raspi has 3.3v

Optimal setting for hardware: enough power as mentioned. Level shifter and ground and +5v connected to both sides of the stripe.

**Comment by NemsMole** [comment]
I'll give the extra power a try, and then try a level shifter, but I notice that when this issue has come up before, the OPs have tried these things to little success

https://github.com/tvdzwan/hyperion/issues/214

Actually while I'm here - Is there a simple way to force all the LEDs to always be "Brighter" in all situations?

**Comment by tpmodding** [comment]
{
                    "saturationGain" : 1.0000,
                    "valueGain"      : 1.0000
                },
change these values... go higher.. eg 1.2 1.6 but dont go direct to 2.0, could be to much/bright

**Comment by NemsMole** [comment]
My thinking is that if it displays ok at higher brightness/saturation, that may be a good middle ground fix till I find out why it's so bad at low luminosity.

And it seems to be working. I need to crank it up to 2.5 but basically zero blinking right now.

**Comment by NemsMole** [comment]
Update: It's almost certainly a PSU issue. I replaced the PSU with an 8A 5V one and have had zero flicker or random blinking. I would advise anyone building this project to ensure they have at least 5a just to be safe.

**Comment by rudelm** [comment]
@NemsMole which PSU did you order? I've ordered a 5V 10A adapter for 104 LEDs and I was not able to use it properly without heavy blinking. My current 5V 3A adapter works with this high number of LEDs but I also have this white blinking from time to time.

**Comment by NemsMole** [comment]
I grabbed this one - http://amzn.to/21DMKU0 based on a friend's
recommendation. Working flawlessly for the past 3~ hours.

On Wed, Mar 2, 2016 at 2:18 PM, Markus Rudel <notifications@github.com>
wrote:

> @NemsMole <https://github.com/NemsMole> which PSU did you order? I've
> ordered a 5V 10A adapter for 104 LEDs and I was not able to use it properly
> without heavy blinking. My current 5V 3A adapter works with this high
> number of LEDs but I also have this white blinking from time to time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tvdzwan/hyperion/issues/522#issuecomment-191381617>.
>



-- 
-L

**Comment by rudelm** [comment]
@NemsMole thank you for the link. I'll try to use my small adapter for now and will think of yours when it starts to flicker again.
