### ISSUE TITLE
Blacklevel causes lights to be on when they should be off during Kodi menu

### ISSUE THREAD

**Issue by DropbearNinja** [tvdzwan/hyperion#524]
Firstly, amazing piece of software, thank you kindly for producing it.

Secondly, I'm not sure this is an issue or just that I'm using it wrong. 

Setup: kodi add-on, hyperion, raspberry pi2 (raspbian), apa102 leds, no direct capture.

I like to use the 'black level' setting, so that when watching something there is a constant minimum level of background illumination. I have it set to the lowest just so that all LEDs are always on during playback. Works beautifully.

However, I also use XBMC checker, which is set to OFF for MENU and ON for VIDEO.

The LEDs are sort of OFF when viewing the menu in the sense they don't capture the screen, but they DO follow the minimum black level rule; so they're at 0.01. During playback they appropriately come ON properly and capture the screen.

Is this intended behaviour, a bug (i.e. they should be completely off when viewing the menu as per the XBMC checker rule) or incorrect setup?

Cheers

Config: http://pastebin.com/Cmigd20f

**Comment by tpmodding** [comment]
First: could you please edit your post and paste your config to pastebin.com and give us the URL...

and now your problen:
Why you use
  "xbmcAddress" : "192.168.1.3", and not  "xbmcAddress" : "127.0.0.1",
Do you use 2 RPis or only one?

**Comment by brindosch** [comment]
This is normal behaviour,
the kodi checker is not affected from blacklevel value and vice versa.
the blacklevel is always set

**Comment by DropbearNinja** [comment]
Thanks brindosch; that answers my query exactly, but is unfortunately not the behaviour I'd like - is there anything I can do my end to achieve the effect I'm after?

tpmodding; I use "xbmcAddress" : "192.168.1.3" since kodi runs on a different system, a HTPC.

**Comment by tpmodding** [comment]
do this work for you? @brindosch and i tested this function, doesnt work for us...only on localhost(127.0.0.1)

**Comment by brindosch** [comment]
I added a new point on the long list for hyperion todos -> Ignore Blacklvl value if kodi option is set to off
As far as i know, no. I´m sorry

You get it working with "external" ip? How? We never could do this :)

**Comment by DropbearNinja** [comment]
Sorry guys, don't know what to tell you. I just entered my HTPC's (a windows 10 PC) IP in hypercon and it worked first go... If I can provide any details to aid in figuring out why it works, please let me know.

**Comment by brindosch** [comment]
@tpmodding 
Maybe the windows firewall blocks.

@DropbearNinja 
You could close it. Thank you
