### ISSUE TITLE
HyperionV4L2/USB Grabber not grabbing whole screen

### ISSUE THREAD

**Issue by NemsMole** [tvdzwan/hyperion#527]
My grabber seems to be missing the bottom 15% of my screen. I'm pretty sure this is a USB grabber issue but I wanted to know if anyone else here has had this issue.

I am using the EasyCap grabber, it's a chipset supported by Hyperion and running fine for the vast majority of the screen.

My config file is as such;

```
{
		"device" : "/dev/video0",
		"input" : 0,
		"standard" : "no-change",
		"width" : 1,
		"height" : 1,
		"frameDecimation" : 2,
		"sizeDecimation" : 6,
		"priority" : 800,
		"mode" : "2D",
		"cropLeft" : 25,
		"cropRight" : 9,
		"cropTop" : 22,
		"cropBottom" : 0,
		"redSignalThreshold" : 0.4,
		"greenSignalThreshold" : 0.2,
		"blueSignalThreshold" : 0.2
	},

```

I've attached a screenshot using basically the above settings too, and one of my actual desktop for comparison.

What's happening here? Is it some weird issue with the resolution? I can't force it any 'better' than 720x480.

Actual Desktop - 
http://i.imgur.com/peIhWs5.png
V4L2 shot - ![screenshot](https://cloud.githubusercontent.com/assets/17555237/13516999/35d5bd40-e18d-11e5-8684-63da42f4b91f.png)

Edit: ignore the green lines and cropping, minor bug.

**Comment by tpmodding** [comment]
{
        "device" : "/dev/video0",
        "input" : 0,
        "standard" : "no-change",
        "width" : 1, <---- you use only 1pixel for width
        "height" : 1, <----- and 1pixel for height... only have an 1x1 picture to work with...
        "frameDecimation" : 2,
        "sizeDecimation" : 6, <--- your 1x1 picture is /6 :)
        "priority" : 800,
        "mode" : "2D",
        "cropLeft" : 25, <---cut 25px from your 1pixel
        "cropRight" : 9, <---- cut 9pixel from your 1pixel 1 -(25+9)= no picture :D
        "cropTop" : 22, <---cut 22pixel from your 1pixel
        "cropBottom" : 0,
        "redSignalThreshold" : 0.4,
        "greenSignalThreshold" : 0.2,
        "blueSignalThreshold" : 0.2
    },

instead try this one

{
        "device" : "/dev/video0",
        "input" : 0,
        "standard" : "no-change",
        "width" : -1,
        "height" : -1,
        "frameDecimation" : 2,
        "sizeDecimation" : 6,
        "priority" : 800,
        "mode" : "2D",
        "cropLeft" : 25,
        "cropRight" : 9,
        "cropTop" : 22,
        "cropBottom" : 0,
        "redSignalThreshold" : 0.4,
        "greenSignalThreshold" : 0.2,
        "blueSignalThreshold" : 0.2
    },

did you do your screenshot with that config you use?
	hyperion-v4l2 --width 1 --height 1 --crop-left 25 --crop-right 9 --crop-top 22  -s 6 -f 2 --screenshot

**Comment by NemsMole** [comment]
I goofed with that, I am actually using -1 in both width and height, that
shot I posted shows that.

**Comment by brindosch** [comment]
This could be a pal/ntsc issue
try to force your pal/ntsc setting
if you use a hdmi to cvbs converter play around there too

**Comment by NemsMole** [comment]
@brindosch That was it! Apparently my US PC and my US TV output in PAL. Who knew. Thanks!
