### ISSUE TITLE
(off-topic) why stk1160/utv007 works but grabbing video is not working correctly

### ISSUE THREAD

**Issue by pete111** [tvdzwan/hyperion#528]
Hello, this is off-topic question. I wondered why hyperion with stk1160/utv007 usb grabber is working correctly (nice colors are produced) but when I use the same grabber for video grabbing I see video with many artefacts?   (with the same RPi) 

Thanks for answer.

**Comment by tpmodding** [comment]
Could you explain your "artefacts" or show us with a screenshot

**Comment by pete111** [comment]
It looks like [this screenshot](http://postimg.org/image/nulgsb48z/) and [this](http://postimg.org/image/yzsbwajst/)
I am using powered usb hub so power is not source of problem.  I am simply not able to get good quality  picture when grabbing from usb grabber. And at the same time I don't understand if v4l2 grab so low quality images (with artefacts) how it is possible that hyperion lights work great with those pictures... Strange...

**Comment by brindosch** [comment]
This is part of the digital <> analog convert. Results may vary from converter to converter too.
But it is working.

If this satisfies you, please close it
Thank you

**Comment by pete111** [comment]
found out it is "overclocking issue" again. When overclocked RPI to 1000mhz, video picture is much better.
