### ISSUE TITLE
Hyperion blue color is green and green clor is blue

### ISSUE THREAD

**Issue by jelmert24** [tvdzwan/hyperion#529]
Hi,
I'm a big fan off the raspberry pi with hyperion.
But i have a little problem with it. When i select or test my color i see that the blue color is green and the green color is blue. The red color is good.
Is it possible to calibrate the colors or something like that?
I'm using a raspbery 1 model b

Thanks a lot!

**Comment by RickDB** [comment]
Hi,

On the top of your Hyperion config (hyperion.config.json) you can re-arrange the colors, it's in this section and called **colorOrder**:

```
"device" :
	{
		"name"       : "yourdevice",
		"type"       : "APA120",
		"output"     : "/dev/spidev0.0",
		"rate"       : 1000000,
		"colorOrder" : "bgr"
	},
```

Also available in the HyperCon tool and named the same there, depending on your device type the default order varies (BGR for APA102 as in example).

**Comment by Chrunchy** [comment]
I had the same issue. Setting the type RBG in hyperon solved it for me (default is RGB)

**Comment by jelmert24** [comment]
That works for me, thanks!

**Comment by brindosch** [comment]
@jelmert24 
Glad that this worked for you.
Could you please close this issue yourself? We can´t.
thank you

**Comment by kundusandeepan** [comment]
Awesome, the color order worked for me. later to realize, it can be selected in the hypercon tool as well.
