### ISSUE TITLE
Hyperion not working on Raspberry Pi 3

### ISSUE THREAD

**Issue by Will1707** [tvdzwan/hyperion#530]
I have tried installing hyperion on OSMC and openELEC and it dosent work on either of them. I'm 100% sure it is wired up correctly, having checked it many times. I am using a WS2801 strip which  I have confirmed to work with an arduino. It installs without any errors and I have changed the config.txt file and updated the configuration file. I have tried for 2 days to get this working without any success. Do you have any hints that might help?

**Comment by brindosch** [comment]
You downloaded the new RPi3 image from OSMC site?
You are not the first one who struggled with the install on OSMC (even with wiki!)

Sad that you spent 2 days for this! I Just copy/paste myself now

To start from the beginning, do the following. Type in line by line

Remove Hyperion with my remove_hyperion.sh script.

`wget -nv -N https://raw.github.com/brindosch/hyperionbeta/master/bin/remove_hyperion.sh`
`chmod +x remo*`
`./remo*`

Now install the latest build with my install script (osmc support)
Please have a look here. All questions should be answered there.
https://github.com/tvdzwan/hyperion/issues/493

**Comment by penfold42** [comment]
Does it report any errors if you start it directly from the command line ?

Does /dev/spidev0.0 exist ?

What if you cat /etc/hosts > /dev/spidev0.0 ?

**Comment by YodAXL** [comment]
I am trying to get a ws2812b ledstrip to work on a raspberry pi 3 with xbian but I cannot seem to get it to start.
I used the install script by @brindosch 
When I try to run hyperion-remote --priority 50 --color red --duration 5000 it replies with:
Unable to connect to host

I updated the config file to support ws2812b.

I downloaded the hyperiond file from @zappatron and replaced the one in /opt/hyperion/bin/
Gave me the same result.

Then I tried a different ledstrip: ws2801 and changed the config file to ws2801 and put the old hyperiond from the installation script back and that also gives me Unable to connect to host.

What am I doing wrong here or what is different for the xbian distribution?

**Comment by brindosch** [comment]
1. I never tested my install script with xbian. Have to do this these days.
2. We have no official support for Rpi2/3 + PWM driven leds (ws2801 work on all Rpis) 
See wiki https://github.com/tvdzwan/hyperion/wiki/WS2812b-PWM
3. the binrays i provide have no pwm support enabled. It won´t run with pwm leds

**Comment by Will1707** [comment]
I tried again with the install script on a fresh install of OSMC and added by config file but it still dosen't work. I dont get any errors when i start or stop hyperion but when I send a test command it says 'unable to connect to host'

**Comment by brindosch** [comment]
@Will1707 
Could you provide a hyperion log?
Thank you
