### ISSUE TITLE
vertical gap or 90° in HyperCon.jar

### ISSUE THREAD

**Issue by fR33Styler-1971** [tvdzwan/hyperion#531]
I use this wonderful stuff for a ambilight for my virtual pinball ([http://www.dietle.de/projekt-vpin-virtueller-flipper/](http://www.dietle.de/projekt-vpin-virtueller-flipper/))

The Playfield-Monitor is vertical (so 90° rotation)... so my LED-Gap for me is instead "bottom gap" a "left vertical gap"... means that the config does not work in vertical... it´s still horizontal (also when the screen in windows is set to vertical) :-(

Can someone help me with use the "bottom gap" as vertical gap in HyperCon.jar?
(or a other idea to rotate the screen?)

Br
Ralf

**Comment by tpmodding** [comment]
Hi,

Could you close this issue and open it here:

https://github.com/tvdzwan/hypercon

Thanks!

Von meinem iPhone gesendet

**Comment by fR33Styler-1971** [comment]
sure. Thanx for feedback
