### ISSUE TITLE
[idea] hyperion version number

### ISSUE THREAD

**Issue by redPanther** [tvdzwan/hyperion#537]
we need a version number for every build so we can identify the origin.

I suggest we use git infos to build a version id.
we can execute following command:
```git log -1  --format="%t/%h (%cn %ci)"```
during cmake and put the output into a "version.h" file. Then we can output the version at boot for identification. 
The output looks similar to that:
``` af99833/816821d (redpanther 2016-03-09 11:03:20 +0100) ```
In addition we can add the build date to, if this is helpfull.

Implementing this is a very quick job. One downside has this method. When compiling git must be available - but this should be manageable for person who provide official builds ...

(BTW I do something similar with subversion in my job and this works great - never not updated version numbers)

**Comment by brindosch** [comment]
Auto generated version numbers are great but, if people say (or you see it in the log)
"I have version af99833/816821d" i think it is harder to understand, but the build time is really good!

On the other hand, we never have to push the version by hand.
On the other hand i can´t hold this "even" with HyperCon to indicate compatiblity. I thought about to integrate the HyperCon version in the header of the config too. We know than with wich version it is created.
I have to thought about it.

Other comments are appreciate :)

**Comment by NicoHood** [comment]
I'd use the git commit as special git commit identifier but also introduce a better readable tag system, starting from 2.0.0 (since the project has now taken over from the community). Then people can visualy see if a new version is available. And if you recompiled the code on your own the git commit stll shows you exactly where you are in the history. So I'd vote for a mix. A lot of bigger projects do it like that.

**Comment by redPanther** [comment]
I suggest we make official binaries only from tags. Then we can take the name of the tag (e.g. v0.1.42) to display. In addition we show a build ID with "cryptic" numbers so we can identify exactly.

If made a branch for this topic: [hyperion_version_id](https://github.com/redPanther/hyperion/tree/hyperion_version_id)

**Comment by brindosch** [comment]
This is a good idea (so we have to create a "tag" in github first and then we compile builds and th last thing is adding the .tar.gz to it?)

One more idea. Make it sense to place the "target platform" too? (pi/x32/x64)
If someone used the wrong bin (manual install) you will see this immediately in the log.
Just a thought.

Thank you for you efforts

**Comment by redPanther** [comment]
in cmake we can make the complete deployment process. The tar.gz could be created and named automaticly (even uploading is possible). I already thought about cmake "meta switches" to compile for ...-platform so we avoid writing extra shell scripts or doing this manualy.

btw. I would love to see that we make tags. Not after every merge, but after a milestone (what ever that is ... bugfixes, time (e.g. every month), features ...)

we should switch to a model of developer builds and release builds.
devolper builds will have the version "master (....)" and release/tag  will have the version "v0.1.42 (...)"

I compiled the latest tag 0.1.42 (with me changes) and this is the output:
during cmake/configure phase:
```-- Current Version: v0.1.42 (redpanther-af99833/816821d-1457517800)```

on startup:
```Application build time: Mar 10 2016 10:40:48
Hyperion initialised, Version: v0.1.42 (redpanther-af99833/816821d-1457517800)```

(redpanther-af99833/816821d-1457517800) means:
author - tree id/last commit id - last commit unix time

**Comment by brindosch** [comment]
Wow, this sounds great.
Maybe we could "sort" aut the files that we don´t need for release image x (at the moment, all builds contain gpio2spi)
Also we need a additional service file for initctl
One with spi (spi platforms)
One without (x32 x64 leads to errors)

One last thing. How could i curl/wget the images from the "release" dir (the latest!) there is always the version number in between.
I found a command, but the dependencies for openelec and raspbian are not given.

**Comment by redPanther** [comment]
I updated my branch.
I also add an option "ENABLE_TESTS" - this is OFF by default.
If ENABLE_TESTS is OFF only the release important files are generated.

Then I add the install commands for the build targets.
now the compile process is this:
```
mkdir build
cd build
cmake -Wno-dev ..     # and the desired -DENABLED_... options
make -j4 all install/strip    # -j4 means 4 compiles parallell 4 is your amount of cpu cores
```
then your stripped and ready to deploy binaries are in deploy/bin. 
I would delay implementing further deployment process. When you think my changes are suitable for now I will make a PR.

**Comment by brindosch** [comment]
i run into a problem.
i setting up a debian 7 32bit with crosscompile howto
I want to run the commands in create_all_releases.sh 

I am sure this is related to rpi cmake?
http://pastebin.com/myZxRkuv

2.
If i run `cmake -Wno-dev ..`  i get the following output/files
http://pastebin.com/dPCrCycq
We don´t need protoc? Is this peventable?

**Comment by redPanther** [comment]
this is not preventable, this is a install command in the protobuffer. We cant/wont change proto lib.
But I did a trick ;-) test my branch again (ad see the diff commit)

**Comment by redPanther** [comment]
protoc is needed during compile to create cpp code for proto message class

**Comment by brindosch** [comment]
hm
`root@debian7:~/hyperion/build-rpi# make -j4 install/strip`
`make: *** Keine Regel, um »install/strip« zu erstellen.  Schluss.`

**Comment by redPanther** [comment]
hmm I never tried crosscompile hyperion. I use only 64bit linux (archlinux/kxstudio) on my desktop machines. 

Can we try normal compile without the crosscompile first.

**Comment by tpmodding** [comment]
pi@raspberrypi:~/hyperion/deploy/bin $ ./hyperiond hyperion.config_VIDEOGRABBER_lpd1.json 
Hyperiond:
	version   : hyperion_version_id (redpanther-7709241/aaac3a7-1457626262
	build time: Mar 10 2016 17:07:08
Selected configuration file: hyperion.config_VIDEOGRABBER_lpd1.json

works :)

**Comment by brindosch** [comment]
@tpmodding cheated with a Pi3?

On Debian 7
I could use `make -j4`
But no gpio2spi (should we "outsource" this? We don´t need that anyway every time am i right?)
No hyperion-dispmanx was build

Back on Rpi2 Wheezy

As tpmodding said, it it working with hypern-dispmanx 
Without gpio2spi

**Comment by redPanther** [comment]
gpio2spi should not be compiled when ENABLE_TESTS=OFF
is gpio2spi needed? for what purpose?

**Comment by brindosch** [comment]
At least the old versions (onRPi)  won´t run if gpio2spi is not in -bin- dir
No longer required?

**Comment by brindosch** [comment]
It is working without, huh strange. Ok then this was weeks ago a fault interpretation

**Comment by redPanther** [comment]
I have a pi1 and hyperion runs fine without. But I use systemd (not the old init scripts) and no spi.

I saw the deployed init script for hyperion wants to start gpio2spi. If this is needed, the sorces shouldn't be located in test folder - we should move it to "src"

**Comment by brindosch** [comment]
I also tested with systemd. hm
And i have not tested Xbian. which service it is used now

**Comment by redPanther** [comment]
did you use spi leds like ws2801 (I have ws2812), did they work? if yes we can kick the gpio2spi from the init script. BTW I'm sure new ws281x stuff will make gpio2spi obsolete

**Comment by brindosch** [comment]
@redPanther 
I just get that qt4 error again and again. It doesn´t make sense! I can´t find any answer on this.
Log: http://pastebin.com/uqVANPpx
Output search
http://pastebin.com/cxGFbNcG

I tested this with the hyperion master branch
If i use your branch, no file for cmake was created, but no error.

I would really appreciate any hints :/

**Comment by redPanther** [comment]
i will setup the crosscompile toolchain in next days. today I have no time for that. Perhaps qt4 isn't find in the crosscompile environment or this is mixed between crosscompile and system environment ....

**Comment by brindosch** [comment]
We will build new image this evening *byhand*.

**Comment by brindosch** [comment]
@redPanther 
We have a running build machine now (sad no imx6...). I tested again with your version_id branch and all is working as expected.
Maybe i have to ask again later to setting up the "release version in hyperion".
You could commit your changes.
Thank you for all efforts.
