### ISSUE TITLE
[Question] Hyperion XBMC addon for RPi

### ISSUE THREAD

**Issue by brunano21** [tvdzwan/hyperion#539]
Hi, 

I see there is an Hyperion XBMC addon, [except for RPi](https://github.com/tvdzwan/hyperion/wiki/XBMC-addon-(not-for-RPi)). Will there be one for RPi in future?

Thanks.

**Comment by tpmodding** [comment]
You have the xmbc Framegrabber...you dont need a addon??

Von meinem iPhone gesendet

**Comment by brindosch** [comment]
Hello brunano21,
at the moment there are no plans for it.
What do you want to achieve?
