### ISSUE TITLE
Hyperion running on Android Devices

### ISSUE THREAD

**Issue by jgato** [tvdzwan/hyperion#54]
Dear All,

I have bought a Lightpack set from Prismatik for my Android TV Box - Geniatech ATV1200. Sadly, by the moment this device is not supported.

Do you have any plan of having Hyperion running on Android devices? I dont mean the android client app, I mean the real service.

best regards,

**Comment by abrenoch** [comment]
Just wanted to bump this - I have an android grabber I'm working on here:
https://github.com/abrenoch/hyperion-android-grabber

Would love some extra hands on the project!

**Comment by packruler** [comment]
I just saw this. I built a mock up that worked a while back but found some limitations in the Android SDK. IIRC I couldn't pull video from hardware inputs nor could I pull video from Netflix streams but the Android TV UI would respond. I haven't had a chance to work on it for a while and Android 7 or 8 may have fixed some issues. Here is my repo if you wanna try it out: https://github.com/packruler/BacklightHandler

**Comment by abrenoch** [comment]
@packruler Hey really nice stuff! I'll be sure to try out some bits of your code to see if it is an improvement on what I'm doing (first glance seemed pretty simple to understand... the code I found and was working with uses openGL for some stuff, and I'm not sure if that is a problem yet or not).

True netflix will not work with this method, but from what I've found it won't work with pretty much anything like that... Short of rooting of course. There may be an xposed module or something that could allow that to happen. What do you mean by hardware inputs though?
