### ISSUE TITLE
only 288 bit package

### ISSUE THREAD

**Issue by Olevinn** [tvdzwan/hyperion#555]
Hy,

My problem: only first 12 pcs led light, more not light.
I measure PWM signal, attached. Only 288 bit send RPi GPIO18, what's wrong?

[Signal](https://i.imgsafe.org/c049995.jpg)
[Wait](https://i.imgsafe.org/02953bd.jpg)

signal All led **FFFFFF**:
RPi send package 288 bit with 800kHz ~ 288 / 24 = **12 pcs led**
signal wait ~9.7 ms

**My hardware config:**
Raspberry Pi2
OpenElec 6.0.3 RPi2.arm
WS2812b strip with PWM GPIO18

**My config file:** [pastebin](http://pastebin.com/BkWMn04B)

//removed config 
brindosch

Update:
92 pcs led
horizontal: 28
left: 18
right: 18
all: 92

**Comment by penfold42** [comment]
Add
 ""eds"= 256,

To your config if you have 256 leds

**Comment by Olevinn** [comment]
Oh...
"leds: 92 works..
HyperCon.jar wrong?

**Comment by Olevinn** [comment]
Thank you!

**Comment by brindosch** [comment]
@penfold42 
It is possible to use with ws281x device ws2812b too? On all Pis? We could kick ws2812B option? And when should you choose ws2812b?
Sorry, i really need more clarification on this, at least to write it down for all.

**Comment by Olevinn** [comment]
WS2812b PWM only Raspi1
WS281x PWM raspi2 and 3

**Comment by brindosch** [comment]
@Olevinn 
Thank you :)
My HyperCon produces configs >200 leds. I don´t knwo what is wrong with your setting. please report back :)

**Comment by penfold42** [comment]
The ws281x driver probably needs a better default than 12.

It should really use the number of configured LEDs.

If I get time over the weekend I'll look into it.

AFAIK this is the only driver that needs a "hard coded" value, but in its defense it is a very recent addition and is an external project that has been hastily dropped in to Hyperion.

BUT it's still the best workable approach for now

**Comment by penfold42** [comment]
Btw, I updated the wiki a few days ago at https://github.com/tvdzwan/hyperion/wiki/WS2812b-PWM-led-devices to briefly cover the different drivers

**Comment by Olevinn** [comment]
It is possible that I was careless.

**Comment by brindosch** [comment]
@penfold42 
thank you for the wiki update. I didn´t notice, good work indeed.
I saw the imported values in your code. Please write down which values the user should capable to change with HyperCon with min/max values, i will add it.

**Comment by penfold42** [comment]
Not my code, but until we fix the driver properly is it easy to get Hypercon to put the correct value in ?

Hypercon just needs to set it to the number of LEDs which it already knows

**Comment by brindosch** [comment]
It is now possible to include the amount leds (quick and dirty solution) to the config with hypercon
/Closed

**Comment by penfold42** [comment]
And I upped the default PWM imposed maximum to 256 rather than 12 in my recent commit
