### ISSUE TITLE
Raspberry Pi2 + Arduino + WS2812B strange behaviour

### ISSUE THREAD

**Issue by kixounet** [tvdzwan/hyperion#557]
Super Hyperion guys,

First of all, here is my setup : 

Raspberry PI2 running openElec.
My Pi is connected to an arduino UNO R3 using USB.

I have a led strip WS2812B of 184 leds (powered by an external powersupply)

I am using the internal frame grabber with the default configuration : 
`"framegrabber" : 
	{
		"width" : 80,
		"height" : 45,
		"frequency_Hz" : 10.0,
		"priority" : 900
	},`

Everything is working fine, but any video with resolution equals to 1080(720 is ok) gives a very strange behaviour.

The issue with 1080p video is that led strip is working properly, but the video on my TV works 5 secondes then the screen  start blinking like grey clouds, blinking very fast and the sound stop working 1 second every two seconds. I don't think that the issue is related to hyperion itself.

Could it be possible that my raspberry PI2 is not powerfull enough to process this (internal frame grabber on 1080p video) ?

My raspberry pi is connected to my pioneer receiver (hdmi) and this one connected to my tv (using hmdi)

If I connect in ssh to openelec and execute the > top then, I see that cpu usage stay under 20% (reason why I am not sure with the performance issue). 

Any idea ? What do you think I should check ? 

Thank you for your support and for the job done ;-)

**Comment by kixounet** [comment]
(and of course video in 1080 works properly if I kill the hyperiond process)

**Comment by mlask** [comment]
+1 -- identical problem in my installation
Tried making few configuration changes, without success. With framegrabber configuration set to 60hz, HDMI output is completely lost. Lowering this value, and the size of framegrabber limits HDMI flickering but still it's unusable. No matter what connection I choose (direct PWM or via Arduino on USB). On the other side - Boblight (standalone, without hyperion) works without any problems, but forces me to use Arduino...

**Comment by penfold42** [comment]
Fascinating - very similar to my issue with PWM LEDs. I presumed it was the ws281x driver at fault.

In my case, if I stop Hyperion, play a movie (stop it if you want) and the start Hyperion it's fine.

**Comment by penfold42** [comment]
And, I can replicate it here - I never thought to try 720P just for fun.
It also doesnt matter which driver I use - ws281x or ws2801 so its not tied to the PWM driver.

I'm recompiling without any PWM support to see what happens

**Comment by penfold42** [comment]
AHA!
I have 2 separate pi3s and this issue only happens on one of them.

Try setting your grabber height and width to both be 64.
Works:  { "width" : 64, "height" : 64, "frequency_Hz" : 25.0 },
Fails: { "width" : 64, "height" : 16, "frequency_Hz" : 25.0 },

**Comment by mlask** [comment]
In fact the problem happens not only on higher resolutions (like 1080p or 720p) but on sdtv and others too - it's only harder to see it, because HDMI keeps connection, but the video (or subtitles) is "jumping".

**Comment by kixounet** [comment]
First of all thanks for the answers ;-) I feel less alone.

I will try to investigate the issue and come back if I have found something.

I have said that cpu usage is below 20% (using top). But does the grabber use the GPU or CPU ? 

Maybe that gpu usage is 100% and can't handle the processing of fullhd video + frame grabbing.

Any case, I wil investigate and post here what I have found.

**Comment by tpmodding** [comment]
Can anybody explain why all of you guys try to run the Framegrabber with 1080p???? 320x240 is enough. Try it...

Von meinem iPhone gesendet

**Comment by kixounet** [comment]
I am playing 1080p video in Jodi and my grabber settings are 80x45 10fps.

**Comment by penfold42** [comment]
@tpmodding were talking about the Pi screen resolution being 1080 or 720, not the dispmanx grabber which is much much lower

**Comment by penfold42** [comment]
@kixounet can you try height and width both 64 ?

**Comment by kixounet** [comment]
@penfold42 , I have tried it yesterday and I have the same issue.

I can't see anything wrong in the logging of hyperion. I will try to enable the kodi logging and see if something came out.

**Comment by mlask** [comment]
Setting framegrabber to 64x64, even with 10fps, changes nothing. And there's no difference when I set driver to "ws281x" (pwm) nor "adalight" (usb).

**Comment by xircom** [comment]
Thank you mask, I've tried with 64x64 10fps and the problem has disappeared!!
