### ISSUE TITLE
Crash loop with mostly white input

### ISSUE THREAD

**Issue by kbarnes3** [tvdzwan/hyperion#558]
When the input on my V4L2 grabber is mostly a white screen, Hyperion seems to crash and restart (I see the startup effect, followed by mostly white lights, followed by the startup effect, etc). This only seems to happen with a predominantly white image from the grabber. Using the XBMC plugin or other mechanisms to drive the LEDs does not lead to this crash. When I've got an image that leads to this crash, I can run hyperion-v4l2 with parameters matching my config and get a reasonable .png successfully.

1. I'm using a Raspberry Pi 3 with Raspbian Lite
2. I'm using APA102 lights and a SHENZHEN FUSHICAI ELECTRONIC CO.,LTD USB capture card. My input is an Xbox One running through an HDMI splitter and an HDMI->Composite converter. The source is originally 1080p.
3. I'd like to provide Hyperion logs, but I couldn't find directions on the wiki for this. Please let me know how I can do this.
4. My config is here: http://www.jsoneditoronline.org/?id=8d5d7da6165bd9de98f6aef2c1d8b0e7

**Comment by penfold42** [comment]
Try running hyperiond directly from a shell prompt.
It should spit it all out on the screen.

**Comment by kbarnes3** [comment]
Thanks, that was helpful. I did this, then got my Xbox input into a state where it would crash. These are the lines that were printed right before hyperiond terminated:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  VIDIOC_DQBUF error 19, No such device
```

Full console output is available at http://pastebin.com/CsUPk5Pw

**Comment by brindosch** [comment]
@kbarnes3 
`VIDIOC_DQBUF error 19, No such device`
Is more a hardware fault or power problem.
You say it is more on white screen? All you leds are on and the power consumption is high.
Your may need more power!

**Comment by kbarnes3** [comment]
I don't think the problem is with my LEDs. I can run through the same content using the Kodi plugin instead of the V4L2 grabber without a problem. I'm trying to rule out a hardware problem with the capture card I'm using by ordering another one from a different brand.

**Comment by brindosch** [comment]
We alle have no problems with utv007. it is working great and stable.
It seams that your grabber shuts down.

**Comment by AEtHeLsYn** [comment]
Today I was playing a bit with utv007 grabber and hyperion running some patterns and fixed colors, no problems at all. The only thing I see is a bit of voltage drop at the end of the strip, but thats a power issue

**Comment by kbarnes3** [comment]
It appears to have been a problem with my particular capture card. I swapped it out for another capture card (that even uses the same chipset) and my problems went away. Thanks for helping me diagnose this!
