### ISSUE TITLE
Grabber is working but there's no LED lights.

### ISSUE THREAD

**Issue by cmvac** [tvdzwan/hyperion#561]
Hi guys, I have a Raspi 2 with a Lightberry kit for the past two years and a Fushicai USBTV007 grabber, which was working flawlessly until I did a factory reset on my instalation and reinstalled the updated Hyperion software. Since then, my grabber simply won't work. 

The grabber is working, I just took a snapshot of the captured image. Also I have added the enable-spi-overlay.dtb file on the overlays folder and the respective line on config.txt. I also have the dev/video0 file. Also the IP address is correct and the "allow remote control" option is active on Kodi. Lsusb shows the grabber as well.

Still, when I turn on the grabber I get no lights from the LEDs. They simply turn off after the initial rainbow splash. This was not happening before I updated Hyperion. 

Here is my configuration: http://www.jsoneditoronline.org/?id=8073fcad20710b7cfc86ba7ef96c07f9

Was there any code change that I am not aware of? Also, how do I access the Hyperion log? And more importantly, how do I fix this?

**Comment by penfold42** [comment]
Start hyperiond from a command prompt.
The logging will be written to the screen.

**Comment by cmvac** [comment]
By typing hyperiond on the command line I get this: 

-sh: hyperiond: not found
[1]+  Done                       /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json 0</dev/null 1>/dev/null 2>&1

Or do you mean the hyperion start command?

/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &

**Comment by cmvac** [comment]
@penfold42 

Could you please give me the full hyperiond log command? I can't find it anywhere...

**Comment by penfold42** [comment]
Try this:
/storage/hyperion/bin/hyperiond /storage/hyperion/config/hyperion.config.json

I don't use openelec so I'm guessing

**Comment by cmvac** [comment]
@penfold42

Ok, I got this message: 

/storage/hyperion/bin/hyperiond: error while loading shared libraries: libQtGui.so.4: cannot open shared object file: No such file or directory
[1]+  Done                       /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json 0</dev/null 1>/dev/null 2>&1

**Comment by cmvac** [comment]
Also, it point to /storage/hyperion/config/hyperion.config.json but the personalized config files are in /storage/.config/hyperion.config.json.

**Comment by cmvac** [comment]
So here's the log with the right folder: 

Application build time: Mar 15 2016 13:18:29
QCoreApplication initialised
Selected configuration file: /storage/.config/hyperion.config.json
ColorTransform 'default' => [0; 51]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "/dev/spidev0.0",
        "rate" : 1000000,
        "type" : "lightberry"
}

Creating linear smoothing
Created linear-smoothing(interval_ms=28;settlingTime_ms=90;updateDelay=0
Effect loaded: Cinema brighten lights
Effect loaded: Cinema dim lights
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Police Lights Single
Effect loaded: Police Lights Solid
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Random
Effect loaded: Running dots
Effect loaded: System Shutdown
Effect loaded: Snake
Effect loaded: Sparks Color
Effect loaded: Sparks
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Effect loaded: Color traces
Effect loaded: UDP listener
Effect loaded: X-Mas
Initializing Python interpreter
Hyperion created and initialised
Boot sequence 'Rainbow swirl fast' run effect Rainbow swirl fast on channel 0
Black border threshold set to 0.2 (51)
DETECTION MODE:default
started
XBMC video checker created and started
terminate called after throwing an instance of 'std::runtime_error'
  what():  Json server could not bind to port
Aborted

**Comment by brindosch** [comment]
Seems good to far. There was a priority cleanup that make it possible to configure all grabber prioritys.
The default value for internal is 900 (If it is not configured - you have to add this by hand ou with hypercon)
your v4l2 is at `"priority" : 1100,`
lower the priority of your v4l2 below 900
The lower the value the higher is the priority

**Comment by cmvac** [comment]
@brindosch Thanks, that solved it! I'll warn the guys over Lightberry about this issue, since the base for my config came from them. 

@tociek I noticed this issue on my Lightberry hyperion.config.json file based on your stock configuration. I don't know if you had any other complaints about this, but I just thought of giving you the "heads up"! 

Keep up your amazing work with Hyperion and Lightberry!

**Comment by cmvac** [comment]
Sorry for reopening this issue, but I now have a different behavior on my LEDs. When a video is playing, the LEDs start blinking, as if both grabber and the Kodi were mixed up. I'll increase the priority and see from there.

**Comment by cmvac** [comment]
Ok, priority 1000 was too much, I got no grabber signal. I now altered it to 950 and it seems to work. Again, thanks for your awesome work!

**Comment by brindosch** [comment]
@cmvac 
Just for your information, we are not affiliated with Lightberry.
Lightberry uses Hyperion because it is open source and free for everyone.
All Hyperion coding/support is done in free time and not paid.
It is a community project after the owner tvdzwan have no more time for it.

Glad that your problem is solved.
/Closed

**Comment by cmvac** [comment]
@brindosch I know that, I just of letting them know and leave that connection here as well because probably someone else will complain about the same thing. Thanks for your help!
