### ISSUE TITLE
Modify brightness level through hyperion-remote/JSON

### ISSUE THREAD

**Issue by soyxan** [tvdzwan/hyperion#565]
Hi,

I want to modify the brightness level (like the Android and iOS apps do) through JSON but I am not able to find the right command not even with the "hyperion-remote" command line tool.

How can I achieve this?

Thanks!

**Comment by penfold42** [comment]
Do you mean the brightness of a single colour ?
I think it just changes the RGB values of that colour.

If you want across the board changes - colour, effects and grabber, you can update the HSV numbers and just change V.

I do this with my mood lighting IR remote control.

**Comment by brindosch** [comment]
Should be done

/closed
