### ISSUE TITLE
Can't use hyperion

### ISSUE THREAD

**Issue by HugoRobineLanglois** [tvdzwan/hyperion#566]
Hi there. Yesterday I have received my led strand and a converter from lightberry.eu.
To deploy hyperion I have followed the instruction here : https://github.com/tvdzwan/hyperion/wiki/Installation-on-OpenELEC for APA102 but my led didn't react when I have tried the test installation command lines.

However Hyperion service is started. Result of 'ps' show the two lines bellow : 
`
332 root       0:00 {hyperiond.sh} /bin/sh /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json
  334 root       0:01 /storage/hyperion/bin/hyperiond /storage/.config/hyperion.config.json
`
So then I have tried the Hyperion plugin for OpenELEC to create a new configuration file, and here I can't see the rainbow wire. The error I get is : 
`
Unable to open RS232 device (IO Exception (2): No such file or directory, file /home/sascha/hyperion/dependencies/build/serial/src/impl/unix.cc, line 100.)
EFFECTENGINE ERROR: Effect directory can not be loaded: /opt/hyperion/effects
EFFECTENGINE ERROR: effect Rainbow swirl fast not found
terminate called after throwing an instance of 'std::runtime_error'
  what():  JSONSERVER ERROR: could not bind to port
Aborted
`

**1.** I use a RPI2 with OpenElec 6.0.3 as OS.
**2.** I have APA102 led directly connected to my RPI2 
**4.** You can find my config file here : http://pastebin.com/vStFtFez

The point is, yesterday it has worked some times, but my blue and my red were inverced so I have done something wrong... And I can't figure out what.
I have reinstalled OpenELEC this morning and it's not woking better...

**Comment by tpmodding** [comment]
Did you contact lightberry? you paid them...they should help you...!

**Comment by HugoRobineLanglois** [comment]
Hum didn't contact them because I thought it was a software problem maybe ?

**Comment by brindosch** [comment]
Your effets path is wrong, search for openelec path. The wiki needs more information sharing anyway.
@tpmodding
We should consider to publish a "this is working" list

**Comment by brindosch** [comment]
Why are you using adalightapa102 in your config, just usw apa102

**Comment by HugoRobineLanglois** [comment]
This config file come with the hyperion plugin I think. I have make the modification you suggested but it is not working better.
I have modify the hyperion.config.new and now it finds the effect path, but I always end with the following error : 
`
started
INFO: Kodi checker created and started
terminate called after throwing an instance of 'std::runtime_error'
  what():  JSONSERVER ERROR: could not bind to port
Aborted
`

On other forums I have found that it may comes from my gpio connections. Even if it is ok in my opinion I will investigate. I have found that it may come from spi which is not enable but in my config file it is (dtparam=spi=on).

I have a question. Yesterday when I first deployed Hyperion on my RPI2, I didn't know that my leds where APA102 (didn't pay attention to that) and I think i have choosen the command line `sh ./install_hyperion.sh WS281X`.What is the difference between this command line and the other ?

**Comment by brindosch** [comment]
I have no idea why it throws that port error.

`./install_hyperion.sh WS281X` won´t add dtparam=spi=on to you config.txt (cause pwm leds don´t need it)
There is no known problem with official OE6.0.3 and hyperion.
Try to start from the beginning with a clean offiicial OE 6.0.3 .img and please don´t use any kodi addon config modificatory.
We don´t provide one so no support for this here, that is the fault of your vendor, if he suggested this. You could write a feedback to their support.

**Comment by HugoRobineLanglois** [comment]
Ok, I'll do that asap and give you a feedback. Anyway, thanks for the help @brindosch

**Comment by HugoRobineLanglois** [comment]
I've done a new installation of OE and ... it's still not working. It's like there is no connection between my led and my RPI, so I'm thinking about an issue with the converter.

`The point is, yesterday it has worked some times, but my blue and my red were inverced so I have done
You need to change the RGB Byte Order, just try it out`

Yeah I know it now, but yesterday I didn't so I have make something else which has destroy it..

I understand that you make no support for the sellers ;) but I was thinking it was coming from Hyperion, otherwise I wouldn't have start an issue here !

I think you can close this one as it seems to be hardware finally
