### ISSUE TITLE
hyperion-v4l2 Not Grabbing

### ISSUE THREAD

**Issue by siam28** [tvdzwan/hyperion#567]
I am using hyperion on Arch Linux on an x86 machine that has a video grabber (1b71:3002 Fushicai USBTV007 Video Grabber [EasyCAP]) attached to a USB port.

I've compiled it today using the latest git sources (as of March 26, 2016) with the following options:
```
	git submodule init 
	git submodule update
	cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_X11=ON
	make hyperiond hyperion-remote hyperion-v4l2 hyperion-x11
```
Hyperion starts up correctly and hyperion-x11 is able to grab images and light up the LEDs; however, hyperion-v4l2 is not working as expected. I am able to take a screenshot using:
```
hyperion-v4l2 --width 640 --height 480 --frame-decimator 2 --size-decimator 8 --crop-left 26 --crop-right 27 --crop-top 20 --crop-bottom 20 --screenshot
```
But when I execute this command without the screenshot option, my LEDs do not light up. This was working before I updated to the latest git source.

**Comment by brindosch** [comment]
We changed nothing inside hyperion-v4l2. So there is no reason why it should not work.
You get a screenshot right?
There was a priority clean up, maybe something gets a (lower value- higher priority) priority than this?

**Comment by siam28** [comment]
Disabling and re-enabling the service seems to have resolved the v4l2 issue, but now I've noticed a new issue with x11 grabbing. Will open a new issue.
