### ISSUE TITLE
framegrabber priority is not working anymore?

### ISSUE THREAD

**Issue by tom4242** [tvdzwan/hyperion#570]
i'm using kodi and the v4l usb grabber.
i believe that since latest update the frame grabber is not switching automatically to/back as before.
where can i find an older version to check this up?
the suggested behaviour should be: usb grabber will have priority. when i watch a movie via kodi kodi frame grabber will be used until i stop the movie. then it should switch back to usb grabber. this is not working anymore. 
set up internal frame grabber priority to 1000 and v4l frame grabber to e.g. 800 and of course updated to config with the latest hypercon.

PRi2, Jessie, Latest hyperion

**Comment by brindosch** [comment]
@redPanther 
I could confirm this, the lower priority (v4l2) should rule out the kodi grabbing?

**Comment by tom4242** [comment]
so, in my aboce commend there was a tying misstake
so now i set up v4l2 prio to 1000 and internal grabber to 900. kodi is only enable for grabVideo.
and this is what happens: it seems that the v4l2 usb grabber is ingnored aand when i start a video in kodi hyperion will do his job. when i stop the video again everything is dark :-(
 
here is my log
pi@raspberrypi:~ $ sudo hyperiond /etc/hyperion.config.json
Hyperion Ambilight Deamon
	Version   : V1.01.1 (brindosch-d4ad877/fc7bc3c-1458755689
	Build Time: Mar 23 2016 14:20:16
INFO: Selected configuration file: /etc/hyperion.config.json
HYPERION INFO: ColorTransform 'default' => [0; 187]
HYPERION INFO: ColorCorrection 'default' => [0; 187]
HYPERION INFO: ColorCorrection 'default' => [0; 187]
LEDDEVICE INFO: configuration: 
{
	"colorOrder" : "rgb",
	"delayAfterConnect" : 0,
	"name" : "MyHyperionConfig",
	"output" : "/dev/ttyUSB0",
	"rate" : 115000,
	"type" : "adalight"
}

Opening UART: /dev/ttyUSB0
INFO: Creating linear smoothing
HYPERION (CS) INFO: Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
EFFECTENGINE INFO: Initializing Python interpreter
INFO: Hyperion started and initialised
INFO: Boot sequence 'Rainbow swirl fast' EFFECTENGINE INFO: run effect Rainbow swirl fast on channel 0
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
started
INFO: Kodi checker created and started
INFO: Json server created and started on port 19444
INFO: Proto server created and started on port 19445
DISPMANXGRABBER INFO: Display opened with resolution: 1920x1080
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
INFO: Frame grabber created and started
V4L2GRABBER INFO: width=720 height=480
V4L2GRABBER INFO: pixel format=YUYV
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
V4L2GRABBER INFO: signal threshold set to: {0,0,0}
V4L2GRABBER INFO: started
INFO: V4L2 grabber created and started
KODICHECK INFO: Kodi Connected
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
KODICHECK INFO: Kodi Message: {"id":666,"jsonrpc":"2.0","result":[]}{"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":false}}
KODICHECK INFO: switching to OFF mode
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
V4L2GRABBER INFO: stopped
EFFECTENGINE INFO: effect finished
KODICHECK INFO: Kodi Message: {"jsonrpc":"2.0","method":"Playlist.OnClear","params":{"data":{"playlistid":1},"sender":"xbmc"}}
KODICHECK INFO: Kodi Message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"dark alien 2014.mkv","type":"movie"},"playlistid":1,"position":0},"sender":"xbmc"}}
KODICHECK INFO: Kodi Message: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"title":"dark alien 2014.mkv","type":"movie"},"player":{"playerid":1,"speed":1}},"sender":"xbmc"}}
KODICHECK INFO: Kodi Message: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
KODICHECK INFO: switching to VIDEO mode
KODICHECK INFO: Kodi Message: {"id":667,"jsonrpc":"2.0","result":{"item":{"file":"smb://BLONDIE/daten/filme/dark alien 2014.mkv","label":"dark alien 2014.mkv","type":"unknown"}}}
KODICHECK INFO: Kodi Message: {"jsonrpc":"2.0","method":"Player.OnStop","params":{"data":{"end":false,"item":{"title":"dark alien 2014.mkv","type":"movie"}},"sender":"xbmc"}}
KODICHECK INFO: switching to OFF mode
^CINFO: Application closed with code 0
KODICHECK INFO: Kodi Disconnected
EFFECTENGINE INFO: Cleaning up Python interpreter

**Comment by brindosch** [comment]
Now it seams wrong. Lower value -> higher priority indeed.

**Comment by tom4242** [comment]
and here the other way around

pi@raspberrypi:~ $ sudo hyperiond /etc/hyperion.config.json
Hyperion Ambilight Deamon
	Version   : V1.01.1 (brindosch-d4ad877/fc7bc3c-1458755689
	Build Time: Mar 23 2016 14:20:16
INFO: Selected configuration file: /etc/hyperion.config.json
HYPERION INFO: ColorTransform 'default' => [0; 187]
HYPERION INFO: ColorCorrection 'default' => [0; 187]
HYPERION INFO: ColorCorrection 'default' => [0; 187]
LEDDEVICE INFO: configuration: 
{
	"colorOrder" : "rgb",
	"delayAfterConnect" : 0,
	"name" : "MyHyperionConfig",
	"output" : "/dev/ttyUSB0",
	"rate" : 115000,
	"type" : "adalight"
}

Opening UART: /dev/ttyUSB0
INFO: Creating linear smoothing
HYPERION (CS) INFO: Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
EFFECTENGINE INFO: Initializing Python interpreter
INFO: Hyperion started and initialised
INFO: Boot sequence 'Rainbow swirl fast' EFFECTENGINE INFO: run effect Rainbow swirl fast on channel 0
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
started
INFO: Kodi checker created and started
INFO: Json server created and started on port 19444
INFO: Proto server created and started on port 19445
DISPMANXGRABBER INFO: Display opened with resolution: 1920x1080
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
INFO: Frame grabber created and started
V4L2GRABBER INFO: width=720 height=480
V4L2GRABBER INFO: pixel format=YUYV
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
V4L2GRABBER INFO: signal threshold set to: {0,0,0}
V4L2GRABBER INFO: started
INFO: V4L2 grabber created and started
KODICHECK INFO: Kodi Connected
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0
KODICHECK INFO: Kodi Message: {"id":666,"jsonrpc":"2.0","result":[]}{"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":false}}
KODICHECK INFO: switching to OFF mode
V4L2GRABBER INFO: stopped
EFFECTENGINE INFO: effect finished
V4L2GRABBER INFO: started
KODICHECK INFO: Kodi Message: {"jsonrpc":"2.0","method":"Playlist.OnClear","params":{"data":{"playlistid":1},"sender":"xbmc"}}{"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"title":"dark alien 2014.mkv","type":"movie"},"playlistid":1,"position":0},"sender":"xbmc"}}
KODICHECK INFO: Kodi Message: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"title":"dark alien 2014.mkv","type":"movie"},"player":{"playerid":1,"speed":1}},"sender":"xbmc"}}
KODICHECK INFO: Kodi Message: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
KODICHECK INFO: switching to VIDEO mode
KODICHECK INFO: Kodi Message: {"id":667,"jsonrpc":"2.0","result":{"item":{"file":"smb://BLONDIE/daten/filme/dark alien 2014.mkv","label":"dark alien 2014.mkv","type":"unknown"}}}
^CINFO: Application closed with code 0
V4L2GRABBER INFO: stopped
KODICHECK INFO: Kodi Disconnected
EFFECTENGINE INFO: Cleaning up Python interpreter

v4l2 has lower prio 100. amblight is starting. after that i play a video in kodi (prio 900) - no reaction of hyperion. still v4l2 grabber is working.

**Comment by redPanther** [comment]
you can call:
./hyperion-v4l2 --help
then you will see:
 -p, --priority <arg>         Use the provided priority channel (the lower the number, the higher the priority) [default: 800]

this explains how priority value works. 
with "kodi prio" you mean the prio of the "framegrabber" ? I made the value adjustable. You can set it to your needs.

The main problem of the setup you have is, that 2 grabbers (v4l2 and dispmanx) are active. Hyperion itself can't decide which grabber you want to in which situation.

Now xbmcchecker comes on stage. xbmcchecker start/stop dispmanx according to state of kodi (aka xbmc). (see src/hyperiond/hyperiond.cpp:237)
To see the dispmanx grabber you have to set it to a value lower then the v4l grabber. Lets say to 890. The v4l is always active and put data on prio channel 900 (the default). The xbmcchecker can't switch the v4l2 on or off.

**Comment by tom4242** [comment]
i managed to check out my older verson e93bd2f and compiled it. now the functionary is back again as expected with the some configuration as of 01.01.1. so in my eyes the problem must be in the current version.

**Comment by redPanther** [comment]
can you set your framegrabber prio to 890 and check again?

**Comment by tom4242** [comment]
framegrabber 890 and v4l2 to 800?

**Comment by redPanther** [comment]
framegrabber 890
v4l 900

**Comment by redPanther** [comment]
not strange - as I described before.  - lower value -> higher prio - xbmcchecker starts/stops the "framegrabber", the v4l is always on. To see the framegrabber the prio value must be below v4l. 
All internal grabbers (= all grabbers you can configure via config file) has prio 900 by default. If you want to use more than one grabber you have to adjust the prio value.

**Comment by tom4242** [comment]
ok now i get it. i was not aware of the external grabbers overrules the internal ones. thanks a lot. you can close this case now.

**Comment by redPanther** [comment]
@brindosch can we do something about this topic in hypercon.
when more than one framegrabber is activated xbmc checker must be activated and grabber for screen ("framegrabber") must have lower prio value then grabber for v4l2 device.
Otherwise you get an unexpected result (like in this issue)

perhaps it is better to say "priority channel" rather than "priority". (like in the usage (--help) of standalone grabbers)

**Comment by brindosch** [comment]
Here i am.
The default values are atm: framegrabber 800, v4l2 900
So it should work right? I could add this as hint and later to the wiki?

**Comment by tom4242** [comment]
no. the default according to configuration file are v4l2 800 and framegrabber 900. maybe this should also changed?
and something goes wrong if you set up priority e.g. v4l2 1000 and framegrabber 900. are prios >1000 somehow not supported?

**Comment by brindosch** [comment]
@redPanther 
we should change the default, it will harm nothing, if you don´t use v4l2

**Comment by redPanther** [comment]
Change hypercon default is a good idea and it would be good to implement better handling of multiple grabbers as suggested.

**Comment by brindosch** [comment]
/Done and part of V1.01.2 (atleast i think it was this version ^^ maybe V1.02 )
