### ISSUE TITLE
installation hyperion failed. chmod: missing operand

### ISSUE THREAD

**Issue by frustrader** [tvdzwan/hyperion#571]
i**Please provide some information that we could help as fast as possible.
Please check the wiki in case your problem is already known/feature requested.**

**1.** Used hardware and sofware (Wetek,RPi1,Rpi2,... Ubuntu 14.04(64bit),OSX,OpenELEC,OSMC,XBian,...)
**2.** Your LED device and additional hardware (if used) (WS2801,APA102,WS2812B,...  connected through (direct,arduino uno,...))
**3.** Please upload your Hyperion log to pastebin.com and insert the link. Have a look at the wiki how you get one.
**4.** Please upload your "Hyperion Configuration File" to pastebin.com and insert the link.

**Comment by frustrader** [comment]
i'm using a pi2b with osmc and 71 ws2801 leds. When i try to download hyperion with:
"wget -nv -N https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh && chmod"
I get this message: chmod missing operand..
Also tried to download it from hypercon config tool V1.01 the i get the message:critical error:. please login as user root trough hypercon
  I already have hyperion installed but want to update to the newest version because im having trouble to calibrate the colours.

**Comment by brindosch** [comment]
your command is incomplete, please check the wiki again
If you want to use hypercon to update you need a working ssh login for user "root" atm.
