### ISSUE TITLE
[Feature Request] full "index" support for hyperion-remote

### ISSUE THREAD

**Issue by brindosch** [tvdzwan/hyperion#572]
@AEtHeLsYn 
There was a feature request regarding your new index implementation. Is it possible to let hyperion-remote accept the "led index" for "transform"(All values) too?
thank you for feedback ;)

**Comment by brindosch** [comment]
before my blame will be increased too much, closed ;)

**Comment by AEtHeLsYn** [comment]
;)

**Comment by brindosch** [comment]
@AEtHeLsYn 
I don´t get it.
How looks the right command for a qualifier?

**Comment by AEtHeLsYn** [comment]
With the current implementation you cannot submit lets, only ID. I didn't dig a lot on the json implementation, but afaik we cannot send leds. I could work on that, but... first things first, working on color adjustments right now ;)
