### ISSUE TITLE
Weird white color

### ISSUE THREAD

**Issue by brunano21** [tvdzwan/hyperion#582]
Hi guys,
**1.** RPi1 B+ OpenELEC
**2.** WS2801 direct connect 
**3.** _Don't think the log is useful._ 
**4.** [Hyperion Configuration File](http://pastebin.com/q9g6bsrp)

I have followed more or less the wiki [here](https://github.com/tvdzwan/hyperion/wiki/Color-Calibration) for the color configuration, however colors are really weird, especially for the white. It's like it's a light violet and not a pure and real white. For checking this I have used a total blank image. [White PNG](https://raw.githubusercontent.com/AEtHeLsYn/hyperion/master/doc/calibration/Gamma/FFFFFF.png)

Here's a picture I took - well the violet is not like in the picture, it's a bit lighter. [link](https://dl.dropboxusercontent.com/u/30454259/IMG_20160401_204023.jpg)

May someone help me to configure it properly?
Thanks!

**Comment by brindosch** [comment]
You caught a bad moment :)
This wiki article is newer than hyperion (some hours), it can´t work that way.
This will be part of the next release. You could wait (1/2 days) or use the settings that used by HyperCon

**Comment by brunano21** [comment]
Oh grand,

so I will wait until the new release will come out.

Thanks.

Bruno Bruzzano / Software Engineer
brunano21@gmail.com / +353 83 321 9468

IBM Ireland Product Distribution Limited
brunobru@ie.ibm.com / +353 1 373 99019
IBM Technology Campus - Office B3-G-114 / Mulhuddart, Dublin 15 / Ireland

[image: Facebook]  <https://www.facebook.com/mbruno.bruzzano>[image: Google
Plus]  <https://plus.google.com/+BrunoBruzzano>[image: Youtube]
<https://www.youtube.com/channel/UCYXcigBgVM5N2ZYn8HskQew>[image: Linkedin]
<http://ie.linkedin.com/pub/bruno-bruzzano/68/b2a/6a7/it>[image: Instagram]
<http://instagram.com/_br1_/>[image: Github]
<https://github.com/brunano21>[image:
Skype]

**Comment by brunano21** [comment]
@brindosch by the way, even though I use HyperCon, the weird white color is still there.

I have configured hyperion few months ago and I've always had that _issue_.

**Comment by brindosch** [comment]
You may be a victim of this or you need a proper guide
https://github.com/tvdzwan/hypercon/issues/14

**Comment by penfold42** [comment]
Weird - it could be a bad batch.

Do you ever see a green component ?
Have you repeated the test with pure red then green and then blue ?

Maybe they fitted the resistors wrong when they assembled it

**Comment by brunano21** [comment]
@brindosch @penfold42 
Uhm - I did not know about fake led strips - Jesus! O.o

However, today I have read this [post](http://www.vervelendemensen.nl/2014/03/how-to-install-hyperion-on-the-raspberry-pi-for-ambilight/) and used those settings for a better colors experience. Effectively right now the white color is more similar to what I would expect. However in certain cases I notice a green component - I do not remember exactly when. So it seems that playing a bit with gamma and so on can make the difference. However, how can modify colors in real time? The android app Hyperion Free helps but not totally.

For reference: the led strip I have bought came from aliexpress.com 
[here](http://www.aliexpress.com/item/1M-32-Pixels-WS2801-5050-RGB-Dream-Color-LED-Strip-Addressable-5V-NP/32397134887.html)

**Comment by brindosch** [comment]
I´m sorry your question was very unspecific. We have Kodi Addon for non RPi users (Windows and so on) So we was very confused what you mean there

**Comment by brunano21** [comment]
@brindosch Yeah, it was my fault because I was just facing this _world_ :)

However going back to the problem described above, what do you suggest?

**Comment by RickDB** [comment]
@brunano21 would try calibrating them using the web control:

http://gamadril.github.io/hyperion-remote/

Using the Transform tab there you can change HSV / RGB values, if you can't get full white that way then you probably have a bad led batch.

**Comment by brindosch** [comment]
@brunano21 
Did you tried RickDBs idea? The new transform is no magic, if it won´t work now, it won´t work with the new. Cause white was never a problem you could transform it to match yout TV white too.

**Comment by brunano21** [comment]
I have tried using hyperion-remote, which basically does the same of Hyperion Free for Android.
However, tweaking using that I'm able to get closer to a full white but then other colors get wrong :/
Anyway I think it's just a matter of finding a good configuration, but I'm not really sure how I can proceed.

By the way: I haven't yet upgraded to the latest version. I'll do as soon as possible.

Any suggestion/comment would be appreciated. Thanks.

**Comment by brindosch** [comment]
Set all values to default and just adjust the whitelevel. with whitelevel set to 1/1/1 you should get a cold white (due to the point that are rgb leds) and just with adjust the whitelevel you should be able to get a good white. If not - fake

**Comment by brindosch** [comment]
@brunano21 

Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions/development threads should be moved to the new forum!
We will close this issue now
