### ISSUE TITLE
Add libreELEC support to install_hyperion.sh 

### ISSUE THREAD

**Issue by jayphizzle** [tvdzwan/hyperion#583]
Setup does not work for libreELEC at the moment.

https://github.com/LibreELEC/LibreELEC.tv

**Comment by brindosch** [comment]
LibreELEC are working on their own installer which uses systemd as service. That prevents to fiddling around with autostart.sh
Please be patient

**Comment by tpmodding** [comment]
you can copy the bin files for now, that will work...
i use libreelec too, copied the files by myself...will wait for libreelec
https://github.com/LibreELEC/LibreELEC.tv/pull/39

**Comment by edwinvd1** [comment]
you ken update libreelec whit http://releases.openelec.tv/OpenELEC-RPi2.arm-6.95.1.tar
