### ISSUE TITLE
RPi2, WS2801 direct: Lights stay on for menus under OpenElec 6.0.3, regardless of config setting

### ISSUE THREAD

**Issue by IVXCVI** [tvdzwan/hyperion#585]
[Config](http://pastebin.com/r8SsAnXB)

```
"grabMenu" : false,
```
This setting worked fine with OpenElec 5.x, but fails to work correctly under 6.0.3.

If logs are needed, I need help finding where to copy it from.

**Comment by AEtHeLsYn** [comment]
Copying from another issue, already answered by @brindosch 

> In Kodi
> navigate ->System->Services->Remote control
> 
> Enable "Allow remote control by programs on this system"
> and "Allow remote control by programs on other systems" (you need both, even on the same machine)

With openelec 6 you need both, with openelec 5 only the first one is needed.

**Comment by brindosch** [comment]
This is a good hint. @AEtHeLsYn 
I didn´t know the OE change there (i don´t use it)
So i had no idea

Thank you
It is already part of the FAQ
https://github.com/tvdzwan/hyperion/wiki/FAQ-Frequently-Asked-(Problems)-Questions

**Comment by brindosch** [comment]
Should be done
/closed
