### ISSUE TITLE
LED's randomly turn off, then reset and flash colors before resetting

### ISSUE THREAD

**Issue by wjohnson1186** [tvdzwan/hyperion#586]
I am kind of a nood here, but I can't find the solution to my problem.

I currently have the Ambilight setup with an HDMI splitter to AV converter to Capture Card to Raspberry Pi.

Pretty frequently now, my LEDs will fade off, then pause, and reset.  During the reset it will flicker a couple colors, then will resume working normally, but will then reset again a few minutes later.  I can post a video of this happening if necessary.

I just got the system working in all last week.  I am unsure of what to do next.

Hardware:
Raspberry Pi 2 with OpenELEC installed.
HDMI Splitter
HDMI2AV
Easier Cap (with UTV007 Chipset)
WS2801 (86 Leds)

I currently have the HDMI Splitter, Converter, and Pi connected to a USB hub.  The LED's are powered from a separate power supply.

WS2801 connected directly to The Raspberry Pi
[Here is my current working HyperCon Config File](http://pastebin.com/38u8YrRQ)

Any and all help would be great.

By the way, thanks to all that develop this program.  Y'all are awesome.

**Comment by brindosch** [comment]
This may be related to your to your splitter/hdmi2av/(less utv007). The leds do just what they get.
Could you use the internal grabber to grab your picture from your openelec an try again?
This is just with external grabbing?

**Comment by wjohnson1186** [comment]
I am fairly certain there is now an issue in the line of connections and not Hyperion.

I haven't had the issue for a couple days now, and I think it may have been an over heating issue on the converter.  Who knew!

I am going to building an enclosure that can hold all the stuff, and include some sort of fan to cool things off.  I appreciate the feedback and comment!  Was just seeing if i did something wrong.
