### ISSUE TITLE
LEDs not listening to commands from Raspberry Pi nor displaying correct color

### ISSUE THREAD

**Issue by ClassyTurkey** [tvdzwan/hyperion#590]
I purchased one of the original LightBerry Set with HDMI Premium Kit and Power Supply back around July 2014 and I am finally having issues with my kit. I have spent the last few days trying to trouble shoot it and am getting no where. I am not certain if their is a short in the strip or something else is wrong.

My LED strip is a constant light blue or almost white color. I have thought maybe something was wrong with the software so I wiped my device and restarted from scratch.

I am running on a Raspberry Pi 1 and have tried using Multiple images on the site, and multiple different installs via this tutorial: https://github.com/tvdzwan/hyperion

I don't believe is the issue 2. discussed here: https://lightberry.eu/support/leds-are-on-when-hdmi-source-is-off/ because it seems that the LEDs are not responding at all to my commands through the raspberry pi. Even when using service hyperion restart does nothing. Even when I turn off the Pi, the lights all stay on. Now on a fresh install of OSMC without hyperion, the LEDs do only have 1 blue light on. But once Hyperion is installed its like the LEDs don't understand the signal  

I will upload my log and config once I get home.

**Comment by brindosch** [comment]
Hello,
please refer to the lightberry support. We are not associated with lightberry and can't help you.
Thank you

**Comment by ClassyTurkey** [comment]
I understand if you believe it is a hardware issue, but I was posting here to see if there is any reason why the software Hyperion on OSMC wouldn't respond/communicate properly with Lightberry. I am posting here and contacting their support just incase it is a software issue as the lights function properly up until Hyperion is install.

**Comment by brindosch** [comment]
Is there a reason why you won´t use the ready to use images on their site?

**Comment by ClassyTurkey** [comment]
See that's the thing I have tried both. The ready to use images as well as the custom tutorial through here with OSMC and still no dice.

**Comment by brindosch** [comment]
Then you should consider to contact lightberry? So it is no issue with hyperion.
