### ISSUE TITLE
Color differences between first and last LED

### ISSUE THREAD

**Issue by sgtriggs** [tvdzwan/hyperion#597]
I'm assuming this is a hardware issue but I'm wondering if anyone has come across this before.

Essentially, the further around the LED strip you go, the more they take on a different color.  I've attached a photo below showing the issue.  This is using a fresh config file, and I'm connected using the IOS remote with the color set to pure white, 100% brightness.  Other colors aren't affected anywhere near as much, but if I really look hard I can spot a subtle difference.

(it's difficult to capture with a camera, but really noticeable by eye).

Everything (Pi, LEDs (APA102), HDMI splitter, HDMI>AV etc) is running of a 5V 20A PSU, so that's well within spec.  I'm actually using a USB cable to drive the LEDs.  I've got the filter PCB connected to a USB header on the back of my box and the LED strip is soldered to a USB port (sugru'd to the back of my TV).  Could it possibly be a cable issue?  The USB is wired up so that the outer pins are +V and GND with the inner pins handling data.  Is the wire in a USB cable a thick enough gauge to drive the LEDs properly?

Reducing the brightness to somewhere around 30%-40% appears to solve the issue, but I'd like to figure out what's actually causing it.

I'd not actually noticed this until tonight after installing the beta and attempting to run through the color calibration guide (which for the record I can't get to work, but that's probably for another topic).

![img_3691](https://cloud.githubusercontent.com/assets/16398763/14512314/e8a4d2d6-01d5-11e6-95b2-e9de616aa708.jpg)

**Comment by brindosch** [comment]
> Reducing the brightness to somewhere around 30%-40% appears to solve the issue, but I'd like to figure out what's actually causing it.

It looks like you just input the voltage at the beginning, also attach +5v and gnd at least at the end.
If you still have this problem input again at the middle of your tv at the top.

**Comment by sgtriggs** [comment]
Ok, it's late here now so I'll give this a go tomorrow.  Thanks for the advice.

**Comment by sgtriggs** [comment]
Powering from both ends has made a massive difference.  I still think there's an ever-so-slight color variation, but it's nowhere near as noticeable.

![img_3692](https://cloud.githubusercontent.com/assets/16398763/14523223/7a7ee4f4-022a-11e6-893c-1fdb12fabf23.jpg)

**Comment by penfold42** [comment]
Yep - try using 600 LEDs without extra feeds.
Not pretty !

**Comment by brindosch** [comment]
To verify the voltage on both end and even at the middle use a multimeter to measure your voltage.
This is the best way to verify a voltage dif

**Comment by tpmodding** [comment]
the "best" solution is to power from your psu after every 50 led

how many leds do you have?

**Comment by sgtriggs** [comment]
@brindosch I'll get the multimeter out at some point and do some testing.

@tpmodding Really?  Is that from personal experience, or do you have a data sheet on APA102 LEDs?  I'm running close to 180 of them by the way.

**Comment by tpmodding** [comment]
only personal experience, didnt read it in any data sheet... than you can be sure every led has engouh power... :) if you look at your last pic, you can see that the right side isnt as shiny as left side :)

**Comment by penfold42** [comment]
If I use ws2812's as an example, each led can draw 60mA. Not only is that a lot of current when you grab 100 of them, the copper traces on the strips are pretty small by comparison.

I had 600 running for xmas outside and needed an extra power lead every 150.

My tv has about 100 and it could do with having power added at the far end.

In case you're wondering about the color change - blue LEDs have a higher forward voltage and so suffer from lower strip voltage first (then green, then red)

**Comment by brindosch** [comment]
Wow, everything is said - the amount of voltage controls the brightness - your indication to tune this to your liking. :+1:

**Comment by BooStars** [comment]
Soo, exactly the same problem hear yesterday... my leds (190s) looked exaclty like sgtriggs.
After I added a second power connect at the end of the strips the problem was gone....

**Comment by brindosch** [comment]
This is part of the FAQ now
/closed
