### ISSUE TITLE
Hyperion with openelec on a htpc (no raspberry)

### ISSUE THREAD

**Issue by JackDaRippa** [tvdzwan/hyperion#62]
I'm sorry but this is likely a noob question. Is the official installation guide for openelec only working with a raspberry system? I abortive trying to run it on a usual htpc with openelec (Arcitc-MC). I need the htpc only for grabbing! There's a RPi in my network which is connected the the leds. And here hyperion is running fine as server. With the old boblight xbmc-addon on my openelec-htpc i am able to connect and grabbing works. But i would like to switch completely from boblight to hyperion ...

I followed the installation guide without any errors. The directories and files are created. I've checked this via putty. But the command "ps ax" doesn't show any hyperion process. I've tried to start  hyperiond and hyperiond.sh manually with this results:

OpenELEC:~/hyperion/bin # ./hyperiond
./hyperiond: line 1: syntax error: unexpected word (expecting ")")
OpenELEC:~/hyperion/bin # ./hyperiond.sh
/storage/hyperion/bin/hyperiond: line 1: syntax error: unexpected word (expecting ")")

I am thankful for a chance of help.

**Comment by Krautmaster** [comment]
progress here?

**Comment by b0mb** [comment]
Stucks...
Am 13.04.2015 18:27 schrieb "Krautmaster" <notifications@github.com>:

**Comment by Krautmaster** [comment]
<- sad. Well,cant u grab the content using boblight X11 and transform ur own hyperion intelligence + output? Current status https://www.youtube.com/watch?v=9b2fOutd0_M

**Comment by BertusG** [comment]
Looks very interesting Krautmaster. Can you make a little how-to? I'm quite sure there are a lot of people interested in running hyperion in combination with openelec and x86/no RPI. 

For instance I run a x86 in combination with arduino a dying to use Hyperion under OpenElec.

**Comment by Krautmaster** [comment]
I simply install openelec + use the addon management to install the servcie boblightd.

Then i simply put the boblight.conf file using the samba share into the folder \\Openelec\Userdata\addon_data\service.multimedia.boblightd + rename the boblight.X11.sample to boblight.X11 in same folder

After that, u need to put a smal autostart.sh script into  \\openelec\Configfiles
-> content:

#!/bin/sh
(boblight-X11 -o gamma=2.0 -o speed=40 -o valuemin=0.006 -o value=1.1 -o saturation=1.0 -o threshold=30
)& 

eg.

Thats all.

**Comment by BertusG** [comment]
This is totally driven by boblight, hyperion is not used in this scenario, or am I wrong?

**Comment by Krautmaster** [comment]
correct, but i thought hyperion might use boblight x11 components like the grabber eg to use own functionality to generate the best output maybe. I cant say what exactly is missing for hyperion to work on openelec. Maybe the boblightd or boblightx11 component can fit an existing gap. I'd like to see what hyperion can do in comparison

**Comment by BertusG** [comment]
No problem and yes I'm also very curious to see Hyperion running on OpenElec (on x86 systems). I used Boblight and Hyperion before on an Ubuntu driven system and have a strong preference to Hyperion. 

Since I'm a very satisfied OpenElec user (and don't want to switch back to Ubuntu) I'm very eager to see Hyperion running on OpenElec and a x86 system. Unfortunately I'm not that "smart" to make this happen, but there must be enough Hyperion enthusiastics around here to make this happen, right?

**Comment by Gamadril** [comment]
Try out the x86 build. I've tested it only with openelec, for other linux distros the installation script might need small modifications.
```
curl -L -O https://raw.github.com/Gamadril/hyperion/master/bin/install_hyperion.sh
bash install_hyperion.sh
```

**Comment by ctugt** [comment]
I got a question,
Having hyperion on a rpi2 is great but its sooooo slow (rpi with kodi) so i i tooked a core2 pc and installed kodibuntu on it, muchhh faster. Im using the tool XBMC addon (not for RPi) and send it to the rpi2 hyperion deamon its woring, cant cap the normal screen use only video, but its ok. I do see little lags sometimes cause its going over network. so i went to google and found this little chip:

https://github.com/sparkfun/SPI_Shortcut/tree/V_1.6

Does hyperion will work with this or is it hardcoded to something in the rpi2 spi controller?
If so, is ther any developer that wanne work with me for this, you can script, i can test.
this would be a cheap solution for those using a htcp and wanne use spi connection to usb.

Thanks!

**Comment by tpmodding** [comment]
@JackDaRippa can be closed?
