### ISSUE TITLE
Use Hyperion with mix of RGB and BGR Leds 

### ISSUE THREAD

**Issue by lord-leicester** [tvdzwan/hyperion#69]
I got 2 sets of LED-stripes. But one has the LED-Order RGB, the other BGR. Is it possible to specify the LED-Order for some areas to be different from default? Both Strips are connected in line correctly. The controller is a ws2801.

**Comment by sweetpi** [comment]
I had the same problem. I've added a `colorOrder` option for each led in the config: https://github.com/sweetpi/hyperion
If you want to use it, you have to compile it from source.

**Comment by patovolador** [comment]
I have a led stripe BGR and I install hyperion with configuration "bgr"  but it still do blue-> Red and Red-> blue, and if i put RGB happens the same. nothinck change, what can it happens¿

**Comment by Jurandor** [comment]
Hi there,

I just finished my Ambilight Setup for my Raspberry Pi. Unfortunately I got one RRB and one BRG LED stripe. I am running Openelec Kodi. 
As I am very new to all this and kind of a Linux Noob, I have no idea on how to change the color order on single LEDs.
Can you help me with my problem. If so a detailed instruction would be wonderful.
Thanks in advance
Martin

**Comment by sweetpi** [comment]
@Jurandor Can't give you a detailed instruction, but a short: Setup hyperion like normal, then set the color order for the wrong leds in the `hyperion.config.json` file:


```
	///           (minimum and maximum inclusive)
	"leds" : 
	[
		{
			"index" : 0,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.9375, "maximum" : 1.0000 }
		},
		{
			"index" : 1,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.8750, "maximum" : 0.9375 }
		},
[...]
		{
			"index" : 15,
			"hscan" : { "minimum" : 0.9500, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.0625 },
			"colorOrder" : "bgr"
		},
		{
			"index" : 16,
			"hscan" : { "minimum" : 0.9643, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.0500 },
			"colorOrder" : "bgr"
		},
[...]
```
(config excerpt)

**Comment by Jurandor** [comment]
Thank you very much. I will try that immediately. I will let you know if it worked for me.

**Comment by Jurandor** [comment]
It works - thank you very much.

**Comment by sweetpi** [comment]
You are welcome, checkout [pimatic](http://pimatic.org).

**Comment by tpmodding** [comment]
@lord-leicester can be closed?
