### ISSUE TITLE
Average Color mode for grabber?

### ISSUE THREAD

**Issue by smoky19x** [tvdzwan/hyperion#72]
Hello,

i searched the forums and the web but didn't find an answer to my question, that's why i ask here:

Is there a way in hyperion to process the average color of the entire video frame, like in ambi-tv from gkaindl? I would like to switch between the modes of border-color detection and average-color.

Thank you.
Daniel

**Comment by tpmodding** [comment]
@smoky19x can be closed?

**Comment by brindosch** [comment]
I added to the feature requests /closed
