### ISSUE TITLE
Strange color in dark scenes (SSH text), results in flickering

### ISSUE THREAD

**Issue by Maerchensarg** [tvdzwan/hyperion#74]
Hello,

I have a problem with hyperion, or maybe the STK1160 grabber. I use my PC as HDMI input and get some strange flickering, caused by the grabber I guess.

You can see the flickering in this video: https://www.youtube.com/watch?v=-M9J60A0SLg

And this is a screenshot of the desktop which is grabbed: http://i.imgur.com/OxZSNJr.png
And this is what the grabber gets: http://imgur.com/ErYfnse As you see there are some strange colors around the SSH text. Do you know why? Is this a grabber problem?

I created a gif with a few frames to show the raw grabber stream: http://imgur.com/SJlKdNe You can see some kind of "grain effect".

This is my HDMI2AV: http://www.ebay.de/itm/321327005674?ssPageName=STRK:MEWNX:IT&_trksid=p3984.m1497.l2649

This is my Grabber (STK1160): http://www.amazon.de/gp/product/B002RX49AU/?tag=httpwwwforumr-21&tag=httpwwwforumr-21

The grabber is connected to a powered USB hub. The WS2801 LEDs connected to the RPi via Bridge Kit. I use the latest Raspbian image (January 2014).

Maybe somebody can post some raw screenshots from the hyperion grabber to compare?

Sorry for my bad english and thanks for help.

**Comment by tpmodding** [comment]
@Maerchensarg can be closed?

**Comment by Maerchensarg** [comment]
Yes, I don't use it anymore.

**Comment by tpmodding** [comment]
@Maerchensarg could you close it? i cant...thx

**Comment by Maerchensarg** [comment]
Ups, sorry. :D
