### ISSUE TITLE
Make hyperion boot and stay on static colour or effect when not being used?

### ISSUE THREAD

**Issue by pigbait** [tvdzwan/hyperion#77]
Hello, first of all GREAT!!! work on hyperion, I just had a question about it... is there any way in the config I can setup hyperion that after booting up if xbmc is not being used it would go to a static colour or an effect? I have hyperion installed on my Raspberry pi, and run XBMC from another PC, The raspberry pi turns on and off with my TV, and I would like to get the pi to boot to a blue lights when not using xbmc

**Comment by ctugt** [comment]
ANyone got this to work, i also like to see static purple when im on the menus

**Comment by ctugt** [comment]
Mainwhile i found a suitable workaround.
1. get the skin Rapier
2. Make a custom catagorie with lets say a purple background.
3. Turn off sceensaver function in Kodi
4. Navigate to youre custom catagorie with the background colours you want.
5. Switch tv to main channels idk its set go do youre thing.

is dev reading this too?

**Comment by pigbait** [comment]
I could never get it working.

**Comment by ctugt** [comment]
I found a way to get it work, with some help from the openelec irc

I use two buttons on my MCE remote, blue for switching on/off, yellow to create a static purple colour. This is how (if you know this its really easy to change the purple colour to youre like)

On/off script for hyperion Remote. In /storage/.kodi/userdata/keymaps/remote.xml define:
<yellow>RunScript("/storage/hyperion/effects/purple.py")</yellow>
<blue>>RunScript("/storage/hyperion/effects/hyperionswitch.py")</blue>

Then create two files in the /storage/hyperion/effects folder.
One called purple.py with this content:
import subprocess
<lrusak> subprocess.Popen('/storage/hyperion/bin/hyperion-remote.sh --priority 100 --color purple', shell=True)

One called hyperionswitch.py with this content:
import subprocess

pid = subprocess.Popen('pidof hyperiond', shell=True, close_fds=True, stdout=subprocess.PIPE)

try:
    if pid.stdout.readlines():
        subprocess.Popen('killall hyperiond', shell=True)
    else:
        subprocess.Popen('/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &', shell=True)
except Exception, e:
    pass

now reboot and thats it.

**Comment by RanzQ** [comment]
@pigbait I've got my own Pi now but I have raspbian on it. The init script I posted earlier didn't work for me either but I just modified the one that comes with hyperion install script:

```
#!/bin/bash
# Hyperion daemon
# description: Hyperion daemon
# processname: hyperiond

DAEMON=hyperiond
DAEMONOPTS="/etc/hyperion.config.json"
DAEMON_PATH="/usr/bin"

NAME=$DAEMON
DESC="Hyperion ambilight server"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
case "$1" in
start)
        if [ $(pgrep -l $NAME |wc -l) = 1 ]
        then
                printf  "%-50s\n" "Already running..."
                exit 1
        else
                printf "%-50s" "Starting $NAME..."
                cd $DAEMON_PATH
                PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
                sleep 5 && hyperion-remote --effect "Cold mood blobs" --priority 200
		#echo "Saving PID" $PID " to " $PIDFILE
                if [ -z $PID ]; then
                    printf "%s\n" "Fail"
                else
                    echo $PID > $PIDFILE
                    printf "%s\n" "Ok"
                fi
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        if [ -f $PIDFILE ]
        then
                printf "%-50s" "Stopping $NAME"
                    PID=`cat $PIDFILE`
                    cd $DAEMON_PATH
                if [ -f $PIDFILE ]; then
                    kill -HUP $PID
                    printf "%s\n" "Ok"
                    rm -f $PIDFILE
                else
                    printf "%s\n" "pidfile not found"
                fi
        else
                printf "%-50s\n" "No PID file $NAME not running?"
        fi
;;

restart)
        $0 stop
        $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac

exit 0
```

See the line with hyperion-remote. I changed the `sleep` to 5 sec and the priority to 200. Now it starts that effect on boot.

**Comment by pigbait** [comment]
You my friend are a hero... this worked awesome.. thank you! thank you!
thank you!

**Comment by solidewebservices** [comment]
Should adding this line to hyperion.config.json on OSMC still work after following the OSMC installation guide. After following this guide Hyperion is started through /etc/systemd/system/hyperion.service. I added the line to auto start an effect on boot but it's not doing anything.

**Comment by RanzQ** [comment]
@solidewebservices services in OSMC work a bit differently, according to this the problem might be network delay: https://discourse.osmc.tv/t/osmc-running-custom-script-at-boot/2425/2

Try with custom shell script, put this in `/home/osmc/start_hyperion.sh`:
```
#!/bin/bash
/opt/hyperion/bin/hyperiond /etc/hyperion.config.json
sleep 5 && /opt/hyperion/bin/hyperion-remote --effect "Cold mood blobs" --priority 200
```
Then modify the service script:
```
[Unit]
Description=Hyperion
After = remote-fs.target network-online.target
[Service]
Type=simple
User=osmc
Group=osmc
UMask=007
ExecStart=/home/osmc/start_hyperion.sh
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target
```
I modified lines `After` and `ExecStart`. I don't have OSMC installed so cannot test. You can also change the effect in that shell script and try adding more sleep if it doesn't work.

**Comment by solidewebservices** [comment]
@RanzQ Thanx for the suggestion. I had tried something similar but it doesnt work. It seems the shell script is not started at all and therefor Hyperion does not start. I also tried add #!/bin/bash at the top of hyperion.services but still a no go. Using the following ExecStart line in hyperion.services does start hyperion but not the desired effect. 

`ExecStart=/opt/hyperion/bin/hyperiond /etc/hyperion.config.json && sleep 50 && /opt/hyperion/bin/hyperion-remote --effect "Cold mood blobs" --priority 200`

**Comment by RanzQ** [comment]
@solidewebservices `&&` doesn't work with systemd, try like this:

```
ExecStart=/opt/hyperion/bin/hyperiond /etc/hyperion.config.json; sleep 50; /opt/hyperion/bin/hyperion-remote --effect "Cold mood blobs" --priority 200
```

As suggested here: https://bbs.archlinux.org/viewtopic.php?pid=1139387#p1139387

**Comment by RanzQ** [comment]
@solidewebservices btw `sleep` means "wait x seconds", so `5` should be enough. :)

**Comment by solidewebservices** [comment]
Yeah, the sleep parameter was a type-o.

I tried using the semicolon in hyperion.services (with spaces on both sides of the semicolon) but this is the same as using ampersands. Hyperions starts but the effect does not.

**Comment by RanzQ** [comment]
@solidewebservices and the effect works if u start it manually?

**Comment by solidewebservices** [comment]
Yup, through the app or through command line everything is fine. I use Hyperion together with the Kodi Add-on which runs on a Intel NUC and that all works fine as well. Just having an effect at start up of the Raspberry Pi with OSMC just refuses to work ... :-|

**Comment by RanzQ** [comment]
Hmm, actually the original shell script runs hyperion on background and dumps the output. So try this:

```
ExecStart=/opt/hyperion/bin/hyperiond /etc/hyperion.config.json > /dev/null 2>&1 &  sleep 5; /opt/hyperion/bin/hyperion-remote --effect "Cold mood blobs" --priority 200
```
`&` makes the first command to start in background, no `;` needed after it.

**Comment by solidewebservices** [comment]
@RanzQ using this command Hyperion does not start anymore. It seems such a simple thing but it looks to be impossible. Thanx for trying though.

**Comment by RanzQ** [comment]
@solidewebservices try one more thing, put that in the bash script:
```
#!/bin/bash
/opt/hyperion/bin/hyperiond /etc/hyperion.config.json  > /dev/null 2>&1 &
sleep 5
/opt/hyperion/bin/hyperion-remote --effect "Cold mood blobs" --priority 200
```
And then
```
ExecStart=/home/osmc/start_hyperion.sh
```

**Comment by solidewebservices** [comment]
Nope, Hyperion does not start ... :-|

**Comment by RanzQ** [comment]
This could also work, create another service which runs once:
```
[Unit]
Description=Hyperion Effect
After=hyperion.service

[Service]
User=osmc
Group=osmc

Type=oneshot
ExecStart=/opt/hyperion/bin/hyperion-remote --effect "Cold mood blobs" --priority 200

[Install]
WantedBy=multi-user.target
```
And save it next to `hyperion.service` as `hyperioneffect.service` for example. If doesn't work, try adding also sleep to it:
```
ExecStart=sleep 5; /opt/hyperion/bin/hyperion-remote --effect "Cold mood blobs" --priority 200
```

I can debug further some day but now I'm too busy to install OSMC myself.

**Comment by RanzQ** [comment]
Also try with color first, those quotes might break the command: `/opt/hyperion/bin/hyperion-remote -c blue`

**Comment by redPanther** [comment]
In my setup I acomplished a static color (or effect) on boot by setting "bootsequence" -> "duration_ms" to 0 in hyperion.cfg

As effect I wrote a "Cinema brigthen lights". This effects fade from one color to another and then holds the end color for ever. You can get the effects in my repo: https://github.com/redPanther/hyperion/tree/master/effects    (cinema*.json and fade.py) Set your desired color and fade time in json file.

This works without hacking boot scripts ...

**Comment by solidewebservices** [comment]
@redPanther awesome, so simple and so effective! Why didnt I think of this myself ...
@RanzQ thanx again for your help though, no need to test with OSMC anymore ..

**Comment by RanzQ** [comment]
Nice. Better solution indeed. :)

**Comment by ctugt** [comment]
My solution is use the autoexec.py

import xbmc,xbmcgui
import subprocess,os
import time

class MyPlayer(xbmc.Player) :

        def __init__ (self):
            xbmc.Player.__init__(self)

        def onPlayBackStarted(self):
            if xbmc.Player().isPlayingVideo():
                os.system('/opt/hyperion/bin/hyperion-remote --clear')

        def onPlayBackEnded(self):
            if (VIDEO == 1):
                os.system('/opt/hyperion/bin/hyperion-remote --priority 100 --duration 86400 --effect "Blue mood blobs"')

        def onPlayBackStopped(self):
            if (VIDEO == 1):
                os.system('/opt/hyperion/bin/hyperion-remote --priority 100 --duration 86400 --effect "Blue mood blobs"')
				
        def onPlayBackPaused(self):
            if xbmc.Player().isPlayingVideo():

        def onPlayBackResumed(self):
            if xbmc.Player().isPlayingVideo():
                os.system('/opt/hyperion/bin/hyperion-remote --clear')

player=MyPlayer()

subprocess.call('/opt/hyperion/bin/hyperiond /etc/hyperion.config.json </dev/null >/dev/null 2>&1 &', shell=True,)
time.sleep(3)
subprocess.call('/opt/hyperion/bin/hyperion-remote --effect "Blue mood blobs"', shell=True,)

while(1):
    if xbmc.Player().isPlayingVideo():
        VIDEO = 1

    else:
        VIDEO = 0

    xbmc.sleep(3000)

**Comment by RanzQ** [comment]
@ctugt yeah that works ofc for Kodi/OSMC :)

Btw why **`</dev/null`**? Inputs from dev/null? Haven't seen that before.

**Comment by redPanther** [comment]
I've made a pull request to set static color on boot. You can set the color in hyperion.config directly. no need for a special effect.

**Comment by tpmodding** [comment]
@pigbait merged, could you close this pls?

**Comment by pigbait** [comment]
you sorry about that
