### ISSUE TITLE
Hyperion on during movies but off during live tv?

### ISSUE THREAD

**Issue by elliott69** [tvdzwan/hyperion#86]
Hi, great work btw!! I was wondering if it is possible to configure hyperion to work during video playback through the movie folder of xbmc but not have them working during live tv playback. Is there a way of separating these types of playback??
Maybe somehow a script could command the hyperion to only work when video files are selected from certain folders?? Would be very useful as I only use the effect during films and not when im watching the weather forecast!! ;)

Many thanks!

**Comment by nurtext** [comment]
@tvdzwan May I as why this issue was closed? For me Hyperion isn't working too in Live TV mode.
