### ISSUE TITLE
Support 3D

### ISSUE THREAD

**Issue by Phil1988** [tvdzwan/hyperion#9]
I wonder if you could add 3D functionallity.
I am coming from the ambi-tv project and it would be great if you can provide a 3D solution as well.

Hyperion just has to calculate the colors of the half picture (for SBS 3D the complete hight and half the width | for TTB 3D it must take half the heigt and the complete width).
Awesome would be if you could also integrate a automatically detection of 2D/3D mode.... or at least a simple switch to turn one mode on/off.

Hope you can do this ^^
Great project....
Cheers!

**Comment by tpmodding** [comment]
@poljvd can be closed?

**Comment by strikegun** [comment]
Can't test it anymore, because of the wetek-box does not support hyperion. Sorry. I am out.

**Comment by Phil1988** [comment]
As this is not possible with the hardwaresolution (HMDI splitter + USB grabber) you can close this.
Hyperion doesnt allow 3D.

**Comment by tpmodding** [comment]
@Phil1988 could you close it please? we are not allowed
