### ISSUE TITLE
Rainbow lights when standalone hyperion has no signal from USB grabber

### ISSUE THREAD

**Issue by HyperFann** [tvdzwan/hyperion#92]
Hi guys, first of all I want to say that you did and still do a wonderfull job with this beautiful project. 

I post here an issue I have when for example, I finished to play with my PS3 and shut it down. All the LEDs turn statics with different color by group of 3 or 4 leds, yellow, blue, green, purple, red, blue and so on but only on my horizontal strip. Vertical strip are all green/white. I would like to tell hyperion to put the led black when the USB grabber has no signal. Is this possible ?

I use a USB grabber DC60 with a STK1160 chip.

thanks in advance for you help

**Comment by nrosier** [comment]
I've also ran into this issue. We really need a reliable source for HDMI2AV convertors that do not display the rainbow bars when no signal is detected. For now I just unplug the power of the convertor but that is not a long-term solution.

**Comment by brindosch** [comment]
I will close this, due to converter fault and age.

**Comment by PhilippSchaffrath** [comment]
Actually i would like to see this re-opened again. A functionality to detect a no-signal image would be usefull.

**Comment by nrosier** [comment]
I agree. Unless someone can provide a store where I can buy a good convertor (100% garantee not do display rainbow colours). I currently have 4 which are all bad (i.e. rainbow).

**Comment by brindosch** [comment]
And how determine you a no-signal image? I don´t know how many color variants and steps are created out there. When you say you see rainbow colors, this is also on your grabbed picture right?

The main problem is: v4l2 shuts down if you have no signal. The hdmi to cvbs converter outputs weird stuff all time. So v4l2 never shuts down.

**Comment by pelrol** [comment]
Would it be possible to provide a "no signal" screenshot to be able to do a comparison ?

**Comment by brindosch** [comment]
Checkout this hint:
https://hyperion-project.org/threads/v4l2-add-shutdown-detection.146/#post-2034

**Comment by nrosier** [comment]
I found what might be a good solution (after having bought 3 "white" HDMI2AV convertors). Either get the HDMI full HD kit from Lightberry (which is a nice all-in-one solution so handy if you haven't bought a splitter and grabber yet) or try and find the 4K convertor they use in their 4K kit. I found 1 on ebay and it works like a charm. No more rainbow colour lights for me.

**Comment by tyreecruz6** [comment]
redSignalThreshold

**Comment by sivilya** [comment]
So, I found out a very simply solution (worked like a charm for me) - just get the hd capture stick (which will replace both the HDMI2AV and the regular video capture stick):
http://s.click.aliexpress.com/e/lUmAtO0u - for example
it will not send out signal if no signal received.
Worked out of the box!

**Comment by Burn-In** [comment]
@sivilya That sounds great. Drivers are already included? Which distribution do you use?

**Comment by sivilya** [comment]
> @sivilya That sounds great. Drivers are already included? Which distribution do you use?

Just the regular main distro...
